### ISSUE TITLE
A GUI for entering download credentials with v 4.1

### ISSUE THREAD

**Issue by zuk22** [YahnisElsts/plugin-update-checker#100]
Hi!
On Plugin Update Checker page you provide link for **A GUI for entering download credentials** http://open-tools.net/documentation/tutorial-automatic-updates.html#wordpress
There is a class extension for Update Checker that looks like. (schematic): 
```
class OpenToolsPluginUpdateChecker extends PluginUpdateChecker_2_1 {
    // class code here
}

 // init
$myUpdateChecker = OpenToolsPluginUpdateChecker::buildUpdateChecker(
	"http://website.com/wp-update-server/?action=get_metadata&slug=my-plugin",
	__FILE__,
	"my-plugin"
);
```
Questions: 
What class I must extend instead PluginUpdateChecker_2_1 in v 4.1? 
How can I do it?

**Comment by YahnisElsts** [comment]
The closest equivalent is `Puc_v4p1_Plugin_UpdateChecker`. However, stuff has been moved around a bit since version 2.1, so the code may need additional modifications. For example, you won't be able to use `buildUpdateChecker()`, so you'll need to instantiate your subclass directly.

**Comment by zuk22** [comment]
Thank for fast response!
Yes, I run it with small modification.
Thank you for help!! :-)

**Comment by YahnisElsts** [comment]
All right, I'm glad to hear that worked.
