### ISSUE TITLE
AccessToken: Question

### ISSUE THREAD

**Issue by pixelbart** [YahnisElsts/plugin-update-checker#106]
Hello!

Before i start: Sorry for my bad english and sorry for the question, is not an issue, just an question!

I'm loving you script! Today i've tested it with private repositories, but i dont know how it works... Can i choose a own access token? Or does it only works with the github repository tokens?

Thank you very much!

Greetings from germany

**Comment by YahnisElsts** [comment]
It has to be a "personal access token" from GitHub. I don't think GitHub lets you choose your own tokens, but you can generate multiple tokens with different permissions and so on.

**Comment by pixelbart** [comment]
Thanks man!!! Thats solved my problem and answer my question!
