### ISSUE TITLE
GitHub and the gitignore file

### ISSUE THREAD

**Issue by anybodesign** [YahnisElsts/plugin-update-checker#109]
hello,

first of all thank you so much for this plugin! it's just awesome to be able to update plugins and themes the wordpress way :)

I was wondering if there was a way of ignoring the gitignore file when a plugin/theme is updated via github? is it also possible to ignore some others files? (sass files for example)

thanks!

**Comment by YahnisElsts** [comment]
Maybe you could do it with a [`.gitattributes`](https://git-scm.com/docs/gitattributes) file? I think the `export-ignore` attribute can be used to exclude files from archives. I don't know if that works on GitHub, but it's worth a try.

**Comment by anybodesign** [comment]
Hey,
it seems to work! thanks again :)
