### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by sadortun** [YahnisElsts/plugin-update-checker#110]
Hi @YahnisElsts !

Great library ! Do you have any plans to add support for Gitlab API ? 

Thanks,
Samuel

**Comment by YahnisElsts** [comment]
GitLab support would be nice to have, but I don't have any definite plans to add it. I don't use GitLab myself, and I'm currently busy enough as it is.

Pull requests welcome!

**Comment by eyeinsky** [comment]
Close this issue since it's merged and worked out-of-the-box for me?

**Comment by YahnisElsts** [comment]
Thanks for the reminder. I'll close it now.
