### ISSUE TITLE
PUC doesn't display any info

### ISSUE THREAD

**Issue by mahdiyazdani** [YahnisElsts/plugin-update-checker#111]
Hello

I have tried to integrate this with my private repo, but it keeps saying the plugin is up to date which I clearly know it is not.
Here is what I did:
1- Followed the guideline step by step
2- Created an access token key
3- Created a release tag and bumped version number

Still, can't see any info on PUC tab!

**Comment by YahnisElsts** [comment]
When you say "tab", do you mean the "PUC (slug)" tab in the [Debug Bar](https://wordpress.org/plugins/debug-bar/)? If not, install Debug Bar and do look at that tab. It should show a bunch of debugging information. Try clicking the "Request info" and see if it returns valid plugin data.

**Comment by mahdiyazdani** [comment]
Yes, that is it.
As you can see, there isn't any!
Any help would be greatly appreciated

https://i.gyazo.com/cb8541de3d383c86baabcc71435cdf21.png

**Comment by mahdiyazdani** [comment]
@YahnisElsts 
Also not sure where is the "Request Info" button?
All I have is an empty screen.

**Comment by YahnisElsts** [comment]
A completely empty screen suggests that there could be a fatal PHP error somewhere. Check the PHP error log. There will probably be a message with a timestamp matching the last time when you tried to look at the tab (though it might not mention PUC or your plugin as such).

As for the "Request info" button, normally it's in that tab.

**Comment by YahnisElsts** [comment]
A JS error could also break the Debug Bar tab, but I don't think it would empty in that case. More likely, you just wouldn't be able to select it.

**Comment by mahdiyazdani** [comment]
Since I don't have any fatal error and my WP_Debug is already enabled, I must say not sure what is happening here.
Would you mind if I ask you to take a look at this in a second?

**Comment by robertharm** [comment]
@mahdiyazdani you are using an old version of plugin update checker which is not compatible with debug-bar v0.9, try either updating your plugin update checker to the latest version or downgrade debug-bar to v0.8.4 (https://wordpress.org/plugins/debug-bar/advanced/)

**Comment by mahdiyazdani** [comment]
Found the content. Can't believe it is been hidden by CSS!
https://i.gyazo.com/4398443142be190f34f36135ff913814.png
Here is the content, could you tell me what is missing here?
https://i.gyazo.com/f12587ebae6736bc7336a6c2d9bec503.png

**Comment by mahdiyazdani** [comment]
@YahnisElsts 
Here is what I get when I am trying to request for info.
```
Warning: set_time_limit(): Cannot set max execution time limit due to system policy in /customers/4/0/7/XXX/httpd.www/dev/wp-content/plugins/XXX/includes/plugin-update-checker/Puc/v4p1/Vcs/PluginUpdateChecker.php on line 35 Successfully retrieved plugin info from the metadata URL:
```

**Comment by mahdiyazdani** [comment]
Reached to my service provider support and it seems ```set_time_limit``` is not allowed to use due to security risks.
Is there anything that we can do about this?

**Comment by YahnisElsts** [comment]
`set_time_limit` is probably not the issue here. The warning is annoying (I'll need to do something about that), but it doesn't prevent updates from showing up.

> Here is the content, could you tell me what is missing here?
> https://i.gyazo.com/f12587ebae6736bc7336a6c2d9bec503.png

The `version` field in the "cached update" section looks wrong. Double-check that the "Version:" header of the 2.0.0 release has the correct value.

**Comment by mahdiyazdani** [comment]
Not sure where to check? Any info on this, please?
I just created a new release using Github release feature with tag name 2.0.0.

> The version field in the "cached update" section looks wrong. Double-check that the "Version:" header of the 2.0.0 release has the correct value.

**Comment by YahnisElsts** [comment]
Check the main plugin file in the release. Is "Version" set to 2.0.0?

**Comment by mahdiyazdani** [comment]
Solved it. Thanks.
But still had to comment ```set_time_limit``` line.
