### ISSUE TITLE
Can't detect update versions < 1.0

### ISSUE THREAD

**Issue by cjfagerstrom** [YahnisElsts/plugin-update-checker#113]
I'm working on a beta plugin and I tried listing my current plugin as v 0.1 and the update as v 0.2, but PUC will not recognize that there is an available update for my plugin. If I change it to v 1.0 and update v 1.1 it will detect a new update available.

**Comment by YahnisElsts** [comment]
That sounds improbable. What are you using to provide updates (JSON, GitHub, BitBucket)? Is PUC able to retrieve the current version number (use [Debug Bar](https://wordpress.org/plugins/debug-bar/) to check)?

**Comment by cjfagerstrom** [comment]
Improbable or not, it says I'm up to date with 0.1 ->0.2 but says there is an update if I do 1.0 ->1.1. I'm using JSON and trying to fetch it from a public directory on the same server.

**Comment by cjfagerstrom** [comment]
Well, I'm not sure what was happening. I just loaded debug bar and setup the version numbers to check and it's working properly now. I had reverified the issue 3 times and got it to show me there was an update available by bumping the v to 1.0, and then reverified by dropping it back down to 0.1, but now it's doing what it should. The only thing I can think of is I did wipe everything out of my plugin directory and reloaded it in after getting it to update, so maybe I had a problematic bit of code somewhere that got cleared out. Sorry to bother you!

**Comment by YahnisElsts** [comment]
I don't doubt that there is/was an issue; my "improbable" comment was about it being caused by versions <1.0. Sorry for not being clear.

If something like this happens again, try clicking the "Request Info" button in the "PUC (slug)" Debug Bar panel and see if it returns the version information that you would expect. Maybe something, somewhere was caching the old JSON response.

**Comment by cjfagerstrom** [comment]
That makes sense. I do have a caching plugin on my site that I was testing serving from. I thought it was odd but I figured maybe you had something in there assuming people wouldn't use numbers less than 1. Thanks for the suggestions!

_____________________________

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a couple of years. 

If you still encounter problems with version numbers lower than 1.0, feel free to reopen the issue or create a new one.
