### ISSUE TITLE
Bitbucket Server possible?

### ISSUE THREAD

**Issue by regenrek** [YahnisElsts/plugin-update-checker#119]
Hi,

we host our repository on a Bitbucket Server instance.
The url doesn't include anything like bitbucket.org / github.org ...
so it's no possible to use the desired Class which provides us setBranch and
the repository methods.

Our repo url is like 

```http://codebase.<url>/projects/plugins/repos/myplugin/browse```
or
```http://<user>@codebase.<url>/scm/plugins/myplugin.git.```

I tried to configure it like something like this:

```php
		$updateChecker = Puc_v4_Factory::buildUpdateChecker(
			"http://codebase.<url>/projects/plugins/repos/myplugin"
			MY_PLUGIN_DIR, // which points to wp-content/plugins/my-plugin
			'my-plugin'
		);
$updateChecker->setBranch('master');
```

This fails since it uses the Plugin_UpdateChecker Class.

Is there any possibility where I can use the Class directly (maybe without the factory) to
achieve something like the  [github-integration](https://github.com/YahnisElsts/plugin-update-checker#github-integration).

Our Code is public (Bitbucket Public Repository) so no token is needed and it should work out of the box since Bitbucket Server is like Bitbucket (but with slightly other url structure).

Regards

**Comment by YahnisElsts** [comment]
**Short answer:**
You'll need to extend the `Puc_v4p2_Vcs_BitBucketApi` class to make it understand your custom repository URL. Then you'll need to manually construct a `Puc_v4p2_Vcs_PluginUpdateChecker` instance and pass an instance of your custom API class as the first constructor argument.

**Long answer:**
The main obstacle is that the current BitBucket API implementation expects a particular repository URL structure and your URL doesn't match those expectations.

You'll need to create a subclass that applies some custom logic to repository URLs and API requests. At a glance, it looks like you'll need to override these methods:
- `__construct` - to extract username and repository from the URL.
- `getDownloadUrl` - to build download links for specific refs (i.e. branches or tags).
- `api` - to send API requests to your own API endpoint instead of `api.bitbucket.org`.

Once that's done, you can initialise the update checker like this:

```php
$updateChecker = new Puc_v4p2_Vcs_PluginUpdateChecker(
    new MyCustomBitBuckerApi('repository-url-here'),
    $fullPathToPluginFile, //Note: Main plugin file, not just directory.
    'plugin-slug'
);
```

**Comment by regenrek** [comment]
Hi,

thank you for your response. I discovered this yesterday and ended up with this.
Actually everything seems to work but when I try to update the plugin it fails
with an error (See Screenshot) http://imgur.com/a/lF7ku

When I Click "Update" Wordress tells me "No Valid URL given" ...

Here is a quick'n'dirty implementation:

```php
$this->api = new BitbucketServerApi("http://code.company.com:7990/rest/api/latest/projects/PLUGINS/repos/myplugin/");
		$this->updateChecker = new Puc_v4p2_Vcs_PluginUpdateChecker(
			$this->api,
			MJ_ACF_FIELDS_PLUGIN_DIR . 'my-plugin.php',
			'my-plugin');
```

Full Source: https://gist.github.com/regenrek/e88c733078214699c487a8cbbe7f5e4b

**Comment by YahnisElsts** [comment]
Does the displayed download URL work if you try to open it manually? Try the "request info" button - does it display valid information?

Also, that's more code than I expected. Is the BitBucket Server API incompatible with the BitBucket.org API, or is there some other reason why you're rewriting most of the API class? 

There are also a few bugs in the code. For example, in `getRemoteFile` file name and ref are hardcoded. This will cause problems if you need any information from readme.txt or the changelog. Tag sorting is commented out, which could cause the wrong version number to show up in certain situations.

**Comment by regenrek** [comment]
> Also, that's more code than I expected. Is the BitBucket Server API incompatible with the BitBucket.org API, or is there some other reason why you're rewriting most of the API class?

Yes the paths are slightly different. Also the validation stuff doesn't match with bitbucket.org.
Since I use public repositories with Bitbucket Server (not private) I don't need the authentication stuff so I skipped them.

For example this is the path how you could read tags via rest api:
https://developer.atlassian.com/static/rest/bitbucket-server/5.2.2/bitbucket-rest.html#idm45866556807520

>There are also a few bugs in the code. For example, in getRemoteFile file name and ref are hardcoded. This will cause problems if you need any information from readme.txt or the changelog. 

Oh true. I've been wondering why the readme fails. Ok I will check this again.

>Tag sorting is commented out, which could cause the wrong version number to show up in certain situations.

Yes there is slightly different output in the rest api. But it works out of the box. This doesn't make any problems. 
http://code.macherjek.com:7990/rest/api/latest/projects/MJPLUG/repos/mj-acf-fields/tags

**Comment by YahnisElsts** [comment]
It looks like you could make sorting work by setting `$this->tagNameProperty` to `displayId` in the class constructor.

**Comment by regenrek** [comment]
Ok it seems that I have to differ between rest api url and repo url. Some things like tags/branch infos are available via rest api and files are via the repo url. 


I updated now the code https://gist.github.com/regenrek/e88c733078214699c487a8cbbe7f5e4b
but the updates fails again.
Maybe its not possible to update a plugin with a file structure like archive...&format=zip.

Don't know...

Regards

**Comment by YahnisElsts** [comment]
If it was a problem with the archive structure you'd get a different error message. By the way, is "No Valid URL given" the full message? I can't seem to find anything like that in WordPress source code.

**Comment by regenrek** [comment]
Oh moment i just translated it from german. 

Here is the full ajax response output. But Url works if you call it in the browser.

http://imgur.com/a/bWH9n

http://code.macherjek.com:7990/rest/api/latest/projects/MJPLUG/repos/mj-acf-fields/archive?at=refs%2Ftags%2F0.0.6&amp;format=zip&#160;&hellip;

**Comment by YahnisElsts** [comment]
Thank you, the full output was helpful. I'm looking at the source code for `wp_http_validate_url` and it seems that WordPress validates the port number when checking if a URL is "safe to use". It allows only these ports: 

- 80
- 443 
- 8080
- The port used by the current site. 

This means that your download URL won't work because WP thinks port 7990 is invalid or unsafe.

I *think* you could get around that restriction by using the `http_request_args` filter to set the `reject_unsafe_urls` argument to `false` when the URL host name matches your site. I don't have any example code handy, though.

**Comment by regenrek** [comment]
Mh `reject_unsafe_urls()` has default value `false`so this doesn't seem the problem here. I will check it further. Also tried to set it to true but then it fails without any error message.

**Comment by YahnisElsts** [comment]
WordPress uses `download_url()` to download updates, which calls `wp_safe_remote_get()`, which sets `reject_unsafe_urls` to `true`.

Be careful with globally disabling `reject_unsafe_urls`. Presumably, there's a reason why it's there, and some plugins might rely on `wp_safe_remote_get()` working as documented. Check the host name before changing request arguments.

> Seems relevant here #61 (comment)
> but is it possible to use the Plugin Structure where the files are in the root and not in a slugname/ Folder?

The last time that I looked at that part of WordPress core, I didn't see any practical ways to do that. If you can figure out how to do it without reimplementing half of `WP_Upgrader`/`Plugin_Upgrader`, I'm all ears. However, it would probably be much easier to just use the recommended directory structure.

**Comment by regenrek** [comment]
Ok i moved the plugin files int to a subdirectory but I get the same error message.


Message: `Update Failed: The directory structure of the update is incorrect. All files should be inside a directory named mj-acf-fields, not at the root of the ZIP archive.`
Repo here: http://code.macherjek.com:7990/projects/MJPLUG/repos/mj-acf-fields/browse?at=0.0.8

**Comment by YahnisElsts** [comment]
*All files* should be inside a directory. That repo still has a bunch of files at the top, e.g. `._.DS_Store` and `._README.md`.

**Comment by regenrek** [comment]
Ok, didn't thought that could cause problems. Yep the error is now gone but I get another one. 

`Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.`

I tried to update some other plugin to test if permissions are incorrect. Worked. Do you know some ways to debug this issue? I reset the permissions according https://aaronjholbrook.com/wordpress-permissions-update-error-resolved/ but nothing happened.

Thanky you!

**Comment by YahnisElsts** [comment]
Interesting, I haven't seen that particular error before.
So is it working now?

**Comment by regenrek** [comment]
Yes. I don't know my permissions on the server are really messed up. But after I change the owner:group to www-data:www-data the update worked without any problems.

Finally! Thank you!
