### ISSUE TITLE
'auto_update_plugin' core filter

### ISSUE THREAD

**Issue by pipdig** [YahnisElsts/plugin-update-checker#120]
I was wondering, does this class work with the [auto_update_plugin](https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter) core filter?

`add_filter( 'auto_update_plugin', '__return_true' );`

I can't seem to get it working, but I just wanted to double check it isn't a configuration issue at our end.

**Comment by YahnisElsts** [comment]
I think it should work, but I haven't actually tested it. What have you tried so far? Do automatic background updates work for other plugins on your site?

**Comment by pipdig** [comment]
When I tested it, the only plugin update available was from this class. There were no "normal" updates available from the w.org repo, so maybe the update process was not being triggered at all. I'll do some proper testing now and let you know how it goes.

**Comment by pipdig** [comment]
I had a chance to test this properly on the following:

- New WordPress site on 4.7.5.
- Set WP_AUTO_UPDATE_CORE to true.
- Install some older w.org plugins/themes.
- Install some older custom plugins/themes (custom theme active so updates show).
- Set both plugin and theme updates to true via [filters](https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter).

All updates were showing correctly in the dashboard.

When the automatic update was run via the next cron, the site updated to 4.8 and all the w.org plugins/themes also updated. However the custom plugins/themes did _not_ update. So it looks like the class is not triggering in the auto-update feature, unfortunately. It would be awesome if this could be added in future. I appreciate it might not be a big request for people though.

**Comment by YahnisElsts** [comment]
All right, I finally got a chance to test it myself. Unfortunately, I can't seem to reproduce the problem. 

I created a basic plugin and enabled plugin updates via the `auto_update_plugin` filter. There were also several pending updates for plugins from wordpress.org. I triggered the automatic updater by running the `wp_version check` cron event. All of the plugins got updated, including the custom plugin that's using PUC.

Are you sure your plugins/themes are set up correctly and have the right file permissions? If I'm reading the automatic updater source code correctly, WordPress will abort an automatic update if the file permissions aren't exactly right.

**Comment by pipdig** [comment]
Interesting! The file permissions should all be correct, however I'll give this another try on a fresh install using a different server to double check.

**Comment by YahnisElsts** [comment]
Did you get a chance to test it on a fresh install yet?

**Comment by pipdig** [comment]
Hi Yahnis, not yet unfortunately. I am still planning on testing it as soon as I get a chance though. I'll let you know how it goes hopefully within the next few days

**Comment by pipdig** [comment]
Sorry it took so long to re-test this. I have now had a chance to test this fully. It looks like the update was failing due to an issue with the zip of the plugin. I tried changing the updater to use a Bitbucket repo and it updated no problem. I'm guessing it didn't like the way the zip was generated manually in the other version.

So I think this issue can be closed!
