### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by qwqoffice** [YahnisElsts/plugin-update-checker#121]
Is possiable auto update when a new version is available, instead of click a update button?

**Comment by OoqwqoO** [comment]
Only for current plugin.

**Comment by OoqwqoO** [comment]
add a argument auto_update to function buildUpdateChecker, if auto_update is true then add a filter to enable auto update for current plugin: 
```
function auto_update_specific_plugins ( $update, $item ) {
    if ( $item->slug == 'PLUGIN_SLUG' ) ) {
        return true; // Always update current plugin 
    } else {
        return $update;
    }
}

add_filter( 'auto_update_plugin', 'auto_update_specific_plugins', 10, 2 );
```

**Comment by YahnisElsts** [comment]
I'm ambivalent about this feature. 

- How many developers would actually use it? AFAIK, very few plugins enable automatic background updates.
- It looks simple. Perhaps too simple? You don't need a library function for 2+2.
- Even trivial features have maintenance costs.

Let's leave it open and see if anyone else chimes in.

**Comment by OoqwqoO** [comment]
I am making a plugin for my customer's website, to send statistic data to us, when I update this plugin, I must take a long time to update it for my each customer, if it  can update automatically, all things will be down to just upload a latest plugin.

**Comment by MikhailRoot** [comment]
Agree with @OoqwqoO  It's good feature to have. especially if you use it to manage updates for multiple plugins.

**Comment by MikhailRoot** [comment]
Btw, solved it with this approach, without even need to modify existing update-checker library
https://gist.github.com/MikhailRoot/fccdf066d883682c335c33ec749a4e31
In my case all plugins are in bitbucket.

**Comment by DavidAnderson684** [comment]
I agree with Yahnis - that this is too simple to bother adding to the library. The necessary code is just one line, isn't it?

```
function auto_update_specific_plugins ( $update, $item ) {
    return ($item->slug == 'PLUGIN_SLUG') ? true : $update;
}
````

**Comment by YahnisElsts** [comment]
Yes, as far as I know, it really is that simple.

**Comment by nhymxu** [comment]
can silent auto update ( not WP core auto update ) or server can send request to client website and client auto update special plugin/theme

**Comment by YahnisElsts** [comment]
No, that's currently not supported. However, you could do something similar by enabling WP core auto update and then showing an update only to a specific client. The client website would then automatically install the update, though there would be some delay - it's an asynchronous process.

**Comment by nhymxu** [comment]
@YahnisElsts  thanks, I have other solutions.
After PUC check update, this class update transient **update_plugins** or not?
Because I see data in **external_updates-$pluginslug** but not found data in **_site_transient_update_plugins**

thansk you

**Comment by YahnisElsts** [comment]
No, this library doesn't update the actual `update_plugins` transient. Instead, it filters the value of this transient by using the (`site_transient_{$transient}`)[https://developer.wordpress.org/reference/hooks/site_transient_transient/] hook. As far as I know, WordPress doesn't write the filtered value back to the database.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

At the moment, there are no plans to add an "enable automatic update installation" feature to this library. For those who need it, the [`auto_update_plugin` filter](https://wordpress.org/support/article/configuring-automatic-background-updates/#plugin-theme-updates-via-filter) mentioned above should still work.
