### ISSUE TITLE
Update available by count but not in the list

### ISSUE THREAD

**Issue by dhunink** [YahnisElsts/plugin-update-checker#123]
Hi,

I've spend the entire day on getting the update-checker and update-server to work. I believe I'm pretty close but keep running into the same issue: according to the little red counter icon there's '1' update available, but when going into the update screen there is nothing there. 
![schermafbeelding 2017-08-08 om 00 24 21](https://user-images.githubusercontent.com/2500356/29048253-03ff3fa6-7bd0-11e7-9e51-ee975ed5fe78.png)

<img width="649" alt="schermafbeelding 2017-08-08 om 00 25 05" src="https://user-images.githubusercontent.com/2500356/29048272-0c9bad2a-7bd0-11e7-9f1b-21de222a9d61.png">

I have installed the WP Debug Toolbar (great suggestion btw). Looks okay to me:
![schermafbeelding 2017-08-08 om 00 25 39](https://user-images.githubusercontent.com/2500356/29048301-29d6d93c-7bd0-11e7-9156-267159b16d27.png)

What am I missing here? What would be the way to go to debug this even further?

**Comment by YahnisElsts** [comment]
It looks like the "plugin file" value is incorrect. It should be the main plugin file - that is, the PHP file that contains the plugin header - not some other file in a subdirectory. 

My guess is that you used the `__FILE__` constant as the second argument to the `buildUpdateChecker` constructor. That only works if the initialisation code is in the main plugin file. Replace the constant with the absolute path to the main file. What I usually do is define a constant like `XYZ_PLUGIN_FILE` in the main file so that I can easily use it in other files.

**Comment by dhunink** [comment]
That indeed did the trick. @YahnisElsts your a hero :) 

For reffenece: I used `plugin_dir_path( __DIR__ ).'main-plugin-file.php'` in the call that's located in /my-plugin/admin/update-checker.php. Worked like a charm :)

**Comment by YahnisElsts** [comment]
That probably means there's no download URL. Are you doing anything special with the URL, like hiding it from people who don't have a license? Double-check that code.

**Comment by YahnisElsts** [comment]
> For reference: I used `plugin_dir_path( __DIR__ ).'main-plugin-file.php'` in the call that's located in /my-plugin/admin/update-checker.php. Worked like a charm :)

That works, but I wouldn't recommend it as a general solution. Consider this paragraph in [WordPress docs](https://developer.wordpress.org/reference/functions/plugin_dir_path/#more-information):
> The “plugin” part of the name is misleading – it can be used for any file, and will not return the directory of a plugin unless you call it within a file in the plugin’s *base* directory.

If your code was in a deeper subdirectory (e.g. `.../my-plugin/admin/includes/foo/update-checker.php`) then that code wouldn't work.

**Comment by dhunink** [comment]
Yes I do indeed. But when [visiting in a browser](http://download.escaperoomresults.com/update-server/?action=get_metadata&slug=escape-room-game-results&installed_version=1.7.0.1&php=7.0.21&locale=nl_NL&checking_for_updates=1&license_key=testLicenseKey78), all the info looks correct. As soon as I check using the Debug Bar however, the download_url appears to be empty:
![schermafbeelding 2017-08-09 om 02 19 07](https://user-images.githubusercontent.com/2500356/29100012-27e2f596-7ca9-11e7-98af-4b3c4344627f.png)

I've gone through all the docs and examples over and over again but find myself lost regarding this issue; can't figure out why this is possible.

For the server-side code on the update-server:
`<?php
class ErgrSecureUpdateServer extends Wpup_UpdateServer {
	protected $licenseServer;
 
    public function __construct($serverUrl, $licenseServer) 

	{
        parent::__construct($serverUrl);
  
    }
    
    protected function initRequest($query = null, $headers = null) 
	{
        $request = parent::initRequest($query, $headers);
 
		
		$license = null;
		$result = false;
		if ( $request->param('license_key') ) 
		{
			//Validate the license_key
			$result = $this->isLicenseValid($request->param('license_key'));
			if($result)
			{
				$license = $request->param('license_key');
			}
			else
			{
				$license = $result;
			}
		}
 
        $request->license = $license;
		$request->license_valid = $result;
        return $request;
    }
 
    protected function filterMetadata($meta, $request) 
	{
        $meta = parent::filterMetadata($meta, $request);
 
        //Include license information in the update metadata. This saves an HTTP request
        //or two since the plugin doesn't need to explicitly fetch license details.
        $license = $request->license;
        if ( $license !== null ) 
		{
            //$meta['license'] = $this->licenseServer->prepareLicenseForOutput($license);
			$meta['license'] = $license;
        }
 
        //Only include the download URL if the license is valid.
        if ( $license && $this->isLicenseValid($license) ) 
		{
            //Append the license key or to the download URL.
            $args = array( 'license_key' => $request->param('license_key') );
			$meta['license_valid'] = $request->license_valid;
            $meta['download_url'] = self::addQueryArg($args, $meta['download_url']);
        } else 
		{
            //No license = no download link.
            unset($meta['download_url']);
        }
 
        return $meta;
    }
 
    protected function checkAuthorization($request) 
	{
        parent::checkAuthorization($request);
 
        //Prevent download if the user doesn't have a valid license.
        $license = $request->license;
        if ( $request->action === 'download' && ! ($license && $this->isLicenseValid($license)) ) 
		{
            if ( !isset($license) ) {
                $message = 'You must provide a license key to download this plugin.';
            } else 
			{
                $error = $license->get('error');
                $message = isset($error) ? $error : 'Sorry, your license is not valid.';
            }
            $this->exitWithError($message, 403);
        }
    }
	
	protected function isLicenseValid($license_key)
	{
		//@TODO: validate against a list/database
		return true;
	}
	
}`

**Comment by YahnisElsts** [comment]
The server-side code seems fine at first glance. How about the plugin code? Could it be that the license key got lost/was removed while you were trying to get the update to show up?

The update server logs all update checks in the `/wp-update-server/logs/request.log` file. Take a look at it and verify that the plugin is actually sending the `license_key` argument to the server.

**Comment by dhunink** [comment]
Wow. Just when I thought I had double-double-double checked everything... 
I did made a small typo in a very hidden place that indeed stopped sending the license keys from the websites using the plugin. Thanks so much point me in the right direction (once again).
Keep up the good work with this amazing set of plugins!
