### ISSUE TITLE
No update showing as available

### ISSUE THREAD

**Issue by Mitosis89** [YahnisElsts/plugin-update-checker#125]
I'm attempting to use this to serve updates to my plugin using a JSON and delivering from my own server (no GitHub integration or anything). I followed the Getting Started directions and the plugin installs and activates fine, but when I check for updates it never detects any.

To note, the index.php header of my plugin specifies a version number of 1.0, which is what appears on the WordPress plugin page when installed.

I started by dropping the plugin-update-checker-4.2 directory into my main plugin folder.

This is the code I added to the main file of my plugin (/myplugin/index.php):

```
require 'plugin-update-checker-4.2/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'http://mydomain.com/my-plugin/plugin.json',
	__FILE__,
	'my-plugin'
```

This is the contents of the .json:

```
{
	"name": "My Plugin",
	"version": "1.1",
	"download_url": "http://mydomain.com/my-plugin/MyPlugin.zip",

	"homepage": "http://mydomain.com",
	"requires": "4.5",
	"tested": "4.8",
	"last_updated": "2017-08-10 11:17:00",

	"author": "Me",
	"author_homepage": "http://mydomain.com",

}
```

I then uploaded a new version of the plugin (identical but with 1.1 in the plugin header in index.php) to "mydomain.com/my-plugin/MyPlugin.zip".

WordPress is reading the correct version (1.0) when installed. I double checked in editors that the plugin as installed in WordPress has the correct link to the .json, and that the .json has the correct link to download the updated plugin (the one flagged in the .json and the header in index.php of the plugin itself as version 1.1).

WordPress simply doesn't detect the update: when I check for updates, it says I have the latest version. I've redone the entire process twice and troubleshooted significantly besides but I can't find the problem. Any help would be appreciated.

**Comment by YahnisElsts** [comment]
Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and look in the "PUC (my-plugin)" panel. There should be a "request info" button there. Try clicking that and verify that it displays the version information that you would expect.

**Comment by Mitosis89** [comment]
Thank you! 

The Debug Bar plugin said there was a problem with the .json metadata and directed me to https://jsonlint.com/ where I could tweak the .json and figure out where the error was. There was an errant comma that was breaking the whole thing. As soon as I got a valid .json, WordPress updated the plugin flawlessly.
