### ISSUE TITLE
ParsedownLegacy.php on PHP7

### ISSUE THREAD

**Issue by chirox** [YahnisElsts/plugin-update-checker#126]
This file through 1 error when run PHP Compatibility Checker. The log here:
 
/plugin-update-checker/vendor/ParsedownLegacy.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1412 | ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.

**Comment by YahnisElsts** [comment]
This file is included for backwards compatibility. It's only used when the site is running PHP 5.2 or below.
