### ISSUE TITLE
Download failed. Service Unavailable when serving the update with php

### ISSUE THREAD

**Issue by sohan5005** [YahnisElsts/plugin-update-checker#127]
Hi,

I'm keeping the zip files outside web root. Then using PHP to serve the download. The download link looks some thing like this:

`http://example.com/?action=download&api_key=000_000&package=my-plugin-slug&ver=2.0`

I'm using the API key to authenticate the user and then serving the file download. The link is perfectly doing it's job. The zip file is downloading perfectly without any error when:
1. Paste the link to browser and download
2. Paste the link to a downloader app
3. Download with a PHP script with `file_get_contents()` with the same url
4. Download with a PHP script with cURL with the same url
5. Download the file with WordPress function `download_url()` with the same url

But when I'm trying to update the plugin, this message appears:

_An error occurred while updating Sample Plugin: **Download failed. Service Unavailable**_

Any idea what is causing the issue?

Thanks in Advance
Sohan

**Comment by sohan5005** [comment]
Oops! Just found the issue after 2 days of troubleshooting and 5 minutes of reading :p

I was trying to update in the same site that serving it and I was using WordPress to serve the update. So when I try to update, it turns on maintenance mode and download url no longer works.

Source: http://docs.easydigitaldownloads.com/article/1413-software-licensing-troubleshooting-update-issues

By the way, Thanks a lot for this awesome library!

**Comment by ve3** [comment]
This may related issue ( https://github.com/YahnisElsts/plugin-update-checker/issues/489 )

I answer here because this issue appears on Google and I think it may helpful with the other.
