### ISSUE TITLE
Displays Update available when both versions are the same

### ISSUE THREAD

**Issue by Twister1002** [YahnisElsts/plugin-update-checker#128]
In my experience with this so far, I've noticed that when I set the json file to 1.2.2 and the current version is 1.2.2 it will show that there is an update available when there is no update. This is highly confusing.

**Comment by YahnisElsts** [comment]
What version number does it show for the update? Does the "view version X details" screen display the correct details from the JSON file or something else (e.g. outdated information)?

Also, install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and take a look at the "PUC (your-plugin-slug)" panel in the "Debug" menu. Do all of the settings look correct? Does the "Request Info" button work and does the info that shows match your JSON file?

**Comment by Twister1002** [comment]
It doesn't give be a "view details" in the updates section. It says: "You have version 1.0.20 (2017-08-30) installed. Update to 1.0.20."

I also do not see any information about "PUC-<plugin>" in the debug menu. All I have is "Object Cache"

**Comment by YahnisElsts** [comment]
That sounds like the update checker isn't even running. What does your initialisation code (i.e. the part with `buildUpdateChecker`) look like and are you sure it's being executed?

**Comment by Twister1002** [comment]
I am 100% positive the updater code is working. I've been able to force updates (when needed by using `add_filter("puc_check_now-".$toUpdate["slug"])` . It also checks the correct URL and grabs all the correct information. I've also been able to download and install updates using this as well.

**Comment by YahnisElsts** [comment]
Interesting. Would you be willing to show me the JSON file and the relevant part of the plugin code? If you don't want to post them publicly, you can contact me via email: `whiteshadow@w-shadow.com`

**Comment by Twister1002** [comment]
theme/info.json
```
{
  "version" : "1.0.23",
  "details_url" : "http://website.com/changelog.html",
  "download_url" : "http://website.com/theme.zip"
}
```

The code used to get the information and such:

```
$toCheck = apply_filters("CheckForUpdates", array());

            foreach ($toCheck as $toUpdate) {
                $checker = Puc_v4_Factory::buildUpdateChecker(
                    ($this->isDev ? self::DEV : self::PRODUCTION).($toUpdate["isPlugin"] ? "plugins" : "themes")."/".$toUpdate["slug"]."/info.json",
                    $toUpdate["file"],
                    $toUpdate["slug"],
                    1
                );

                // Force updates
                if ($this->isDev) {
                    add_filter("puc_check_now-".$toUpdate["slug"], function($shouldCheck, $lastCheck, $period) {
                        return true;
                    }, 1, 3);
                }
            }
```

**Comment by YahnisElsts** [comment]
I missed it at first, but I think I see what the problem is now: PUC uses [`version_compare()`](http://php.net/manual/en/function.version-compare.php) to compare version numbers, and this function treats `1.0.20 (2017-08-30)` as lower than `1.0.20`. This is probably a side-effect of how `version_compare()` handles alpha/beta/RC versions: `1.2RC1` is lower than `1.2` and so on. See PHP docs for details.

Suggestion: Remove the date from the `Version` header.

**Comment by Twister1002** [comment]
Yep the fixed the issue. So good note: Don't add anything to the version number except the version.

Appreciate the help, now I can have ease of mind :)
