### ISSUE TITLE
Puc Request Info Doesn't Work Bitbucket

### ISSUE THREAD

**Issue by justadaniel** [YahnisElsts/plugin-update-checker#129]
Hey, I'm having issues with trying to get my plugin to update. I tried multiple times and I can't get it to work at all. Everything should be working and I'm dumbfounded. I have a private repository and I setup the consumer key and secret for the plugin, I put in the readme the correct version, I used the debug bar and clicked the Request Info button, but it doesn't work for some reason. Would you mind helping me out? Here is the code below from my functions.php.

`require_once(MONSTRUM_ROADMAP_DIR . '/plugin-update-checker.php');`
`$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(`
`	'https://bitbucket.org/dacheezypuffs/roadmapper',`
`	__FILE__,`
`	'monstrum-roadmap'`
`);`

`//Optional: If you're using a private repository, create an OAuth consumer`
`//and set the authentication credentials like this:`
`$myUpdateChecker->setAuthentication(array(`
`	'consumer_key' => 'XXXXXXXX',`
`	'consumer_secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',`
`));`

`//Optional: Set the branch that contains the stable release.`
`$myUpdateChecker->setBranch('dev');`

Let me know if you need any more information.

**Comment by YahnisElsts** [comment]
What exactly happens when you click the "Request Info" button, if anything?
Also, does the debug panel show the correct API client (`Puc_v4p2_Vcs_BitBucketApi`)?

**Comment by justadaniel** [comment]
Absolutely nothing happens when I click it. It looks like I didn't click it and yeah it does show the correct API client.

<img width="960" alt="2017-09-02 18_59_28" src="https://user-images.githubusercontent.com/1112585/29999517-279492ae-9011-11e7-807b-2a16297ae62e.png">

**Comment by YahnisElsts** [comment]
That sounds like there's a JavaScript error somewhere. Check [the JS console](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers) for error messages. Most likely, an error will show up either when you open the page or when you click the button.

Also, the formatting of the debug info looks a bit different from the usual. Are you using a custom admin theme? Alternatively, could it be that a bug in another plugin or theme is preventing some CSS/JS files from being loaded?

**Comment by justadaniel** [comment]
Actually there isn't anything modifying the admin side. The JS Console also just has a single log in it.

<img width="957" alt="2017-09-03 05_13_11" src="https://user-images.githubusercontent.com/1112585/30002125-3235832a-9067-11e7-9d31-17e49aed7e15.png">

**Comment by YahnisElsts** [comment]
Here's how it should look:
![puc-ame-debug-panel](https://user-images.githubusercontent.com/2527434/30002185-8c273b64-90ab-11e7-8f3a-60a9d828f322.png)

The formatting is similar, but there's clearly some CSS missing from your example. That suggests that some JS could also be missing, which would explain why the "Request Info" button does nothing.

Take a look at the page source and verify that these two files are being loaded:
- `plugin-update-checker/css/puc-debug-bar.css`
- `plugin-update-checker/js/debug-bar.js`

**Comment by justadaniel** [comment]
Yeah they aren't getting called. I don't know what it could be either.

**Comment by YahnisElsts** [comment]
Is there anything that could be messing with CSS output? Optimization plugins, caching tools, domain mapping, custom script concatenation solutions, URL filtering, custom redirects?

In case you're curious, the code that enqueues the CSS and JS is in `/Puc/v4p2/DebugBar/Extension.php`.

**Comment by justadaniel** [comment]
Ok, let me run this in another environment, eliminate some variables, and I'll come back to this.

**Comment by justadaniel** [comment]
I got it working now. It turns out it was missing a file. Sorry about the issue!
