### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT

### ISSUE THREAD

**Issue by NimbusDigital** [YahnisElsts/plugin-update-checker#130]
This may be entirely unrelated to PUC, but I wondered if anyone can shed any light on this error message? It shows up when I first try to update my plugin via PUC. However, if I attempt the same update for a second time, the update is installed successfully.

`Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`

**Comment by YahnisElsts** [comment]
The message means that the ZIP file is either corrupted or not a ZIP file at all. Maybe the update download got interrupted due to a network error or something like that? Make sure that the download link works reliably.

**Comment by NimbusDigital** [comment]
Thanks - that's kind of what I gathered... just strange it works 2nd time.

**Comment by YahnisElsts** [comment]
Does it *always* work on the second attempt, or is it semi-random? If there's an intermittent network issue, it might sometimes work on the first try, and sometimes on the 3rd.

**Comment by NimbusDigital** [comment]
Seems always on the 2nd attempt.

My current thinking is it's either something to do with the way my computer ZIPs up the plugin folder (though I'm just using my Mac's built-in "Compress" command), or it's something to do with my hosting environment. I've tested on a couple of dev sites, but I do not have access to other hosting platforms to test. 

Thanks for your help, anyway.

**Comment by YahnisElsts** [comment]
Actually, some other users have reported problems with making ZIP files on a Mac, though they were usually not related to file corruption. Try a third-party archiver. I'm not familiar with macOS, but I think [7-zip](http://www.7-zip.org/download.html) might have an unofficial version for that system.

**Comment by NimbusDigital** [comment]
Well, you know what, I re-zipped my plugin folder using Keka (a free Mac port of 7-zip).
I uploaded an old version and then ran PUC.

All updated successfully first time!

It's a bit strange because I had been using the built-in Mac Zip utility without problem until recently. Perhaps an update borked it in some way?

Also note, Keka allowed me to automatically exclude Mac cruft (.DS_store files etc.) - maybe that helped?

Anyway, all seems to be working now. Thanks!

**Comment by YahnisElsts** [comment]
I'm not sure could cause the built-in utility to produce seemingly invalid files, but it's good to hear that Keka worker for you. 

I'll close this issue now.
