### ISSUE TITLE
Re-install, re-update plugin

### ISSUE THREAD

**Issue by claytoncollie** [YahnisElsts/plugin-update-checker#132]
I updated my plugin and it threw a generic error about connection timing out. Caused a bit of mess from not all of the files being updated properly.  It got me thinking that maybe there can be an option to re-update or re-install the plugin?  Much like the re-install button on update-core.php for WP core.  Could be a simple hyperlink next to the "Check for Updates" on the plugins.php page
 

![image](https://user-images.githubusercontent.com/4236538/30180398-5e57467a-93d5-11e7-9738-e9c57512dfc9.png)

**Comment by YahnisElsts** [comment]
It's an interesting idea, but I think it would be too complex to implement.

If the plugin files are messed up, you have to prepare for the possibility that the scripts that are supposed to perform the re-installation are *also* missing or corrupted, or have incorrect file permissions. That leads to integrity checks and all kinds of edge cases. Also, the re-installation script would be part of the plugin, so it would get deleted or overwritten during installation, which is another place for things to go wrong.
