### ISSUE TITLE
Inject update information received out-of-band

### ISSUE THREAD

**Issue by DavidAnderson684** [YahnisElsts/plugin-update-checker#133]
Hi Yahnis,

Thanks again for your work on this - it continues to be useful to me in various projects.

I have a class which builds on top of PUC, by adding an interface for a user to provide authentication credentials to connect, including UI elements in the WP dashboard. https://github.com/DavidAnderson684/simba-plugin-manager-updater . (And http://wordpress.org/plugins/simba-plugin-updates-manager/ is a free server for the other end).

I decided that I wanted to save one HTTP round-trip, by including the "update check" results in the "connect" step, and then feeding them back to PUC.

Of course, I want to do that in the last hacky way I can. As far as I could tell, this involved copying several lines from PUC's internals; see here: https://github.com/DavidAnderson684/simba-plugin-manager-updater/commit/131abcf4a3f781c3104020887e9c0d56a0db5f37#diff-5993e4dadd52ad90e9cad2d196201547R195 . Those lines are all from `Puc_v4p2_UpdateChecker::checkForUpdates()`. The only thing I had to do was to provide my own `Puc_v4p2_Update` object. The only thing that makes `Puc_v4p2_UpdateChecker::checkForUpdates()` something I can't use is because it always calls `$this->requestUpdate()`.

So, my suggestion: it'd be a minor improvement if there was a method that allows you to inject update results received from elsewhere. Obviously it was fairly easy to do, but what I've done is probably a bit fragile; if you change any of the internal structure or APIs around, then it'll soon break.

**Comment by YahnisElsts** [comment]
Actually, I think your current implementation is pretty good. It's very similar to what I would do if I wanted to insert an update from another source. The only minor nitpick I have is that you could simplify the middle part a little and get rid of the redundant `save()` call. Like this:

```php
$state = $update_checker->getUpdateState();
$state
    ->setLastCheckToNow()
    ->setCheckedVersion($installed_version)
    ->setUpdate($plugin_update)
    ->save();
```

`getUpdateState()` is part of the main update checker object and it's marked `public`, so I consider it a part of the public API. It should be fairly stable for the foreseeable future.

**Comment by DavidAnderson684** [comment]
@YahnisElsts Thank you. The redundant `save()` call was copied from `Puc_v4p2_UpdateChecker::checkForUpdates()` - I was thinking that since it was there, it must be for a good reason?

**Comment by YahnisElsts** [comment]
The reason why `checkForUpdates` saves twice is that there's a risk it could be terminated halfway. `requestUpdate()` sends a HTTP request, which could take a very long time and could cause the script to exceed the `max_execution_time` limit. Updating the last check timestamp and the version number *before* sending the request helps ensure that you won't get a situation where PUC tries to check for an update, crashes due to a timeout, then immediately tries to check again.

All of that doesn't really apply to your situation, so you don't need the redundant `save()`'s.

**Comment by DavidAnderson684** [comment]
Got it - thank you!
