### ISSUE TITLE
Issue: Puc suddenly stopped working

### ISSUE THREAD

**Issue by glkx** [YahnisElsts/plugin-update-checker#134]
Hi,

I have a question about following config. A couple of weeks ago Puc suddenly stopped working. The strange thing the config didn't change in any way or other significant parts of the plugin.

I have tried the following solutions:
- Rolling back the plugin several versions (incl. Puc from 4.2 to 4.1)
- Disabling caching
- New BitBucket Oauth key
- Contacted hosting provider for networking issues or blocking BitBucket request
- Checked all error logs

No of the above show any issues or solve the problem. In the debug it's only shows: "Failed to retrieve plugin info from the metadata URL."

The config:
```
require_once('library/vendor/plugin-update-checker/plugin-update-checker.php' );

$updateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://bitbucket.org/account-name/bitbucket-name',
	__FILE__,
	'plugin-name'
);

$updateChecker->setAuthentication( array(
	'consumer_key' => 'key',
	'consumer_secret' => 'secret',
) );

$updateChecker->setBranch( 'master' );
```

and readme.txt:
```
=== Plugin Name ===
Contributors: Name
Requires at least: 4.2
Tested up to: 4.8
Stable tag: 1.4.4
License: GPLv2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
```

Is their a way to find and solve the issue / is it miss configured? 

Thanks in advance!

Guido

**Comment by YahnisElsts** [comment]
"Failed to retrieve plugin info from the metadata URL" is a general error that means [`Puc_v4p2_Vcs_PluginUpdateChecker::requestInfo()`](https://github.com/YahnisElsts/plugin-update-checker/blob/a0e272295a9f10f3072c63fcca2ae993add1e58b/Puc/v4p2/Vcs/PluginUpdateChecker.php#L32) returned `null`. The update checker doesn't have any logging in that code, so you'll have to dig in and do one or all of the following:

- Trace the execution with a debugger. I'd recommend starting with the aforementioned `requestInfo` method.
- Add some `var_dump`'s or another form of debug output in strategic places and see if any `WP_Error`'s or `null`'s show up. Some suggestions: 
    - [Puc_v4p2_Vcs_BitBucketApi::api()](https://github.com/YahnisElsts/plugin-update-checker/blob/a0e272295a9f10f3072c63fcca2ae993add1e58b/Puc/v4p2/Vcs/BitBucketApi.php#L188) - dump the `$response` array and check if you're getting any error responses from the BitBucket API.
    - [`Puc_v4p2_Vcs_BitBucketApi::chooseReference()`](https://github.com/YahnisElsts/plugin-update-checker/blob/a0e272295a9f10f3072c63fcca2ae993add1e58b/Puc/v4p2/Vcs/BitBucketApi.php#L38) is an important decision point. Check if it finds a valid `$updateSource`.
- Log HTTP requests (there are many plugins and external tools for that) and see if any BitBucket API errors show up.

**Comment by glkx** [comment]
Thanks for the suggestions. I will try try your suggestions. If I have found something interesting I wil report it :)

**Comment by glkx** [comment]
BitBucket returns an 401 Unauthorized error. Making the repository public and removing the authorizing fixes the problem. It's only not desirable that the repository is public.

The complete error:
`HTTP/1.1 401 Unauthorized Server: nginx WWW-Authenticate: Basic realm="Bitbucket.org HTTP" Content-Type: text/html; charset=utf-8 Strict-Transport-Security: max-age=31536000; includeSubDomains; preload Date: Thu, 21 Sep 2017 09:04:52 GMT X-Served-By: app-161 X-Static-Version: 4166677bc668 ETag: "d41d8cd98f00b204e9800998ecf8427e" X-Render-Time: 0.0100750923157 Connection: close X-Version: 4166677bc668 X-Request-Count: 201 X-Frame-Options: SAMEORIGIN Content-Length: 0`

Creating new OAuth key and secret didn't fix the problem with authorizing, the same goes for enabling all the permissions for the consumer.

The permissions:
![schermafbeelding 2017-09-21 om 12 15 17](https://user-images.githubusercontent.com/7963103/30691036-9db4e524-9ec6-11e7-8c03-94bf4807e637.png)

**Comment by YahnisElsts** [comment]
That's concerning. I've re-run some of my old BitBucket tests and they produce similar errors. My guess would be that BitBucket changed what OAuth versions or implementations they will accept.

Unfortunately, I know virtually nothing about OAuth. The [signature generator](https://github.com/YahnisElsts/plugin-update-checker/blob/a0e272295a9f10f3072c63fcca2ae993add1e58b/Puc/v4p2/OAuthSignature.php) that PUC uses is a very basic OAuth 1.0 (0-legged) implementation adapted from somewhere else. It might be necessary to switch to OAuth 2.0 or change the grant type. Do you (or anyone else reading this) know how one would go about that?

**Comment by YahnisElsts** [comment]
Note: I tried enabling the "This is a private consumer" checkbox in the OAuth consumer settings and it seemingly fixed the issue. However, the settings page explicitly says:

>Installable applications that ship their OAuth consumer credentials as part of the application should not be marked as private.

**Comment by glkx** [comment]
It looks like they dropped OAuth 1.0. In the documentation they refer to 2.0: https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html

**Comment by YahnisElsts** [comment]
> Edit: The trick with enabling "This is a private consumer" didn't work for me unfortunately.
Strange. It definitely works here.

> I self have no experience with OAuth, but based on what I just read 2.0 is easier to work with than 1.0.

It's probably not going to be as easy as it sounds. I tried it with [this BitBucket API implementation](https://gentlero.bitbucket.io/bitbucket-api/1.0/) and got an error: "Cannot use client_credentials with a consumer marked as "public". Calls for auto generated consumers should use urn:bitbucket:oauth2:jwt instead." It looks like you would still have to mark the consumer as private (which is not recommended) or use JWT (which is another pile of complications).

**Comment by glkx** [comment]
You are right the trick with enabling as private consumer does work. I was little to quick with drawing conclusions. Great to have a work around :)

After some more reading I understand the pickle with OAuth 2.0 in combination with PUC. I am not advanced enough to create an sustainable solution.

**Comment by Mikk3lRo** [comment]
Just sent a PR with a small notice referencing this issue.

If I have time I'll look into a better solution.

I can't seem to find any documentation about what the checkbox actually means though, but it's pretty counter intuitive that we have to tick it to get it to work, since it specifically says that "Installable applications that ship their OAuth consumer credentials as part of the application should not be marked as private."

Weird that *not* marking it private seems to limit access somehow.

**Comment by YahnisElsts** [comment]
Thanks, I've merged the PR.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year and the PR has already been merged.

**Comment by lukeseager** [comment]
Is anyone else having issues with this recently? In the last 3 weeks I've not been able to update any of my sites which are updated by tagging private bitbucket repositories.
