### ISSUE TITLE
Can't update from GitHub

### ISSUE THREAD

**Issue by npalmqvist** [YahnisElsts/plugin-update-checker#135]
Having problems with this, might be a configuration problem, don't know... Or maybe I missed a step in the process.

I've downloaded the latest release and I have this in my plugin file: 

```<?php
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/npalmqvist/hk-leaguestats/',
	__FILE__,
	'hk-leaguestats'
);

//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->setAuthentication('<secret_token>');

//Optional: Set the branch that contains the stable release.
$myUpdateChecker->setBranch('master');
```
No errors so far. 

I have installed the Debug Bar and everything seems to be ok. This is the info I get:

```Successfully retrieved plugin info from the metadata URL:
Puc_v4p2_Plugin_Info Object
(
    [name] => 
    [slug] => hk-leaguestats
    [version] => 1.1.2
    [homepage] => 
    [sections] => Array
        (
            [changelog] => There is no changelog available.
        )

    [banners] => 
    [translations] => Array
        (
        )

    [download_url] => https://api.github.com/repos/npalmqvist/hk-leaguestats/zipball/1.1.2?access_token=<secret_token>
    [author] => 
    [author_homepage] => 
    [requires] => 
    [tested] => 
    [upgrade_notice] => 
    [rating] => 
    [num_ratings] => 
    [downloaded] => 
    [active_installs] => 
    [last_updated] => 2017-09-21T10:06:57Z
    [id] => 0
    [filename] => hk-leaguestats/inc/update-checker-settings.php
)
```

and 

```An update is available:
Puc_v4p2_Plugin_Update Object
(
    [id] => 0
    [homepage] => 
    [upgrade_notice] => 
    [tested] => 
    [filename] => hk-leaguestats/inc/update-checker-settings.php
    [slug] => hk-leaguestats
    [version] => 1.1.2
    [download_url] => https://api.github.com/repos/npalmqvist/hk-leaguestats/zipball/1.1.2?access_token=<secret_token>
    [translations] => Array
        (
        )

)
```

Also my wordpress install shows me that I have 3 new updates for plugins, but visiting the updates page only shows me 2 plugins (none of them mine...), see screenshot... 

![skarmavbild 2017-09-21 kl 12 16 05](https://user-images.githubusercontent.com/468741/30691189-3f2eae76-9ec7-11e7-8d60-d92b42a4fd78.png)

What am I doing wrong here?

**Comment by YahnisElsts** [comment]
It looks like the second argument to `buildUpdateChecker` is incorrect. This argument must be an absolute path to the main plugin file. Based on the `Puc_v4p2_Plugin_Update` output, it's actual value is a path to `inc/update-checker-settings.php`, which is almost certainly not the main file.

To fix the issue, replace `__FILE__` with the full path to the main plugin file. The "main" file is the one that contains the plugin header.

**Comment by npalmqvist** [comment]
Of course! Thank you! That solved my problems!
