### ISSUE TITLE
PHP7 Error 1412

### ISSUE THREAD

**Issue by TylerJohnsonDev** [YahnisElsts/plugin-update-checker#144]
Getting the following error in vender/ParsedownLegacy.php:

1412 | ERROR | Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity.

Just thought I'd make you aware.

**Comment by Mikk3lRo** [comment]
Are you using the latest version? Sounds a lot like https://github.com/YahnisElsts/plugin-update-checker/commit/c7fcfb38b13f91919856a4b1a5c5658518f44c06

**Comment by YahnisElsts** [comment]
The new release is out now.
