### ISSUE TITLE
Case sensitive readme.txt causes 404 errors for README.txt

### ISSUE THREAD

**Issue by claytoncollie** [YahnisElsts/plugin-update-checker#147]
I am using Query Monitor to see all of the HTTP API calls and found that PUC fails to find readme.txt, when the branch is set, because my plugin uses README.txt instead of the lowercase readme.txt.  I make these plugins from Devin Vinson's boilerplate repo.   I removed the branch designation to by pass this check.  Thought you would want to know.  Thanks for making this library!

readme.txt is set on line 57 in Api.php inside the Vcs folder

![2017-10-30 12_53_07-wordpress updates blueprint wordpress](https://user-images.githubusercontent.com/4236538/32186927-722d1e0c-bd71-11e7-84cd-6f160e079f6d.png)

**Comment by YahnisElsts** [comment]
Hmm, that's inconvenient. Thank you for the report. It should be fixed now.

**Comment by claytoncollie** [comment]
Thank you!
