### ISSUE TITLE
Plugin icons

### ISSUE THREAD

**Issue by MTphilclothier** [YahnisElsts/plugin-update-checker#153]
Hi!

It looks like WP 4.9 now shows the plugin icon in the updates page - https://i.imgur.com/TDfOZfE.png

It would be awesome if this will be possible with PUC too.  If not already?

Thanks!

**Comment by YahnisElsts** [comment]
This is not possible yet, but it would make a nice addition to the project.

It looks like we'd need to add something like this to the update info:

```json
{
	"icons": {
		"svg": "https://example.com/icon.svg",
		"1x": "https://example.com/icon-128x128.png",
		"2x": "https://example.com/icon-256x256.png",
		"default": "https://example.com/icon.svg"
	}
}
```

More info on plugin icons:
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

**Comment by Remzi1993** [comment]
Is there any process on this? I would like to implement a feature like this. My company uses your library to update our private WP Plugins.

**Comment by YahnisElsts** [comment]
Yes, basic support for plugin icons has been added. See the `icons` property in this example code:
https://github.com/YahnisElsts/plugin-update-checker/blob/master/examples/plugin.json

There's no real documentation for this feature, but this commit has some usage instructions: 585f60d91c337667e95e6dbd13f834d9875c9711

**Comment by Remzi1993** [comment]
Thank you!

**Comment by anybodesign** [comment]
Hello,
Is it possible to use this feature with Github integration? It looks like it's not… :)

**Comment by webdados** [comment]
> Hello, Is it possible to use this feature with Github integration? It looks like it's not… :)

Anyone? :-)

**Comment by YahnisElsts** [comment]
For GitHub, remote icons are not supported, but you can put icons in an `assets` subdirectory in your plugin, and the update checker should pick them up. That is, it will show icons from the *installed* version, not from the *update*. Supported icon file names are:

- icon.svg
- icon-256x256.png
- icon-256x256.jpg
- icon-128x128.png
- icon-128x128.jpg
