### ISSUE TITLE
Readme doesn't match latest release.

### ISSUE THREAD

**Issue by CasperBraske** [YahnisElsts/plugin-update-checker#156]
On the readme you read "Puc_v4p3_Factory" but the class shipped in the [ZIP file](https://github.com/YahnisElsts/plugin-update-checker/archive/v4.3.1.zip) is actually "Puc_v4_Factory", rasing a fatal error.

**Comment by YahnisElsts** [comment]
The readme you're looking at is for the `master` branch. Check the readme in the ZIP file, it should have the correct class names for that release.

That said, I realize that most people will probably expect the instructions they see on the project page to work with the latest release. I'll see if I can fix those docs for the next release.

**Comment by YahnisElsts** [comment]
The docs were fixed a while ago but I forgot to close this issue, so I'm closing it now.
