### ISSUE TITLE
How to show the invalid license key error?

### ISSUE THREAD

**Issue by gradosevic** [YahnisElsts/plugin-update-checker#157]
Is there a way to show an error message inside the plugin's body on Plugins page?

For example, this hook can be used to update the message:
[after_plugin_row](https://developer.wordpress.org/reference/hooks/after_plugin_row/) but the problem is that we should get the result from **$myUpdateChecker->addResultFilter** which is executed much later than **after_plugin_row** hook, so I wasn't able to update the message. 

On the server, I'm just throwing a 4xx error with exitWithError. Is there any other alternative way to do this? Thank you.

**Comment by YahnisElsts** [comment]
There's no built-in support for showing a custom message on the "Plugins" page.

The way I would do it is this:

1. Add a result filter.
2. In the filter, detect the error and store the message somewhere (e.g. your own option or transient).
3. Add an `after_plugin_row` action that outputs the stored message.

> [...] the problem is that we should get the result from $myUpdateChecker->addResultFilter which is executed much later than after_plugin_row hook, so I wasn't able to update the message.

I don't think "much later" really applies in this context. The result filter runs when checking for updates, which usually happens in a WP-Cron event. In theory, it's not part of the sequence of hooks that run on the "Plugins" page. (In practice, it can sometimes run on that page, but that's not the common case.)

**Comment by gradosevic** [comment]
Thanks for the clarification, it works when setting a transient to hold the results. Thanks!
