### ISSUE TITLE
Update Failed: The directory structure of the update is incorrect. 

### ISSUE THREAD

**Issue by LittleHamster** [YahnisElsts/plugin-update-checker#159]
@YahnisElsts 
So I decided to go with the old zip file update and now I keep getting this error:
 
```
Update Failed: The directory structure of the update is incorrect. 
All files should be inside a directory named plugin-slug, not at the root of the ZIP archive.
```

but here is how the folder structure is 
```
-plugin-slug.zip
   --plugin-slug
      ---plugin-slug.php
      ---other-files

```

the zip file is automatically created using this command:
```
zip -r ....
```
if I download the zip file it works without issue but when I try to update it on the site, I get that above error.

**Comment by YahnisElsts** [comment]
That sounds like it *should* work, but chances are good that there actually is something wrong with the ZIP file. Are you sure there aren't any hidden dotfiles in the root folder? Are you doing this on MacOS by any chance?

**Comment by LittleHamster** [comment]
@YahnisElsts 
yes, I am on Mac

**Comment by YahnisElsts** [comment]
That might explain it. Other users have reported that Mac's built-in compression tool makes it look like a ZIP file contains a single folder when it actually contains multiple files.

Try running `unzip -l filename.zip` to list the files in the archive. Do the file names include the plugin folder name?

**Comment by LittleHamster** [comment]
@YahnisElsts 
I see, you are absolutely right. 
I downloaded the file on Windows machine and everything was in the root folder. But when opened in Mac, it actually showed me a folder. Thank you for your support.
