### ISSUE TITLE
Download failes because of invalid download link

### ISSUE THREAD

**Issue by Lars-** [YahnisElsts/plugin-update-checker#160]
Hello,

Today I encountered an error that I don't understand. When updating a plugin (no Git), I get the error that the download has failed because the download link is invalid. Then it prints the download link. 

When I go to this download link myself (https://example:8080/1.0.0.zip), it just downloads without a problem.

How to debug and solve this?

Kind regards,
Lars Jansen

**Comment by Lars-** [comment]
It has probably something to do with this: https://www.emanueletessore.com/wordpress-download-failed-valid-url-provided/

**Comment by Lars-** [comment]
Okay, I found the problem. It's in the wp_http_validate_url function. It checks if the port is 443, 80, 8080 or the same as the home port (which it is all not). I should probably host the plugin somewhere else.

**Comment by YahnisElsts** [comment]
FYI, if "example" maps to localhost (e.g. 127.0.0.1), you might be able to override the validation process by using the `http_request_host_is_external` filter.

**Comment by Lars-** [comment]
The problem was that example had a port other than 80, 443 or 8080 (it wasn't localhost). Therefore, `wp_http_validate_url()` always returned false. This function has no filter in it, so I had no choice but to host the plugin elsewhere.

**Comment by YahnisElsts** [comment]
Ah, I see. I was confused because the link in the first post used port 8080.
