### ISSUE TITLE
Removing the json file

### ISSUE THREAD

**Issue by DeveloperWilco** [YahnisElsts/plugin-update-checker#161]
Hello,

I currently want to stop updating my older themes and remove the theme.json file. 
What will happen to websites that currently use the update checker? 

I want to make sure it doesn't give an error when removing the json file.
Thanks in advance!

**Comment by YahnisElsts** [comment]
On most sites, nothing will happen. Update checks will just fail silently.

On sites where `WP_DEBUG` is set to `true`, every update check will trigger a PHP warning: "The URL (your URL here) does not point to a valid metadata file". Most sites have error display turned off, so users *probably* won't see this message in the WordPress dashboard. However, anyone who checks the PHP error log will see it.
