### ISSUE TITLE
how do i check in my code if the version i have is the most recent

### ISSUE THREAD

**Issue by VitorReisM** [YahnisElsts/plugin-update-checker#162]
i have a plugin and in every website its needed to be on maximum version and if not i need to kinda block the admin menu and make the admins go to the plugins and updated to last version, i am using bitbucket

if anyone can help i would apreciate :)
happy christmas

**Comment by YahnisElsts** [comment]
I recommend using the `getUpdate()` method. If there is an update available, it returns an instance of `Puc_v4p3_Update`. Otherwise it returns `null`. 

Example:
```php
if ($myUpdateChecker->getUpdate() !== null) {
    //An update is available.
} 
```

**Comment by VitorReisM** [comment]
Thank you
