### ISSUE TITLE
MU Plugin - problem with updating from GitHub

### ISSUE THREAD

**Issue by dompl** [YahnisElsts/plugin-update-checker#163]
Hiya,

Thank you for your amazing work. great plugin.

I have an issue with plugin update. Whenever I try to update to the latest version it keeps on returning

> Update Failed: Update package not available.

I checked everything with Debug and there is no issues whatsoever.

Would it be because it is a mu plugin?

Thank you.

**Comment by YahnisElsts** [comment]
> Would it be because it is a mu plugin?

Yes, almost certainly. WordPress doesn't support automatic updates for mu-plugins. You can still show update notifications (like this library does), but the user has to manually download and install the update.

**Comment by dompl** [comment]
I though so. Thank you.
