### ISSUE TITLE
theme update checking not working

### ISSUE THREAD

**Issue by matt-wiz** [YahnisElsts/plugin-update-checker#165]
Does this still work with themes? 

I was originally using the previous theme update checker that was discontinued. I tried updating with the plugin update checker but with no success. I have followed the instructions included and even tried implementing the WP update server API as well. 

I have the following in my themes file:

`require 'updates/update-checker.php';`
`$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://mydomain.com/update/?action=get_metadata&slug=' . theme_textDomain,
	__FILE__,
	theme_textDomain
);
`

If I open the debug menu in the admin and I can see the link to the standard JSON file and even the wp update server generated JSON file, both which show the correct version, however the debug menu is showing that the "checked version" is still version 1.0 and not the new version. The most recent check was just an hour ago but it's still saying the checked version is 1.0. If I hit "check now" nothing happens. 

Any suggestions as to what may be causing the issue would be great. I appreciate the help.

**Comment by YahnisElsts** [comment]
Yes, it should still work with themes.

"Checked version" is the version that was *installed* when the update checked last checked for an update. Assuming that you have version 1.0 installed right now, that value is fine. The version information for the update (if available) will be on the next row: "Cached update".

> The most recent check was just an hour ago but it's still saying the checked version is 1.0. If I hit "check now" nothing happens.

That sounds like there's a JS or PHP error somewhere. Please open the browser's JS console and click "Check now" again. Do any errors show up? If not, take a look at the server's PHP error log. Are there any recent entries there?

**Comment by matt-wiz** [comment]
Thanks so much for the quick reply.

The cached version is showing up as null in the debug window. When I click on "check now" nothing happens and no errors pop up in the JS console. There are also no errors showing up in the PHP error logs. However, there is one warning:

`PHP Warning:  Invalid argument supplied for foreach() in /wp-admin/includes/plugin.php on line 1432`

The only plugin I have active right now is the debug bar.

**Comment by matt-wiz** [comment]
UPDATE:

I've updated to the newest version of the plugin updater. I am now getting the following error:

`Notice: The theme metadata is missing the required "details_url" key. in /var/www/html/sffcu.mwiz.net/cms/wp-content/themes/genii/updates/Puc/v4p4/Metadata.php on line 42`
```
No updates found.
The update checker encountered 1 API error.
```

```
1) The theme metadata is missing the required "details_url" key.
Error code:
tuc-invalid-metadata
```

I have a "Details URI:" in my theme style.css. Has this variable changed to Details URL?

**Comment by YahnisElsts** [comment]
`Details URI` is the correct header name. If I recall correctly, if this header is missing then the update server will use the value of the `Theme URI` header as the details URL.

Take a look at the JSON file. Does it have a `details_url` field? Do the other fields have the correct values?

**Comment by matt-wiz** [comment]
After updating to the most recent version of the plugin, clearing my cache, and reloading the WP update checker API URL, all seems to be working as expected now. Thanks so much for the help!
