### ISSUE TITLE
Passing license key

### ISSUE THREAD

**Issue by togethernet** [YahnisElsts/plugin-update-checker#166]
I'd like to pass a license key to the update checker and for it to check for a valid licence before allowing the update to proceed. I think I can add the validation code but not sure about adding code for passing the key - would appreciate any guidance here.

**Comment by YahnisElsts** [comment]
Take a look at this blog post:
http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/

Among other things, it describes how to add a new parameter (e.g. a license key) to update requests.

**Comment by togethernet** [comment]
So we have...
`/* ... Code that initializes the update checker ... */
 
//Add the license key to query arguments.
$updateChecker->addQueryArgFilter('wsh_filter_update_checks');
function wsh_filter_update_checks($queryArgs) {
    $settings = get_option('my_plugin_settings');
    if ( !empty($settings['license_key']) ) {
        $queryArgs['license_key'] = $settings['license_key'];
    }
    return $queryArgs;
}`

I can see how to adapt the function so as to grab my licence key; but I am unsure where to put the code so that the license key is added to query arguments at the appropriate time.

**Comment by togethernet** [comment]
...but now I see, as it's a filter I don't need to worry about that , I can just add this code, (amended to get the licence key from my database) to my plugin's main code?

**Comment by YahnisElsts** [comment]
Yes, you can just add it after the code that initialises the update checker. I would recommend changing the function name to something unique since other developers might be using the same example code.

**Comment by ketanshah79** [comment]
Hello,

I was wondering if I can add a header to the request instead of a query param which is less secure?

For licensing, I am generating a JWT Token from the WordPress users login and plan to use that token as a license key. However I don't want to pass the JWT token as a query param as it could be misused. I want to pass it in the authorization header. This will ensure that I generate download_url for authenticated users only. 

Thank you.

**Comment by YahnisElsts** [comment]
You can use the `request_info_options` filter (full tag: `puc_request_info_options-$slug`) to modify the options passed to `wp_remote_get`, which lets you set HTTP headers. I would recommend using the `addHttpRequestArgFilter` utility method to register the filter.

Untested example:
```php
$updateChecker->addHttpRequestArgFilter(function($options) {
    $options['headers'] = array_merge(
        $options['headers'], 
        array(
            'name' => 'value',
        )
    );
    return $options;
});
```

**Comment by ketanshah79** [comment]
Thank much @YahnisElsts  for your quick turnaround. Have a good one
