### ISSUE TITLE
Show Dashboard Updates plugin icon when not using JSON file.

### ISSUE THREAD

**Issue by JiveDig** [YahnisElsts/plugin-update-checker#167]
First, thank you so much for this code... I LOVE it!

I was excited to see the update to allow showing a plugin icon, however I'm using PHP method to run the updater.

`$updater = Puc_v4_Factory::buildUpdateChecker( 'https://github.com/my-plugin-path-here/', __FILE__, 'text-domain' );`

Is there a way to grab the icon files here, in PHP?

**Comment by YahnisElsts** [comment]
You could probably use a update request result filter to add your own icon. For example (untested code):
```php
$updateChecker->addResultFilter(function($pluginInfo, $httpResponse = null) {
	$pluginInfo->icons = array(
		'1x' => 'http://example.com/icon.png',
		'2x' => 'http://example.com/icon-high-res.png',
	);
	return $pluginInfo;
});
```

(The `addResultFilter` is a convenience wrapper that binds a callback to the `puc_request_info_result-$slug` filter.)

**Comment by JiveDig** [comment]
I appreciate the response and code example, thank you.

Gave it a shot and pushed a couple beta releases to confirm, but it doesn't appear to work for me.
```
// Add icons for Dashboard > Updates screen.
$updater->addResultFilter( function( $info, $response = null ) {
	$info->icons = array(
		'1x' => MAI_PRO_ENGINE_PLUGIN_URL . 'assets/images/icon-128x128.png',
		'2x' => MAI_PRO_ENGINE_PLUGIN_URL . 'assets/images/icon-256x256.png',
	);
	return $info;
});
```

My understanding was that the icons were only used on plugins from the WP repo. Would be great to have this for non-repo/premium plugins too.

**Comment by YahnisElsts** [comment]
All right, I just tested that code myself. It works for me. All I did was change the `$updater` variable and the URLs to match my test plugin. The `1x` icon showed up.

Are you sure it's not still using the cached update data in your case? Try clicking the "check for updates" link in the plugin description on the "Plugins" page.

**Comment by JiveDig** [comment]
Hmmm, still not getting it. Should the updater code be running on a specific hook, earlier or later?

**Comment by YahnisElsts** [comment]
It should run pretty early, preferably before or during the `plugins_loaded` action.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

If it's still valid, feel free to reopen it.
