### ISSUE TITLE
Example code from the docs for Gitlab

### ISSUE THREAD

**Issue by jvandeudekom** [YahnisElsts/plugin-update-checker#168]
Hi,

In the example it says the following: 
$myUpdateChecker = new Puc_v4p4_Vcs_PluginUpdateChecker 

But shouldn't it be:
$myUpdateChecker = new Puc_v4_Vcs_PluginUpdateChecker.

With my modification it does work and everythings work fine.

Regards

**Comment by YahnisElsts** [comment]
Thank you for drawing my attention to this issue. The example code should use `Puc_v4p4_Vcs_PluginUpdateChecker`, and I've updated it now. 

In case you're curious, class names include version numbers to avoid conflicts with older versions of the library. Apparently, I missed this particular line of code when changing the version number.

**Comment by jvandeudekom** [comment]
I see that i've actually said it wrong in my comment haha, i already had Puc_v4p4_Vcs_PluginUpdateCheckerin my code.. 

Thanks for changing it!
