### ISSUE TITLE
details_url not working for theme

### ISSUE THREAD

**Issue by transbetacism** [YahnisElsts/plugin-update-checker#170]
I am implementing PUC v4.4 for a theme with self-hosting and the following json:

```
{
  "version": "1.5.3",
  "download_url": "http://content.hellodetail.com/releases/scandinavian/secret-file-name.zip",
  "details_url": "http://content.hellodetail.com/releases/scandinavian/new-version.html"
}
```

The update is showing, but the View details link is missing:

<img src="https://d3vv6lp55qjaqc.cloudfront.net/items/2Y380G1E432X2v0R0b0r/Image%202018-01-20%20at%202.11.10%20em.png" />

Isn't a View details link supposed to be shown?

Thanks,
Joakim

**Comment by YahnisElsts** [comment]
As far as I know, WordPress never shows "View version X details" links for themes on the "Dashboard -> Updates" page. You need to go to "Appearance -> Themes" and click the theme to see the details link.

**Comment by transbetacism** [comment]
I see. But how is the `details_url` used in the self-hosted version for themes? That isn't shown under Appearance > Themes either, is it?

<a href="http://share.hellodetail.com/oyHs" target="_blank"><img src="https://d3vv6lp55qjaqc.cloudfront.net/items/3d273N382c0Z15040T1O/%5Bc2aa4d99e47b551c8fbaeb58c735e560%5D_Image+2018-01-21+at+2.24.04+em.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by YahnisElsts** [comment]
It is shown under "Appearance -> Themes" when you click the theme. Example:

![theme-view-details](https://user-images.githubusercontent.com/2527434/35194721-7b322c6e-fec0-11e7-98fc-63b96fdbf776.png)

**Comment by transbetacism** [comment]
Ok great, thanks for the clarification!

/Joakim
