### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by KaiReichart** [YahnisElsts/plugin-update-checker#172]
Could not determine if updates are available...

I have hosted on <a href="www.strato.de">Strato</a>
On my other Site it works without Problems with the same configuration...

I'm running WP Version 4.9.3

<img width="1079" alt="bildschirmfoto 2018-02-06 um 13 32 16" src="https://user-images.githubusercontent.com/29383712/35859917-4e1ac25c-0b42-11e8-80b3-f429002c7fb4.png">

My Config:
```php
require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/KaiReichart/WP-Bankimport-Plugin/',
	__FILE__,
	'WP-Bankimport-Plugin'
);
```

**Comment by YahnisElsts** [comment]
Usually that would mean that the repository is private and the access token is either missing or invalid. However, it looks like the repository is actually public. Was it public to begin with, or did you change it from private to public recently?

I installed your plugin on a local test site and tried to check for updates. It worked fine and there were no "403 Forbidden" errors. If you're still getting the same error, it might mean that your server doesn't allow outgoing HTTP requests to github.com. Maybe you could ask the host about that?

**Comment by KaiReichart** [comment]
The repo was public from the beginning...
Ok Thanks, ill ask the host then

**Comment by KaiReichart** [comment]
The Host doesn´t support Data Transfer via https
I had to change the url to http://github.com/... and now it works
