### ISSUE TITLE
Idea: exclude specific files from update (from being deleted with new update)

### ISSUE THREAD

**Issue by KaiReichart** [YahnisElsts/plugin-update-checker#173]
It would be great to be able to exclude specific files from updates, e.g. i have a .htaccess and .htpasswd file generated in the plugin directory and it always gets lost with new updates. 
As it contains passwords, it might not be the best idea to save the passwords in the database and generate it new every time there is an update...

**Comment by YahnisElsts** [comment]
It would indeed be useful, but it's probably not feasible. This library doesn't install updates. It just tells WP that an update is available. WP core handles the actual file copying and overwriting.

I guess we could try something clever like moving excluded files to a "safe" location before the update and then moving them back, but this approach has its own complications (e.g. file permissions, OS differences, WP core having suitable hooks).

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year and there doesn't seem to be an easy way to implement this feature suggestion.
