### ISSUE TITLE
Wrong display of version in WordPress screen.

### ISSUE THREAD

**Issue by devanonyme** [YahnisElsts/plugin-update-checker#174]
Hello,

I'm testing your plugin and the version displayed in WordPress is always 1.0.0. 

![screen shot 02-09-18 at 03 12 pm](https://user-images.githubusercontent.com/21067311/36048028-e21c428a-0dab-11e8-9827-f9338fd33075.PNG)

I will investigate further but would take any hint of things I could have missed but the details data seems to be good.

I'm using a fork of a boiler plate plugin repo to test  : https://github.com/devanonyme/WBU-Plugin-Boilerplate

Thanks for the project, looking forward to have it working with our project (sources not release yet).

Eric

**Comment by devanonyme** [comment]
Oh, I think I found the issue, it was more on my side.

I had a patched local version (with plugin update checker) and had forced the version to a lower revision thinking this would work ( * Version:           0.0.1), so it looks like it was messing up the code (the details where the same for 0.0.1 and 3.0.8 by exemple).

I have changed to existing tag (3.0.5) and now I see the update and the details are corrects.

**Comment by YahnisElsts** [comment]
The update checker tries to get the update version number from the "Version" header in the main plugin file that's in the selected tag/branch. It will only fall back to using the tag name as the version number if it can't find the plugin file. 

This means that if you have a tag like "3.0.3" but the plugin header says "Version: 1.0.0", you will see "1.0.0" in the admin panel. 

Also, the update checker ignores pre-releases.

**Comment by devanonyme** [comment]
A thing that could be improved, but I have not checked the code, would be to display the local readme.txt instead of remote one when version tag is invalid (if this can be catched) 

In this screen, when I was using 0.0.1 and clicking on detail of current version (orange square), it was the detail of the updated version details (3.0.5) that was displayed. 

![screen shot 02-09-18 at 05 07 pm](https://user-images.githubusercontent.com/21067311/36052473-c8bfed86-0dbb-11e8-9761-0a85f9dd6764.PNG)

Anyway, works very well, thank you! I'm using fr_CA but it's basically fr_FR but I'm not sure if WordPress had a default behavior use the the available lang if specific locale is not available, I will double check that.

You can close the issue!

**Comment by YahnisElsts** [comment]
> In this screen, when I was using 0.0.1 and clicking on detail of current version (orange square), it was the detail of the updated version details (3.0.5) that was displayed.

I believe that's also the standard WordPress behaviour. For plugins hosted on wordpress.org, the "view details" link shows information about the latest release, not about the currently installed version. One of the design principles of this update checker is to stay consistent with the existing WordPress interface and behaviour. So showing the remote readme.txt or the latest release description makes sense.

Anyway, as you suggested, I will close the issue now.
