### ISSUE TITLE
`$this->slug` empty when initializing with `Puc_v4_Factory::buildUpdateChecker()`

### ISSUE THREAD

**Issue by connerbw** [YahnisElsts/plugin-update-checker#180]
While writing a unit test to check that our code properly uses this plugin, I noticed the following (Screenshot of Xdebug in PhpStorm):

![slug](https://user-images.githubusercontent.com/812192/36547721-8309acfe-17bc-11e8-802f-fe303e365514.png)

Init looks like this:

```php
$updater = \Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/pressbooks/pressbooks/',
	untrailingslashit( PB_PLUGIN_DIR ) . '/pressbooks.php', // Fully qualified path to the main plugin file
	'pressbooks',
	24
);
$updater->setBranch( 'master' );
$updater->getVcsApi()->enableReleaseAssets();
```

My PhpUnit test is currently this:

```php
$this->assertTrue( has_filter( 'puc_is_slug_in_use-' ) );
```

The above assertion passes.  I find that strange. I was expecting:

```php
$this->assertTrue( has_filter( 'puc_is_slug_in_use-pressbooks' ) );
```

**Comment by YahnisElsts** [comment]
Good catch! This is a bug. At that point in the code, the `slug` property hasn't been initialised yet. It's set later, in the parent constructor. 

I'll change it to use the local variable instead.
