### ISSUE TITLE
Update checker cannot determine if plugin or theme

### ISSUE THREAD

**Issue by vyskoczilova** [YahnisElsts/plugin-update-checker#186]
I have got this error, any ideas what to do? I'm trying to create an update checker for my child theme, thanks a lot!

`Fatal error: Uncaught RuntimeException: The update checker cannot determine if "/hosting/www/dybbuk.cz/eshop/wp-content/themes/suisen-child/includes/include_update_checker.php" is a plugin or a theme. This is a bug. Please contact the PUC developer. in /hosting/www/dybbuk.cz/eshop/wp-content/themes/suisen-child/includes/plugin-update-checker/Puc/v4p4/Factory.php:50 Stack trace: #0 /hosting/www/dybbuk.cz/eshop/wp-content/themes/suisen-child/includes/include_update_checker.php(9): Puc_v4p4_Factory::buildUpdateChecker('https://bitbuck...', '/hosting/www/dy...', 'suisen-child') #1 /hosting/www/dybbuk.cz/eshop/wp-content/themes/suisen-child/functions.php(48): require_once('/hosting/www/dy...') #2 /hosting/www/dybbuk.cz/eshop/wp-settings.php(424): include('/hosting/www/dy...') #3 /hosting/www/dybbuk.cz/eshop/wp-config.php(177): require_once('/hosting/www/dy...') #4 /hosting/www/dybbuk.cz/eshop/wp-load.php(37): require_once('/hosting/www/dy...') #5 /hosting/www/dybbuk.cz/eshop/wp-admin/admin.php(31): require_once('/hosting/www/d in /hosting/www/dybbuk.cz/eshop/wp-content/themes/suisen-child/includes/plugin-update-checker/Puc/v4p4/Factory.php on line 50`

this is how I included it:

```
require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://bitbucket.org/kybernaut/dybbuk-suisen-child-theme',
	__FILE__,
	'suisen-child'
);

//Optional: If you're using a private repository, create an OAuth consumer
//and set the authentication credentials like this:
//Note: For now you need to check "This is a private consumer" when
//creating the consumer to work around #134:
// https://github.com/YahnisElsts/plugin-update-checker/issues/134
$myUpdateChecker->setAuthentication(array(
	'consumer_key' => 'nRABDUsomemissingpartsVqL6gK',
	'consumer_secret' => 'zxDXNs4HWJ3psomemissingpartsP5uv7a2jGe2',
));

//Optional: Set the branch that contains the stable release.
$myUpdateChecker->setBranch('stable');
```

**Comment by YahnisElsts** [comment]
It looks like you've placed the code that initialises the update checker in a separate file. That's fine, but you need to adjust the code a bit to account for that.

Specifically, the second argument that's passed to `buildUpdateChecker` must be the full path to any file in the theme's root directory. In this case, it points to a file in a subdirectory, which won't work. I would recommend replacing it with the full path to your `functions.php` or `style.css`.

**Comment by vyskoczilova** [comment]
Ah, you are right, changed that for the style.css and works perfectly. Thanks a lot!
