### ISSUE TITLE
Check for updates -> Are you sure you want to do this?

### ISSUE THREAD

**Issue by karolispx** [YahnisElsts/plugin-update-checker#187]
Hi, 

When I click on the 'Check for updates' I get 'Are you sure you want to do this?' error, which seems to be caused by a nonce? Latest version of WP.

**Comment by YahnisElsts** [comment]
What does the URL of the "check for updates" link look like? Does it contain the correct plugin slug and a `_wpnonce` parameter?

For reference, usually the URL is similar to this:
`http://example.com/wp-admin/plugins.php?puc_check_for_updates=1&puc_slug=example-slug&_wpnonce=7a4ef955d7`

**Comment by karolispx** [comment]
http://local.wp.com/wp/wp-admin/plugins.php?puc_check_for_updates=1&puc_slug=xxxxx-xxxxx does not contain nonce part unfortunately

**Comment by karolispx** [comment]
When I hover on the links on plugins page, I can see the nonce. But once the link is clicked, the nonce part is stripped out.

**Comment by YahnisElsts** [comment]
That's very strange. Could it be caused by a bug in another plugin or theme? Try deactivating all other plugins.

**Comment by karolispx** [comment]
All other plugins are inactive. Also switched to other theme instead of using 2017, nothing has changed. Tried renaming nonce, no difference. 
Remove wp_nonce_url and the following nonce check, the page kept loading for about 20s. and then timedout with 'too many redirects'. 

Strange. This used to be working before with no issues.

**Comment by karolispx** [comment]
I've also regenerated salts and stuff and nothing has changed.

**Comment by karolispx** [comment]
Also tried specifying the nonce like this: 

$_wpnonce = wp_create_nonce( 'puc_check_for_updates' );
$linkUrl = admin_url( 'plugins.php?puc_check_for_updates=1&puc_slug=' . $this->slug . '&_wpnonce=' . $_wpnonce );

Still no luck, it keeps getting stripped out.

**Comment by YahnisElsts** [comment]
Some wild guesses:
- Anything unusual in .htaccess? Something security- or redirect-related?
- Firewall or IDS on the server? That shouldn't be an issue for what sounds like a local site, but who knows.
- Anything interesting in the "Network" tab of the browser console? Are there really lots of redirects? Perhaps there are some clues in the HTTP response headers.
- Process of elimination: Take the "check for updates" URL and start removing stuff (parameters) until it stops redirecting.

**Comment by karolispx** [comment]
As part of our plugin security review, we've sanitized $_POST / $_GET variables throughout the plugin to avoid sql injections. Using sanitize_text_field and isset() seems to not work properly and that's the problem we're seeing right now. I've removed the isset() check and everything seems to work fine now. Thanks!

**Comment by eric-gagnon** [comment]
It’s probably not related but I had this useless message recently while testing install from upload in WordPress, it was caused by a too low upload size limit in php.
