### ISSUE TITLE
Theme Check errors

### ISSUE THREAD

**Issue by DeoThemes** [YahnisElsts/plugin-update-checker#188]
I would love to use this library, but it generates so many errors in a Theme Check. Are you aware of these?

WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'View details'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'More information about %s'
WARNING: Found PHP short tags in file ParsedownLegacy.php.
Line 760: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))
WARNING: Found PHP short tags in file Parsedown.php.
Line 762: if (preg_match('/^\[(.+?)\]:[ ]*<?(\S+?)>?(?:[ ]+['\'(](.+)['\')])?[ ]*$/', $Line['text'], $matches))
WARNING: Found ini_set in the file Extension.php. Themes should not change server PHP settings.
Line 142: @ini_set('display_errors', 'On');
WARNING: Found base64_encode in the file OAuthSignature.php. base64_encode() is not allowed.
Line 71: $parameters['oauth_signature'] = base64_encode(hash_hmac('sha1', $stringToSign, $secret, true));
WARNING: Found base64_decode in the file GitLabApi.php. base64_decode() is not allowed.
Line 212: return base64_decode($response->content);
WARNING: Found base64_decode in the file GitHubApi.php. base64_decode() is not allowed.
Line 267: return base64_decode($response->content);
INFO: readme-parser.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 244: require_once(dirname(__FILE__) . '/Parsedown' . (version_compare(PHP_VERSIO
INFO: UpgraderStatus.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 126: require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
INFO: UpdateChecker.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 221: require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
INFO: Autoloader.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 32: include ($this->libraryDir . $this->staticMap[$className]);

**Comment by YahnisElsts** [comment]
I was not aware of that, but I think most of those don't qualify as actual errors.

> WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'View details'

This is deliberate. One of the design goals of this update checker is to be consistent with the existing WordPress interface. This means that, among other things, the "view details" links that are added by the update checker should have the same label as the "view details" links displayed by WP core. It's more practical to re-use the existing translations than to find volunteers to translate the update checker into 70+ languages.

> WARNING: Found PHP short tags in file ParsedownLegacy.php.
Line 760: if (preg_match('/^[(.+?)]:[ ]<?(\S+?)>?(?:[ ]+''(['')])?[ ]$/', $Line['text'], $matches))

As you can see, this is a false positive and not an actual short open tag. Also, this file is an old version of a third-party library that's only included for backwards compatibility purposes. If you're on PHP 5.3 or anything more recent, the file will never be loaded.

> WARNING: Found ini_set in the file Extension.php. Themes should not change server PHP settings.
Line 142: @ini_set('display_errors', 'On');

This code is part of a debugging component. It will only be loaded if the user installs the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin, opens the update checker panel in that plugin, and clicks the "Check Now" or "Request Info" button in that panel. Basically, it's a tool for developers. I think it's acceptable to temporarily change PHP settings to provide more debugging information to developers.

> WARNING: Found base64_encode in the file OAuthSignature.php. base64_encode() is not allowed.
Line 71: $parameters['oauth_signature'] = base64_encode(hash_hmac('sha1', $stringToSign, $secret, true));
WARNING: Found base64_decode in the file GitLabApi.php. base64_decode() is not allowed.
Line 212: return base64_decode($response->content);
WARNING: Found base64_decode in the file GitHubApi.php. base64_decode() is not allowed.
Line 267: return base64_decode($response->content);

GitHub API, GitLab API and OAuth all use Base64 encoding in various places. It would be impossible (or at least hard) to support these services without using `base64_encode` and `base64_decode`. If you don't plan to use GitHub/GitLab/OAuth, you can delete these files to stop Theme Check complaining about them. 

> INFO: readme-parser.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 244: require_once(dirname(FILE) . '/Parsedown' . (version_compare(PHP_VERSIO
INFO: UpgraderStatus.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
Line 126: require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
(and so on)

Naturally, a library of any complexity will use `include` or `require`. There's not really any way around that. I think Theme Check is being a bit paranoid here.
