### ISSUE TITLE
Updating from a fork

### ISSUE THREAD

**Issue by eric-gagnon** [YahnisElsts/plugin-update-checker#189]
Hello,

I currently have a problem where the update check seem to be done from origin instead of fork release.
It's my first public release on Github so I wanted to double check that everything was fine by testing release and update in a fork copy.

Everything went fine with the plugin but I'm blocking on theme update, while debugging it looks like the library is doing the update check on the original repo, not the fork. Is this intended behavior? I was actually thinking of adding a option in my settings panel to make the update url more visible / editable.

```
[](Puc_v4p4_Theme_Update object {
  extraFields => array(1) (
    [0] => (string) details_url
  )
  details_url => (string) https://github.com/originalaccount/theme/
  slug => (string) theme
  version => (string) 1.0.0
  download_url => (string) https://api.github.com/repos/originalaccount/theme/zipball/master
  translations => array(0)
})
```

The update code in my local testing installation is currently
```
if ( class_exists( 'Puc_v4_Factory' ) ) {
	$update_checker = Puc_v4_Factory::buildUpdateChecker(
		'https://github.com/forkaccount/theme/',
		__FILE__,
		'theme'
	);
    $update_checker->setBranch('test-release');
}
```

I have changed the update repo after the initial install, maybe the origin repo is saved before in a option or there is something else?

I will continue searching for the cause but if you have any idea of what I could look for I would appreciate the help.

Thanks!

**Comment by eric-gagnon** [comment]
I think the problem is indeed caching in the option, ex. puc_external_updates_
I will try to reactivate the plugin or delete the options and see if it helps.

**Comment by eric-gagnon** [comment]
Yeah, reactivating the plugin was enough.
Any suggestion on how I should handle the reset, juste delete the options?

Is there a reason for the different identifiers?

puc_external_updates_theme-name-of-theme
external_updates-name-of-plugin

**Comment by eric-gagnon** [comment]
On update, I get "La mise à jour a échoué : Vous avez la dernière version de ce thème." (update failed, you have last version).

**Comment by eric-gagnon** [comment]
I'm a bit lost.
I was trying to trace it, I was in bulk_upgrade and there was a big error (timeout maybe). The update check seem to no be working anymore.

I will close, restart the test and trace the code, I will open another bug once I understand a little bit more what it's happening.

**Comment by eric-gagnon** [comment]
Just a update, it's again totally my fault. I wanted to do a test to document the release procedure, I was suspecting that naming could be a trap (when you download from Github, there is a version appended). My folder was named "theme-1.0" and when WordPress do the bulk_updgrade the key match is not done appropriately.

The values known in "response" is:
[theme-1.0] => array(4) (

But the value of $theme is "theme-10", so the match is not done correctly
if ( !isset( $current->response[ $theme ] ) ) {
            
The solution is obviously to not have the version number in the name of the folder but I wonder if this would not be a error that should be fixed (the install name when uploading a theme should be the slug but that value doesnt exist in style.css. Maybe it's extracted from Theme URI (was undefined in my file as I wanted to update it when on Github).

Sorry for the false issue.

**Comment by YahnisElsts** [comment]
> The values known in "response" is:
[theme-1.0] => array(4) (
> 
> But the value of $theme is "theme-10", so the match is not done correctly, not sure why there is a mismatch there (maybe the theme slug is not calculated the same way in plugin checker?), I will maybe investigate that later.

Are you saying that `$theme` didn't match the theme directory name? Where exactly did you see that discrepancy, what part of the code?

**Comment by plateforme-medialab-responsables** [comment]
Yes.

Sorry my writting is hard to read, my first language is french.

I think it could be related to the transformation done in wp_ajax_update_theme

$stylesheet = preg_replace( '/[^A-z0-9_\-]/', '', wp_unslash( $_POST['slug'] ) );

I found the suspect by searching in the code, I will do a test to confirm, I guess that adding the same transformation in Puc could solve this part of the problem (failing upgrade).

Also, I'm surprised that WordPress used the folder name as is, I think it could be related to Theme URI missing in my readme.txt but I'm not 100% sure, I will double check that also as it's a bit unconvenient with the install procedure of my projet that suggest to take the lastest zip release (wich contains tag no and I dont want the user to manually change the filename).

**Comment by plateforme-medialab-responsables** [comment]
It looks like the install by upload of WordPress has a bug.

I upload my theme theme-1.0.zip, the created folder in wp-content/themes is theme-1.0.zip (looks like Theme URI is not used to calculate the folder name, I will trace the code).

If I try to delete the theme using WordPress ui, I get a "theme doesnt exist" error (but the delete does complete if I manually correct the filename (without version) in the file system.

**Comment by YahnisElsts** [comment]
> I think it could be related to the transformation done in wp_ajax_update_theme
> $stylesheet = preg_replace( '/[^A-z0-9_-]/', '', wp_unslash( $_POST['slug'] ) );

That's interesting. On the one hand, that does look like a bug in WordPress core. On the other, some developers could reasonably argue that theme and plugin folder names shouldn't contain special characters.

In general, I would not recommend including the version number in the folder name. It should just be `theme-slug`. However, if an *update* contains the version number - like the `theme-slug-X.Y.zip` archives generated by GitHub - then that's fine. The update checker will detect the name mismatch and automatically rename the folder.

For what it's worth, I don't think it has anything to do with Theme URI, but I haven't looked at that part of WordPress core code in a while.

**Comment by eric-gagnon** [comment]
Sorry, I had posted with the organisation account that I want to use for our project and should.

I repost here what I have deleted

----------
Yes.

Sorry my writting is hard to read, my first language is french.

I think it could be related to the transformation done in wp_ajax_update_theme

$stylesheet = preg_replace( '/[^A-z0-9_-]/', '', wp_unslash( $_POST['slug'] ) );

I found the suspect by searching in the code, I will do a test to confirm, I guess that adding the same transformation in Puc could solve this part of the problem (failing upgrade).

Also, I'm surprised that WordPress used the folder name as is, I think it could be related to Theme URI missing in my readme.txt but I'm not 100% sure, I will double check that also as it's a bit unconvenient with the install procedure of my projet that suggest to take the lastest zip release (wich contains tag no and I dont want the user to manually change the filename).


It looks like the install by upload of WordPress has a bug.

I upload my theme theme-1.0.zip, the created folder in wp-content/themes is theme-1.0.zip (looks like Theme URI is not used to calculate the folder name, I will trace the code).

If I try to delete the theme using WordPress ui, I get a "theme doesnt exist" error (but the delete does complete if I manually correct the filename (without version) in the file system.

**Comment by eric-gagnon** [comment]
"For what it's worth, I don't think it has anything to do with Theme URI, but I haven't looked at that part of WordPress core code in a while."

I just have trace the upload and there is nothing I cant do, it use the folder name and no other metadata to calculate folder name, I think it's a bug or could be improve, I will try to open a bug on WordPress for this (and the delete issue). Also, there is no mecanisme to find style.css in a subfolder so it's not possible to encapsulate the folder with the appropriate name in another one with a more variable file name.

Looks like the only viable solution is to rename the release filename in Github to remove the tag that is added by default. It's too hard but it's another manual steps easy to forget (and why it's done this way later on).

**Comment by YahnisElsts** [comment]
As long as you can make sure that the package that the user downloads doesn't have the tag or version number in the name, it should be fine to keep GitHub releases as-is. The update checker will automatically handle different names for updates. However, this might not help much if you're primarily distributing the theme via GitHub since you would still need to prepare a tag-less release for new users.

**Comment by eric-gagnon** [comment]
Yes. The plan is to have install and upgrade process the most simple and smooth possible.
Really happy to have stumbled on your project!

**Comment by eric-gagnon** [comment]
https://core.trac.wordpress.org/ticket/43503#ticket
