### ISSUE TITLE
Plugin update not showing on update page

### ISSUE THREAD

**Issue by victorlap** [YahnisElsts/plugin-update-checker#190]
Hello, 

The plugin update checker is working fine, however the information is not shown on the update page which makes users unable to update the plugin

Wordpress version 4.9.4
PUC version 4.3

update_checker.php

```php
<?php

require 'plugin-update-checker/plugin-update-checker.php';

$myUpdateChecker = \Puc_v4_Factory::buildUpdateChecker(
	'https://bitbucket.org/***/***',
	__FILE__,
	'***'
);

$myUpdateChecker->setAuthentication( array(
	'consumer_key'    => '***',
	'consumer_secret' => '***',
) );
```

See screenshots:

![screen shot 2018-03-12 at 08 54 45](https://user-images.githubusercontent.com/1645632/37271472-576d210a-25d3-11e8-86e9-9bf2acefb21a.png)
![screen shot 2018-03-12 at 08 56 09](https://user-images.githubusercontent.com/1645632/37271475-58b75620-25d3-11e8-9eb8-007d6f9ff6c5.png)
![screen shot 2018-03-12 at 08 56 42](https://user-images.githubusercontent.com/1645632/37271478-59c699c2-25d3-11e8-910e-5c77220e4338.png)

**Comment by YahnisElsts** [comment]
Double-check the file name that you're sending to the `buildUpdateChecker()` method. It must be the full path to the main plugin file. If it's anything else, the update won't show up in the right place(s).

**Comment by victorlap** [comment]
Thanks,

I copied the example from the readme, but __FILE__ was not the main pluginfile.
