### ISSUE TITLE
Theme update not appear on update page

### ISSUE THREAD

**Issue by Spidlace** [YahnisElsts/plugin-update-checker#192]
Hi,

I have a self-instance of Gitlab and i connect all my plugins homemade and my parent theme on Gitlab.
For all my plugin I have no problem, everything work perfectly (with auto update).

But with my theme I have a problem : 
I put in functions.php this code for check update : 
```php
require(get_template_directory().'/plugin-update-checker/plugin-update-checker.php');
$myUpdateChecker = new Puc_v4p4_Vcs_PluginUpdateChecker(
	new Puc_v4p4_Vcs_GitLabApi('https://gitlab.domain.net:8080/user/repo/'),
	get_template_directory().'/style.css',
	'noyau'
);
$myUpdateChecker->setBranch('master');
```

The version of the theme parent (noyau) on Gitlab is : **2.3.44**
The version of the theme parent (noyau) in file style.css is : **2.3.43**

With plugin debug bar, he checks and find the new version : [See image](https://image.ibb.co/gQc1Sx/update_checker_noyau.jpg)

But, in my update page (wp-admin/update-core.php), I see no update.
With this function : _get_theme_updates()_, no update detect...

Where is my mistake ?
Thanks a lot !

**Comment by YahnisElsts** [comment]
Since it's a theme and not a plugin, you need to use the `Puc_v4p4_Vcs_ThemeUpdateChecker` class. Try replacing `Puc_v4p4_Vcs_PluginUpdateChecker` with `Puc_v4p4_Vcs_ThemeUpdateChecker`.

**Comment by Spidlace** [comment]
Thanks a lot !

For everybody who had this error : 

```php
require(get_template_directory().'/plugin-update-checker/plugin-update-checker.php');
$myUpdateChecker = new Puc_v4p4_Vcs_ThemeUpdateChecker(
	new Puc_v4p4_Vcs_GitLabApi('https://gitlab.creasrv.net:8080/creasit/noyau/'),
	'noyau',
	'noyau'
);
$myUpdateChecker->setBranch('master');
```
