### ISSUE TITLE
First time using, What am I missing?

### ISSUE THREAD

**Issue by solepixel** [YahnisElsts/plugin-update-checker#194]
I have the library setup in my plugin, I'm testing the update on my site to make sure it works and it's showing via Debug Bar that the latest version is 1.9.9c and I have 1.9.9b installed. https://3cd.co/1Z461L0s0c3Z

When I visit the Dashboard > Updates page, it doesn't give me a prompt to update my out-of-date plugin. Am I doing something wrong?

**Comment by YahnisElsts** [comment]
Check the file name that's passed to `buildUpdateChecker`. It should be the full path to the main plugin file, not some other file.

**Comment by solepixel** [comment]
I think I've got it figured out. I believe my problem was here:
```
//Optional: Set the branch that contains the stable release.
$myUpdateChecker->setBranch('stable-branch-name');
```
I'm using the Tag feature on Gitlab to release new versions and when I set this, it was possibly confusing the plugin. It seems to be working now.
