### ISSUE TITLE
Use case for multiple plugins?

### ISSUE THREAD

**Issue by solepixel** [YahnisElsts/plugin-update-checker#196]
I'm trying to write a plugin that uses this library to handle updates for the plugin. I'd also like to have extensions to this plugin that also auto-update. To keep from having to reproduce the same code, I'd like to keep all the update/license check code in the Main plugin, and each extension utilizes the main plugin code to handle updates.

This is the code I have:
```
$this->updaters[ $this->plugin_slug ] = Puc_v4_Factory::buildUpdateChecker(
	$this->repo_url,
	$this->plugin_path . $this->plugin_filename,
	$this->plugin_slug
);
$this->updaters[ $this->plugin_slug ]->setAuthentication( $this->repo_access_key );
```

All my values are being passed in correctly, and tagging even works to some degree (notifies of an update available when tagged), however the part that's not working is the repo for the extension for some reason is using the repo from the main plugin. When I click "View version details" everything is for the correct repo, however when I click update, the main plugin replaces the extension. Is it possible to use this in this way, or do I need to separate the library into 2 separate plugins/directories and call them independently?

**Comment by solepixel** [comment]
So, I think this sort of works for different plugins, however there's something in this library that is caching update requests. Still digging around, but testing this out today 0.9.9 -> 1.0.0 works for the extension, but when I change 2.0.1 to 2.0.0, there is not update notification. I think the library has stored the 1.0.0 update for the extension and isn't checking for the main plugin.

**Comment by solepixel** [comment]
Ahh! I figured it out. There was an option stored as "external_updates" and I traced it back to realize I can separate the plugins by using a 5th parameter in buildUpdateChecker() to identify each plugin. Hope that helps someone!

**Comment by YahnisElsts** [comment]
Wait a minute, that option is supposed to be named `external_updates-$slug` instead of just `external_updates`. Could it be that you're accidentally passing an empty slug to `buildUpdateChecker`?

**Comment by solepixel** [comment]
@YahnisElsts You are very correct! That is very much a possibility. During my development of this functionality I may have not yet implemented a check to make sure the slug was passed through unempty, so it could have stored it while I was testing some stuff.

**Comment by YahnisElsts** [comment]
I see. Normally you don't need to explicitly specify the option name to prevent different update checker instances from conflicting with each other. In fact, you don't even need to specify the slug - the update checker will choose it automatically based on the file name. You only need to set it if you plan to do something with it, like using PUC-related hooks.
