### ISSUE TITLE
Call to undefined method Puc_v4p4_Theme_UpdateChecker::setAuthentication() 

### ISSUE THREAD

**Issue by RustaLenin** [YahnisElsts/plugin-update-checker#197]
Download fresh null theme from http://underscores.me/
Start developing
End developing ( Simple blog theme )
Add plugin update checker like usually and see this error:

`Fatal error: Uncaught Error: Call to undefined method Puc_v4p4_Theme_UpdateChecker::setAuthentication() in D:\localhost\domains\advance-blog\wp-content\themes\advice_theme\functions.php:221 Stack trace: #0 D:\localhost\domains\advance-blog\wp-settings.php(426): include() #1 D:\localhost\domains\advance-blog\wp-config.php(89): require_once('D:\\localhost\\do...') #2 D:\localhost\domains\advance-blog\wp-load.php(37): require_once('D:\\localhost\\do...') #3 D:\localhost\domains\advance-blog\wp-blog-header.php(13): require_once('D:\\localhost\\do...') #4 D:\localhost\domains\advance-blog\index.php(17): require('D:\\localhost\\do...') #5 {main} thrown in D:\localhost\domains\advance-blog\wp-content\themes\advice_theme\functions.php on line 221`

WP 4.9.5
LocalHost
PHP 7.2x64
MariaDb-10.2-x64

**Comment by YahnisElsts** [comment]
That method is only available when using a supported VCS host like GitHub, BitBucket or GitLab. What kind of a repository do you have?

**Comment by RustaLenin** [comment]
BitBucket on our own server

**Comment by RustaLenin** [comment]
Let me guess, it's check what Class and Method to use by domain name?

**Comment by YahnisElsts** [comment]
In that case, you'll need to directly create an instance of `Puc_v4p4_Vcs_ThemeUpdateChecker`. As you guessed, `buildUpdateChecker` checks the domain name, so it doesn't work with self-hosted repositories.

**Comment by YahnisElsts** [comment]
Something like this:
```php
return new Puc_v4p4_Vcs_ThemeUpdateChecker(
	new Puc_v4p4_Vcs_BitBucketApi('http://repository-here'),
	__FILE__,
	'slug'
);
```

**Comment by RustaLenin** [comment]
For know it

`Fatal error: Uncaught InvalidArgumentException: Invalid BitBucket repository URL: "https://myownserver.com/projects/CST/repos/advice_theme/" in D:\localhost\domains\advance-blog\wp-content\themes\advice_theme\plugin-update-checker\Puc\v4p4\Vcs\BitBucketApi.php:26 `

**Comment by YahnisElsts** [comment]
Hmm, my bad. I was thinking of GitLab. PUC actually doesn't support BitBucket repositories that are not on bitbucket.org. It would take some work to add that support.

**Comment by RustaLenin** [comment]
I see. Seems we will use one of public cloud services for now. Thank's for quick answer.
