### ISSUE TITLE
Disabling SSL verification on plugin updates

### ISSUE THREAD

**Issue by seyfro** [YahnisElsts/plugin-update-checker#20]
Hi Yahnis,

first thanks for your great plugin, I use it in my plugin Maps Marker Pro (www.mapsmarker.com). 

A few months ago I started delivering my plugin updates via SSL. This worked fine for well maintained servers but as my user base grew over time, more and more error reports were filed that updates could not be retrieved. In most cases the reason was, that the SSL libraries on the server were outdated and could not verify the SSL certificate (sslverify).

As most users were on shared hosts and had little influence on the maintenance of SSL libraries, I decided to still deliver plugin updates via SSL but to disable the ssl verification. Not a beautiful solution, but needed as otherwise plugins wouldnt be delivered and as in the near future I am planning to redirect all http-requests to https which would cause issues if I didnt use https for the plugin-update-checker.

Just want to share with you how I did this (sorry for not sending a PR, thought, making an issue here would be easier):

With in the "public function __construct" I added two filters for disabling ssl verification, right after "$this->installHooks();":

`add_filter( 'https_ssl_verify', '__return_false' );`
`add_filter( 'https_local_ssl_verify', '__return_false' );`

In addition, within "public function requestInfo($queryArgs = array()){" I also added the wp_remote_get-option 
`'sslverify' => false,`
so that with plugin checks also no SSL verification is done.

Perhaps this is also helpful for you!
best,

Robert

**Comment by ajoah** [comment]
For those interested, the code I used to disable ssl verification only for my update server requests:
```php
add_filter('http_request_args', 'my_http_request_args',10,2);
function my_http_request_args($request_args, $url) {
	if (strpos($url, 'http://example.com/') === 0) {
		$request_args['sslverify'] = false;
	}
	return $request_args;
}
```
