### ISSUE TITLE
Readme file not read

### ISSUE THREAD

**Issue by Streamlinelv** [YahnisElsts/plugin-update-checker#200]
Hi,

I have setup a Bitbucket integration. Updates are downloaded and everything is working fine but somehow the Readme file which previously was properly read now is not. It is still formatted after WorPress standards. Do you have any clues what could be the issue?

By the way - Changelog also is showing empty which should not be empty for sure.
And it seems that Readme.txt file is not being read at all but everything is read from main plugin .php file. How is that possible?

<img width="816" alt="screen shot 2018-04-30 at 12 45 24" src="https://user-images.githubusercontent.com/6198156/39422056-7c8735ee-4c74-11e8-9b51-74e17b472f0e.png">

**Comment by YahnisElsts** [comment]
There are a number of things that could cause that. Here are some ideas:
- Does the local installation have a readme file? The update checker won't bother looking for a readme in the repository if the installed version doesn't have it.
- What's the name of the readme file? The local and remote file names must match exactly, and it's a case-sensitive comparison. For example, if the installed plugin has `readme.txt` and the repository has `Readme.txt`, that's not going to work.
- Enable `WP_DEBUG` and click the "check for updates" link. Do any BitBucket API errors show up?

**Comment by Streamlinelv** [comment]
Thanks for getting back so quickly.
As mentioned previously - I was working fine before but recently (yesteday) I noticed that the readme file is not being read and therefore all information is almost blank and now I noticed that the info is taken from plugins main .php file.

1) the plugins readme.txt file is located in the root directory of the plugin folder (as WordPress suggests)
2) Both Bitbucket and local versions have exactly the same name for the file "readme.txt"
3) WP_Debug shows no errors whatsoever and gives this message "Successfully retrieved plugin info from the metadata URL"

**Comment by YahnisElsts** [comment]
Hmm, there's nothing else I can think of that doesn't require access to the actual plugin code. 

Maybe you could try stepping through the `requestInfo` method in `/Puc/v4/Vcs/PluginUpdateChecker.php` with a debugger or adding some logging code? Lines 90 to 92 contain the high-level readme related logic. I'd start there and then drill down into the functions called on those lines.

**Comment by Streamlinelv** [comment]
Thanks for the tip. Managed to locate the issue now.
Found the issue - My readme file had some extra spaces that were ok in the Wordpress but not here.

Thanks for the great plugin!

**Comment by YahnisElsts** [comment]
It's good to hear that you figured it out. That sounds like it could be a bug in PUC. It's supposed to support the same readme syntax as WordPress.org. Would you mind posting the relevant part of the file? I'd like to figure out why the readme parser was having problems with it.

**Comment by Tofandel** [comment]
Just remembered my PR #229, didn't it fix this issue ?

**Comment by YahnisElsts** [comment]
It's hard to say if this was the same issue since we haven't seen this particular readme.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months and there is not enough information to determine if it was a parser bug or not.
