### ISSUE TITLE
Update not using the release zip file (browser_download_url).

### ISSUE THREAD

**Issue by eric-gagnon** [YahnisElsts/plugin-update-checker#201]
Hello,

It looks like the update of my plugin to 1.0.1 didnt work as expected. Detection was fine, update from WordPress too but it was missing the vendor folder (composer) that is only present in the release zip file, so I guess that the update was done using the source.

Is it me that didnt understood correctly that part? (the source of the update).

I will test again in a separated fork and report.

Eric

**Comment by eric-gagnon** [comment]
I can reproduce it here : https://github.com/eric-gagnon/platform-shell-plugin/releases/tag/v1.0.1
On my local installation I had to change the repository url in the plugin main file as it's not in a configuration.

I will trace and try to understand what's happening under the hood.

**Comment by eric-gagnon** [comment]
It looks like plugin update using zipball_url, not browser_download_url.

https://api.github.com/repos/eric-gagnon/platform-shell-plugin/zipball/v1.0.1 (without vendor)
https://github.com/eric-gagnon/platform-shell-plugin/releases/download/v1.0.1/platform-shell-plugin.zip (with vendor folder).

Looks like the only option I have for now is to add the folder folder in the repo.

What do you think?

I will check the code some more make sure I didn't miss something, I'm surprised that I didn't notice that before.

**Comment by eric-gagnon** [comment]
I have tested and things do work with the missing line.
I'm closing. All my fault but I think it could be nice to add a note in the main documentation.

**Comment by YahnisElsts** [comment]
`enableReleaseAssets()` is indeed the right solution for that. I'll make a note to update the documentation.

**Comment by eric-gagnon** [comment]
Perfect, thanks!
