### ISSUE TITLE
Update for Must-use Plugins?

### ISSUE THREAD

**Issue by HW-Siew** [YahnisElsts/plugin-update-checker#203]
Hi, is this plugin checker works with must-use (MU) plugins? How do I trigger an auto update if it is?

Thanks

**Comment by YahnisElsts** [comment]
WordPress doesn't support automatic update installation for must-use plugins, so this update checker doesn't support it either. You can use the update checker to display an update notification for a mu-plugin, but the user won't be able to actually install the update from the WordPress dashboard.

**Comment by HW-Siew** [comment]
Thank you for the information.
