### ISSUE TITLE
Error when checking for updates?

### ISSUE THREAD

**Issue by JordanNZ** [YahnisElsts/plugin-update-checker#204]
Hey, I've just installed the plugin and trying to get this work to no avail, I'm wanting to update plugins from a private repo on github i've added the code below to my main plugin file and get the following [error](http://prntscr.com/jov4la) any idea how I can go about fixing this/where i have gone wrong?

```
/**
 * Update Plugin Checker
 * Will hopefully check if the version is the latest version and if not display a notification
 *
*/

require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Jordan/Hail/',
	__FILE__,
	'spf-hail'
);

//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->setAuthentication('derp');

//Optional: Set the branch that contains the stable release.
//$myUpdateChecker->setBranch('master');

//Grabs the releases
$myUpdateChecker->getVcsApi()->enableReleaseAssets();
```

**Comment by YahnisElsts** [comment]
Please double-check the repository URL and the access token. The error suggests that one of them might be incorrect.

**Comment by JordanNZ** [comment]
Well shit, turns out I forgot my own username lmao thank you for this.
