### ISSUE TITLE
Issue with displaying plugin info for beta versions

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#21]
Hi Yahnis,

got the following issue: I just uploaded a beta version (1.9-beta1) to my plugin update server at https://www.mapsmarker.com/updates/?action=get_metadata&slug=leaflet-maps-marker-pro-beta
As you can see from the URL, the plugin infos are retrieved correctly.

If I try to in contrast retrieve the plugin infos from within WordPress by going to Plugins and clicking on "View version 1.9-beta1 details" next to my plugin in the list, a popup with the following error opens:

An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums.

The plugininfo for non-beta-versions (e.g. 1.8) in contrast was displayed successfully when clicking on that link.

Do you know if there are any issues with displaying plugininfo when plugin version is not regular, like it is with beta-versions (1.9-beta1)? I turned on debugging and looked into the server PHP error logs but didnt find any hint on whats wrong here - so any help would be really appreciated!
best,

Robert

**Comment by YahnisElsts** [comment]
Update: In my case, updating the server OS to a newer version completely fixed the issue. This further confirms that it wasn't caused by the update checker as such, and probably had something to do with the server having an outdated version of CURL/a SSL library.
