### ISSUE TITLE
Redux: Getting "Update Failed: The directory structure of the update is incorrect." (When directory structure appears to be correct)

### ISSUE THREAD

**Issue by rickhellewell** [YahnisElsts/plugin-update-checker#210]
I am getting the same error as here: https://github.com/YahnisElsts/plugin-update-checker/issues/62 .

The plugin code is self-hosted on a public server. The plugin code is placed in the my-custom-functions.zip file. The Zip file contains, at it's root, all plugin files and folders.  The plugin.json file in the public server location points to the plugin-name.zip file. 

The plugin is recognized as needing an update. Performing the update gives me this error:

`Downloading update from https://example.com/git/my_custom-functions.zip…
Unpacking the update…
Installing the latest version…
Plugin update failed.An error occurred while updating My Custom Functions: The directory structure of the update is incorrect. All files should be inside a directory named my-custom-plugin, not at the root of the ZIP archive.`

Note that the directory name in the error message is 'my-custom-plugin', not 'my-custom-functions'.

The plugin main file is called my-custom-plugin.php .  That file has the proper 'buildupdatechecker' parameter pointing to the public location of the zip file; that same public location also contains the plugin.json file.

So I am confused as to the directory structure of the ZIP file. 

I am on Win10, using 7-zip as the archiver.

Thanks.

**Comment by YahnisElsts** [comment]
> The plugin code is placed in the my-custom-functions.zip file. The Zip file contains, at it's root, all plugin files and folders.

It sounds like you're saying that the current ZIP file layout looks something like this:

```
my-custom-functions.zip
    my-custom-plugin.php
    readme.txt
    /some-folder
    /other-folder
    ...
```

Is this accurate? If so, you need to create a folder with the same name as the plugin slug and move everything into that folder:


```
my-custom-functions.zip
    /my-custom-functions
        my-custom-plugin.php
        readme.txt
        /some-folder
        /other-folder
        ...
```

**Comment by rickhellewell** [comment]
Just to clarify: the zip file should contain the '/my-custom-functions' folder, and then all the plugin files are in that my-custom-folder (as part of the zip file). 

I don't have to extract the plugin files and place them in the my-custom-functions folder, in addition to the zip file. Correct?

And suggest that the docs/readme for the self-hosted files has this folder structure information.

**Comment by YahnisElsts** [comment]
> Just to clarify: the zip file should contain the '/my-custom-functions' folder, and then all the plugin files are in that my-custom-folder (as part of the zip file).

That's correct.

> I don't have to extract the plugin files and place them in the my-custom-functions folder, in addition to the zip file. Correct?

I'm not sure I really understood that, but you only need a ZIP file. You don't need a second copy of the plugin's files.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for more than a year.

**Comment by allamberto** [comment]
I am having similar problems as this post and #62. The update is recognized as needing an update but when I attempt to update I receive the error "The directory structure of the update is incorrect". My file structure is as follows. I have a 
pp-plugin.zip file that when decompressed creates a pp-plugin folder. I have another pp-plugin folder inside that. In this folder, I have all my files:
`pp-plugin.zip
    /pp-plugin
        index.php       
        /some-folder
        /other-folder
        ...`

This seems to fit the hierarchy you described in the comments. Could this be a ZIP tool problem or still a hierarchy problem? I am using AWS CodeDeploy as the ZIP tool. Thanks!

**Comment by YahnisElsts** [comment]
Could it be that you're on macOS? I've received multiple reports that the default ZIP tool on that OS makes it look like archived files are in a folder when they're actually not. The hierarchy that you've shown looks fine to me, but if you're on a Mac then what you see might not match the actual folder hierarchy. I would recommend trying a different ZIP tool to view the files.
