### ISSUE TITLE
Only a question

### ISSUE THREAD

**Issue by BartzikWebdesign** [YahnisElsts/plugin-update-checker#211]
Hi @YahnisElsts,

I try to get the plugin-update-checker to run with my private repo on GitHub. Therfor I use this code in the `functions.php`:

```
require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/user-name/repo-name/',
	__FILE__,
	'unique-plugin-or-theme-slug'
);

//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->setAuthentication('your-token-here');

//Optional: Set the branch that contains the stable release.
$myUpdateChecker->setBranch('stable-branch-name');

```
Please can you tell me where to find / to get / to set the access token for a private repo on GitHub? I can't find anything about this...

Thank you so much!

**Comment by YahnisElsts** [comment]
I think it's in the general GitHub settings: *Settings -> Developer Settings -> Personal access tokens*. There should be a "Generate new token" button.
