### ISSUE TITLE
Updating from git - possible to add a hotfix branch?

### ISSUE THREAD

**Issue by vyskoczilova** [YahnisElsts/plugin-update-checker#214]
Hi, 

I'm using this plugin (thanks a lot!) for theme updates from GitHub (deploying from master branch). Do you think that it could be possible to check a let's say "hotfix" branch first and then master with a big change? We have multiple branches with updates which are slowly merged to master - preparing for a release - but sometimes we need to push a quick hotfix and this complicates our flow.

Is there a particular way you would recommend doing that? Later, I could pull this feature to the plugin (client is ok with that) so that's why I'm asking first.

**Comment by YahnisElsts** [comment]
I would recommend starting with the [`chooseReference()`](https://github.com/YahnisElsts/plugin-update-checker/blob/01863da0e8445e563abe4fcd5a440d576470eb6a/Puc/v4p4/Vcs/GitHubApi.php#L311) method in GitHubApi.php. You could expand it to try other branches before falling back to `master`. The current implementation looks like this:

```php
if ( $configBranch === 'master' ) {
	//Use the latest release.
	$updateSource = $this->getLatestRelease();
	if ( $updateSource === null ) {
		//Failing that, use the tag with the highest version number.
		$updateSource = $this->getLatestTag();
	}
}
//Alternatively, just use the branch itself.
if ( empty($updateSource) ) {
	$updateSource = $this->getBranch($configBranch);
}
```

You could change the section that tries the configured branch to instead try several different branches and use the first valid result. For example:

```php
//Use the first valid branch from a list.
$branches = array('hotfix', 'another-branch', $configBranch);
foreach($branches as $branch) {
	$updateSource = $this->getBranch($configBranch);
	if ( !empty($updateSource) ) {
		break;
	} 
}
```

Alternatively, you could also have more complicated branch selection logic, like querying multiple branches, sorting the results, and choosing the one with the highest version number.
