### ISSUE TITLE
Little doubt

### ISSUE THREAD

**Issue by cptolemy** [YahnisElsts/plugin-update-checker#215]
Hi again,

I just have a quick question, if I may. Instead of placing the url to fetch the version json file, I made a script which receives the request. Basically I have done something like:

$url = "http://mywebsite.com/myscript.php?param1=etc&param2=etc2";

And the code:

$json = array( "name" => "myPlugin",
	              "version" => "2.0.0.0",
	              "download_url" => "http://mywebsite.com/myfile.zip",
	              "homepage" => "http://mywebsite.com/",
	              "last_updated" => "2018-07-01 09:00:00"
                       );
header("Content-type:application/json");
$out = json_encode($json, true);
echo $out;

This was working - but not anymore. Can you help me understand why? If I place as url a json file, I get no problems. But this method was working. And I can see in your code, you get the json info with wp_remote_get and accepting the application/json header.

Kind regards,

**Comment by YahnisElsts** [comment]
Try comparing the server responses that you get when you access your script and a plain JSON file. Are the contents exactly the same? If not, what is the difference and what could cause it? Are the response headers the same? You can view the headers in the browser's developer tools.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for about a year.

If you still encounter this problem, feel free to reopen the issue or create a new one.
