### ISSUE TITLE
Constantly prompted for update

### ISSUE THREAD

**Issue by Matthewrbowker** [YahnisElsts/plugin-update-checker#216]
Hello!
Normally I don't use issues to ask for help, but I can't figure out where else to ask.  I've installed plugin-update-checker on a private WordPress plugin, which is hosted on BitBucket.  I am constantly getting prompted for an update on the admin control panel, even though I am running the latest version.  Running the update succeeds yet claims there's a new update immediately.  

Relevant sections of my readme.txt:

> === BBAV Scheduling Extension ===
> Contributors: mbowker
> Tags: scheduling
> Requires at least: 4.6
> Tested up to: 4.9.6
> Stable tag: 1.2.1
> Requires PHP: 5.2.4
> License: Proprietary
> 
> Scheduling extension for BBAV Studios, allowing our team to manage their availability so we can react quickly to new opportunities.

And screenshots of what I'm seeing:
<img width="1474" alt="screen shot 2018-07-16 at 15 23 04" src="https://user-images.githubusercontent.com/802331/42784399-5992dec4-890c-11e8-8ebd-f6b79a5042e7.png">
<img width="1494" alt="screen shot 2018-07-16 at 15 23 34" src="https://user-images.githubusercontent.com/802331/42784400-59b50c56-890c-11e8-8735-fbdf387ab2bf.png">
<img width="1480" alt="screen shot 2018-07-16 at 15 24 09" src="https://user-images.githubusercontent.com/802331/42784401-59db3b60-890c-11e8-8d4b-8f3b2b808bf0.png">

**Comment by YahnisElsts** [comment]
It seems odd is that the second screenshot doesn't show the currently installed version of the plugin. Does the plugin have `Version:` header? Please check if for typos and make sure it contains a valid version number.

**Comment by Matthewrbowker** [comment]
That fixed it, I missed that step in configuration (I was following purely the BitBucket configuration steps) so it appears to be working successfully.  You are welcome to close this ticket, I feel like a bit of an idiot now...

**Comment by YahnisElsts** [comment]
No worries, I get configuration questions all the time. 

One thing that I would recommend is to enable [WP_DEBUG](https://codex.wordpress.org/WP_DEBUG). When `WP_DEBUG` is set to `true`, the update checker will trigger PHP warnings or notices when it detects certain configuration problems. You can then find those messages in the PHP error log.
