### ISSUE TITLE
Updating Theme Creates a Subdirectory?

### ISSUE THREAD

**Issue by lheazel** [YahnisElsts/plugin-update-checker#220]
I'm certain that this is an error on my part. I'm using your plugin to manage updates for a Wordpress them as well as several child themes. I have my JSON file hosted on GitHub and the zipped versions on an Amazon S3. The update checker code is in my functions.php files as required. Each theme, obviously, has its own JSON and S3 repos, and own versions of the update code.

When I test updating my themes, the download works fine, but the unzipped theme nestles itself within a self-named subfolder. The result is "wp-content/themes/theme-name/theme-name/actual theme code". Absurdly, this only occurs with two of the themes; the third works perfectly. The error is also does not occur when testing on localhost.

I can't for the life of me figure out the cause of this. The folder format within the zip file in the repo seems to have no impact on this, and I've been able to reproduce it in numerous locations on remote servers.

**Comment by YahnisElsts** [comment]
My first guess would also be the folder layout in the ZIP file. That's the most common source of problems with updates installing in the wrong (sub-)directory.

Could you show me the JSON and the download URL or ZIP file for one of the affected themes? I might be able to spot something. If you don't want to post that publicly, feel free to send me an email: `whiteshadow@w-shadow.com`

**Comment by lheazel** [comment]
Actually, I'm not sure if it's necessary. For all three themes, the top-level in the zip was the theme folder, containing the theme files itself.

I checked the process again after the weekend and everything seemed oddly to work. My best guess is that things got weird with the CDN and worked themselves out while I was gone. I'll be keeping an eye on this though, and if the error pops up again I'll be sure to return. Regardless, thanks for your prompt response!

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for about a year.

If you still encounter this problem, feel free to reopen the issue or create a new one.
