### ISSUE TITLE
GitHub API error

### ISSUE THREAD

**Issue by FlorianValois** [YahnisElsts/plugin-update-checker#221]
Hi !

First of all, thank you for this plugin, it's save my life. ^^"

The configuration is very simple and it works properly locally. I work on two sites, one is used to develop my plugin, the other allows me to see if the update is correctly detected (in auto or manual, both work perfectly)

On a remote server, it's something else. I have an error message that appears:

>     Could not determine if updates are available for Boilerplate plugin.
>     
>     GitHub API error. Base URL: "/repos/:user/:repo/releases/latest", HTTP status code: 403. puc-github-http-error
>     GitHub API error. Base URL: "/repos/:user/:repo/tags", HTTP status code: 403. puc-github-http-error
>     GitHub API error. Base URL: "/repos/:user/:repo/branches/master", HTTP status code: 403. puc-github-http-error
>     Could not retrieve version information from the repository. This usually means that the update checker either can't connect to the repository or it's configured incorrectly. puc-no-update-source

Whether for detection with the button "check update" or in automatic detection, this message is displayed.

Knowing that the file in question at CHMOD rights required.

Do you have an idea ?

Thanks and have a good day.

**Comment by YahnisElsts** [comment]
Here are some ideas:

- Is it a private GitHub repository? Make sure that the access key is valid and that the plugin is using the same key locally and on the remote server. For example, if the key is stored or cached somewhere, maybe one of the sites might have an outdated key.
- Does the server have a firewall that blocks outgoing request? Do you need to add `api.github.com` to a whitelist?
- Does the site use a proxy that might be blocking the request?
- You can use the [Core Control](https://wordpress.org/plugins/core-control/) plugin to log HTTP requests sent by this update checker (and plugins/themes in general). Looking at the full HTTP headers and response body might give you some clues.
