### ISSUE TITLE
403 error with WooCommerce

### ISSUE THREAD

**Issue by davy440** [YahnisElsts/plugin-update-checker#223]
I want to include auto-update functionality for my WordPress Themes. 
Since I am using WooCommerce, a link to a WooCommerce Upload does not work since the 'woocommerce_uploads' folder is secured and not publicly accessible.

The way out I found was uploading the file to a publicly accessible place but I don't want to compromise security. How should I go about it?

**Comment by YahnisElsts** [comment]
It sounds like you need a license manager. This update checker doesn't include anything like that, though it's generally extensible enough to integrate it with existing license management systems. I currently have [an open issue](https://github.com/YahnisElsts/plugin-update-checker/issues/222) asking for feedback on whether this library needs license management features and how that should work.

I personally haven't done license management with WooCommerce, but a quick search suggests that there are multiple options available, e.g. [WooCommerce Software License](https://woosoftwarelicense.com/) (no affiliation). Maybe one of them would work for you?

**Comment by davy440** [comment]
Got it! Thanks for pointing me in the right direction.
