### ISSUE TITLE
Github private repo with access token 403 Forbidden if not logged in to Github 

### ISSUE THREAD

**Issue by JiveDig** [YahnisElsts/plugin-update-checker#226]
We've been using the github access token to increase API limits on some of our personal/client sites. I've noticed that the update check gives 403 errors if I'm not logged in to my github account in the browser I'm checking with.

Here's the setup when we see the issue:

All of the plugins affected are using PUC.
One plugin has the token added to increase API limit.
2-3 other plugins do not have the token.

If I use a token from my GH account, and I'm logged in, everything works well. If someone else visits Dashboard > Plugins they get 403's. If I change to someone else's token and visit Plugins page then I see the 403's.

See here:
![screen_shot_2018-09-07_at_12_18_51_pm](https://user-images.githubusercontent.com/540990/45231120-0ea16a00-b299-11e8-84ec-53e4e3d0088e.jpg)

One of the plugins that 403 has this setup:
```
$updater = Puc_v4_Factory::buildUpdateChecker( 'https://github.com/maithemewp/mai-testimonials/', __FILE__, 'mai-testimonials' );
```

The plugin with the token has this setup:
```
// Setup the updater.
$updater = Puc_v4_Factory::buildUpdateChecker( 'https://github.com/maithemewp/mai-theme-engine/', __FILE__, 'mai-theme-engine' );

/**
 * Allow branch and updater object manipulation.
 * This let's us do beta releases via a branch change,
 * among other things.
 */
$updater->setBranch( apply_filters( 'mai_updater_branch', 'master' ) );

// Allow tokens to be used to bypass GitHub rate limit.
if ( defined( 'MAI_UPDATER_TOKEN' ) ) {
	$updater->setAuthentication( MAI_UPDATER_TOKEN );
}
```

**Comment by YahnisElsts** [comment]
Hmm, I'm not sure what's going on there. It would be useful to know what the API response body looks like when there's an error, it might have a more detailed error message. Could you perhaps log the HTTP responses with [Core Control](https://wordpress.org/plugins/core-control/) or intercept them with a proxy or a packet sniffer?

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.

If you still encounter this problem, feel free to reopen the issue or create a new one.
