### ISSUE TITLE
Replacing files due to update

### ISSUE THREAD

**Issue by goodwinpress** [YahnisElsts/plugin-update-checker#227]
Hi! Is the any chance to replace not the whole theme or plugin files from old to new, but  exclude one single file, so that one specific file remains the same? Thank you.

**Comment by YahnisElsts** [comment]
No, that is currently not possible. This library only retrieves and displays updates, it doesn't handle the actual installation process. That part is managed by WordPress core, which doesn't provide a way to prevent certain files from being overwritten.

**Comment by goodwinpress** [comment]
Thank you very much for quick and clear answer!
