### ISSUE TITLE
I can see an update is needed but don't get the update option anywhere.

### ISSUE THREAD

**Issue by xymantec** [YahnisElsts/plugin-update-checker#228]
Hi Yahnis,
First, thanks for making this awesome library! Second, I'm experiencing a weird problem that, assuming with your level of debugging this library, should be easy to identify... perhaps? 
Anywho, I can see on the dashboard that there is an update available, the debugger toolbar shows everything is working, the check function doesn't fail. Even though I see an update is available I get no option to update the plugin anywhere. 

![dash-updates](https://user-images.githubusercontent.com/6463675/45724874-ef45ef00-bb6c-11e8-9775-1b90165797c7.png)

The plugin displays not mention of any update.
![dash-plugin-display](https://user-images.githubusercontent.com/6463675/45725133-2a94ed80-bb6e-11e8-83dc-aeccfd903691.png)

any idea? no errors are being displayed in apache's log either.

A breif rundown of the current configuration settings.

```
// inside /wp-content/plugins/my-custom-plugin/functions.php
require plugin_dir_path( __FILE__ ).'plugin-update-checker-4.4/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://wp.domain.com/repo/custom-plugin/metadata.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'ws-custom-plugin'
);
```

The metadata.json validates correctly:
```
{
    "name" : "custom plugin name",
    "download_url" : "https://wp.domain.com/repo/custom-plugin/ws-custom-plugin.zip",
    "version" : "2.0",
	"homepage": "https://www.domain.com/",
	"requires": "4.5",
	"tested": "4.9.8",
	"last_updated": "2018-09-18 16:17:00",
	"upgrade_notice": "dudeeeeeeeeeeeeeeeeeeeeeeee...",
    "author" : "Miguel A. Vallejo",
	"author_homepage": "https://www.whatever.com/",
    "sections" : {
        "description" : "Its time to update."
    }
}
```
Any help is appreciated.

**Comment by YahnisElsts** [comment]
Is `functions.php` the main plugin file? In this context, the main file is the one that contains the plugin header comment, for example:

```php
/*
Plugin Name: My Plugin
Plugin URI: http://example.com/
Description: Lorem ipsum dolor sit amet.
...
*/
```

If `functions.php` isn't that file, you'll need to either move that code to the main file or to replace the second argument to `buildUpdateChecker` with the full path to the main file.

**Comment by xymantec** [comment]
Got it working, I had the plugin file my-plugin-name.php including the functions.php that then included the Puc libraries, I move the request the main file (my-plugin-name.php) and it worked. Thanks for your help!
