### ISSUE TITLE
Question - Composer install and ignore vendor/

### ISSUE THREAD

**Issue by vitorreis** [YahnisElsts/plugin-update-checker#230]
Hello there,

First of all thanks for the project, it's a really cool library. Here goes my question / use case:

I have a custom theme and I am using PUC with the github integration. I need to a SDK in my plugin which is managed with composer. I would like to ignore the directory `/vendor` in my `.gitignore` and perform the `composer install` everytime we attempt to install the theme with PUC (or any other solution that avoid me to don't commit the vendor directory.

I couldn't find a way to handle this with the git integration... I guess that with the self hosted approach I should be able to do it... is there a way to achieve this with the github integration?

**Comment by YahnisElsts** [comment]
Maybe you could use GitHub releases and add the full plugin package (including the `vendor` directory) as a release asset? You can make PUC download the first release asset instead of the source code archive by calling the `enableReleaseAssets()` method:
```php
$myUpdateChecker->getVcsApi()->enableReleaseAssets();
```

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.
