### ISSUE TITLE
Folder name issue with bitbucket updates

### ISSUE THREAD

**Issue by HowDoes** [YahnisElsts/plugin-update-checker#231]
How can I update a theme from a private bitbucket repo?

When the file structure in the repo is:
reponame/
       - index.php
       - style.css

The theme folder gets changed to username-reponame-hash/ after updating.

If all the files in the repo are within a folder with the theme name:
reponame/
        - reponame/
                 -- index.php
                  -- style.css

The theme folder after updating is reponame/reponame/ after updating.

Is there any way I can tell the plugin update checker to rename the themefolder to reponame/ or themename/?

**Comment by YahnisElsts** [comment]
First, please double-check the file name that you're passing to the `buildUpdateChecker` method. Using the wrong file could prevent the update checker from renaming the theme folder, even if the file path is valid and the file is accessible. This function argument should be set to the full path to `functions.php`, `style.css` or another file that's in the theme's root directory. A file in a subdirectory won't work.

Other than that, try manually downloading the ZIP file for the tag/branch that contains the update. What does the file structure of that archive look like? It should be something like this:

```
anyfoldername/
 - index.php
 - style.css
```

That is, it doesn't matter what the folder is called, but there must be exactly one folder at the root of the archive. Theme files (and folders) must be inside that folder, not in deeper subfolder. 

For example, this wouldn't work:

```
anyfoldername/
 - anotherfolder/
  -- index.php
  -- style.css
```

**Comment by HowDoes** [comment]
Thanks for your answer. 
After double checking and testing, updating directly from a private bitbucket repo works.
