### ISSUE TITLE
Can't get "Update now" link

### ISSUE THREAD

**Issue by 1844144** [YahnisElsts/plugin-update-checker#232]
Hello, thank you for Great plugin.

I've configured plugin to check updates from Bitbucket private repo. It normally checks for updates and writes at top of page (new version of xx available).

But at same time i don't get "update now" link. I've dig little bit in code, `injectUpdate` gives right results, but somehow my plugin is missing during `after_plugin_row_xxx` action calls.
What is wrong?

**Comment by 1844144** [comment]
Strange, but testing on 2 different sites (with same WP version gives same results)
PHP 7.1 and 7.2
Wordpress 4.9.8

__Issue was fixed__ by making `injectUpdate` very last handler

plugin-update-checker/Puc/v4p4/UpdateChecker.php:111:
``` add_filter('site_transient_' . $this->updateTransient, array($this,'injectUpdate'));```
changed to 
``` add_filter('site_transient_' . $this->updateTransient, array($this,'injectUpdate'),50);```

Not sure if I have to make an pull request.

**Comment by YahnisElsts** [comment]
> Issue was fixed by making injectUpdate very last handler

That sounds like the problem might be some kind of a conflict between this update checker and another plugin or theme that uses the same filter. Could you please deactivate any other plugins one by one and check when the "update now" link starts showing up? If that doesn't happen, try also switching to the default theme. 

> Not sure if I have to make an pull request.

I'd like to find the root cause before implementing a fix. I think it's necessary to have a full understanding of the problem to make sure that the solution is reliable.

**Comment by 1844144** [comment]
You are right, it confilicts with Formidable Forms plugin (v3.03)(but my plugin is addon for Formidable Forms so i need that plugin).

Formidable adds own handler (and has own updater) here
https://github.com/Strategy11/formidable-forms/blob/8e525a50a9c16f9762097bc9aaaf7231a5a42b47/classes/models/FrmAddon.php#L75-L80

And then in `clear_expired_download` at line 195 it removes my plugin from `response`
https://github.com/Strategy11/formidable-forms/blob/8e525a50a9c16f9762097bc9aaaf7231a5a42b47/classes/models/FrmAddon.php#L164-L200

**Comment by YahnisElsts** [comment]
I see. Well, using two custom update checker for the same plugin and at the same time probably isn't going to work. Is there a way you could turn off the addon update checker if you don't want to use it?

**Comment by 1844144** [comment]
You are right :) As my addon is modification of existing one , there was code that turned on default Formidable Forms updater. (i missed it before)

Thank you!
