### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by Wp-business** [YahnisElsts/plugin-update-checker#235]
**I have added the main code like this:**
require 'plugin-update-checker.php'; // Is een correct path

$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://www.wpbeveiligen.nl/wpb-update/plugin.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'wpb_antivirus'
); 

It's in the _class-wpb_antivirus-admin.php_

https://ibb.co/d06NiL (Screenshot)

**And I have the update info/json**

https://ibb.co/jBZsiL (Screenshot)

When I go to updates the plugin does not show up.
I am doing something wrong, I just dont have an clue what.

I read the instructions multiple times.

Can you help me to make the code correct? There must be an small mistake I made, I hope you can spot it.

,Math

**Comment by YahnisElsts** [comment]
In this context, "main plugin file" means the file that contains the plugin header. If `class-wpb_antivirus-admin.php` is not that file, please either move the update checker code to that file or replace `__FILE__` with the absolute path to that file.

**Comment by Wp-business** [comment]
Thanks! It works perfectly now.
