### ISSUE TITLE
Did I configured this correctly?

### ISSUE THREAD

**Issue by Remzi1993** [YahnisElsts/plugin-update-checker#236]
I made a open source plugin for our company for jQuery: https://github.com/Remzi1993/wp-jquery-updater

I have worked with your updater a lot, but only self hosted with a json file, this time I want to use my GitHub repository. I couldn't get this to work. See my code below:

```
define( 'WPJ_UPDATER_PLUGIN_DIR_URL', plugin_dir_url( __FILE__ ) );

// Plugin updater GitHub Repository
require WPJ_UPDATER_PLUGIN_DIR_PATH . 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Remzi1993/wp-jquery-updater',
	__FILE__,
	'wpj_updater_plugin'
);

$myUpdateChecker->getVcsApi()->enableReleaseAssets();
```

I would like to use the releases page of GitHub: https://github.com/Remzi1993/wp-jquery-updater/releases

Maybe I did configured something wrong?
I get the following error messages:
Could not determine if updates are available for WP jQuery Updater.
1. GitHub API error. Base URL: "/repos/:user/:repo/releases/latest", HTTP status code: 403. puc-github-http-error
2. GitHub API error. Base URL: "/repos/:user/:repo/tags", HTTP status code: 403. puc-github-http-error
3. GitHub API error. Base URL: "/repos/:user/:repo/branches/master", HTTP status code: 403. puc-github-http-error
4. Could not retrieve version information from the repository. This usually means that the update checker either can't connect to the repository or it's configured incorrectly. puc-no-update-source

**Comment by Remzi1993** [comment]
PS: 
![chrome_2018-11-05_11-16-13](https://user-images.githubusercontent.com/980950/47992095-420f4200-e0ec-11e8-9872-cb6dc389ac28.png)

**Comment by YahnisElsts** [comment]
That's odd, usually you would only see errors like that if you were trying to use invalid credentials with a private repository. However, it looks like your repository is public.

Could it be that there's a firewall somewhere between your plugin and GitHub that's blocking access? Also, maybe you could use something like [Core Control](https://wordpress.org/plugins/core-control/) to log the HTTP requests that the update checker makes and look at the full response body.

**Comment by Remzi1993** [comment]
The thing is, that it works correctly now, this is very strange.
Maybe, we could debug this together?

**Comment by YahnisElsts** [comment]
Sure, but to do that we usually need the problem to be reproducible. If it starts happening again or you find a way to make it happen on demand, please let me know.

**Comment by Remzi1993** [comment]
That's true, okay I will let you know.
I was testing this locally with the latest version of XAMPP and 7.2.11

**Comment by Remzi1993** [comment]
Hi @YahnisElsts you could close this ticket. I have also sent you a mail about joining an open source project. Maybe you could take a look and tell me what you think? https://github.com/Remzi1993/wp-jquery-manager
