### ISSUE TITLE
403 Forbidden only GitHub, self hosted fine

### ISSUE THREAD

**Issue by Remzi1993** [YahnisElsts/plugin-update-checker#237]
I get 403 Forbidden see image below:
![chrome_2018-11-19_10-46-34](https://user-images.githubusercontent.com/980950/48698970-afd96480-ebe8-11e8-9610-d761f5606907.png)

And now I understand why, I checked the link: https://api.github.com/repos/Remzi1993/wp-jquery-manager/contents/wp-jquery-manager.php?ref=1.3.0 <br>
See GitHub's message:
`{
  "message": "API rate limit exceeded for 185.85.82.14. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}`

This is really strange, maybe this is because you do to many requests per hour? Could check this code?
I see that a lot of people have the same problem "GitHub 403 Forbidden"

See below for more information: 
![chrome_2018-11-19_10-54-47](https://user-images.githubusercontent.com/980950/48699372-98e74200-ebe9-11e8-91f8-338ac5d27a43.png)
You can see in the image that fetching a .json file works accordingly and that GitHub has a 403 Forbidden status.

You could reproduce this issue, just have something on GitHub, include your updater and just use it until you get the same error.

**Comment by YahnisElsts** [comment]
Interesting, that's not what I was expecting. The [rate limit for unauthenticated requests](https://developer.github.com/v3/#rate-limiting) is up to 60 requests per hour, so the update checker will not hit it during normal operation. By default, it checks for updates about twice per day and each check involves up to 5 requests. This means it should stay well under the rate limit. 

Update checks will happen more often if someone visits the "Plugins" page (up to once per hour) or the "Updates" page (up to once per minute). However, that still shouldn't hit the limit unless they refresh the "Updates" page 10+ times. 

Could it be that there is something else on that server that is also using the GitHub API? Or perhaps you were checking for updates many times in a row as part of testing? 

In any case, here are some ideas on what to do about the problem:
- Create your own update scheduler and remove special cases like "check more often if the user opens the "Updates" page". You'll need to create a subclass of `Puc_v4p4_Scheduler`, override the `getEffectiveCheckPeriod` method to implement your custom scheduling logic, then override the `createScheduler` method in `Puc_v4p4_Plugin_UpdateChecker` to make it return an instance of your custom scheduler.
- Use an authentication token. I think this will increase the rate limit.
- Do nothing. Even if you hit the limit during development, a typical user probably won't encounter it.

**Comment by Remzi1993** [comment]
Okay, now I understand the problem. If I develop and do local testing on a local server I sometimes visit the plugins page to turn on or off other plugins, to check if my plugin plays nice with other plugins and to check if any links and text work as intended.

I iterate and then check immediately if things go smooth and then I again iterate or create a function or class and check again and if there are errors if any I work on the PHP errors that occur. This is my development cycle.

**Comment by YahnisElsts** [comment]
> Is there an option to limit the check or disable it for development purposes? 

You can disable automatic update checks by setting the `$checkPeriod` argument to `0` when you call the `buildUpdateChecker()` method. You would still be able to check manually by clicking the "Check for updates" link.

> You're correct to also assume that more plugins use your updater. Our whole company uses your updater! We have around 6 or 8 WordPress plugins, maybe this is the problem?

Is the company network set up in such a way that all developer machines have the same public IP address? That might make you hit the rate limit much sooner than if everyone had a unique IP.

**Comment by Remzi1993** [comment]
Do you mean like this:

```
$wp_jquery_manager_plugin_updater = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Remzi1993/wp-jquery-manager',
	__FILE__,
	'wp_jquery_manager_plugin',
	$checkPeriod = 0
);
```

Or something like this:

```
// Plugin updater GitHub Repository
require WP_JQUERY_MANAGER_PLUGIN_DIR_PATH . 'inc/plugin-update-checker/plugin-update-checker.php';
$wp_jquery_manager_plugin_updater = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Remzi1993/wp-jquery-manager',
	__FILE__,
	'wp_jquery_manager_plugin'
);
// Updater options
$wp_jquery_manager_plugin_updater->getVcsApi()->enableReleaseAssets();
$wp_jquery_manager_plugin_updater->setBranch('master');
$wp_jquery_manager_plugin_updater( $checkPeriod = 0 );
```

I don't want to mess directly into your files, because
- I want it to turn it off and on easily
- I want my plugin debug options in one place

Our whole company had optic fiber internet connection and a static IP address.
But the strange thing is that only one plugin uses GitHub as an update source, we have one open source plugin and all the other plugins are proprietary and thus are self-hosted.

**Comment by YahnisElsts** [comment]
I don't think PHP supports named parameters, so you would have to do it like this instead:

```php
$wp_jquery_manager_plugin_updater = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/Remzi1993/wp-jquery-manager',
	__FILE__,
	'wp_jquery_manager_plugin',
	0
);
```

> But the strange thing is that only one plugin uses GitHub as an update source, we have one open source plugin and all the other plugins are proprietary and thus are self-hosted.

Perhaps there is some other GitHub-related activity? Anything that uses the GitHub API without authentication would contribute towards reaching the rate limit, even if it has nothing to do with WordPress plugins.

**Comment by Remzi1993** [comment]
@YahnisElsts Thank you for your example!

There is only one open source plugin and all other plugins and theme are proprietary, thus updating happens from our own dev server.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.

If you still have issues with hitting GitHub rate limits, or you've discovered what caused it, please reopen the issue or create a new one.

**Comment by Remzi1993** [comment]
@YahnisElsts Oops, my apologies this issue is fixed. I'm very satisfied with the project and the examples given.
