### ISSUE TITLE
Removal of usernames from user-referencing APIs

### ISSUE THREAD

**Issue by altrovideo** [YahnisElsts/plugin-update-checker#239]
Hi, and first of all thank you for this plugin!
I've received an email that alert about an API change politic in Bitbucket 
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

> We are deprecating the use of username from user objects through the API. This affects URLs containing a username in the path on /users endpoints. As of 12 April 2019 usernames will no longer be supported in API URLs that reference users, and account_id or uuid should be used to identify an account instead

Is something that will affect BitBucketApi.php ?
Thank you

**Comment by YahnisElsts** [comment]
Thank you for letting me know. If I'm reading the announcement correctly, this change should not affect the update checker because it doesn't use any of the affected endpoints. It mainly uses `/repositories` endpoints, not `/users` or `/teams`.

**Comment by altrovideo** [comment]
Hi YahnisElsts ,
the doubt is in this section https://github.com/YahnisElsts/plugin-update-checker#bitbucket-integration 
the repository name is after the username: that username could be affected by the new policies?
`https://bitbucket.org/`**user-name**`/repo-name`

**Comment by YahnisElsts** [comment]
I don't think BitBucket is going to remove usernames from repository base URLs. The changes apply only to the API, right?

**Comment by altrovideo** [comment]
Thank you YahnisElsts, I also think so, I try to help this project in case there are other changes in Bitbucket

**Comment by YahnisElsts** [comment]
All right, I'll close this for now. If any username-related problems start to show up, feel free to reopen it/let me know.
