### ISSUE TITLE
Archive.zip download on Plugin Update with GitLab does not work anymore

### ISSUE THREAD

**Issue by shtief** [YahnisElsts/plugin-update-checker#240]
The Download of the Zip Archive:
https://gitlab.repo/PROJECT_GROUP/PROJECT_NAME/repository/TAG_NAME/archive.zip?private_token=PRIVATE_TOKEN

Does not work anymore in the new GitLab Community Edition 11.5.1 Version. See here:
https://gitlab.com/gitlab-org/gitlab-ce/issues/54572#note_120859334

**Comment by meszarosrob** [comment]
I am not sure how GitLab is going to handle this situation.

I have trouble understanding the ramifications of this issue, but I too have noticed today that the updates/downloads stopped working.

I am able to get the archive file for a *specific tag* using this URL pattern.
`https://gitlab.com/GROUP/PROJECT/-/archive/0.11/PROJECT-0.11.zip` where `0.11` is the tag.

is this working for you @shtief ?

As a workaround I modified the [GitLabApi.php](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitLabApi.php#L221) like so:

```diff
public function buildArchiveDownloadUrl($ref = 'master') {
    $url = sprintf(
-      'https://%1$s/%2$s/%3$s/repository/%4$s/archive.zip',
+      'https://%1$s/%2$s/%3$s/-/archive/%4$s/%3$s-%4$s.zip',
        $this->repositoryHost,
        urlencode($this->userName),
        urlencode($this->repositoryName),
        urlencode($ref)
    );

    if ( !empty($this->accessToken) ) {
        $url = add_query_arg('private_token', $this->accessToken, $url);
    }

-   return $url;
+   return urldecode_deep($url);
}
```

I only tested with a repo where I use tags. The [branch URL](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitLabApi.php#L97) might need a different pattern.

This modification might serve only as a temporary quick fix.

**Comment by shtief** [comment]
Hmm, for me this is still not working. There is no difference between the old and the new URL for me. Both do not work with the private_token. When I'm logged in both URLs work but with private_token none of them work.
When you are not logged in and only use the token you get a 302 on the "/users/sign_in.zip" page.

Before gitlab was switched to GitLab Community Edition 11.5.1 everything was fine with the first URL.

**Comment by froger-me** [comment]
```diff
public function buildArchiveDownloadUrl($ref = 'master') {
    $url = sprintf(
-      'https://%1$s/%2$s/%3$s/repository/%4$s/archive.zip',
+      'https://%1$s/api/v4/projects/%2$s/repository/archive?format=zip',
        $this->repositoryHost,
-       urlencode($this->userName),
-       urlencode($this->repositoryName),
-       urlencode($ref)
+       urlencode($this->userName . '/' . $this->repositoryName)
    );
+
+   $url = add_query_arg('sha', urlencode($ref), $url);

    if ( !empty($this->accessToken) ) {
        $url = add_query_arg('private_token', $this->accessToken, $url);
    }

    return $url;
}
```

Above seems the way to go, but the `zip` format seems not supported, even if it is clearly indicated in the doc (https://docs.gitlab.com/ee/api/repositories.html#get-file-archive)

See issue: https://gitlab.com/gitlab-com/support-forum/issues/4154

**Comment by froger-me** [comment]
@meszarosrob as for branches: https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch

**Comment by froger-me** [comment]
FIX!!!

```diff
public function buildArchiveDownloadUrl($ref = 'master') {
    $url = sprintf(
-       'https://%1$s/%2$s/%3$s/repository/%4$s/archive.zip',
+       'https://%1$s/api/v4/projects/%2$s/repository/archive.zip',
               $this->repositoryHost,
-       urlencode($this->userName),
-       urlencode($this->repositoryName),
-       urlencode($ref)
+       urlencode($this->userName . '/' . $this->repositoryName)
    );
+
+   $url = add_query_arg('sha', urlencode($ref), $url);

    if ( !empty($this->accessToken) ) {
        $url = add_query_arg('private_token', $this->accessToken, $url);
    }

    return $url;
}
```

```diff
public function getLatestTag() {
-   $tags = $this->api('/:user/:repo/repository/tags');
+   $tags = $this->api('/:id/repository/tags');
    if ( is_wp_error($tags) || empty($tags) || !is_array($tags) ) {
        return null;
    }

    $versionTags = $this->sortTagsByVersion($tags);
    if ( empty($versionTags) ) {
        return null;
    }

    $tag = $versionTags[0];
    return new Puc_v4p4_Vcs_Reference(array(
        'name' => $tag->name,
        'version' => ltrim($tag->name, 'v'),
        'downloadUrl' => $this->buildArchiveDownloadUrl($tag->name),
        'apiResponse' => $tag
    ));
}
```

```diff
public function getBranch($branchName) {
-   $branch = $this->api('/:user/:repo/repository/branches' . $branchName');
+   $branch = $this->api('/:id/repository/branches/' . $branchName);
    if ( is_wp_error($branch) || empty($branch) ) {
        return null;
    }

    $reference = new Puc_v4p4_Vcs_Reference(array(
        'name' => $branch->name,
        'downloadUrl' => $this->buildArchiveDownloadUrl($branch->name),
        'apiResponse' => $branch,
    ));

    if ( isset($branch->commit, $branch->commit->committed_date) ) {
        $reference->updated = $branch->commit->committed_date;
    }

    return $reference;
}
```

```diff
protected function buildApiUrl($url, $queryParams) {
    $variables = array(
        'user' => $this->userName,
-       'repo' => $this->repositoryName
+       'repo' => $this->repositoryName,
+       'id'   => $this->userName . '/' . $this->repositoryName,
    );

    foreach ($variables as $name => $value) {
        $url = str_replace("/:{$name}", urlencode('/' . $value), $url);
    }

    $url = substr($url, 3);
    $url = sprintf('https://%1$s/api/v4/projects/%2$s', $this->repositoryHost, $url);

    if ( !empty($this->accessToken) ) {
        $queryParams['private_token'] = $this->accessToken;
    }

    if ( !empty($queryParams) ) {
        $url = add_query_arg($queryParams, $url);
    }

    return $url;
}
```

**Comment by shtief** [comment]
Hi, I also figured that the format=zip does not work. I tried a lot of URLs to generate the archive.zip for a tag via the API but until now I couldn't find a working solution. I also tried to add the GET parameter "refs" with the tag name.
Your fix returns the archive.zip for the **master** and **not for the tag**.

**Comment by froger-me** [comment]
```
curl -L --header "Private-Token: $token" "https://gitlab.com/api/v4/projects/$userName%2FrepositoryName/repository/archive.zip?sha=$tag" --output ~/Downloads/test.zip
```

This URL works for tags

**Comment by shtief** [comment]
The following URL is working and returns a tar.gz for the tag:
https://GITLAB/api/v4/projects/ID/repository/archive?private_token=TOKEN&sha=TAG_NAME

But when you append the format with "zip" you get a "The requested format 'zip' is not supported.":
https://GITLAB/api/v4/projects/ID/repository/archive?private_token=TOKEN&sha=TAG_NAME&format=zip

Yeah, you're right! Sorry, I missed the "sha". Great!

**Comment by YahnisElsts** [comment]
I've created [an `issuse-240-fix` branch](https://github.com/YahnisElsts/plugin-update-checker/tree/issue-240-patch) that includes the fix proposed by @froger-me and a few other minor changes. Please try it out and let me know if it works.

**Comment by esfahanweb** [comment]
> I've created [an `issuse-240-fix` branch](https://github.com/YahnisElsts/plugin-update-checker/tree/issue-240-patch) that includes the fix proposed by @froger-me and a few other minor changes. Please try it out and let me know if it works.

hi,
tnx for pathing
I replaced this branch with my old plugin-update-checker folder but can't update yet.

`An error occurred while updating xxxx Plugin: Download failed. Not Found`

i used setBranch method

**Comment by YahnisElsts** [comment]
Hmm, it works for me when I use `setBranch`. Check the update download URL - does it look correct and does it work if you paste it in the browser? You can use [Debug Bar](https://wordpress.org/plugins/debug-bar/) to get the download URL. It should be in the "PUC (your-plugin-slug)" section of Debug Bar.

**Comment by esfahanweb** [comment]
if you paste it in the browser and you are logged in your gitlab account, you can download it, because it does not belong to the private token.

**Comment by YahnisElsts** [comment]
Could you please post the download URL that you're seeing? Feel free to remove the private token and replace your username/repository with some placeholder values, I just want to see if the overall URL syntax is correct.

**Comment by esfahanweb** [comment]
apologies for my delay,

Downloading update from https://gitlab.com/xxxx/xxxx-plugin/repository/1.0.x/archive.zip?private_token=xxxxxxxx

**Comment by YahnisElsts** [comment]
That looks like you're still using the unpatched version of the update checker. Please try [this version](https://github.com/YahnisElsts/plugin-update-checker/archive/issue-240-patch.zip) instead.

**Comment by esfahanweb** [comment]
I used the correct version but I think that link was incorrect, because update check was not worked and I caught the previous link.
I installed Debug Bar and there is a problem when wordpress try to check new version from gitlab

```
No updates found.
The update checker encountered 1 API error.

1) GitLab API error. URL: "/:user/:repo/repository/files/project-name.php", HTTP status code: 404.
Error code:
puc-gitlab-http-error
Requested URL:
https://gitlab.com/api/v4/projects/project-group/project-name/repository/files/project-name.php?ref=1.0.x&private_token=xxxxxxx
HTTP status:
404 Not Found
Response headers:
server: nginx
date: Sun, 09 Dec 2018 06:21:56 GMT
content-type: application/json
content-length: 25
cache-control: no-cache
vary: Origin
x-request-id: nLZ7UL04ui1
x-runtime: 0.024032
ratelimit-limit: 600
ratelimit-observed: 2
ratelimit-remaining: 598
ratelimit-reset: 1544336576
ratelimit-resettime: Mon, 09 Dec 2018 06:22:56 GMT
Response body:
{"error":"404 Not Found"}
```

hoever when i try to get download link manualy i can download it.
`https://gitlab.com/api/v4/projects/project-group%2Fproject-name/repository/archive.zip?sha=1.0.x&private_token=xxxxx`

**Comment by esfahanweb** [comment]
the problem may be solved if we use `%2F` instead of `/` in version check request URL

`https://gitlab.com/api/v4/projects/project-group/project-name/repository/files/project-name.php?ref=1.0.x&private_token=xxxxxxx`

to

`https://gitlab.com/api/v4/projects/project-group%2Fproject-name/repository/files/project-name.php?ref=1.0.x&private_token=xxxxxxx`

**Comment by YahnisElsts** [comment]
It looks like you're right about that encoding issue. It's strange that it worked fine in my tests; maybe I was looking at the wrong version myself.

In any case, that should be fixed now. Please re-download the patch and try again.

**Comment by esfahanweb** [comment]
this worked, tnx @YahnisElsts

**Comment by kevindaus** [comment]
Hi @YahnisElsts  - I applied [the patch that you provided](https://codeload.github.com/YahnisElsts/plugin-update-checker/zip/issue-240-patch) but it doesnt seem to work . I still met with this error 
![plugin updater broken](https://user-images.githubusercontent.com/10745021/49797031-3cef8380-fd79-11e8-872a-3f6845994206.PNG)

![my plugin url](https://user-images.githubusercontent.com/10745021/49797084-60b2c980-fd79-11e8-8911-47463cb4782d.PNG)
`https://gitlab.com/optibiz1_gdl/drivers-handbook-guideline/repository/1.3.16/archive.zip?private_token=mysecretoken` -- (not the secret token)

when I copy paste the url in my browser works only if I loggin but when I paste the url in 
incognito..

![woops](https://user-images.githubusercontent.com/10745021/49797197-b2f3ea80-fd79-11e8-80fd-6a0644635249.PNG)

**Comment by froger-me** [comment]
@kevindaus Does this URL work?

```
https://gitlab.com/api/v4/projects/optibiz1_gdl/drivers-handbook-guideline/repository/archive.zip?sha=master&private_token=mysecretoken
```

You mentioned:
>  -- (not the secret token)

Just to make sure there is no misunderstanding, the `private_token` parameter should be one of the private access tokens created in your profile [https://gitlab.com/profile/personal_access_tokens](https://gitlab.com/profile/personal_access_tokens).

**Comment by kevindaus** [comment]
> Just to make sure there is no misunderstanding, the private_token parameter should be one of the private access tokens created in your profile https://gitlab.com/profile/personal_access_tokens.

Yes

---

```
https://gitlab.com/api/v4/projects/optibiz1_gdl/drivers-handbook-guideline/repository/archive.zip?sha=master&private_token=mysecretoken
```
 I tried it and replaced mysecrettoken with my mine. 

I got this 
```
{"error":"404 Not Found"}
```
![404](https://user-images.githubusercontent.com/10745021/49810432-31618400-fd9c-11e8-8cfb-f34eecd7d5f8.PNG)

**Comment by YahnisElsts** [comment]
@kevindaus: Try encoding the forward slash as %2F as discussed above:
`https://gitlab.com/api/v4/projects/optibiz1_gdl%2Fdrivers-handbook-guideline/repository/archive.zip?sha=master&private_token=mysecretoken`

Also, based on the URL displayed in your screenshot, either the update checker is using cached update information or the wrong version of the update checker is loaded. Try clicking the "check for updates" link to refresh the download URL. If you still see the wrong URL, make sure that there isn't something else (e.g. another plugin) that's loading an unpatched/outdated version of the update checker.

**Comment by kevindaus** [comment]
>  make sure that there isn't something else (e.g. another plugin) that's loading an unpatched/outdated version of the update checker.

you are right... I think this is what caused it . I have 3 plugins using this plugin updater.  I have updated them all all and its working. Thank you @YahnisElsts

**Comment by YahnisElsts** [comment]
This patch has now been merged into `master` and the `issue-240-fix` branch was deleted.
