### ISSUE TITLE
Support for GitLab Subgroups

### ISSUE THREAD

**Issue by meszarosrob** [YahnisElsts/plugin-update-checker#241]
With version 9.0, GitLab introduced the concept of „subgroups”. Subgroups are a way of organising projects and permissions. The [release page](https://about.gitlab.com/2017/03/22/gitlab-9-0-released/#subgroups-ce-ees-eep) and the [documentation](https://docs.gitlab.com/ee/user/group/subgroups/) does a great job explaining in detail what subgroups are.

Currently subgroups are not supported by Plugin Update Checker and this is understandable because:
- subgroups are a relatively new feature in GitLab
- [support for GitLab](https://github.com/YahnisElsts/plugin-update-checker/commit/3760c5140e628925a773a8713bcdf0950be4bcfe) is a relatively new for PUC too, thanks to @aaronkirkham
- GitHub and BitBucket does not support subgroups

I for one I am using subgroups.

Lets pretend that this is a WordPress plugin: [https://gitlab.com/gitlab-org/gitter/gitter-markdown-processor](https://gitlab.com/gitlab-org/gitter/gitter-markdown-processor)

and call the `buildUpdateChecker` static method:

```php
$update_checker = Puc_v4_Factory::buildUpdateChecker(
    'https://gitlab.com/gitlab-org/gitter/gitter-markdown-processor/',
    __FILE__,
    'gitlab-markdown-processor'
);
```

At one point `getVcsService` is called which returns `null` instead of returning GitLab. `getVcsService` is responsible for determining the services based on the URL. Every services has its own dedicated class.

`null` is returned because [as explained in the comment](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Factory.php#L193) the [regex](https://www.phpliveregex.com/p/q8E) checks for the "/user-name/repository" pattern.

The good thing is that there is a way to bypass this check. The readme file notes an alternative way of initialising - while it is recommended for self-hosted GitLab instances: 

```php
$update_checker = new Puc_v4p4_Vcs_PluginUpdateChecker(
    new Puc_v4p4_Vcs_GitLabApi('https://gitlab.com/gitlab-org/gitter/gitter-markdown-processor/'),
    __FILE__,
    'gitlab-markdown-processor'
);
```

The constructor of `Puc_v4p4_Vcs_GitLabApi` [assumes that an URL](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitLabApi.php#L32]) that does not follow the "/user-name/repository" pattern is probably a self-hosted GitLab installed in a subdirectory.

This results in calling the [an undesired API endpoint](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitLabApi.php#L186). Instead of calling the [https://gitlab.com/api/v4/](https://gitlab.com/api/v4/projects) it calls the [https://gitlab.com/gitlab-org/api/v4/](https://gitlab.com/gitlab-org/api/v4) URL, the response is a `404`.

I don’t consider this a bug because it is expected behaviour taking in account all the things however I think we should add support for subgroups.

One solution would be to add and `elseif` conditional. For example:

```php
if ( preg_match( … ) ) {
    // for the "/user-name/repository" pattern
} elseif ( $this->repositoryHost === 'gitlab.com' && … ) {
    $parts = explode( '/', trim( $path, '/' ) ); // $path was "/gitlab-org/gitter/gitter-markdown-processor"
    $last = array_pop( $parts ); // $last is "gitter-markdown-processor"
    $this->userName = implode( '/', $parts ); // userName is "gitlab-org/gitter"
    $this->repositoryName = $last;
} else {
    // assuming self-hosted in subdirectory
}
```

`gitlab-org/gitter/gitter-markdown-processor` must be part of a subgroup because GitLab.com can't be a subdirectory install.

Pros:
- straightforward solution for the problem
- easy to implement

Cons:
- does not take in account subgroups for self-hosted installs
- more assumptions, more conditionals

An alternative solution would be to have separate class for GitLab.com and another for self-hosted version.

What do you all think?

**Comment by jonkratz** [comment]
Being able to use projects organized in subgroups would be hugely helpful to us as well! Great suggestion @meszarosrob.

**Comment by YahnisElsts** [comment]
All right, I've made a [gitlab-subgroups](https://github.com/YahnisElsts/plugin-update-checker/tree/gitlab-subgroups) branch with a basic implementation of the approach suggested by @meszarosrob. I haven't tested it myself, but it seems like it might work, possibly with some small modifications. Give it a try.

**Comment by meszarosrob** [comment]
I think this https://github.com/YahnisElsts/plugin-update-checker/issues/240 might be a blocker. Possible broken updates are more important than the subgroup at this point.

**Comment by YahnisElsts** [comment]
This change has now been merged into `master`.

**Comment by meszarosrob** [comment]
@YahnisElsts I appreciate your effort and dedication on this issue and on https://github.com/YahnisElsts/plugin-update-checker/issues/240 as well.

I updated [Dummy Subgroups for PUC](https://gitlab.com/implenton/wordpress/dummy-subgroups-for-puc) with the latest `master` PUC and it works well for me.

From my part this issue can be closed 💯
