### ISSUE TITLE
Change $repositoryHost visbility for Puc_v4p4_Vcs_GitLabApi

### ISSUE THREAD

**Issue by meszarosrob** [YahnisElsts/plugin-update-checker#242]
I would like to change the [visibility of `$repositoryHost` to `protected`](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitLabApi.php#L14) - currently it is set to `private`.

The properties for the [GitHub](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/GitHubApi.php) are set to `protected`, while the properties for [BitBucket](https://github.com/YahnisElsts/plugin-update-checker/blob/v4.4/Puc/v4p4/Vcs/BitBucketApi.php) are set to `private`.

I drew the conclusion that there is no standard to follow, it depends on the services implementation.

Considering the ever changing nature of APIs `private` properties might complicate quick fixes.

Also… if subgroups are not added to the PUC #241 then by having all proprieties set to `protected` the `Puc_v4p4_Vcs_GitLabApi` can be extended easily:

```php
class My_Vcs_GitLabApi extends \Puc_v4p4_Vcs_GitLabApi {
    public function __construct( $repositoryUrl, $accessToken = null ) {
        parent::__construct( $repositoryUrl, $accessToken );

        $this->repositoryHost = @parse_url( $repositoryUrl, PHP_URL_HOST );
        $path = @parse_url( $repositoryUrl, PHP_URL_PATH );
        $parts = explode( '/', trim( $path, '/' ) );
        $last = array_pop( $parts );
        $this->userName = implode( '/', $parts );
        $this->repositoryName = $last;
    }
}
```

**Comment by YahnisElsts** [comment]
That seems reasonable. I'll merge PR now.

**Comment by meszarosrob** [comment]
Thank you,
