### ISSUE TITLE
PHP warning

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#244]
Hi Yahnis,

We are using your plugin update checker in our plugin Maps Marker Pro - a user reported, that the following PHP error log entry was created on his site:

`Warning: mb_strpos(): Empty delimiter in /wp-content/plugins/maps-marker-pro/dist/plugin-update-checker/Puc/v4p4/Plugin/UpdateChecker.php on line 641`

line 641 from the `isMuPlugin()` function: `$cachedResult = (strpos($pluginPath, $muPluginDir) === 0);`

We have not seen this log entry on our sites so far though & I am not sure if this really is an issue - just wanted you to know.
best,

Robert

**Comment by YahnisElsts** [comment]
Thank you for the report. I think someone sent me an email about a similar issue a while ago, but I wasn't able to determine the cause at that time.

The warning indicates that `$muPluginDir` is empty, which could mean one of the following things:
- `WPMU_PLUGIN_DIR` is not defined.
- `WPMU_PLUGIN_DIR` is incorrect (e.g. there's a typo in the path).
- PHP doesn't have read permissions for one of the directories in the directory hierarchy. For example, `WPMU_PLUGIN_DIR`  is `/abc/def/foo/mu-plugins` and PHP can't access `/abc/def/`.
- There's something weird going on with symlinks that causes one of the above.

Does any of that sound like it might apply to the site in question?

**Comment by robertharm** [comment]
thanks for the info - I will forward this to the user reporting this...
