### ISSUE TITLE
Update links are missing (GitHub). Debug Bar is okay.

### ISSUE THREAD

**Issue by jozefpinter** [YahnisElsts/plugin-update-checker#249]
It is not showing update links. Nothing. It shows a bubble. But no links to update a plugin. Debug Bar is showing "there is an update" but no links to update.

![abubble](https://user-images.githubusercontent.com/15308415/50364760-b6555600-0571-11e9-946d-fe975ebee03d.png)
![ok](https://user-images.githubusercontent.com/15308415/50364766-bce3cd80-0571-11e9-8115-6a78102d25f4.png)

**Comment by YahnisElsts** [comment]
Please check the file path that is passed to `buildUpdateChecker`. If the path is incorrect or doesn't point to the main plugin file, you'll get update notifications but no update links.

**Comment by jozefpinter** [comment]
Thanks. Do you mean [download_url] ?

**Comment by jozefpinter** [comment]
// Automatic Updates. Plugin implemantation YahnisElsts/plugin-update-checker
require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/ThemesEmail/woocommerce-email-testing/',
	__FILE__,
	'woocommerce-email-testing'
);


What is wrong here?

**Comment by jozefpinter** [comment]
this code is inside functions.php.

Thanks. I will try.

**Comment by jozefpinter** [comment]
Thank you so much. This was exactly the case. Now is everything okay.

One more thing. Is there a way to set automatic updates for my plugin? I know. It has nothing to do with your plugin. Just curious.

**Comment by YahnisElsts** [comment]
The `auto_update_plugin` filter might be useful for that:
https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter

**Comment by jozefpinter** [comment]
Thanks.

I noticed one thing. I don't get an icon or banner. In the JSON file i can specify the icon and the banner. But what about readme.txt ? Can I use 

banner_url: https...
icon_url: https...
?

**Comment by YahnisElsts** [comment]
Right now, icons and banners are supported only when using a JSON file. It doesn't work with GitHub repositories. This is something I'd like to improve in the future, but currently there's no easy workaround.

**Comment by jozefpinter** [comment]
Thank you so much. Nevermind.

Last question. I am using **WP 5.0.2** and in the readme.txt is set "**Tested up to: 5.0.2**" - but WP displays: Compatibility with WordPress 5.0.2: **Unknown**  

what I am doing wrong?

**Comment by YahnisElsts** [comment]
Hmm, I'm not sure why that's happening. Does it still show the correct value in the Debug Bar?

**Comment by YahnisElsts** [comment]
I've looked at readme.txt and I think the problem might be that this file doesn't fully comply with the [WordPress.org plugin readme standard]. Specifically, the file should start with a `=== Plugin Name ===` line, not `# Plugin Name`. I think there should be no blank line after the plugin name. Also, readme section names like should be formatted like this: `== Section Name ==`.

**Comment by jozefpinter** [comment]
Before Github. This plugin was hosted in wordpress.org oficial repository. I had no problem with readme.txt / it was validated.

Now I just removed some "not important" lines like Screenshots, FAQ etc.

But thanks. I can try your advice.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months and the initial problem (update links not showing up) has been resolved.

If you still encounter other problems, feel free to create a new issue.
