### ISSUE TITLE
Can't update to latest version from Gitlab

### ISSUE THREAD

**Issue by renzramos** [YahnisElsts/plugin-update-checker#250]
**Chrome Console**
Downloading update from [link] -- the link is working
but it show issue after that **Download failed. Not Found**

**Comment by eightam** [comment]
Same problem here. How to fix this?

**Comment by YahnisElsts** [comment]
Due to some relatively recent changes to the GitLab API, the old way of generating download links no longer works. Please update to version 4.5 of this library (released just now) to fix the downloads.
