### ISSUE TITLE
PHP 7.3: Non-string needles will be interpreted as strings in the future

### ISSUE THREAD

**Issue by oliver-graetz** [YahnisElsts/plugin-update-checker#251]
I am getting this message in logs on installations using PHP 7.3:

```
Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future.
Use an explicit chr() call to preserve the current behavior in
/path/to/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p4/Plugin/UpdateChecker.php
on line 641
```

This is with updater version 4.4 and inside the `isMuPlugin` which has since moved, but the code remained the same:
```php
$muPluginDir = realpath(WPMU_PLUGIN_DIR);
$pluginPath  = realpath($this->pluginAbsolutePath);
$cachedResult = (strpos($pluginPath, $muPluginDir) === 0);
```
The last line produces the message. I suppose it happens because the realpath for `$muPluginDir` fails and returns `false`, which is not a string. This should be either explicitly handles or the false should be typecast to srting before the `strpos` call.

**Comment by YahnisElsts** [comment]
I've added a check for `false` and a workaround: when `realpath` fails, we'll use `wp_normalize_path` instead. I expect that this will be a bit less reliable, but it's better than nothing.

**Comment by wp-organic** [comment]
> I am getting this message in logs on installations using PHP 7.3:
> 
> ```
> Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future.
> Use an explicit chr() call to preserve the current behavior in
> /path/to/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p4/Plugin/UpdateChecker.php
> on line 641
> ```
> 
> This is with updater version 4.4 and inside the `isMuPlugin` which has since moved, but the code remained the same:
> 
> ```
> $muPluginDir = realpath(WPMU_PLUGIN_DIR);
> $pluginPath  = realpath($this->pluginAbsolutePath);
> $cachedResult = (strpos($pluginPath, $muPluginDir) === 0);
> ```
> 
> The last line produces the message. I suppose it happens because the realpath for `$muPluginDir` fails and returns `false`, which is not a string. This should be either explicitly handled or the false should be typecast to string before the `strpos` call.

Yes - we facing this issue same is it. please help!!!

**Comment by YahnisElsts** [comment]
Are you sure you have the latest version of the update checker? I believe this issue should be fixed in version 4.6.

**Comment by wp-organic** [comment]
Thank you for the prompt response.

We are working with version 1.2

/*
Plugin Name: External Update Example
Plugin URI: http://example.com/
Description: Demonstrates how to handle plugin updates from a third-party source. 
Version: 1.2
Author: Janis Elsts
Author URI: http://w-shadow.com/
*/

**Comment by wp-organic** [comment]
<img width="774" alt="My version" src="https://user-images.githubusercontent.com/41462181/58378810-e63cd580-7fb7-11e9-8eed-07c3b62feeb3.png">
<img width="877" alt="Lastest Version" src="https://user-images.githubusercontent.com/41462181/58378812-e63cd580-7fb7-11e9-9b3f-9042f223aafd.png">

We build your plugin with integrate with my live plugin. Can you help me to solved this issue. can i replace this function with my older version function ?

Thanks in advance.

**Comment by YahnisElsts** [comment]
1.2 is example plugin version, not the update checker version. To find the update checker version, look in the `plugin-updates/Puc` subdirectory. You should see a directory named `v4p6`. If you see `v4p4` or `v4p5` then you have an older version and need to download the [latest release](https://github.com/YahnisElsts/plugin-update-checker/releases/latest).

As for the screenshots, the second one is the correct version that contains the bugfix. If you prefer, you can replace the old version of the function with the new one, but I would recommend updating the whole library and not just one function.

**Comment by wp-organic** [comment]
Thank you @YahnisElsts
