### ISSUE TITLE
How to verify domain name ?

### ISSUE THREAD

**Issue by rajeshsingh520** [YahnisElsts/plugin-update-checker#252]
I am have created a license checking server, in that, I will be putting a restriction like number of domain name license key will work

but I can't find a way to verify if the update request is coming from a particular domain

the Get request that is coming in cUrl don't have any method to verify the request sender domain name 

that we can trust

**Comment by YahnisElsts** [comment]
I think that's beyond the scope of this library. I recommend looking elsewhere.
