### ISSUE TITLE
How to fetch GitLab Private Project & Subgroup?

### ISSUE THREAD

**Issue by calvinseng** [YahnisElsts/plugin-update-checker#253]
With the latest v4.5 I have tried to fetch private project & subgroup with GitLab API Token being set as the Authentication but the debug showed account log in is required. Kindly advise.
Thanks!
![screenshot 2019-01-04 at 9 33 00 pm](https://user-images.githubusercontent.com/12848046/50690574-bf155400-1068-11e9-8e66-afc731c458bb.png)

**Comment by YahnisElsts** [comment]
The requested URL doesn't seem right. The update checker shouldn't be accessing the repository that way when using the GitLab API. Could you please post the code that you're using to initialise the update checker? (Feel free to remove any passwords and identifying information.)

**Comment by calvinseng** [comment]
Thanks! May be you could advise the URL path for project and subgroup. 

require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://gitlab.com/gerp/add-ons/gerp-toolkit/',
	__FILE__,
	'gerp-toolkit'
);
//Note: Self-hosted instances of GitLab must be initialized like this:
$myUpdateChecker = new Puc_v4p5_Vcs_PluginUpdateChecker(
	new Puc_v4p5_Vcs_GitLabApi('https://gitlab.com/gerp/add-ons/gerp-toolkit'),
	__FILE__,
	'gerp-toolkit'
);
//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->setAuthentication('x1234467891s');

Tried a few on the path but not sure which is the right format. Thanks!

**Comment by YahnisElsts** [comment]
The code block that starts with "Note: Self-hosted instances..." applies only to self-hosted GitLab repositories, not projects hosted on GitLab.com. Please remove it. 

Other than that, the code seems correct. It still shouldn't be showing the output in the screenshot. Are you sure that something isn't loading an older version of PUC in parallel? Try replacing `Puc_v4_Factory` with `Puc_v4p5_Factory`.

**Comment by calvinseng** [comment]
Hi @YahnisElsts  thank you for the support and I have managed to figure out the URL pattern, 

$myUpdateChecker = new Puc_v4p5_Vcs_PluginUpdateChecker(
    new Puc_v4p5_Vcs_GitLabApi('https://gitlab.com/gerp/add-ons/'),
    __FILE__,
    'gerp-toolkit'
);

For whoever trying to pull from private GitLab project / subgroup, the correct class would be to use Puc_v4p5_Vcs_PluginUpdateChecker and Puc_v4p5_Vcs_GitLabApi or any upcoming newer versions class.

And the path to the private repo should be https://gitlab.com/project_name/subgroup/ would do, omitting plugin path after subgroup.

**Comment by calvinseng** [comment]
@YahnisElsts Any update about why plugin update failed? Thank you.

**Comment by YahnisElsts** [comment]
I've had a similar issue with updates failing where it turned out that WP couldn't remove the old version of the plugin because some of the files were still open or didn't have the correct permissions. Maybe it's something like that? Is there anything in the PHP error log?

Also, try manually downloading the update and verify that you're getting the right files.

**Comment by calvinseng** [comment]
Thanks and I have realised it may be due to the folder structure in GitLab, and I have created a new project to house the plugin but still it's not able to update, same problem and there's no PHP error for it. Permissions have been set correctly.

The new code is as following

`$gerp_updatechecker = Puc_v4_Factory::buildUpdateChecker(
	'https://gitlab.com/gerp/gerp-toolkit/',
	__FILE__,
	'gerp-toolkit'
);`

**Comment by YahnisElsts** [comment]
Is this still on the same site that seemingly had a problem with different versions of PUC being loaded at the same time? If so, could you please deactivate the other plugin or theme that is also using this update checker to verify that it's not conflicting in some way?

If there's still no error message, I think you might have to actually put some breakpoints and/or logging statements in the part of WordPress core that's responsible for installing updates to figure out what's wrong.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.

If you still encounter this problem, feel free to reopen the issue or create a new one.
