### ISSUE TITLE
Updater shows error message even though the update succeeds 

### ISSUE THREAD

**Issue by tomscholz** [YahnisElsts/plugin-update-checker#255]
Hey there 👋,
I just updated the PUC to the latest version, but I keep getting the following message:
<a href="https://user-images.githubusercontent.com/20381749/51258000-315f3000-19a9-11e9-95f0-e01f6294f557.png"><img width="1953" alt="screen shot 2019-01-16 at 16 03 47" src="https://user-images.githubusercontent.com/20381749/51258000-315f3000-19a9-11e9-95f0-e01f6294f557.png"></a>

The update is successful, but the updater still throws a warning.
I did install the Debug Bar plugin, but I can't find anything unusual there. The only thing, that is off, is a js error thrown, that is visible in the console:
```js
Uncaught TypeError: Cannot read property 'data' of undefined
```

We provide an updater class for all of our inhouse developed plugins. The class is contained inside a separate WordPress plugin and looks like this: 
```php
class companyUpdater {
    /**
     * companyUpdater.class constructor.
     * @param string $pluginName Should be the same as the repo/folder name.
     * @param string $pluginLocation Usually __FILE__.
     * @param string $gitlabURI Should be formated like this: user/repo.
     */
    public function __construct($pluginName, $pluginLocation, $gitlabURI) {
        $this->companyUpdateChecker = new Puc_v4p5_Vcs_PluginUpdateChecker(
            new Puc_v4p5_Vcs_GitLabApi('https://git.xxxxxx.com/'. $gitlabURI),
            $pluginLocation,
            $pluginName
        );

        $this->companyUpdateChecker->setAuthentication('XXXXXXXXXXXXX');
        $this->companyUpdateChecker->setBranch('master');
    }
}
```

A plugin then instantiates the updater like this:
```php
// This enables automatic updates
if ( file_exists( plugin_dir_path(__DIR__)."/company-updater/company-updater.php") ) {
    include_once( WP_PLUGIN_DIR . '/company-updater/company-updater.php' );

    if ( class_exists('companyUpdater') ) {
        new companyUpdater(myPlugin, __FILE__, "gitlabGroupOrUser/repo");
    }
}
```

Possibly related: #196, #245 and #240 

I am using a  self-hosted GitLab instance.
Does anyone have an idea how to prevent the UI from displaying an error?

**Comment by YahnisElsts** [comment]
My guess would be that there's something wrong with the AJAX response that WordPress returns when updating a plugin. Take a look at it in the network console. Is there any extraneous text in the response body, like error messages or blank lines? Maybe the HTTP status code indicates an error even though the response says "success"?

**Comment by tomscholz** [comment]
You're right, there are blank lines before the actual response:
```json
»blank line«
»blank line«
»blank line«
{"success":true,"data":{"update":"plugin","slug":"XXXXXX","oldVersion":"Version 1.1.7","newVersion":"Version 1.2.11","plugin":"XXXXXX\/plugin.php","pluginName":"XXXXXX","debug":["Enabling Maintenance mode&#8230;","Downloading update from https:\/\/git.XXXXXX.com\/api\/v4\/projects\/XXXXXX%2FXXXXXX\/repository\/archive.zip?sha=v1.2.11&amp;private_token=XXXXXX&#8230;","Unpacking the update&#8230;","Installing the latest version&#8230;","Renaming XXXXXX-v1.2.11-f9bb4f78b64923c71ffe984d7cacef973b1af814 to bb-eip&#8230;","Directory successfully renamed.","Removing the old version of the plugin&#8230;","Plugin updated successfully.","Disabling Maintenance mode&#8230;"]}}
```

Seems like one of the dev on our team forgot to remove some linebreaks after `?>` 🙄 

Thanks anyways :)
