### ISSUE TITLE
Microsoft Visual Studio Team Foundation Server  use git ?

### ISSUE THREAD

**Issue by gerasart** [YahnisElsts/plugin-update-checker#256]

**Comment by YahnisElsts** [comment]
What exactly are you asking? Do you want to use a private/self-hosted Git repository for plugin updates? Unfortunately, that is currently not supported. Only GitHub, BitBucket, and GitLab repositories are supported.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months and there is not enough information for a meaningful response.
