### ISSUE TITLE
Only question, not issue, about include Update Checker only if is_admin()?

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/plugin-update-checker#259]
Is there any known problem or limitation if Update Checker code is included only if [is_admin()](https://developer.wordpress.org/reference/functions/is_admin/) returns true, not on every public request?

Thanks in advance.

**Comment by YahnisElsts** [comment]
There will be side-effects. There are three that immediately come to mind:

- The update indicator in the admin bar/Toolbar will show an incorrect number of available updates.
- Command line tools like WP-CLI might not be able to display or install your updates.
- Remote administration tools like ManageWP might not be able to display or install your updates.

**Comment by ddur** [comment]
Then, checking is_user_logged_in() and/or current_user_can ( 'update_plugins' ) will reduce load on public site side, as much is possible, without important side-effects?

I'm trying to minimize speed performance impact. Currently I do not care much about WP-CLI and remote administration. :see_no_evil: Though, I guess they will work too.

Great repository and quick response. Thank you very much.

**Comment by YahnisElsts** [comment]
That would help with the admin bar issue, but I'm not sure if this approach would work with WP-CLI/ManageWP. I don't know if WP-CLI simulates user login or not. You'd have to ask someone who's more familiar with the internal workings of that tool.

In any case, it's good to hear that you like this project 👍

**Comment by DavidAnderson684** [comment]
@ddur End users do care about managing their sites in other tools (ManageWP, MainWP, UpdraftCentral, WP-CLI etc). Trying to save 1 HTTP request per day per paying customer is absurd (how much do you estimate 1 incoming HTTP request costs you?), and you will pay for it in terms of time spent having to keep answering the support question as to why updates to your plugin don't show up outside the WP dashboard.
