### ISSUE TITLE
Notice when i open plugin page

### ISSUE THREAD

**Issue by rajeshsingh520** [YahnisElsts/plugin-update-checker#260]
I have added this in my plugin, but whenever I go to plugin page after a long time it generate this notice, it disappears on page refresh and doesn't come back, but it is back on a revisit 

Notice: Failed to parse update metadata. Try validating your .json file with http://jsonlint.com/ in E:\UniServerZ\www\telco\wp-content\plugins\css-js-manager-pro\plugin-update-checker\Puc\v4p4\Metadata.php on line 35

![image](https://user-images.githubusercontent.com/2164574/53011612-c650bf80-3466-11e9-830f-bc88d2355acb.png)

**Comment by YahnisElsts** [comment]
It sounds like the update metadata might not be formatted correctly. Could you post it here so that I can take a look? If you don't want to post it publicly, you can contact me via email: `daerils@gmail.com`

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a few months.

If you still encounter this problem, feel free to reopen the issue or create a new one.
