### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DavidAnderson684** [YahnisElsts/plugin-update-checker#261]
Hi Yahnis,

Any chance of a new release? We're starting to get reports in the real-world of the issue fixed in https://github.com/YahnisElsts/plugin-update-checker/commit/9d087b7d9c4e040087b14aaba2c171aa81d34603 , as people start trying out PHP 7.3.

Thank you, as ever, for your work on this project.

David

**Comment by YahnisElsts** [comment]
Thank you for the reminder! Before I tag a new release, could you confirm if this patch actually fixes the issue? I've received a report that one user is still seeing PHP warnings even with the latest patch, though so far I haven't been able to verify that they have the correct file(s).

**Comment by KevinBatdorf** [comment]
Hi @YahnisElsts I work with @DavidAnderson684 and the user we sent a dev build with this patch applied confirmed that the warning did indeed disappear. Thanks

> I installed the patched version and the warning message has disappeared from the dashboard pages

**Comment by YahnisElsts** [comment]
All right, I've made a new release.

**Comment by DavidAnderson684** [comment]
@YahnisElsts Thank you.

The release hasn't been picked up by Packagist; it still thinks 4.5 is the latest - https://packagist.org/packages/yahnis-elsts/plugin-update-checker . Last year the mechanism they used to automatically receive info from Github was deprecated, and you have to click through a new authorisation to get that set up again.

**Comment by YahnisElsts** [comment]
All right, I think I've done that. The package should be up to date now.

**Comment by KevinBatdorf** [comment]
@YahnisElsts @DavidAnderson684 I can confirm it's now working, thanks!
