### ISSUE TITLE
Checks a lot more frequent than expected due to cron work-around

### ISSUE THREAD

**Issue by DavidAnderson684** [YahnisElsts/plugin-update-checker#266]
On an audit of our server load, I'm seeing a lot more incoming updates checks than expected from all requesting sites that I'm checking. I think I've found the cause.

The class `Puc_v4p5_Scheduler` contains this fragment:

```
				//In case Cron is disabled or unreliable, we also manually trigger
				//the periodic checks while the user is browsing the Dashboard.
				add_action( 'admin_init', array($this, 'maybeCheckForUpdates') );
```

Down in the method `getEffectiveCheckPeriod()`, the returned value depends on `DOING_CRON`, such that the result is (+/- some fuzziness) `$this->checkPeriod` hours (default, 24). The intention is that the "background", "cron" checks should only happen about once a day (or whatever the consumer over-rode it too).

However, in the case of the `admin_init` action, `getEffectiveCheckPeriod()` will fall back to its default of 1 hour. As a result, if anyone (of any user level) is logged into the WP dashboard, then a check will happen hourly.

I think that the fix is to also check on `doing_action('admin_init')` (or equivalent, on versions of WP before 3.9), as an equivalent condition to `DOING_CRON`. I will send in a pull request.

**Comment by DavidAnderson684** [comment]
If you do merge this or another fix, then I'd be really grateful for a swift release, to spare me from coding a work-around and then removing it when the release does come!

**Comment by YahnisElsts** [comment]
I'm looking at `getEffectiveCheckPeriod()` and unfortunately I'm not seeing how this could happen: 

> However, in the case of the admin_init action, getEffectiveCheckPeriod() will fall back to its default of 1 hour. 

The default `else` branch sets `$period = $this->checkPeriod * 3600`. There is a branch that sets it to `3600`, but that only runs when `in_array($currentFilter, $this->hourlyCheckHooks)` and I don't think `admin_init` is ever in `hourlyCheckHooks`. What am I missing?

**Comment by DavidAnderson684** [comment]
Argh, yes, you are right - I misread that.

So, my problem is something else. But it is very perplexing. If I look in the log for the most recent incoming updates checks, and then look for how often that site is checking for updates, it's always more than the expected once a day. It doesn't seem plausible that on a random sample of users, they all are visiting their 'updates' page in the WP dashboard most days, especially when lots of them are running out-dated versions of the plugin.

I wonder if it's the `upgrader_process_complete` hook. The code mentions "bulk upgrader", but on a quick look at WP core, it seems to run on all sorts of updates, including themes and WordPress core. It passes parameters to indicate what was updated. Presumably if that didn't include the 'current' entity (from the point of view of the updater class), then lowering the check time to 60 seconds there is overkill? What do you think?

**Comment by YahnisElsts** [comment]
I did some quick testing and yes, it looks like `upgrader_process_complete` runs after every upgrade and not just bulk upgrades. I'm not sure if this would explain all the extra update checks that you're seeing. If the users aren't visiting the "updates" page, it seems unlikely that they would be installing a bunch of updates every day.

Anyway, I agree that it would indeed be more efficient to only reduce the check period when the current plugin or theme is the thing that's upgraded. However, the last time I looked at that part of WP core (which was a while ago), it was ridiculously complicated to figure out what exactly is being upgraded. There is the `Puc_v4p5_UpgraderStatus` class, but I haven't verified that it works in this situation. It might need some minor changes and a bunch of testing.

**Comment by DavidAnderson684** [comment]
That all sounds reasonable. Info on what was upgraded is passed in the third parameter to the `upgrader_process_complete` filter, so in principle it should be fairly easy to check what was updated.

**Comment by YahnisElsts** [comment]
In theory, yes. I would still want a lot of testing for this one because there are three or four different ways to install an update and the parameters of other upgrade-related hooks (used to) vary depending on the approach.

**Comment by DavidAnderson684** [comment]
Here's the new PR, that checks if the update is the current entity: https://github.com/YahnisElsts/plugin-update-checker/pull/268

It's effect is to suppress the call to `maybeCheckForUpdates()` upon the `upgrader_process_complete` action if the action is notifying of an update type (which could be core, translation, plugin or theme) not matching the instance's type, and 

I've tested it successfully. The data formats sent through for themes and plugins are as below. (For core or translations, the `type` parameter has a corresponding/different value). If there is only one entity being updated, then the format is the same (but with just one item in the relevant sub-array).

```
Array
(
    [action] => update
    [type] => theme
    [bulk] => 1
    [themes] => Array
        (
            [0] => twentynineteen
            [1] => twentysixteen
        )

)
```

```
Array
(
    [action] => update
    [type] => plugin
    [bulk] => 1
    [plugins] => Array
        (
            [0] => query-monitor/query-monitor.php
            [1] => wordpress-beta-tester/wp-beta-tester.php
        )

)
```
```

**Comment by DavidAnderson684** [comment]
The format is the same if updating a single plugin on the "plugins" page. i.e. It's not just when you use the "bulk" facility from `update-core.php`:

```
Array
(
    [action] => update
    [type] => plugin
    [bulk] => 1
    [plugins] => Array
        (
            [0] => two-factor-authentication/two-factor-login.php
        )

)
```

**Comment by YahnisElsts** [comment]
That looks pretty good. I have merged that PR.

**Comment by DavidAnderson684** [comment]
Thanks! Looking at it again, I realise that a check I intended wasn't there, after some re-arranging. Hence, a new PR to add it back: https://github.com/YahnisElsts/plugin-update-checker/pull/269

**Comment by YahnisElsts** [comment]
All right, that has also been merged.

**Comment by DavidAnderson684** [comment]
As this is merged and released, I'll close the issue.
