### ISSUE TITLE
Gitlab build API URL function has https hardcoded so fails on custom gitlab hosts

### ISSUE THREAD

**Issue by timwiel** [YahnisElsts/plugin-update-checker#270]
In file Puc/v4p5/Vcs/GitLabApi.php:

Unfortunately the build API URL has "https://" hardcoded into the code to build the API call to gitlab servers however unfortunately some custom gitlab installs do not use https so the built URL fails 

It should use the custom host url variables provided from perhaps the $repositoryUrl variable used in the __construct

**Comment by timwiel** [comment]
Likewise function `buildArchiveDownloadUrl`  in file Puc/v4p5/Vcs/GitLabApi.php has hardcoded https:// rather than using the custom repositoryUrl

**Comment by YahnisElsts** [comment]
That should be fixed in 8499f5c. Please give it atry.

**Comment by timwiel** [comment]
This works to build the archive download url correctly however I seem to be having an issue with the updates actually working.

It seems to be very similar to issue #240 however error is now 

> Download failed. A valid URL was not provided. 

I have the latest PUC version installed but the update fails with above message. What is strange however is the both the debug panel download url and `downloading update from <url>...` work in an incognito window correctly downloading the file. 

Any ideas...

**Comment by YahnisElsts** [comment]
I suspect it's due to the port number. By default, the `wp_http_validate_url()` function that WordPress uses in lots of places accepts only the following port numbers:

- 80
- 443
- 8080
- Same port number as the home URL.

URLs that contain any other port number can be rejected as invalid even if they actually work fine.

**Comment by timwiel** [comment]
> I suspect it's due to the port number. By default, the `wp_http_validate_url()` function that WordPress uses in lots of places accepts only the following port numbers:
> 
> * 80
> * 443
> * 8080
> * Same port number as used in the home URL.
> 
> URLs that contain any other port number can be rejected as invalid even if they actually work fine.

That is definitely the issue I was encountering as I can fix it by modying the following code in http.php's `wp_http_validate_url`

`	if ( 80 === $port || 443 === $port || 8080 === $port || 4554 === $port ) {
		return $url;
	}
`

Not sure how to fix this in a production environment as any changes to this core Wordpress file will be overwritten with every Wordpress update - any ideas?

**Comment by timwiel** [comment]
> That should be fixed in [8499f5c](https://github.com/YahnisElsts/plugin-update-checker/commit/8499f5c42954975a4f1222d6ccedacfaa5fb1d77). Please give it atry.

This fix definitely works so the issue can be closed - my new issue has nothing to do with the plugin-update-checker

**Comment by timwiel** [comment]
> That should be fixed in [8499f5c](https://github.com/YahnisElsts/plugin-update-checker/commit/8499f5c42954975a4f1222d6ccedacfaa5fb1d77). Please give it atry.

This fix definitely works so the issue can be closed - my new issue has nothing to do with the plugin-update-checker

**Comment by YahnisElsts** [comment]
Maybe you could use the `http_request_args` filter and set the `reject_unsafe_urls` argument to `false` when you detect that the requested URL points to your server? I haven't actually tried this, but it's the first thing that comes to mind.

**Comment by timwiel** [comment]
> Maybe you could use the http_request_args filter and set the reject_unsafe_urls argument to false when you detect that the requested URL points to your server? I haven't actually tried this, but it's the first thing that comes to mind.

Yes this works with the following code:
`function http_request_local( $args ) {
$args[‘reject_unsafe_urls’] = false;
return $args;
}
add_filter( ‘http_request_args’, ‘http_request_local’ );`
