### ISSUE TITLE
Error: PUC 4.5 does not support GitHub

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/plugin-update-checker#271]
It's a great piece of code. Just once a while a new customer contact us with some strange issue. In this case there was an error message during plugin installation:

Fatal error: PUC 4.5 does not support GitHub in /homepages/43/d7318/htdocs/domainame.online/colorado/wp-content/plugins/pluginname/updates/Puc/v4p5/Factory.php on line 95

**Comment by YahnisElsts** [comment]
The only way I can think of that this could happen is if some of the PUC files did not get uploaded or were corrupted somehow. Specifically, if the `Puc/v4p5/Vcs/GitHubApi.php` file is missing then you might get an error like that.

**Comment by janeks** [comment]
What this file is for? I do not store anything on GitHub.

**Comment by YahnisElsts** [comment]
The file is for finding and downloading updates from a GitHub repository. Since you're not using the GitHub API, chances are that the user has another plugin installed that uses PUC & GitHub, and the other plugin is bundled with an older version of PUC so it uses your version instead.

**Comment by janeks** [comment]
Yes, that's what I suspected. I'm going to post another question regarding GitHub repository updates.
Thank you again for a great updater.
