### ISSUE TITLE
Disable automated checks for GitHub repository updates.

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/plugin-update-checker#272]
Is there a way to disable or comment out checks for code updates on GitHub,  BitBucket and others?
I prefer to do it manually as needed.

**Comment by YahnisElsts** [comment]
There is no way to globally turn off updates for specific repository types. For an individual plugin, you can turn off automatic update checks by passing `0` as the fourth argument to `builtUpdateChecker`. For example:

```php
$updateChecker = Puc_v4p5_Factory::buildUpdateChecker(
    'https://example.com/...',
    __FILE__,
    'my-plugin-slug',
    0 // <-- How often PUC should check for updates. 0 = no automatic checks.
);
```

Note that even if that's set to 0, PUC will still attempt to instantiate a GitHub API client (or the equivalent for other VCS). It just won't send any requests until you manually click the "check for updates" link.

**Comment by janeks** [comment]
This option is off the table, since I really like the automated updates.
Are you saying then even if I point to the updated files location like: 

`Puc_v4p5_Factory::buildUpdateChecker('https://domain-name.net/wp-update-server/?action=get_metadata&slug=...`

the program will also check the GitHub ?

**Comment by YahnisElsts** [comment]
> Are you saying then even if I point to the updated files location like: [...]
> the program will also check the GitHub ?

No. The update checker will only check GitHub if someone tells it to check GitHub. If it's set up like in your code example then *that instance* of PUC won't do anything with GitHub.

However, if there are other active plugins/themes that are also using PUC and calling `buildUpdateChecker()`, one of *them* might try to point it at a GitHub repository. I'm guessing that's what's happening if you're seeing GitHub-related errors even though your own plugin doesn't use it.

**Comment by janeks** [comment]
Now I understand. Thank you.
