### ISSUE TITLE
The update checker API error - Visitor anti-robot validation

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/plugin-update-checker#273]
It's not the update checker problem but I'm looking for some suggestions how to fix this error message and why it's happening. 

Debug Bar > PUC > Check Now

```
The update checker encountered 1 API error.

1) HTTP response code is 403 (expected: 200)
Error code: puc_unexpected_response_code
..........
<title>Visitor anti-robot validation</title>
....
Long string truncated. Total length: 184942 bytes.
```

**Comment by YahnisElsts** [comment]
It looks like the server that hosts the update information has been configured to block bots, probably as a way to improve security. The update checker sends automated requests, so it's not too surprising that it would trigger defences of that sort.

I did some googling and it looks like this particular error message is related to this product: [BitNinja.io](https://bitninja.io/). It seems to be used by several hosting providers. Does it show up in your host's control panel? Maybe there's a way to whitelist the update info URL or something similar.

**Comment by janeks** [comment]
I think we're getting somewhere. There is no BitNinja in cpanel but came across a page where my hosting provider has been listed an a quote: "_They tried more options to solve this issue, but the final solution was BitNinja to them._"

I'm going to contact them and ask.
