### ISSUE TITLE
The longest time to check for automatic updates.

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/plugin-update-checker#274]
What is the longest time I can set up to check for automatic updates? 
Currently I have 24 hours (I think so):

> $updateChecker = Puc_v4p5_Factory::buildUpdateChecker(
>     'https://example.com/...',
>     __FILE__,
>     'my-plugin-slug',
>     24
> );
> 

Can I make it longer?

**Comment by YahnisElsts** [comment]
There is no hard limit. In theory, you can make it as long as you want. In practice, you will be limited by the integer size of the installed PHP version (e.g. 32-bit vs 64-bit). If the check period exceeds about 160 000 hours, there's a risk of hitting the [year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) on 32-bit systems.

**Comment by janeks** [comment]
That's great. I don't need the automatic checks performed too often. 
Thank you.
