### ISSUE TITLE
Github--Scope of personal access token

### ISSUE THREAD

**Issue by shoroar** [YahnisElsts/plugin-update-checker#275]
Which scope I have to select before creating a personal access token from GITHUB for plugin-update-checker? There is a lot of scopes and a little bit confused which one I have to select and which one I shouldn't select?

**Comment by YahnisElsts** [comment]
I think you only need the `repo` scope and its sub-scopes. You can leave everything else unchecked. Since users will be able to find the access token in the plugin source code or configuration, it's probably best to select as few scopes as possible.
