### ISSUE TITLE
Error: PUC does not support updates for plugins using JSON metadata

### ISSUE THREAD

**Issue by janeks** [YahnisElsts/plugin-update-checker#279]
Changing: 
`Puc_v4_Factory::buildUpdateChecker( ....`
to: 
`Puc_v4p5_Factory::buildUpdateChecker( ....`

Raises an error: Fatal error: PUC does not support updates for plugins using JSON metadata in .......\Puc\v4p5\Factory.php on line 79

**Comment by YahnisElsts** [comment]
I suspect that this could be related to a known bug. Does the site have any other active plugins that use this library and which version(s) of the library are they using?

**Comment by janeks** [comment]
It's development server. I have Library 4.2 and Library 4.5 on active plugins. 
Disabling 4.2 plugins, makes the error go away.

**Comment by YahnisElsts** [comment]
That makes sense. I think what's going on is that 4.2 is loaded first and grabs the `Puc_v4_Factory` alias. Version 4.5 registers its classes only with `Puc_v4_Factory` and not `Puc_v4p5_Factory`, so the version-specific `Puc_v4p5_Factory` class doesn't have any registered classes/APIs and it can't create an update checker instance.

I've just committed a patch that should fix this bug. Please try the master branch.

**Comment by janeks** [comment]
Seems to be working. Updated just one plugin and changed to:
`Puc_v4p5_Factory::buildUpdateChecker( ....`
Now I've a mix of different versions and no errors.

Thank you.
