### ISSUE TITLE
SSL and HHVM issues

### ISSUE THREAD

**Issue by jacobschweitzer** [YahnisElsts/plugin-update-checker#28]
The plugin does not read the metadata correctly and comes back with nothing when SSL is turned on for the server.  Also, HHVM causes this same issue to happen but only sometimes. So when somebody checks for updates it says there is no updates available. However I know that there is, tried using static JSON files, and tried without SSL. I checked using the debug bar and for SSL it said there was a SSL v3 handshake error. The whole time I could go to the URL in the browser and see the JSON file that was generated, but for some reason the update checker could not read the file as a JSON file, I checked that the headers were correct in Chrome developer tools as well.

**Comment by YahnisElsts** [comment]
Connectivity issues are generally outside my control. The library uses the standard WordPress HTTP API. The API, in turn, uses whatever transport layer is available on your server  (curl, fsockopen, streams, etc). If anything goes wrong on that level, it has to do with the server or WP, not the library. 

That said, it sounds like you might have a compatibility problem. SSLv3 is old and  insecure. Some providers have deprecated and disabled it. Perhaps one of your servers no longer supports it? Make sure that both ends - the server running the plugin and the server hosting the update info - support modern SSL encryption. 

Šajā datumā 2015. gada 28. janvāris 16:32:16 EET, Jacob Schweitzer <notifications@github.com> rakstīja:
>The plugin does not read the metadata correctly and comes back with
>nothing when SSL is turned on for the server.  Also, HHVM causes this
>same issue to happen but only sometimes. So when somebody checks for
>updates it says there is no updates available. However I know that
>there is, tried using static JSON files, and tried without SSL. I
>checked using the debug bar and for SSL it said there was a SSL v3
>handshake error. The whole time I could go to the URL in the browser
>and see the JSON file that was generated, but for some reason the
>update checker could not read the file as a JSON file, I checked that
>the headers were correct in Chrome developer tools as well. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/YahnisElsts/plugin-update-checker/issues/28

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by jacobschweitzer** [comment]
Well I did notice the script just uses wp_remote_get so maybe there is an issue with its compatibiity. The update server is using only secure SSL ciphers I got from here - https://cipherli.st/ . I've tested locally on an XAMPP lite configuration (ServerPress) and on a client's server, both had the same issue not finding the updates. 

For now I've stopped forcing SSL and am using php-fastcgi instead of HHVM for the update server folder which is working. I've tried using different SSL ciphers from that site which are supposed to provide more compatibility and it still didn't work right . Here is the exact error when I turn on WP_DEBUG and click the Request Info button in Debug Bar:

Warning: The URL does not point to a valid plugin metadata file. WP HTTP error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure in plugin-update-checker.php on line 235
Failed to retrieve plugin info from the metadata URL.

Thanks for responding to me, I will let you know if I find any solutions. A lot more sites are switching to SSL now, especially for sensitive things like plugin updates so this is something important that should have a good solution without compromising on security. Also, thank you very much for creating these wonderful pieces of code!

**Comment by YahnisElsts** [comment]
> Warning: The URL does not point to a valid plugin metadata file. WP HTTP error: **error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure** in plugin-update-checker.php on line 235
Failed to retrieve plugin info from the metadata URL.

That's a `curl` error. I googled the error message and, based on some of the results, it probably means that installed curl version is either out of date or linked against an old version of OpenSSL (or other SSL/TLS library).

Take a look at the `phpinfo();` info output on your WordPress sites. The "curl" section should include a "SSL Version" field. Look it up in [this table](http://curl.haxx.se/docs/ssl-compared.html) and see if it supports the ciphers enabled on the update server.

**Comment by jacobschweitzer** [comment]
Hey thank you very much for the input. I have updated OpenSSL on my local Xampp install and that seems to have fixed the issue. Here is what I had to do to fix it --- 

download zip files from here -
	http://indy.fulgan.com/SSL/
For me it was this file - 
		http://indy.fulgan.com/SSL/openssl-1.0.2-x64_86-win64.zip

stop apache 

rename libeay32.dll and ssleay32.dll files in xampplite\apache\bin with prefix __OLD__
copy new versions of libeay32.dll and ssleay32.dll files into xampplite\apache\bin

rename xampplite\php\extras\openssl\openssl.exe with prefix __OLD__
copy new version of openssl.exe into xampplite\php\extras\openssl\
