### ISSUE TITLE
Plugin update available but no Update link

### ISSUE THREAD

**Issue by codemountain** [YahnisElsts/plugin-update-checker#283]
Hello Yahnis, both the update-server installed and serving JSON and download links and the plugin-update-checker linked to custom plugin. I can get the plugin to check that an update is available but usually afterwards Worpress shows the section below the plugin listing to actually **Click to update** the plugin. Not sure where to go from here.
Included PUC Debug txt fee, the request sees the download_url and info (changed to acme.ca for privacy)
[Puc_v4p6_Plugin_Info.request.txt](https://github.com/YahnisElsts/plugin-update-checker/files/3065509/Puc_v4p6_Plugin_Info.request.txt)

Screenshot:
![Screen Shot 2019-04-10 at 3 11 58 PM](https://user-images.githubusercontent.com/777190/55907143-f03f7c00-5ba3-11e9-9211-3f88e5dc5506.png)

**Comment by YahnisElsts** [comment]
One thing that could cause that is an incorrect file name being passed to the update checker. Make sure that, when you're creating a PUC instance with `buildUpdateChecker`, you pass the full path to the main plugin file as the second argument. In this context, the "main" file is the one that contains the plugin header comment. Any other file will not work.

**Comment by codemountain** [comment]
Thanks for the feedback :-)
It does contain the full path i believe by using this: 
`$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'http://acme.ca/update_server/?action=get_metadata&slug=acme-admin',
	__FILE__,'acme-admin');`

Anything there i'm not seeing? thanks so much.

**Comment by YahnisElsts** [comment]
This may sound obvious, but is this code in the main plugin file or another `.php` file? Since it uses the `__FILE__` constant it would only work if it's in the main file.

It looks like this site has many active plugins. Could one of them be hiding updates? Also, does the update show up in "Dashboard -> Updates"?

**Comment by codemountain** [comment]
Hmm de-activated and reactivated most plugins and now it works, i can see the banner and the Dashboard updates. Not sure why that would be , a plugin is usually in conflict or not. But hey, i'll take it for now :-) Have a great day Yahnis!

**Comment by YahnisElsts** [comment]
If it's intermittent, it could be related to caching or something like that.

In any case, I'll close this issue now. If you do find a conflict or a bug, feel free to reopen it.
