### ISSUE TITLE
Unable to update theme from self-hosted GitLab repository

### ISSUE THREAD

**Issue by hvianna** [YahnisElsts/plugin-update-checker#284]
First of all, thank you so much for this great tool! I have PUC working for a plugin hosted in our own GitLab repository. Now I'm trying to integrate it with a custom theme.

I can see an update badge in the *Plugins* menu on the WP dashboard, and Debug Bar also shows an update available, but there are no update options in the Updates page itself.

This is what I'm using in my theme's `functions.php`:

```
// update checker
require 'vendor/plugin-update-checker/plugin-update-checker.php';

$PortalUpdateChecker = new Puc_v4p6_Vcs_PluginUpdateChecker(
	new Puc_v4p6_Vcs_GitLabApi('https://gitlab.ufpel.edu.br/websites/Portal'),
	__FILE__,
	'Portal'
);

$PortalUpdateChecker->setAuthentication('XX'); // actual key redacted :)
$PortalUpdateChecker->setBranch('master');
```

I also tried replacing `__FILE__` with `get_stylesheet_directory() . '/style.css'`, but it didn't seem to change anything.

Some screenshots:

![image](https://user-images.githubusercontent.com/1033735/56807273-bbb6fb80-6804-11e9-8f5e-8380a71e8789.png)

(You may notice I've made some changes to the API URLs, because we're using an old GitLab version, stuck with API v3 - it is working fine for the plugin though).

![image](https://user-images.githubusercontent.com/1033735/56807298-cbcedb00-6804-11e9-9d4e-f09e01b4ddac.png)

![image](https://user-images.githubusercontent.com/1033735/56807630-c7ef8880-6805-11e9-9a7f-34adfa9d13b0.png)

Would appreciate any advice. Thanks again!

**Comment by YahnisElsts** [comment]
Since this is a theme and not a plugin, you'll need to replace `Puc_v4p6_Vcs_PluginUpdateChecker` with `Puc_v4p6_Vcs_ThemeUpdateChecker`.

**Comment by hvianna** [comment]
Got it, thank you!
