### ISSUE TITLE
Update from self-hosted Gitlab is trying to update functions file, not theme directory

### ISSUE THREAD

**Issue by peter-mumford** [YahnisElsts/plugin-update-checker#285]
I am using a self-hosted Gitlab repo. I am instantiating PUC like this, in functions.php:
```
$myUpdateChecker = new Puc_v4p6_Vcs_ThemeUpdateChecker(
	new Puc_v4p6_Vcs_GitLabApi('http://gitlab.fmcna.com/petermumford/fmcna-pamplona/'),
	__FILE__,
	'fmcna-pamplona'
);
$myUpdateChecker->setAuthentication('XXXX');
$myUpdateChecker->setBranch('master');
```
In my updates panel, I see this:
<img width="1037" alt="theme-update" src="https://user-images.githubusercontent.com/31707793/56864784-82ad9100-6994-11e9-9097-4417885b9afc.png">
It can't see the theme folder, just the path to the functions file.

In the debug panel, I can see the PUC config, and it seems to have the wrong value for theme directory:
<img width="770" alt="PUC-config" src="https://user-images.githubusercontent.com/31707793/56864879-dcfb2180-6995-11e9-8c13-e0a105b16d01.png">
I checked that the download URL is accurate. And the theme slug, theme folder, and repo name are all the same. What am I doing wrong? 
P.S. also, trying to run the update fails, due to a naming conflict: "Unable to rename the update to match the existing directory".

**Comment by YahnisElsts** [comment]
For themes, when you instantiate PUC directly, you need to set the second constructor argument to the theme directory name. For example, if the code is in functions.php, something like this might work:
```php
basename(dirname(__FILE__))
```

In some cases `get_stylesheet()` will also work, but it might not be the right choice if you're using parent/child themes or updating a theme from a plugin.

**Comment by peter-mumford** [comment]
That works!
