### ISSUE TITLE
Question regarding site_transient

### ISSUE THREAD

**Issue by jatind93** [YahnisElsts/plugin-update-checker#286]
Hi
I want to know if I can get response to check updates, using  get_site_transient( 'update_plugins' ); ???
Currently I am not getting result by using above code.

**Comment by YahnisElsts** [comment]
Yes, technically you can get update information that way. 

Are you sure an update is actually available? Is it showing up on the "Dashboard -> Updates" page? Also, makes sure that the code that retrieves the transient run *after* the code that initialises the update checker. If you try to read the `update_plugins` transient before creating an update checker instance, it won't include your update(s) because the filter that inserts updates won't be set up yet.

**Comment by jatind93** [comment]
Are you sure an update is actually available? Is it showing up on the "Dashboard -> Updates"
Ans : Yes it's showing me the update is available.

[Example link ](https://w-shadow.com/blog/2010/09/02/automatic-updates-for-any-plugin/)
I had tried your example as explained in above mentioned link for both old and new version but I am not getting any results. I would appreciate if you could explain in a bit easier way by giving example if possible.

Thank you

**Comment by YahnisElsts** [comment]
Sure, I suppose I could post a basic example. What exactly are you trying to do? Just output the `update_plugins` transient for testing purposes? You could do something like this:

```php
add_action('admin_notices', function() {
	echo '<pre>';
	echo htmlentities(print_r(get_site_transient('update_plugins'), true));
	echo '</pre>';
});
```

I've tested this with PUC and the output includes updates that were retrieved by PUC.

**Comment by jatind93** [comment]
Que: What exactly are you trying to do?
Ans:  i am trying to disable update notification if the user is not register with our licence key.
Do you know any way to perform this or is it possible to disable using 
`add_filter( 'site_transient_update_plugins'`???

**Comment by YahnisElsts** [comment]
There are several ways to do that, but a transient filter might be the one that takes the smallest amount of code. Here's an example:

```php
function puc_example_filter($updates) {
	$pluginBasename = plugin_basename(__FILE__);
	//Depending on how your plugin is implemented, you might need to change this.
	//Basically, $pluginBasename needs to be "your-plugin-directory/plugin-file.php".

	if ( !isset($updates, $updates->response, $updates->response[$pluginBasename]) ) {
		//There's no update for this plugin, so there's nothing to do.
		return $updates;
	}
	$isLicenseValid = false; //Put the real license validation here.
	if ( !$isLicenseValid ) {
		unset($updates->response[$pluginBasename]);
	}
	return $updates;
}
add_filter('site_transient_update_plugins', 'puc_example_filter', 20);
```

**Comment by jatind93** [comment]
I have able to remove update link from plugins-> list.
[Screenshot-1](https://i.imgur.com/HkG816z.jpg)

I need to remove update list from dashboard->updates->list. Could you suggest me any action/filter. Have you provided such functionality ?
[Screenshot-2](https://i.imgur.com/yYVNkpa.jpg)

I really appreciate your technical support.

**Comment by YahnisElsts** [comment]
I believe that the "Dashboard -> Updates" list uses the same transient, so in theory the same code should work for both pages. Make sure that your code is running on all admin pages and not just the "Plugins" page.

**Comment by jatind93** [comment]
I was Silly. Thank you for explanation.
Your library worked fine when tested on single site but as I am testing it on multisite it is not showing plugin update option. Is this functionality available by your library????

**Comment by YahnisElsts** [comment]
On Multisite updates will only work if your plugin is one of the following:
- Active on the main site
- Network activated
- Installed in mu-plugins

When you're in the network admin, WordPress runs only those plugins that meet one of the above conditions. If your plugin isn't running in the network admin, it can't add updates to the `update_plugins` transient, so updates don't show up.

**Comment by jatind93** [comment]
@YahnisElsts 
Hi,
Thank you,
You were great help my friend. It would have been very difficult to solve issue if you were not there. I really appreciate your support. I hope I would be able to do the same.
Thank you once again👍

**Comment by YahnisElsts** [comment]
All right, no problem.
