### ISSUE TITLE
Bitbucket API 1.0 deprecated

### ISSUE THREAD

**Issue by joordiii** [YahnisElsts/plugin-update-checker#289]
Hi Yahnis,
I have just installed plugin-update checker to be able to update my wordpres plugin hosted in bitbucket. I get several errors, and changes in my bitbucket repo are not recognised.
It looks like the Bitbucket API 1.0 is deprecated.

I also installed debug bar plugin, the list of errors is the following:

The update checker encountered 3 API errors.
1) BitBucket API error. Base URL: "https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/readme.txt", HTTP status code: 410.
Error code:
puc-bitbucket-http-error
Requested URL:
https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/readme.txt?oauth_consumer_key=consumer_key&oauth_nonce=----------------------&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1560323022&oauth_version=1.0&oauth_signature=------------------------------
HTTP status:
410 Gone
Response headers:
vary: User-Agent
content-type: application/json; charset=utf-8
date: Wed, 12 Jun 2019 07:03:41 GMT
content-length: 262
Response body:
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

2) BitBucket API error. Base URL: "https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/add-shortcodes-tinymce-plugin.php", HTTP status code: 410.
Error code:
puc-bitbucket-http-error
Requested URL:
https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/add-shortcodes-tinymce-plugin.php?oauth_consumer_key=consumer_key&oauth_nonce=-------------------&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1560323023&oauth_version=1.0&oauth_signature=----------------------------
HTTP status:
410 Gone
Response headers:
vary: User-Agent
content-type: application/json; charset=utf-8
date: Wed, 12 Jun 2019 07:03:43 GMT
content-length: 262
Response body:
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

3) BitBucket API error. Base URL: "https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/readme.txt", HTTP status code: 410.
Error code:
puc-bitbucket-http-error
Requested URL:
https://api.bitbucket.org/1.0/repositories/grupoblidoo/add-shortcodes-tinymce-plugin/src/master/readme.txt?oauth_consumer_key=---------------------&oauth_nonce=--------------------------------&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1560323024&oauth_version=1.0&oauth_signature=-------------------------
HTTP status:
410 Gone
Response headers:
vary: User-Agent
content-type: application/json; charset=utf-8
date: Wed, 12 Jun 2019 07:03:43 GMT
content-length: 262
Response body:
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

Thanks

**Comment by jabbergabber** [comment]
I am having the same issue - so far I have found that :

getRemoteFile() in BitBucketApi.php is still set to use 1.0
			$response = $this->api('src/' . $ref . '/' . ltrim($path), '1.0');
I changed this to '2.0' but now the api function fails as it can not json_decode a non encoded file.

I am in the process of hacking the code thus:

BitBucketApi.php

160			$response = $this->api('src/' . $ref . '/' . ltrim($path), '2.0');

161			if ( is_wp_error($response) || !isset($response) ) {
162			//if ( is_wp_error($response) || !isset($response, $response->data) ) {

217    	$temp = json_encode($body);
218		$document = json_decode($temp);

Seems to be working but it needs some proper investigation ! :)
Hope that helps get you by until Yahnis has had chance to catch up.

Regards
Pete

**Comment by joordiii** [comment]
Many thanks Pete for your reply. Your code is also working for me, goooodd!
The only think left to have everything working fine is related to a multisite. In a single site, there is a link "Check for updates" (this link is generated by plugin-update-checker)  where I can manually check for new updates. I don't receive automatic notifications of the updates but with the link I can manually check it, this is fine for me. The problem commes for a multisite, in this case the link "Check for updates" is not appearing at the plugins admin section. So, I'm not receiving automatic notifications for updates and I can not check it manually. Any suggestions??
Jordi

**Comment by jabbergabber** [comment]
Hi Joordiii - glad it helped - Im not sure about the multisite problem I'm afraid - I had to add some extra 'hacks' to make the branch and tags work due to the issue with the non json files being received. I am sure there is a simple and more elegant fix than mine - I just need to get an update sorted on a live site pronto!
If I get chance later I will take a look for you. Regards Pete

**Comment by jabbergabber** [comment]
Just had a quick scan for 'multi' in the code and can't find anything relevant - if you can find any code we can look at I can take a look and try and work something out for you. Regards Pete

**Comment by YahnisElsts** [comment]
Thank you for the report. I've just committed a patch that should fix the BitBucket API errors. Please give it a try and let me know if it helps. The patch is broadly similar to what @jabbergabber suggested. I switched `getRemoteFile` to API version 2.0 and disabled JSON decoding for all `src/` resources.

As for the missing "check for updates" link in Multisite, that sounds like an unrelated issue. @joordiii Could you tell me a bit more a bit more about how your plugin is set up? For example, is the plugin installed in `plugins` or `mu-plugins`? Is it network activated? Is the file name that you're passing to `builUpdateChecker` the correct path to the main plugin file?

**Comment by jabbergabber** [comment]
Excellent - Thanks Yahnis.
My 'hacks' removed and your patch applied and all is good in the world !
Thanks Again

**Comment by joordiii** [comment]
Hi Pete and Yahnis, thank you for your help. Both codes work very well.
Soon I'll write a full explanation about the second issue. 
Best

**Comment by joordiii** [comment]
Hi, here goes a more detailed explanation of the second issue. I can't update my plugin from a Multisite Network.

### **Local wordpress installation for a single site:**
When I locally install my plugin with plugin-update-checker files on it, I get the button check for updates and I also receive automatic updates. _Everything OK_.
![image](https://user-images.githubusercontent.com/26466392/59587789-5be31f80-90e6-11e9-9076-6951824742db.png)

### **Multisite wordpress installation:**
I install my plugin in the Network. It is not network activated, I only activate the plugin in the sites I need it.
What I get is the following:
![image](https://user-images.githubusercontent.com/26466392/59588593-41aa4100-90e8-11e9-954e-8e084005eefa.png)
In this case the "Check for updates" button is not appearing and it also doesn't receive automatic notifications about new versions uploaded in the repository.

If I activate it for a single site among the ones in my Network, I get this:
![image](https://user-images.githubusercontent.com/26466392/59588975-2a1f8800-90e9-11e9-939c-92baa06ab7a6.png)
The button "Check for updates" appears, and clicking the button the connection is successful and gets the right information. The url shows "no-updates-available" or "updatea-available" if it is the case.
Update available
![image](https://user-images.githubusercontent.com/26466392/59588933-04927e80-90e9-11e9-9bb8-0121d717b640.png)

Even though there is an update, the link "update now" never appears.

Anyway, for a single site in my Network I don't need to update the plugin, the place to update the plugin is in the plugins section in my Network admin (First image of this explanation).

I hope the explanation is clear enough for you to get the idea of what is happening.
Thanks

**Comment by YahnisElsts** [comment]
Thank you for the detailed description. I think I can guess why the update links are not showing up in the network admin.

As you probably know, the update checker needs to be loaded and running for it to display the "check for updates" link and other update-related things. This means that your plugin needs to be active and running as well (because the update checker is part of your plugin). Specifically, for updates to show up in the network admin, your plugin needs to run in the network admin.

In Multisite, the only plugins that WordPress loads in the network admin are the plugins that meet one of these conditions:
- Installed in `mu-plugins`.
- Network activated.
- Active on the main site of the network.

It sounds like your plugins isn't any of the above. As a result, it isn't loaded/running in the network admin, so the update checker isn't running either, and the update links don't show up.

As far as I know, there is no way around this limitation. If you want updates to work in Multisite, your plugin must run in the network admin. Alternatively, you could have a separate network-activated plugin or mu-plugin that just manages your plugin's updates.

**Comment by joordiii** [comment]
Hi Yahnis,
I have just activated my plugin in the Network and the links show up perfectly. 
Now everything appears to be working fine!
(A deeper checking is needed but all looks good)
![Captura de pantalla de 2019-06-18 12-46-38](https://user-images.githubusercontent.com/26466392/59676912-eef48600-91c8-11e9-8804-9976709672a7.png)
Thanks for developing such an amazing pluging and for your help.
If I find something else, I'll tell you.
(Pete, your help was also very valuable at that moment. THX)
