### ISSUE TITLE
Update via Github

### ISSUE THREAD

**Issue by thaikolja** [YahnisElsts/plugin-update-checker#29]
Do you think you can implement a function that checks plugins on Github **not** based on the plugin version but on the Github commit hash?

And please keep up your good work. I really love this script.

**Comment by YahnisElsts** [comment]
What's the use case for this? If you just need to keep the plugin directory synchronized with a GitHub repository then there are probably more straightforward ways to do that.

**Comment by thaikolja** [comment]
Well, then don't. It'd be useful for me, and probably also for some other users.

**Comment by YahnisElsts** [comment]
Sure, it would be useful. It's just probably outside the scope of this project. This library has a bunch of features not related to synchronization, and you have to install each update manually. Something like a cronjob that runs `git pull` would take far less code and be fully automatic.

**Comment by thaikolja** [comment]
Okay, thanks for pointing that out.
