### ISSUE TITLE
bitbucket theme update error

### ISSUE THREAD

**Issue by jessequinn** [YahnisElsts/plugin-update-checker#292]
When using check now in the debug bar for the plugin theme updater i receive the following error:

```
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}
```

Any idea? I believe the base url is wrong for the API OAuth call.

**Comment by YahnisElsts** [comment]
I believe this error was fixed a little while ago, but the last release was fairly old and did not include the necessary patch. I've made a new release just now that includes the fix. Please download the latest version (4.7) and try again.

**Comment by jessequinn** [comment]
thanks
