### ISSUE TITLE
GiTea Support

### ISSUE THREAD

**Issue by DjSni** [YahnisElsts/plugin-update-checker#297]
Hello,

are there any plans to support GiTea ?
GiTea is a GitHub clone written in GO and can be self-hosted.

Greeting

**Comment by YahnisElsts** [comment]
I have no such plans at the moment. 

However, if someone else wants to take a shot at adding GiTea API support, feel free. If necessary, I can provide some recommendations or answer any questions you might have about how GitHub/VCS integration works in this update checker.

**Comment by DjSni** [comment]
#298
