### ISSUE TITLE
no updates from bitbucket

### ISSUE THREAD

**Issue by media-store-net** [YahnisElsts/plugin-update-checker#299]
Hi, i'm use the update checker in a plugin more than 1 year with a private Bitbucket Repo. After last Update to v3.056.8 i can see no updates anymore on Branch mvc. Current Version on mvc branch is v3.057.2 

What is wrang? No changes on consumer_key or secret 

![image](https://user-images.githubusercontent.com/20956285/61547034-d89d4c80-aa4a-11e9-8897-05820af24edc.png)

![debug1](https://user-images.githubusercontent.com/20956285/61547056-e6eb6880-aa4a-11e9-9754-d3be8ecd900f.png)

![debug2](https://user-images.githubusercontent.com/20956285/61547069-ed79e000-aa4a-11e9-872e-89ff50ca8c7f.png)

**Comment by YahnisElsts** [comment]
Try upgrading to the [latest version](https://github.com/YahnisElsts/plugin-update-checker/releases/latest) of the update checker. BitBucket made some changes to their API a while ago and older versions of plugin-update-checker might not work any more.

**Comment by media-store-net** [comment]
thanks, that is it... new version works again.
