### ISSUE TITLE
PHP 7.3 Deprecated Message

### ISSUE THREAD

**Issue by artprojectgroup** [YahnisElsts/plugin-update-checker#303]
This message is showed in /wp-admin/plugins.php:
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior
--

File:
/Puc/v4p5/Plugin/Package.php

Line: 
167

The test installation hasn't any mu-plugin directory.

Thanks a lot for your great plugin.

Kind regards.

**Comment by YahnisElsts** [comment]
Could you please try that with the [latest release](https://github.com/YahnisElsts/plugin-update-checker/releases/latest) of `plugin-update-checker`? I think it should fix this issue.

**Comment by artprojectgroup** [comment]
Fixed! Thank you.

Kind regards.
