### ISSUE TITLE
View version X details are not displaying

### ISSUE THREAD

**Issue by ljubomir1301** [YahnisElsts/plugin-update-checker#304]
Hi, 
First of all, great plugin! Congrats! I have some issue here, like the title says. When i click view version X on a theme, comes to a blank popup page. But if click open in a new tab on the browser, changelog external link works. Any idea how to fix this?

Screenshot: https://ibb.co/2Sj04gC

Thanks!

**Comment by YahnisElsts** [comment]
Try this: open the browser's developer tools/console and then try clicking the "View version X" link again. Do any errors or warnings show up in the console when you do that? In particular, look for JavaScript errors and errors related to frames. It could be that the page that you're using is configured to block attempts to display it in an iframe.

**Comment by ljubomir1301** [comment]
Looks like something it's blocking it. Here is the error: Blocked loading mixed active content
i guess HTTPS is blocking it? Any way to bypass this?

**Comment by ljubomir1301** [comment]
Or how to add "target=_blank" into the changelog link? So, can be opened in a new tab on any browser?

**Comment by YahnisElsts** [comment]
I think [mixed content blocking](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) is a browser security feature. You might be able to somehow disable or bypass it in your browser, but I doubt that it's possible to do that for everyone who uses your theme. 

> Edit: Also i change the changelog.html link from .json to https:// still the same.

The update data is cached so you'll need to trigger an update check to see the changes. Normally, there's no way to do that directly (for themes) unless you're using the Debug Bar plugin. However, you can do it indirectly by changing the theme version number and visiting "Dashboard -> Updates". 

> Or how to add "target=_blank" into the changelog link? So, can be opened in a new tab on any browser?

You'd need to replace the link with a new one. It's probably doable, but switching to HTTPS might be simpler if you already have it enabled on your site.

**Comment by ljubomir1301** [comment]
I tried all those options, you listed above and still is the same. Purged cache, triggered update from "Dashboard -> Updates", installed Debug plugin, installed SSL, i tried plugin to bypass mixed content...  

I guess the only option i have left is just changing the link destination to taget=_blank link.

**Comment by YahnisElsts** [comment]
Did switching to SSL change anything about the error message? It should show the URL after the error; did that URL change to `https://...`? Also, does the debug bar show the correct (HTTPS) URL?

**Comment by ljubomir1301** [comment]
Nope, still loaded blank popup even after switching to SSL. And yes, it was the correct HTTPS Url.

**Comment by YahnisElsts** [comment]
I'm sorry for asking the same thing again, but that result doesn't match up with my understanding of how mixed content works so I want to make sure I'm not missing something. Can you confirm that the console shows the message "blocked loading mixed active content" and a `https` URL?

**Comment by ljubomir1301** [comment]
Yes sir. It does. Sorry for not explaining in details. But whatever i do, as you suggested above, still there is error and blank popup.

**Comment by YahnisElsts** [comment]
That's strange and unfortunate. Also, I just searched for ways to replace the link with a different one and I didn't find any obvious solutions. For a plugin you could use the `plugin_row_meta` filter to add/remove links, but themes don't seem to have anything similar. 

The update notification message appears to be generated by the `get_theme_update_available()` function in `/wp-admin/includes/theme.php`. I've looked at the code and unfortunately I don't see any filters that you could use to replace the link or to add `target="blank"` to the link.

**Comment by ljubomir1301** [comment]
Well... thanks anyway. I'll try to figure out how to fix this issue, with the default code. I'll keep an eye for updates if you change anything :)

Thanks!

**Comment by YahnisElsts** [comment]
Sure. I'll close the issue for now, but if you have any additional questions or suggestions, feel free to reopen it.

**Comment by ljubomir1301** [comment]
However, i fixed it. Here's how:
1. Added https://www. in "details_url" in .json 
2. Reset whole SSL on the domain
3. Refreshed it with Debug bar plugin

I hope won't be issue for any user who doesn't have SSL installed from now... But great plugin to use customized HTML changelog :)
