### ISSUE TITLE
Inconsistency in handling of "Tested" value

### ISSUE THREAD

**Issue by DavidAnderson684** [YahnisElsts/plugin-update-checker#307]
When a background updates check is done via `Puc_v4p7_Plugin_UpdateChecker::requestUpdate()`, that method calls `Puc_v4p7_UpdateChecker::filterUpdateResult()`, which calls `fixSupportedWordpressVersion()` in the same class. This results in the metadata stored in the database having the fixed WP version.

However, when viewing information about an available update via the plugins page (/wp-admin/plugin-install.php?tab=plugin-information&plugin=(slug)&section=changelog), that information is not used. `Puc_v4p6_Plugin_UpdateChecker::injectInfo()` is called via the `plugins_api` filter; this goes to `Puc_v4p6_Plugin_UpdateChecker::requestInfo()` which does not do any equivalent version-munging.

The result is that the user sees unwanted warnings about the plugin not being tested, and the "Tested up to:" field shown is just X.Y (i.e. no third component).

**Comment by YahnisElsts** [comment]
Thank you for the report. This should now be fixed.

I considered several different options for where the version number could be adjusted and eventually settled on just calling `fixSupportedWordressVersion()` in `injectInfo()`.
