### ISSUE TITLE
Update process is losing files from plugin

### ISSUE THREAD

**Issue by diegomagikal** [YahnisElsts/plugin-update-checker#308]
Hi,

When I update my wp plugin (self-hosted) with your updater, a lot of files and folders are deleted. Basically only vendor folder, and composer.json, composer.lock and plugin.php files are intact. I have been trying it since v4.5. 

I can experience it both in online server as in my localhost (windows 7).

**Before update:**
![before update](https://user-images.githubusercontent.com/16082344/64195805-bde73180-ce58-11e9-8b52-da11b7ee8be8.JPG)

**After update:**
![after update](https://user-images.githubusercontent.com/16082344/64195806-bde73180-ce58-11e9-84f8-406bd15b865b.JPG)

Any idea? Thanks in advance.

**Comment by YahnisElsts** [comment]
The way that the update installer works is that it deletes the old version of the plugin (i.e. the one that's  already installed) and then replaces it with the downloaded version. Can you confirm that the new version ZIP file actually contains all of the necessary files?

**Comment by diegomagikal** [comment]
Yes... all files are inside the downloaded zip!

**Comment by YahnisElsts** [comment]
All right, and are you sure the update checker is using the same ZIP that you're looking at? Are you manually specifying the `download_url` field in JSON metadata or is it automatically generated in some way?

**Comment by diegomagikal** [comment]
Thanks, after check all my code I can see that my automated deploy script is changing incorrectly the download_url  in update.json. Solved!
