### ISSUE TITLE
Bitbucket Failed to Download Update, Not found

### ISSUE THREAD

**Issue by hwsiew** [YahnisElsts/plugin-update-checker#309]
Hi,

Previously i was extended bitbucketapi in 4.4 and now update to 4.7 for this plugin checker. I was trying to download the new update from bitbucket, but it shows an error 'Update Failed: Download failed. Not Found'.

This is the download link i find in Debug bar : 
https://bitbucket.org/chatleh/my-test/get/master/dist/my-test-0.5.zip?oauth_consumer_key=9jfxGLJQDDkhg9CDe5&oauth_nonce=9a2d6efeb9219cc50dfbdf4d8fed2766&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1567927328&oauth_version=1.0&oauth_signature=frTNO%2F6NLXlbo%2BdzsYqAufwPKl0%3D

Any idea what would be the issue?

**Comment by YahnisElsts** [comment]
Verify that your `consumer_key` and `consumer_key` are correct. I've previously run into a situation where I got a "Not Found" error but the real problem was that my authentication details were wrong.

If that doesn't help, could you tell me a bit more about your update configuration? Are you using tags, branches, or something else? What is the repository URL that is passed to the update checker?

**Comment by hwsiew** [comment]
Yup confirmed the consumer key and secret are correct. 

The repo url pass to update checker : https://bitbucket.org/chatleh/my-test/

I extend the bitbucketApi class and override the 'getDownloadUrl' to return the download url from a specific folder('dist') in my repo as follow. And the others are all default.

```
protected function getDownloadUrl( $ref ) {

		return sprintf(
				'https://bitbucket.org/%s/%s/get/%s.zip',
				$this->username,
				$this->repository,
				'master/dist/my-test-' . $ref 
			);
}
```

The following is the download url generated where i got it from debug bar : 

https://bitbucket.org/chatleh/my-test/get/master/dist/my-test-0.5.zip?oauth_consumer_key=9jfxGLJQDDkhg9CDe5&oauth_nonce=17cd757b425d2e7c4af057742a4f95d9&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1567936310&oauth_version=1.0&oauth_signature=BmTye9Ex5EZUD8z9vcLPgMU%2FdnM%3D

**Comment by YahnisElsts** [comment]
My understanding is that the last part of the download URL is usually `/get/ref.zip` where `ref` can be a tag, branch, or maybe a commit hash. Are you sure `/get/master/dist/my-test-ref.zip` is a valid alternative? Does it work if you try it in the browser instead of in the update checker?

**Comment by hwsiew** [comment]
I see. It doesn't work in browser. but if I try /get/master.zip it download the my whole repo as zip. 

Any ways I can download a zip file in specific folder 'dist' in my repo?  

Many thanks for advice.

**Comment by YahnisElsts** [comment]
Unfortunately, I don't know any way to do that. A quick Google search didn't turn up anything promising either.

**Comment by hwsiew** [comment]
It seems to be the following endpoint is working. 

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/src#get

Thanks for your assistance @YahnisElsts
