### ISSUE TITLE
Issue with updating via GitHub

### ISSUE THREAD

**Issue by samhotchkiss** [YahnisElsts/plugin-update-checker#31]
When using the GitHubChecker class, the update has the commit hash appended to the end of the plugin folder downloaded from GH, breaking the update since the plugin has moved to a new path.

Any suggestions on how to resolve?

**Comment by YahnisElsts** [comment]
That's when using the "update now" link that installs the update without refreshing the page, correct? I'm guessing that it would work fine if you use "Dashboard -> Updates".

Try the master branch, this bug should be fixed there.

**Comment by YahnisElsts** [comment]
Update: This should be fully fixed in the 2.2 release.

**Comment by samhotchkiss** [comment]
Awesome, thank you!  We use PUC in our official Jetpack Beta Tester plugin, and it rocks.
