### ISSUE TITLE
Conflict between tags on different branches

### ISSUE THREAD

**Issue by amiranagram** [YahnisElsts/plugin-update-checker#311]
Hello Yahnis,

I've been using your package for a while now and I you have made my life so much easier.
I have one issue though. I am hosting my repository on GitLab and I'll be honest I'm not very familiar with GitLab's API but I've been having this issue with tags.

The scenario: I push the code to my development branch and create a tag for it, and I do that many times over, since we have a WordPress website for testing purposes there will be many tags to fix the minor issues. Back onto my production branch there will be naturally one tag only after the testing finished successfully. And on our clients' WordPress websites the update checker displays version from the development branch.

Maybe I missed your documentation and maybe you already have a solution or this, but I would like the tags between branches not to have any conflicts between themselves.

Regards.

**Comment by YahnisElsts** [comment]
I'm not a Git expert, but my understanding is that tags exist independently from branches. That is, you can create a tag from a branch, but once that's done then the tag is no longer tied to that branch. You can delete the branch and the tag will persist. Also, tags point to commits, and one commit can be part of multiple branches.

I also looked at the [GitLab API documentation on tags](https://docs.gitlab.com/ee/api/tags.html) and it appears that the response you get when listing/retrieving tags doesn't include any information about branches.

Unless I'm missing something, it seems that there's no easy way to do what you're suggesting.
