### ISSUE TITLE
Works only on repo scope why?

### ISSUE THREAD

**Issue by soniadarsh** [YahnisElsts/plugin-update-checker#312]
Hello Yahnis?

Why this library shows update notifications in repo scope only, here is my OAuth apps scope settings
![2019-09-21_11h22_50](https://user-images.githubusercontent.com/44223053/65368992-89031900-dc65-11e9-97f8-d90d50650516.png)
repo (Scope)---> Provide full control over private repositories, i don't want this, is there any way to give users only read only access with upgrade notices, what i am missing ?

Note: Access token key is off contributor(me)

==========  **Used Following Code In My Plugin Main Php File** ============
`require ( INKCA_PATH . 'qwerty-addons-update-checker/plugin-update-checker.php' );
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/qwerty/qwerty101/',
	__FILE__,
	'qwerty-addons'
);

$myUpdateChecker->setAuthentication('[redacted]');
$myUpdateChecker->setBranch('master');
//Optional: If you're using a private repository, specify the access token like this:
$myUpdateChecker->getVcsApi()->enableReleaseAssets();`

**Comment by YahnisElsts** [comment]
The library uses this approach because it's the only way I know how to get access to private repositories when using the API. I agree that potentially giving users read-write access is not ideal. If you know a way to restrict it to read-only access, I would love to hear it.

**Comment by soniadarsh** [comment]
Hi Yahnis

Thanks for reply,

Is there a way in which i can create public repository of all content instead of private repo, such that OAuth apps scope settings can only give read access to remote user with update notifications working?

**Comment by YahnisElsts** [comment]
I don't know a way to do that, no. However, someone else recently posted a different workaround in another thread:
https://github.com/YahnisElsts/plugin-update-checker/issues/258#issuecomment-533964233

As far as I understand, it boils down to creating a second GitHub account with more limited permissions. I haven't tried that myself, but it sounds like it could work.

**Comment by soniadarsh** [comment]
Hi Yahnis,

Facing one more issue, plugins taking another plugin update from releases for example if suppose i have a plugin xyz1 recently done commit of xyz1 and also releases a tag for it v1.1.6 and after that i have a another plugin xyz2 done commit of xyz2 and releases a tag for it v1.0.4 now what happens xyz2 plugin shows view details--v1.16 notifications and when i click update now button it takes all things of xyz1 plugin inside xyz2, how can i point out particular plugin notifications correctly, what i iam missing 

**==============my plugin code=============**
`require ( INKCA_PATH . 'xyz1/xyz1.php' );
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/soniadarsh/plugins/',
	__FILE__,
	'xyz1'
);

$myUpdateChecker->setBranch('master');
$myUpdateChecker->getVcsApi()->enableReleaseAssets();`

![2019-09-24_11h38_15](https://user-images.githubusercontent.com/44223053/65485638-04600700-dec0-11e9-9ad4-c7a860a0a84c.png)

**Comment by YahnisElsts** [comment]
One way that could happen is if both plugins were using the same repository URL for some reason. Please make sure that each plugin has its own repository.

**Comment by YahnisElsts** [comment]
Most likely, this has to do with the plugin's directory structure. All of the plugin files and directories must be at the root of the repository, not in a subdirectory. For example, [WooCommerce](https://github.com/woocommerce/woocommerce) has the correct directory structure.

On the other hand, if the directory structure in your repository looks like this:
- myplugin-repo
    - /myplugin
        - /assets
        - /stuff
        - plugin.php
        - other plugin files

... then updates might not work properly because the plugin files will end up in the wrong place. 

You might be able to work around that by creating release assets with the right directory structure, but I don't have much experience with that.

If you have any further questions that are not related to the original issue, please open a new issue instead of posting a comment.

**Comment by joelmcdwebworks** [comment]
Thank you for reporting this issue. I couldn't figure out why it wasn't working, so I switched the scope, and now it's working.

**Comment by josueochoa** [comment]
> The library uses this approach because it's the only way I know how to get access to private repositories when using the API. I agree that potentially giving users read-write access is not ideal. If you know a way to restrict it to read-only access, I would love to hear it.

Wanted to share the solution i'm using to solve this issue, i created a specific Github user for the purpose of providing its Token for updates, that User is then invited to the private repo with only read-access. Seems to be working fine.

**Comment by YahnisElsts** [comment]
I've seen that approach recommended in multiple places. It sounds like a pretty good workaround.
