### ISSUE TITLE
cached update shows new download url, but still says no update available

### ISSUE THREAD

**Issue by bgrundon** [YahnisElsts/plugin-update-checker#318]
ok, I had this working at one point, and then it just suddenly stopped.

I have the main plugin filed named 'blocks-dev.php' and the plugin directory is also named 'blocks-dev. In the buildUpdateChecker it is set like this;

`require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/repo-name-here/blocks-dev',
	__FILE__,
	'blocks-dev'
);`

As you can see here, the check shows that there isn't an update available, even tho it's checking the existing version of 1.0.0 and the latest is 1.2.1
I have tried clearing cache, cookies, and deactivating and reactivating my plugin, but it just won't give me the update.

Am I missing something obvious here?

![InkedScreenshot_2019-09-26 Plugins ‹ Blocks Dev Site — WordPress_LI](https://user-images.githubusercontent.com/1263128/65714922-0ebe0480-e06a-11e9-84a1-5ebda62a20f6.jpg)

**Comment by YahnisElsts** [comment]
Make sure that the `Version:` header in the new version is correct. Mismatched version numbers could cause problems like this.

Also, how are you marking new versions - do you use tags, GitHub releases, a separate branch, or just update the version number in the `master` branch?

**Comment by bgrundon** [comment]
Yup, that did the trick - updated the version in the header, matched the release tag to that version and it found the update right away, thanks for the help
