### ISSUE TITLE
Multiple plugins

### ISSUE THREAD

**Issue by flowdee** [YahnisElsts/plugin-update-checker#32]
Using your update checker (and server) for all of my plugins. 

Unfortunately it doesn't work when 2 plugins are ready to be updated. After the first plugin is updated correctly, the second plugin seems to take the data from the first and will be removed from wordpress after the update, due to the fact, that the "original" plugin file (and all other files) are overwritten by the first one.

Any idea how to prevent this?

**Comment by YahnisElsts** [comment]
How exactly are the two plugins configured? Are you doing bulk updates, or updating the plugins one by one?

A few things to check:
- Double-check that each plugin has its own update checker instance and, a unique metadata URL, and that the correct file name is passed to the update checker constructor. 
- Verify that the "slug" field in the update JSON files returned by the server is unique to each plugin. 
- Verify that the ZIP file has the right structure (all plugin files inside a directory, directory name matches the install directory). 
- Verify that you're using the latest version of the update checker.
- Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and take a look at the "PUC (your-plugin-slug)" panels. Does everything look correct?

**Comment by YahnisElsts** [comment]
Any news on this? Did you find out what was causing the problem?

**Comment by flowdee** [comment]
What exactly do you mean with an own update checker instance? Example implementation for this? Right now I'm requiring the library directly in the main plugin file:

```
/* Plugin Update Checker */
require 'lib/plugin-update-checker/plugin-update-checker.php';

try {
	$MyUpdateChecker = PucFactory::buildUpdateChecker(
		'http://updates.flowdee.de/?action=get_metadata&slug=my-plugin',
		__FILE__, //Full path to the main plugin file.
		'my-plugin'
	);
} catch (Exception $e) {
	// do nothing
}
```

I'll validate the next few days and report my result.

**Comment by YahnisElsts** [comment]
I mean that each plugin should have a unique $updateChecker variable and a unique URL should be passed to `buildUpdateChecker`. For example, if one plugin uses `$MyUpdateChecker`, the other plugin should use `$AnotherUpdateChecker`. Yes, it sounds obvious, but it's still one of the things that I would check in a situation like this.

**Comment by flowdee** [comment]
ok thanks Yahnis! I'll check this and give you feedback as soon as possible.

**Comment by YahnisElsts** [comment]
Any news on this issue? Did you figure out what the problem was?

**Comment by flowdee** [comment]
it worked. Nothing to do with your app. Thanks bud
