### ISSUE TITLE
Question: is it possible to add the "Check for updates" link even for inactive plugins?

### ISSUE THREAD

**Issue by timvanuum** [YahnisElsts/plugin-update-checker#322]
We use statispress to make our plugins available through composer.
But with many plugins wordpress becomes slow with all those plugins active.

For satispress it's not necessary to have them active.
But without it being active the update checker link is gone.
And we need to enable all plugins to check for updates.

So as the title says is it possible to add the link with the plugin being inactive?

**Comment by YahnisElsts** [comment]
The update checker needs to be running to display the "check for updates" link, there's no way around that. However, technically you don't have to add the update checker to each individual plugin. You could instead have one plugin that handles updates for all of your other plugins. Then updates would work even if the other plugins were inactive.

PUC doesn't have any special support for this use case, so you would have to somehow detect which of your plugins are installed and then create an update checker instance for each plugin.

**Comment by timvanuum** [comment]
Thanks you for your comment. That's a great idea. We Will probably work something out. Thanks.

**Comment by anybodesign** [comment]
Hi @timvanuum I'm also interested in finding a way to update inactive themes or plugins… unfortunatly I'm not a developer so my skills are limited. Have you found some resources?
