### ISSUE TITLE
Spreading updates checks evenly throughout a day

### ISSUE THREAD

**Issue by DavidAnderson684** [YahnisElsts/plugin-update-checker#323]
This line - https://github.com/YahnisElsts/plugin-update-checker/blob/908249c92e81c46cb66e4d81632c5e917dc879ae/Puc/v4p8/Scheduler.php#L54 - `wp_schedule_event(time(), $scheduleName, $this->cronHook);` means that update checks on the updates server will not arrive spread evenly throughout the day. On the contrary, they will reflect the times of day when people activate plugins.

This basically means "working hours" - which is the time when the updates server (if it does other things, e.g. serve websites) is likely to be busy already.

On an analysis on our updates server for updraftplus.com, we found that the busiest hour (between 3pm and 4pm GMT) has 2.4 times more updates checks than the quietest hour (4am to 5am). Generally, it would be best if the updates check happened at a difference of 12 hours - this would mean more updates checks when people are not working, which means the server has the lowest load (change `time()` to `time() + 43200`). Another alternative would be to randomise it to go for an even spread across the 24 hours - `time() + rand(0, 86400)`;

I think that `time()` (i.e. "now") is used because there's the desire to trigger an immediate check. In that case, in the above suggestions, it should use minus instead of plug (e.g. `time() - 43200`).

Though, the above assumes a check interval of 24 hours, which may not be the case. I think the most general solution would be to randomise it over the check interval: `time() - rand(0, $this->checkPeriod * 3600`. But if you made it filterable, then individual plugin authors could then implement their own scheme (we'd then use it to prefer "night time").

**Comment by YahnisElsts** [comment]
Some thoughts:

- Checking for updates immediately after activation seems like a good thing to me. The user might have installed an outdated version of the plugin/theme and getting an update notification almost immediately instead of several hours later is probably better user experience.
    - I'm not sure how past timestamps work with WP Cron. Is there a risk it could just skip a scheduled event if the timestamp is too far in the past?
- It seems pretty easy to make the first check time filterable.
- Regarding "working hours" and making update checks happen in "night time":
    - Time zones make this complicated. Something as simple as "-12 hours" is not going to work reliably unless all of your users are in your time zone.
    - Since WP Cron is triggered by page loads, you'll still get more checks during active hours. To be fair, the difference could pretty minor.
    - Since PUC (and WP itself) check for updates more often when someone visits pages like "Plugins" and "Dashboard -> Updates", and those visits are more likely to happen during working hours, you'll get more checks during that time regardless of scheduling changes.

Personally, I think randomisation would be the best compromise, but I'd still like the first check to happen immediately.

**Comment by DavidAnderson684** [comment]
> I'm not sure how past timestamps work with WP Cron. Is there a risk it could just skip a scheduled event if the timestamp is too far in the past?

There's no risk. The WP cron code (which I'm very familiar with and have contributed to in WP core to try to fix some of its (many) issues, through the need scheduling reliable backups) nowhere compares the time with "now". It just gets all events that are due, and runs through them in order. So, scheduling a repeating task for "2 hours ago" is the same as scheduling for "now", except that that the next run will be sooner.

> Time zones make this complicated. Something as simple as "-12 hours" is not going to work reliably unless all of your users are in your time zone.

Whether they're in *my* time zone doesn't matter, because the updates server load doesn't depend upon the server owner's time zone; it depends upon the averaged distribution of the users. The "+ 12 hours" idea depends upon the users' time zones generally reflecting their working hours (and so, "+ 12 hours" generally means when they're *not* working). But, yes, I tend to agree with you that randomising over the check period is probably the best default. With a filter people (like us) who want a more specific strategy are still free to implement it. (And yes, people visiting the 'Plugins' or 'Updates' pages will trigger more "working hours" checks - but with the filter, we can still account for that; our algorithm will have a bias that takes account of current overall load over the 24 hours to try to even it out).

**Comment by YahnisElsts** [comment]
I've implemented randomisation using negative timestamps and added a `first_check_time` filter (full name: `puc_first_check_time-$pluginSlug`). The filter is passed one argument: the timestamp of the first check. You can return a different timestamp and PUC will pass it to `wp_schedule_event` without modification.

**Comment by DavidAnderson684** [comment]
Sounds great, thank you!
