### ISSUE TITLE
Install update from GitLab artifact

### ISSUE THREAD

**Issue by noplanman** [YahnisElsts/plugin-update-checker#326]
I'm busy looking into automated deployment of a private plugin and am using GitLab CI to do the plugin build. The final compressed plugin file is saved as an artifact.

Is there any way to direct PUC to check the artifact of a GitLab job and use that as the installation package?

Thanks :pray:

**Comment by YahnisElsts** [comment]
PUC currently doesn't have any built-in support for build artifacts. 

The best I can suggest would be to use the `puc_pre_inject_update-$slug` filter to replace the package download URL with the artifact's URL. The filter receives a `Puc_v4p8_Update` instance which has a `download_url` property. You could make a filter callback that sets a custom URL and returns the modified instance.

**Comment by noplanman** [comment]
@YahnisElsts thanks for your explanation and suggestion.

If I do move forward to use PUC I'll definitely give this a try :+1:
