### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by flagster-rgb** [YahnisElsts/plugin-update-checker#331]
Im getting a warning and an error here that crashes my website when the plugin checks for updates. The warning is :

`call_user_func_array() expects parameter 1 to be a valid callback, function 'add_secret_to_download_url' not found or invalid function name' at /home/www/swphdev.com/sandbox/intern/order-sign-clean/wp-includes/class-wp-hook.php 288:`

And the fatal error is :

`Call to a member function toWpFormat() on null in .... plugin-update-checker/Puc/v4p4/UpdateChecker.php on line 478`.

After some debugging i found out that on the line 478 of the UpdateChecker.php file, the function toWpFormat is called on null because the filter applied to the $update variable returns it null.

I've search around the web information regarding the puc_pre_inject_update hook but i cant find anything regarding to this.

Any ideeas how i can fix this ? Im using the 4.4 version of the update checker.

Later Edit :
I've tryied updating the updateChecker to the last version and im still getting the same error. If i comment the apply_filter line, the website works, the update is seen, but the update wont work, returning Forbidden error.

**Comment by YahnisElsts** [comment]
It sounds like a plugin is using the update checker incorrectly. Specifically, it looks like the plugin has configured the update checker to call the `add_secret_to_download_url` function when checking for updates, but that function doesn't actually exist. When the update checker tries to call the non-existent function, it triggers a warning, and when it tries to use the return value of the function, it crashes.

If you are the author of the plugin, try either removing the code that adds this non-existent callback or try implementing the `add_secret_to_download_url` function. If you are not the author, you could try asking the person who made the plugin to fix it.

**Comment by flagster-rgb** [comment]
I've looked trough the plugin code, and you are right.
The problem was, the function was declared under an IF statement. And the function would not exist. I moved the function at the end of the plugin file and now everything works as expected.

Thanks alot for your help and for the quick response !
