### ISSUE TITLE
Update badge shows up as expected in admin bar and sidebar, but no update option is presented

### ISSUE THREAD

**Issue by bookchiq** [YahnisElsts/plugin-update-checker#332]
I've added PUC to my plugin and connected it to a BitBucket private repo, and the signs were looking good—I released an update via the stable tag method and got a badge within WordPress letting me know there was an update.

However, when I followed the link from the admin bar to the general updates page, there were no updates listed. When I clicked through to the Plugins page from the sidebar, there are no plugins listed with available updates, and the specific plugin I updated (Yoko Co Extend) doesn't show any updates available directly on its listing.

I installed "Debug Bar" and, as best as I can tell, it looks like everything is working; it's picking up the update, has a valid download URL, etc.

Screenshots are below. Any idea what the issue could be?

![Debug data](https://user-images.githubusercontent.com/280882/72018034-cc38c600-321b-11ea-99fc-739fa817b669.png)

![No plugins with updates](https://user-images.githubusercontent.com/280882/72018033-cc38c600-321b-11ea-81ed-a622988339a4.png)

!["Yoko Co Extend" doesn't show any updates](https://user-images.githubusercontent.com/280882/72018032-cc38c600-321b-11ea-8a50-f870b4cd6866.png)

**Comment by YahnisElsts** [comment]
Thank you for including the screenshots. I think I see the problem in the Debug Bar output: the plugin file name is incorrect. 

When you call the `buildUpdateChecker()` method, you need to pass the full path to the main plugin file as the second argument. If the code that sets up the update checker is in the main plugin file then you can just use the `__FILE__` constant. However, if it's in a different file or a subdirectory, you'll need some other way to specify the file name.

For example, you could create a new constant in your main plugin file:
```php
define('MY_PLUGIN_MAIN_FILE', __FILE__);
```
Then you could pass the `MY_PLUGIN_MAIN_FILE` constant to `buildUpdateChecker()`.

**Comment by bookchiq** [comment]
You are 100% correct! That was the problem, and once I fixed it, everything is working beautifully. Thanks for creating this tremendously useful plugin, and especially for your prompt reply.
