### ISSUE TITLE
Fatal Error with Plugin Checker

### ISSUE THREAD

**Issue by zedley** [YahnisElsts/plugin-update-checker#335]
First of all, many thanks for your work — you absolutely make my life easier by several orders of magnitude. I had a strange problem when I got a new computer — I moved everything over, thought I set it up all the same for my local dev, but I kept getting this fatal error:

```
Fatal error: Uncaught Error: Call to a member function isMuPlugin() on null in /Users/dherman1/Sites/Wordpress/psu-plugins/psucom-updater/vendor/plugin-update-checker/Puc/v4p8/Plugin/UpdateChecker.php on line 316
```

I tried running it on PHP 7.2, 7.3 and 7.4, and got the same error every time. Here's the code I'm using to call the plugin checker:

```
$plugins = [  
    'newsroom-assimilator-client',  
    'newsroom-expiration-redirect',  
    'newsroom-ingestor-plugin',  
    'psucom-http-authentication',  
    'psucom-masks',
    'psucom-updater',
    'psucom-ufc'
];
$all_plugins = get_plugins();
foreach($all_plugins as $plugin_slug=>$info) {
    foreach($plugins as $psucom_plugin) if(strstr($plugin_slug,$psucom_plugin)) {
        $var_name = $psucom_plugin . '_update_checker';
        ${$var_name} = new \Puc_v4p8_Vcs_PluginUpdateChecker(
            new \Puc_v4p8_Vcs_GitLabApi('https://git.psu.edu/comweb/' . $psucom_plugin),
            realpath(__DIR__ . '/../' . $psucom_plugin . '/' . $psucom_plugin . '.php'),
            preg_replace('/-/','_',$psucom_plugin),
            12,
            'bb_'.preg_replace('/-/','_',$psucom_plugin)
        );
        ${$var_name}->setAuthentication('[redacted]');
        ${$var_name}->setBranch('deploy');
    }
}
```

And this had been working, but when I moved it all over it stopped working. I was using V4p4, I think — I updated to V4p8, same problem.

When I dug into the underlying code, I noticed that in Puc/V4p8/Plugin/UpdateChecker, the parent constructor function is never called (though it is in /Theme/UpdateChecker), which would explain why $this->package is never declared. When I added

`parent::__construct($metadataUrl, $pluginFile, $slug, $checkPeriod, $optionName, $muPluginFile);`

to line 37, it worked again. It's very possible that something in my code is what was actually causing the problem and this is a symptom, but I wanted to run it by you to see if you saw something I didn't, or to provide the fix if that is indeed the problem. Thanks again for all your hard work!

**Comment by YahnisElsts** [comment]
Thank you for the report. This sounds like it could be a bug. The class `Puc_v4p8_Plugin_UpdateChecker` does call the parent constructor ([see line 69](https://github.com/YahnisElsts/plugin-update-checker/blob/8212c5235ed96f955a6b178c68cacac8087dd15e/Puc/v4p8/Plugin/UpdateChecker.php#L69)), but it might need to call it earlier to make sure that `$this->package` is initialised by the time it calls `isUnknownMuPlugin()`. 

Could you please try moving that parent constructor call a few lines up, to line 58 or 59? I think it should be above this comment:
```php
//Backwards compatibility: If the plugin is a mu-plugin [...]
```

**Comment by zedley** [comment]
Oops, sorry, didn't look that far down because it was after the calling code! That fixes it. I moved it directly above that comment and it's working.

**Comment by YahnisElsts** [comment]
All right, I've just made the same change. This patch will be included in the next PUC release.
