### ISSUE TITLE
[Github] Authorization HTTP header instead of the `access_token` query parameter

### ISSUE THREAD

**Issue by dfinnema** [YahnisElsts/plugin-update-checker#337]
Currently, the update checker uses a legacy way to authenticate with Github. Please consider updating the API call with an Authorization HTTP header instead, as using the `access_token` query parameter.

Source
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by salih-cairs** [comment]
Getting mail regarding this from today morning.
`Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.`

**Comment by YahnisElsts** [comment]
I've just committed an experimental fix (see 3857481c65d7cb25b5a2fde3a21d22b4907aafcf). It's inspired by #338 but uses a different approach for handling downloads. It needs more testing. Please give it a try and let me know if you notice any issues.

**Comment by espiat** [comment]
Question: I only need to update my package with this actuall download?
-> https://github.com/YahnisElsts/plugin-update-checker.git

The code for config is same as before?
https://github.com/YahnisElsts/plugin-update-checker#github-integration

**Comment by YahnisElsts** [comment]
Yes, you only need to download the latest PUC code from the `master` branch. You don't need to change your update configuration.

**Comment by Akiletour** [comment]
@YahnisElsts Everything seems to be working perfectly with this fix.

**Comment by dfinnema** [comment]
@YahnisElsts Did some testing and all seems to be working now, no issues found on my end. Thanks for sorting this issue so quickly!

**Comment by espiat** [comment]
Yeah. Works like a charm.Many thanks.

**Comment by YahnisElsts** [comment]
Version 4.9 is out. If anyone still has the same problem with this release, feel free to reopen the issue.

**Comment by cpginfo** [comment]
I am using the latest available version, 4.10, and I am receiving emails warning about deprecated authentication on github. How should I do ?

**Comment by YahnisElsts** [comment]
Could it be that some of your users haven't updated and they are still using an older version?
