### ISSUE TITLE
What are the minimum scopes I should use in my Github access token

### ISSUE THREAD

**Issue by otakupahp** [YahnisElsts/plugin-update-checker#342]
I have added this scopes but I am not sure if they are enough:

  - read:packages
  - repo:status
  - repo_deployment

**Comment by YahnisElsts** [comment]
It needs access to the code in the repository. As far as I know, that requires the `repo` scope. It doesn't need the `read:packages` scope.

**Comment by otakupahp** [comment]
But the REPO scope seems a bit too much
![imagen](https://user-images.githubusercontent.com/26227907/74162489-dcfba380-4bee-11ea-958c-f9c4f7b69b31.png)

**Comment by YahnisElsts** [comment]
I agree. The update checker doesn't really need "full control" of the repository, and giving it that could be a security risk. Unfortunately, I don't know a way to give a token read-only access to the repository.

**Comment by otakupahp** [comment]
I'll leave with the actual 3 that I set and will tweak as needed

**Comment by YahnisElsts** [comment]
All right. If that works, please let me know.

**Comment by otakupahp** [comment]
Another question (I know that maybe I should open another issue).
How do I activate the release feature? it is not clear on the read me

**Comment by YahnisElsts** [comment]
Do you mean release assets: binary files that you can attach to your GitHub releases? To enable support for release assets, get the VCS API instance from the update checker instance and call the `enableReleaseAssets` method:
```php
$myUpdateChecker->getVcsApi()->enableReleaseAssets();
```
If you have multiple files per release, you choose which file(s) PUC will use by passing a regular expression to the `enableReleaseAssets` method.

Or did you mean releases as such? You don't need anything special to tell PUC to search for available releases. It will do that by default. If a repository contains both tags and releases, PUC wil prioritize releases.

**Comment by otakupahp** [comment]
I was talking about the second option. I understood it as you say but it is not working as expected.

Maybe I need to keep tweaking the access token

**Comment by otakupahp** [comment]
After some tests and reading documentation, the REPO scope is needed. That is a terrible security hole. However, I do not know any better option

**Comment by YahnisElsts** [comment]
A while ago I had the idea to create a proxy of sorts that would sit between end-users and GitHub/BitBucket/etc. It would get update information from private repositories and then present it in the JSON-based format that PUC already understands. This way you would only need to entrust your access credentials to one site/app, not to everyone who uses your plugin. It could also have some side benefits, like generating aggregate statistics like update requests per day.

I'm still not sure how much demand there is for something like that.

**Comment by otakupahp** [comment]
There is a service that already does that kernl.us 

I pay them a monthly fee and I only need to add 1 file to handle the update; however, I need to support many private plugins and the cost is prohibitive for me.

**Comment by YahnisElsts** [comment]
Interesting. Can you elaborate on the cost (assuming that disclosing this info is not forbidden by their ToS or some such)? I don't see any pricing details on their site.

**Comment by otakupahp** [comment]
If you scroll down you could see them.

![imagen](https://user-images.githubusercontent.com/26227907/74442402-70c3ae80-4e3f-11ea-8eca-6e857ef8a6ae.png)

My current requirement is to have unlimited plugins updated from my private repos in GitHub. But this is very specific in my case

**Comment by otakupahp** [comment]
At the moment my best option is to fork your plugin, trim it to fit my needs, create an additional plugin locally to handle the Github token

**Comment by YahnisElsts** [comment]
Oops, not sure how I missed that. My bad.

> At the moment my best option is to fork your plugin, trim it to fit my needs, create an additional plugin locally to handle the Github token

My `wp-update-server` repository has some code might be useful when building your own update provider:
https://github.com/YahnisElsts/wp-update-server/

**Comment by otakupahp** [comment]
Great, I'll take a look too...

I would like a 1 file updater solution (as I told you, I hate to have files I do not use as that increase the plugin size) added to the plugin, plus a few lines configuration in the main class.

In my server, I would like just to handle the Github connection and archive download.

If it could be done easy, great, if no... I will wait for your service :)

**Comment by YahnisElsts** [comment]
How about a [phar](https://www.php.net/manual/en/intro.phar.php) file? I haven't really used Phar before, but it looks like it could be a convenient way to bundle the PUC library into one file. It might even be possible to make a generator lets you easily build a custom phar file that only contains the features that you actually need.

**Comment by otakupahp** [comment]
If you could trim it, that would be great. I haven't used a phar before neither so I do not know how small it could be

**Comment by YahnisElsts** [comment]
Here, try this:
https://w-shadow.com/puc-builder/

**Comment by otakupahp** [comment]
That's awesome!

Thanks for doing that.

One last question. How works the PHP 5.2 compatibility?

**Comment by YahnisElsts** [comment]
That just adds a legacy version of the [Parsedown](https://parsedown.org/) parser. Without it, the update checker will crash if it ever needs to parse a Markdown file on PHP 5.2.

**Comment by YahnisElsts** [comment]
By the way, the "Debug Bar" option currently may not work properly, so I would recommend disabling that.

**Comment by otakupahp** [comment]
Cool, I'll just use the plugin and GitHub support

**Comment by MichelleBlanchette** [comment]
I was also concerned about the security of using a PAT since I'll be providing my (private repo) WordPress plugin publicly. The [current access scopes](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps) are obviously an immense security risk since it would allow the token holder to have:
> ...full access to private and public repositories. That includes read/write access to code, commit statuses, repository and organization projects, invitations, collaborators, adding team memberships, deployment statuses, and repository webhooks for public and private repositories and organizations. Also grants ability to manage user projects.

However, I found [this helpful article](https://www.openshift.com/blog/private-git-repositories-part-3-personal-access-tokens) that discusses creating a "machine user" and granting the account read-only access to limited repositories. Here's a great summary of the current security concern with using GitHub PATs:

>At this point in time, GitHub doesn't provide a way of setting the scope of a personal access token such that it has read-only access to repositories. Instead, one has to enable the repo scope which gives full control of private repositories.
>
>Giving full control is not ideal as it means that anyone who gets control over the personal access token would also be able to write to any repositories the account has write access to. This is one of the reasons why read-only repository SSH keys bound to a specific repository are preferred.

**Comment by otakupahp** [comment]
That would be great!
