### ISSUE TITLE
Please use the Authorization HTTP header instead, as using the `access_token` 

### ISSUE THREAD

**Issue by oempire** [YahnisElsts/plugin-update-checker#345]
Have updated to the latest but still getting alerts for this

Please use the Authorization HTTP header instead, as using the `access_token`

**Comment by YahnisElsts** [comment]
The latest release contains no references to `access_token` except one mention in a comment, so it seems very unlikely that it could be the thing that's still using this query parameter. Could it be that some of your users still have an older version of your plugin or theme and that is using an old version of PUC?

**Comment by oempire** [comment]
Ahhh i know! its another plugin i have that uses this aswell. Sorry about that ill make sure all copies get updated
