### ISSUE TITLE
Got an error when deactivating the plugin

### ISSUE THREAD

**Issue by otakupahp** [YahnisElsts/plugin-update-checker#346]
Hello, me again.

I am using your Phar file but I am having some issues.

First, I had to use the .tar instead of the .tar.bz2 since my local PHP argued that BZip compression was needed and since it is a WP plugin, I do not know if it will be active in all systems that use the plugin.

I also get an error when deactivating the plugin:

![imagen](https://user-images.githubusercontent.com/26227907/75100974-940afe00-55a3-11ea-9a5a-7241be1e4f9c.png)

If I access wp-admin again it loads normally but the plugin is still active. If I deactivate it again, it is deactivated.

**Comment by YahnisElsts** [comment]
Gzip compression is also an option. It requires the Zlib extension. I'm not sure how common that is; I've seen some conflicting statements about it being enabled/disabled by default.

As for the error, it looks like this is a problem with the autoloader. It uses [`realpath()`](https://www.php.net/manual/en/function.realpath.php) when loading certain classes and `realpath()` doesn't work inside a Phar. I just committed a patch for this, but I can't add it to the Phar generator without making a full release. Try just replacing the file `Puc/v4p9/Autoloader.php` in your .tar archive with the version from the master branch.

**Comment by otakupahp** [comment]
Thanks for your work on this. I tried in with the full library and it works, I'll test with the solution you suggest

**Comment by otakupahp** [comment]
I want you to know that I got errors sending the tar file to GitHub, it marked it as corrupt so I used the folder. 

Also, your fix did not work:
```
$this->libraryDir = $this->rootDir . '../..';
if ( !self::isPhar() ) {
    $this->libraryDir = realpath($this->libraryDir);
}
$this->libraryDir = $this->libraryDir . '/';
```

**_self::isPhar()_** was not recognized and gave me an error.

However, the option to choose what to include helped a lot.

Thanks for your great package.
