### ISSUE TITLE
conflict with "rise" theme 

### ISSUE THREAD

**Issue by robertharm** [YahnisElsts/plugin-update-checker#35]
Hi Yahnis,

I discovered that there is an issue when using your plugin-update-checker together with the "rise" theme from http://thrivethemes.com/, showing the following error in the dashboard:

Warning: The URL http://members.thrivethemes.com/plugin_versions/content_builder/update.json?checking_for_updates=1&installed_version=1.100.1 does not point to a valid plugin metadata file. WP HTTP error: Could not resolve host: http (Domain name not found) in /(wp-content/plugins/leaflet-maps-marker-pro/inc/class-plugin-update-checker.php on line 248

it seems that the GET parameter checking_for_updates is also used by the theme and causing this issue.

Perhaps renaming checking_for_updates to puc_checking_for_updates would solve this and any further related issues...
best,

Robert

**Comment by YahnisElsts** [comment]
I'm reluctant to break backwards compatibility just to work around a buggy theme.

Look at it this way: you *could* rename the query parameters and force everyone who uses them to update their code, but who's to say that the new URL won't conflict with some other buggy theme or plugin? Maybe another theme uses the same path suffix ("_versions") or file name ("update.json"), or looks for a "members." prefix in the domain name. Maybe some poorly written plugin breaks all HTTP requests that use a particular timeout setting or where the URL is more than 100 characters long. 

Would it really be a good idea to stuff a plugin full of workarounds for every buggy WordPress product out there?

**Comment by robertharm** [comment]
did not think about that changing that parameter would break backward compatibility - if that is the case, I wouldnt change this either. Just thought, I let you know about this issue. Will contact the theme developer instead and tell him about this issue...

**Comment by YahnisElsts** [comment]
Yeah, if `plugin-update-checker` was a brand-new library I would probably just change the parameter and be done with it. However, "checking_for_updates" and "installed_version" were introduced more than two years ago. There are probably developers who rely on them. In this case, contacting the theme author seems like the best approach.
