### ISSUE TITLE
Update Checker not working with Easy Updates Manager plugin

### ISSUE THREAD

**Issue by abuyoyo** [YahnisElsts/plugin-update-checker#353]
I have several plugins using this library to update from private repos.
The plugins are set-up properly and work as expected when updating manually from the `plugins.php` screen. The plugins also update properly when updating them manually from the default WP Admin `update-core.php` page.

I also have [Easy Updates Manager](https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/) plugin installed and activated.

Easy Updates is set on my installation as ‘Custom’ and ‘Choose per plugin’.
The plugins using `plugin-update-checker` are set to ‘Plugin Updates: Allowed’ and ‘Automatic Updates: On’ in the Easy Updated Manager Plugins tab.

However running `wp_update_plugins` WP-Cron event does not update the plugins.
I've opened [an issue on the Easy Updates Manager plugin's support page](https://wordpress.org/support/topic/easy-updates-manager-not-working-with-github-updater/) about this and am cross-posting here.

Interestingly, 
I also have a private repo theme using PUC library - and the theme DOES update automatically with the Easy Updates Manager plugin.

**Comment by YahnisElsts** [comment]
I'm not familiar with how Easy Updates Manager works internally, so this is a guess: are your plugins active and loaded when Easy Updates Manager tries to install updates? Since the PUC library is part of your plugin, updates will only work while the plugin is running. If EUM performs updates in some kind of a special context where it's the only plugin loaded, it won't see your updates. Similarly, if you've attached the PUC initialisation code to a particular hook and EUM inadvertently prevents that hook from running, updates also won't work.

**Comment by abuyoyo** [comment]
The plugins are active. 
And as far as i know EUM just filters the default WordPress auto-update processes but it doesn't run the updates themselves. WordPress core runs the updates - `wp_update_plugins` and `wp_update_themes` WP-Cron jobs.
EUM just removes or adds plugins to/from those Cron jobs.
EUM does not have any custom Cron jobs.

I've written a simple test plugin that literally only updates itself (and is active). No hooks, filters. etc.
I version bump it just to test the updater. Manual updates work perfectly (also they get logged by EUM as 'manual') but `wp_update_plugins` skips the plugin
.
I also had a hunch that this issue is on the EUM end of things, but diligence dictated I post here as well. Especially since I found out EUM *DOES* update themes using the PUC library.
```
/**
 * Plugin Name: Test Plugin2
 * Description: This plugin is used to test github update checker.
 * Plugin URI: https://github.com/abuyoyo/test-plugin2
 * Version: 1.0.1
 */
use YeEasyAdminNotices\V1\AdminNotice;

$test_plugin2_data = get_plugin_data( __FILE__ , false );

Puc_v4_Factory::buildUpdateChecker(
	$test_plugin2_data['PluginURI'],
	__FILE__,
	'test-plugin2'
)->setAuthentication($github_oauth); // private repo

AdminNotice::create()
	->success("Test Plugin2 is now at version {$test_plugin2_data['Version']}")
	->dismissible()
	->show();
```

**Comment by YahnisElsts** [comment]
I tried to reproduce the issue today. I have a basic plugin in a private GitHub repository just for testing PUC updates. After a bit of debugging, I was able to get the plugin to update itself. Here's what I did:

1. Install Easy Updates Manager 9.0.1.
2. Go to EUM settings and change "Plugin updates" to "Choose per plugin". 
3. Find my plugin in the "Plugins" tab and change "Automatic Updates" to "On".
4. Verify that the update is showing up under "Plugins -> Installed Plugins".
5. Go back to EUM, switch to the "Advanced" tab, select "Force automatic updates" and click "Force updates".

Initially, this did not work. After some debugging and adding some `error_log()` statements to WordPress core files, I figured out why: WordPress will block a background update if the thing being updated _or the WordPress root directory_ looks like a VCS checkout. It looks for a few known subdirectories like `.git`, `.svn` and so on to determine this. After I disabled this check for my plugin, the "Force updates" button worked as expected and my plugin was updated.

Could it be that your plugin directory or the WP root directory also contains some Git or SVN subdirectories and that's what prevents updates from working?

**Comment by abuyoyo** [comment]
Thanks for the time spent trying to debug this issue. Much appreciated.
I did what you instructed - and it works. But the issue is not the configuration/source control subdirectories. I have none. "Force Update" is still a manual process, Much like updating from WP core's plugins page or `update-core.php` page. Pretty much invalidates what I need the EUM plugin for (automatic updates).

I'm hoping EUM support will find a solution for this. I'm fairly confident at this point the problem is either the EUM plugin or maybe something about how WP-cron operates on my specific installation. Will investigate further.

Again, thanks for your time and help.

ps.
Found this:
```
add_filter( 'automatic_updates_is_vcs_checkout', '__return_false', 1 );
```

**Comment by YahnisElsts** [comment]
I used "Force updates" to speed things up while debugging. I assumed that updates would work the same way if I waited for the relevant cron job to trigger, but I admit I didn't actually test that.

If you have the time, maybe you could try adding some logging code to `/wp-admin/includes/class-wp-automatic-updater.php`? This might help figure out what happens when WordPress attempts an automatic update on your site. For example, I discovered the VCS issue by adding some `error_log()` statements to the `should_update` method.

**Comment by DavidAnderson684** [comment]
All plugins that we've seen to date that EUM doesn't automatically update are ones that add their updating code only in response to `admin_*` hooks. i.e. Only for logged-in pages in the admin area. So the fault isn't in `plugin-update-checker` or EUM, but in the plugins that are not hooking in most of the time.

**Comment by abuyoyo** [comment]
@DavidAnderson684
Thank you for that. I've not tested this yet, but what you wrote might well be the cause.

My plugins do indeed call `Puc_v4_Factory::buildUpdateChecker` on `admin_init` (priority 9)
Right before 'Puc_v4p8_Scheduler->maybeCheckForUpdates()` that hook on  `admin_init` priority 10 - which for some reason I thought was the right way to go.
I understand now that PUC's checking for updates might be a separate concern/event.

Thank you both for helping me debug this. I'll update with results.

**Comment by abuyoyo** [comment]
Problem solved.
The issue was not with PUC or EUM. It was with all due to my plugins hooking `buildUpdateChecker` on `admin_init`.

Also, just spent a couple of hours trying to debug/error_log `wp_update_plugins` only to find out `wp_version_check` does the automatic updates. Who knew.
