### ISSUE TITLE
"tested" : "5.4" becomes "Compatible up to: 5.4.999"

### ISSUE THREAD

**Issue by galbaras** [YahnisElsts/plugin-update-checker#356]
The value "5.4" in the "tested" field is translated to "5.4.999" in the plugin details view in WordPress.

This does not happen with wp.org plugins. They just show "5.4". Also, setting "requires" to "5.2" shows "5.2" in WordPress just fine.

**Comment by YahnisElsts** [comment]
This is a known trade-off of the algorithm that PUC uses to imitate a wordpress.org feature that automatically changes the "tested" version to match the latest patch version. For example, if you have a plugin on wordpress.org and you set the "Tested up to" field to "5.3", wordpress.org will show it as "5.3.2" instead.

The update checker doesn't know what the latest version is in every WordPress branch, so it uses some heuristics to guess the patch version, and, if that doesn't work, it uses ".999" as a fallback.

**Comment by galbaras** [comment]
Fallback should be "0", then. If it should be something else, that something else needs to be tested first, and then specified.

Using 999 means allowing the update when it may not be compatible.

**Comment by YahnisElsts** [comment]
Using "0" as the fallback would mean that in the future updates that are tested up to 5.4 would show up as incompatible on the "Dashboard -> Updates" page when the site is running WP 5.4.1. This would also be inconsistent with the default wordpress.org behaviour where it automatically changes "5.x" to "5.x.y" (y = latest patch version). 

One thing that I could do is to improve the way that PUC behaves when the latest WordPress release doesn't actually have a patch version number (e.g. "5.4"). Right now PUC will change it to 5.4.999, but 5.4.0 or maybe even 5.4 would work fine (probably; requires testing).

**Comment by galbaras** [comment]
When a new core version comes out, for which the plugin hasn't been tested, it is correct for WordPress to flag this. If wp.org fudges this information, that's not a good thing, and you shouldn't either.

I vote for "5.4", because that's what human users will expect to see.

**Comment by RichardCoffee** [comment]
One way that could be checked is to `explode( '.', $wp_version )`.  If the count on the resulting array is 2, then don't add a patch version.

**Comment by YahnisElsts** [comment]
I've just committed a change that will leave the `tested` field unmodified if it already matches the installed/latest WP release and that release doesn't have a patch number (e.g. "5.4"). It will still add a ".999" suffix when `tested` refers to an old WP release like 5.2.

**Comment by galbaras** [comment]
Makes sense, although if I'm on 5.4 and the plugin is tested up to 5.2 or 5.2.999, there's no practical difference.

Thank you!

**Comment by bouveng** [comment]
Sorry for bumping this.. but, great plugin!
Thanks for the commit fixing this.

Br.
