### ISSUE TITLE
Bitbucket issues for theme updates

### ISSUE THREAD

**Issue by kaitwalla** [YahnisElsts/plugin-update-checker#357]
I noticed this issue while running routine updates; I was on 4p6, updated to 4p9 but still had the same issues.

The code hasn't changed; here's the loop I run for my themes:

```
$themes = array(
    'theme1',
    'theme2',
    'theme3'
);

foreach ($themes as $theme) {
    $var_name    = $theme . '_update_checker';
    ${$var_name} = new \Puc_v4p9_Vcs_ThemeUpdateChecker(
        new \Puc_v4p9_Vcs_BitBucketApi('https://bitbucket.org/USERNAME/' . $theme . '/', $credentials),
        $theme,
        $theme
        );

    ${$var_name}->setBranch('deploy');
}
```

For what it's worth, I only use the theme version + branch for updates. Here are the errors I'm getting:

```
1) cURL error 56: OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0

Error code:
    http_request_failed

2) cURL error 56: OpenSSL SSL_read: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading, errno 0

Error code:
    http_request_failed

3) Could not retrieve version information from the repository. This usually means that the update checker either can't connect to the repository or it's configured incorrectly.

Error code:
    puc-no-update-source
```

I did check to make sure that the theme URL is correct. Any ideas or help would be greatly appreciated!

**Comment by YahnisElsts** [comment]
It looks like this could be related to an issue with a recent cPanel upgrade that somehow prevents PHP scripts from making SSL connections. See this thread:
https://forums.cpanel.net/threads/openssl-errors-in-php-scripts-after-upgrade-to-86-0-17.669905/
