### ISSUE TITLE
Code spacing when updating a plugin

### ISSUE THREAD

**Issue by misulicus** [YahnisElsts/plugin-update-checker#36]
I notice on a test site after i used the plugin updater that the source code of the plugin in discussion got some extra spaces

Something like 
```
$var = 123;
$newvar = 234;
```
became
```
$var = 123;

$newvar = 234;
```

any ideas ?

**Comment by YahnisElsts** [comment]
That looks like a line break problem. As you probably already know, different OS have different line break conventions. Most Unix-like systems use `\n` (LF), Windows and some other systems use `\r\n` (CR LF). If some of the software that you use doesn't know how to properly handle both standards, or if it's not configured correctly, you can end up with duplicate line breaks.

For example, some FTP software can cause this problem:
http://stackoverflow.com/questions/554960/how-can-i-stop-filezilla-changing-my-linebreaks

Overall, this is probably not directly related to the plugin updater. When WordPress updates a plugin, it doesn't mess with the source code. It just installs the new files and deletes the old ones. The `plugin-upate-checker` itself never modifies plugin files - it just retrieves update information and passes it to WordPress.

**Comment by YahnisElsts** [comment]
Bump. Did you ever figure out what was causing the extra spaces?

**Comment by misulicus** [comment]
Not really no. didn`t had the time to investigate that.
I guess you can close this for now.
Thanks

**Comment by YahnisElsts** [comment]
All right, closed. Feel free to reopen the issue if you find anything.
