### ISSUE TITLE
Plugin always finding new version

### ISSUE THREAD

**Issue by Bergmam** [YahnisElsts/plugin-update-checker#364]
I have a problem where my Wordpress plugin is always finding a new version, even though I just updated to for example v1.1.5, it still recognizes v1.1.5 as a new update and tells me there's a new version of my plugin available. 

What could I have missed?

**Comment by YahnisElsts** [comment]
Make sure that the version number in the plugin header (e.g. `Version: 1.2.3`) matches the version number in the JSON file or the Git tag/release name. If the version number in the plugin header is lower, the update checker will keep reporting that an update is available.

**Comment by RichardCoffee** [comment]
I've run into that exact same problem, and yes, it was my fault. :)

**Comment by Bergmam** [comment]
> Make sure that the version number in the plugin header (e.g. `Version: 1.2.3`) matches the version number in the JSON file or the Git tag/release name. If the version number in the plugin header is lower, the update checker will keep reporting that an update is available.

That fixed it! thanks!
