### ISSUE TITLE
Wordpress Update

### ISSUE THREAD

**Issue by stingray82** [YahnisElsts/plugin-update-checker#365]
Hi, Thanks for the code it has been a real help to me, I modified it some time ago into a plugin I can activate and deactivate to update all my hosted plugins on my sites but when it's activated it blocks wordpress.org updates with that in mind I have just been deactivating it, I now have a little time and was wondering if I could fix this issue.

My working code is here: https://github.com/stingray82/ninja-updater/blob/master/ninja-updater.php

Ideal I'd like it to check my repo if it's not in my repo to check and update it from the official update / wordpress.org my issue is I don't understand enough about wordpress.org update protocols and everything I google just brings me back here.

It would be even better if it could compare my repo to the official version and install the newer.

I was wondering if you could point me in the right direction as I am not having much luck

Thanks
Nathan

**Comment by YahnisElsts** [comment]
I think the [`Puc_v4p9_UpdateChecker::injectUpdate()`](https://github.com/YahnisElsts/plugin-update-checker/blob/4e0d4ade4659ca3ccaf0023cae7d3aec11113259/Puc/v4p9/UpdateChecker.php#L512) method is what you might want to look at. That's where the update checker removes stale updates and updates provided by other services like wordpress.org. Something as simple as commenting out this line might work:
```php
$updates = $this->removeUpdateFromList($updates);
```

Alternatively, you could add some extra code to check if the update is from wordpress.org (e.g. by looking at the download URL) before deciding whether you want to remove it or not.

**Comment by stingray82** [comment]
@YahnisElsts 
The first option would work, I've simulated testing, and it appears to do what I need, 

I'd prefer an option where I didn't need to edit your code, if possible so I can just drop in the update when you release one, not sure how that would look, but will take a look  at your second suggestion, thank you I will probably be back as I haven't found anyone as knowledgable on the update regime 

Now, this is the second time I've been assisted by you, can I buy you a drink? let me know how to go about doing that as if I can get this working as I want it to with MainWP it is going to save me so much time.

**Comment by stingray82** [comment]
Thanks Again, 

Donation sent, I think this could be beyond my ability but will have a read and see what I come up with

Thank you again
