### ISSUE TITLE
Can this work with themes too?

### ISSUE THREAD

**Issue by benallfree** [YahnisElsts/plugin-update-checker#37]
Just wondering if there is anything newer than the 2011 blog post.

**Comment by YahnisElsts** [comment]
Do you mean this post?
http://w-shadow.com/blog/2011/06/02/automatic-updates-for-commercial-themes/

As far as I know, that library still works. I have it installed on a test site running WP 4.4-alpha and the updates show up correctly.

**Comment by benallfree** [comment]
Thanks. Are you the author of both? I can't find a git repo of the theme version.

**Comment by YahnisElsts** [comment]
Yes, I'm the author. At the moment there is no public repository for theme update checker. It's less popular than the plugin version, so I haven't taken the time to migrate it from my private SVN repository.

**Comment by benallfree** [comment]
Thank you. I don't plan on making any modifications to the theme library but if you wanted to throw it into a github repo I'd be happy to send pull requests for anything I do.

I'm surprised it's not getting more attention from premium theme developers. It's a perfect solution.

**Comment by YahnisElsts** [comment]
All right. Maybe I'll get around to that eventually.

**Comment by jacquesletesson** [comment]
@YahnisElsts Would love to see it for theme also! Great work by the way.

**Comment by delucis** [comment]
I’d love to know what the differences are between theme & plugin updating. Hoping to get the theme updater to work with GitHub.

**Comment by YahnisElsts** [comment]
If I recall correctly, the general process is the same, but there's a whole bunch of minor differences - different update fields, different hooks used to display the updates, and so on. I'm not sure how much of the existing code can actually be reused.

**Comment by delucis** [comment]
Thanks — I got the old theme update checker working with GitHub releases fairly easily, but would be interested in the more complete features here.

**Comment by cscheltinga** [comment]
Had the old theme-update checker, which was pretty awesome! Would love to see it again :-)

**Comment by YahnisElsts** [comment]
I'm working on this in a the [theme-support branch](https://github.com/YahnisElsts/plugin-update-checker/tree/theme-support). It's unfinished, but feedback is welcome.

**Comment by YahnisElsts** [comment]
Update: Version 4.0 has been released and it includes support for theme updates. See the updated readme for usage instructions.

**Comment by stallionseo** [comment]
Been using the old code in a premium theme (Stallion Responsive) for years, not had any major issues (still working in 4.9 alpha). I run the theme on 70+ of my own domains and updates are just like with themes in the WordPress theme repo. About to use the plugin version on a plugin and saw this, guess I need to check out the latest theme code as well to see what's changed and if it's worth a theme update as well.

**Comment by YahnisElsts** [comment]
There are a lot of internal changes and some extensibility improvements, but, if I recall correctly, they're all fairly general and not specific to themes.

**Comment by Remzi1993** [comment]
@YahnisElsts IMHO you should close some issues so that you could focus on the ones who are open and relevant.
