### ISSUE TITLE
How do we know if the checker is "checking"?

### ISSUE THREAD

**Issue by commadelimited** [YahnisElsts/plugin-update-checker#377]
I'm new to WP development and I was excited to find this plugin updater. I believe I've implemented it properly but I'm not sure. I've included the `enableReleaseAssets` method call and my repo is several versions ahead of what's currently installed in Wordpress. But I'm not being told that there's an upgrade. Is there a way for me to force an update check, or see the output of the call when it's being made?

Does this plugin only activate the update checker when it's installed for the first time?

**Comment by YahnisElsts** [comment]
I would recommend using the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin to view the status of the update checker. The "PUC (your-slug)" section in the debug bar should show the last check time, the next check time, cached update details, and more. It also has a "Check Now" button that you can use to force an update check.

> Does this plugin only activate the update checker when it's installed for the first time?

By default, it will check for updates every 12 hours. It will check more often when you visit certain admin pages, e.g. "Dashboard -> Updates" (this is what WordPress itself does and PUC tries to emulate that).

**Comment by commadelimited** [comment]
@YahnisElsts Thanks. The 12 hour time frame was the main question I had. I was finally able to get it working properly. As long as there's a "check for updates" button, that's fine for development. Thank you.
