### ISSUE TITLE
how the correct structure of files on repository?

### ISSUE THREAD

**Issue by madeinnordeste** [YahnisElsts/plugin-update-checker#382]
I'm learning how to update plugins, but have a question. How the correct structure files of plugin on repository:

**repository A:**

    - readme.txt
    - my-plugin.php

**repository B:**

    -  my-plugin/
            - readme.txt
            - my-plugin.php

Thanks a lot

**Comment by YahnisElsts** [comment]
Option A is the correct choice for this update checker. It currently doesn't support option B.

**Comment by madeinnordeste** [comment]
> Option A is the correct choice for this update checker. It currently doesn't support option B.

Thanks @YahnisElsts !
