### ISSUE TITLE
Problem update when using a child theme

### ISSUE THREAD

**Issue by Djomobil** [YahnisElsts/plugin-update-checker#385]
I've a problem, when i active my template child, he try to update the child theme with the parent from my depot gitlab

Gitlab : 
2 depots : 
 - poka_v2 (Version 999.1.2)
![Capture d’écran 2020-08-10 à 14 07 24](https://user-images.githubusercontent.com/11764599/89781091-f4bad280-db12-11ea-85f1-bc4521a9144c.png)

 - poka_v2_child (Version 999.1.1)
![Capture d’écran 2020-08-10 à 14 06 54](https://user-images.githubusercontent.com/11764599/89781099-fa181d00-db12-11ea-878d-eb4377bcb77e.png)

On my wordpress: 
I've installed my Themes :
 - poka_v2 (parent)
![Capture d’écran 2020-08-10 à 14 09 57](https://user-images.githubusercontent.com/11764599/89781231-364b7d80-db13-11ea-9343-4e16b72a2f2d.png)

 - poka_v2 (child theme)
![Capture d’écran 2020-08-10 à 14 09 39](https://user-images.githubusercontent.com/11764599/89781234-38154100-db13-11ea-8712-9cf1856cf536.png)

But the problem is, when he try to check an new update, he detect an update from the parent theme.
Debug screen :
![Capture d’écran 2020-08-10 à 14 04 17](https://user-images.githubusercontent.com/11764599/89780967-b58c8180-db12-11ea-876a-c3d43ed1436d.png)

Can you explain me how can i fix

**Comment by YahnisElsts** [comment]
It might be that the update checker is not fully configured. Could you please show the code that you use to initialise the update checker in the child theme? Feel free to edit out any secret keys or domain names.

**Comment by Djomobil** [comment]
in the function.php (poka_v2_child)
```php
add_action('after_setup_theme', function() {
    if (function_exists('plugin_update_checker')) {
        plugin_update_checker(__FILE__);
    }
});
```

all themes use this code (parent/child)


in the file plugin-update-checker.php

```php
function plugin_update_checker($file) {
  require __DIR__."/PUC/plugin-update-checker.php";

  $partial_url = explode('/', $file);
  $dump = array_pop($partial_url);
  $partial_url = array_slice($partial_url, -2, 2, false);
  $slug = $partial_url[1];
  $partial_url = $partial_url[0]."/".$partial_url[1];

  // $myUpdateChecker->setAuthentication('********);
  // $myUpdateChecker->setBranch('master');
  // return;
  if ($partial_url[0] == "p") {
    $myUpdateChecker = new Puc_v4p9_Vcs_PluginUpdateChecker(
      new Puc_v4p9_Vcs_GitLabApi('https://gitlab.domain.tld/private-group/wordpress/plugins/'.$slug.'/' , null, 'wordpress/plugins'),
      $file,
      $slug
    );
  } else if ($partial_url[0] == "t") {
    $myUpdateChecker = new Puc_v4p9_Vcs_ThemeUpdateChecker(
      new Puc_v4p9_Vcs_GitLabApi('https://gitlab.domain.tld/private-group/wordpress/themes/'.$slug.'/' , null, 'wordpress/themes'),
      null,
      $slug
    );
  }
    $myUpdateChecker->setAuthentication('*********');
    $myUpdateChecker->setBranch('master');

  

}
```

**Comment by YahnisElsts** [comment]
That's pretty complicated, but I think I understand what's going on. Most likely, the problem is in this part of the code:

```php
 $myUpdateChecker = new Puc_v4p9_Vcs_ThemeUpdateChecker(
      new Puc_v4p9_Vcs_GitLabApi('https://gitlab.domain.tld/private-group/wordpress/themes/'.$slug.'/' , null, 'wordpress/themes'),
      null, // <--- Don't leave this set to NULL when in a parent theme.
      $slug
    );
```

The second constructor argument is supposed to be the theme directory name, like `poka_v2` or `poka_v2_child`. When you set it to `NULL`, the update checker will call `get_stylesheet()` and use the directory name returned by that. Since `get_stylesheet()` always returns the _child theme_, this means the update checker will use the same directory name for the parent theme and the child theme. I'm not sure what exactly will happen when you have two different update checker instances associated with the same theme, but it's virtually certain to cause problems.

Try replacing that `null` with the theme directory name. If I've understood your code correctly, you could use `$partial_url[1]` here.

**Comment by Djomobil** [comment]
That okay thank for informations 👍
