### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by halilkabaca** [YahnisElsts/plugin-update-checker#388]
Hello,
I am trying to implement it on my plugin and I am using the GitHub integration (private repo with a personal access token). Somehow the update checker always shows the plugin is up to date even when I try to manually check for updates.

I have tried using GitHub releases or specific repo for releases and couldn't get it to work. How can I debug it to understand where the issue is? I enabled WP_DEBUG but I couldn't see anything logged.

Looking forward for your answer.
Regards

**Comment by YahnisElsts** [comment]
I would recommend trying the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin. The "PUC (your-slug)" panel in the debug bar should show a bunch of useful debugging information like the last update check time, cached update information, and so on. 

It also has "Check Now" and "Request Info" buttons - try clicking them and see if any errors show up. Normally, the update checker doesn't show HTTP errors that it encounters when trying to retrieve plugin information from a repository, but it will show them if you initiate the request from the Debug Bar.

**Comment by halilkabaca** [comment]
Thank you very much for the fast response, I manage to solve it with the Debug Bar plugin :)

**Comment by tkc49** [comment]
@halilkabaca 

If you push your personal access token to Github, the personal access token may have been removed from your Github settings.
Please check.
