### ISSUE TITLE
AddqueryArg without a filter

### ISSUE THREAD

**Issue by misulicus** [YahnisElsts/plugin-update-checker#39]
ok so my plugin before running the `PucFactory::buildUpdateChecker` is doing a check to see if its "legit" to run

Once the plugin is legit to run it runs the update checker code.
At the moment i got something like 
```
$update_checker->addQueryArgFilter('my_function');
```

The thing is `my_function` does the exact same check that the PucFactory initialization "legit". I`m wondering if for example something like this might work and if not how to use the queryargfilter without the "callback" function
```
$update_checker->addQueryArgFilter( $my_array );
```

**Comment by YahnisElsts** [comment]
Currently there is no way to use `addQueryArgFilter` without a callback.

Why do you need a "is it legit?" check in `my_function` when you've already established that before initializing the update checker? What is the benefit of doing the exact same check again?

**Comment by misulicus** [comment]
The first check verifies if the current Plugin has a license key added to the website. 
On the callback function it does the same thing but also adds the license key to the params.
I could not see a way to pass the license key directly in the updater initialization

**Comment by YahnisElsts** [comment]
Correct me if I'm wrong, but it seems that the callback function doesn't need to verify if the plugin has a license key. You've already verified that before adding the callback. If there is no license key, the function won't even get called.

Alternatively, you could use a closure as the callback. This way you could pass the license key into the callback without having to retrieve and verify it again. For example (not tested):

```php
$updateChecker->addQueryArgFilter(function($args) use ($licenseKey) {
    $args['license_key'] = $licenseKey;
    return $args;
});
```
However, you will need PHP 5.3 or later to use closures.

**Comment by epohs** [comment]
It looks like addQueryArgFilter() only appends the 'license_key' argument on `get_metadata` calls.  Not on `download` calls. Am I understanding this correctly?

So, if the key doesn't get passed to the server on download, how do you verify that a download is authenticated?

**Comment by YahnisElsts** [comment]
That's correct. To put it another way, `addQueryArgFilter()` only lets you add query arguments to requests sent by the update checker. It doesn't apply to requests sent by WordPress core, like when WordPress downloads an update.

There are several ways to modify the download URL. For example, you could use the `'puc_pre_inject_update-$slug'` filter to change the current PluginUpdate instance before the update checker passes it to WordPress.

**Comment by epohs** [comment]
Thank you! That worked perfectly.
