### ISSUE TITLE
Update not working with github

### ISSUE THREAD

**Issue by JustineCrenier** [YahnisElsts/plugin-update-checker#392]
Hello, 

I follow the instruction for GitHub Integration.
It works with my first test, I make changes and need to update so I created a tag v2.00
And now it doesn't work anymore... And there is no error in my log.

Here is my code, did I do anything wrong ?

`require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://github.com/JustineCrenier/Poush-Theme',
	__FILE__, //Full path to the main plugin file or functions.php.
	'Poush-Theme'
);
$myUpdateChecker->setAuthentication('token'); //In my code there is a real token here !
$myUpdateChecker->getVcsApi()->enableReleaseAssets();
$myUpdateChecker->setBranch('master');`

Any help would be really appreciated! Thx

**Comment by YahnisElsts** [comment]
Your code looks fine to me. It seems that the formatting got a bit messed up when the code was pasted here, but I don't see anything wrong with the code itself.

Could you please elaborate on "it doesn't work anymore"? For example, is there something specific that should be happening but isn't happening?

I would recommend installing the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin and looking at the "PUC (Poush-Theme)" panel. Try clicking the "Check Now" button and see if it outputs any errors. Also, verify that the "checked version" and "cached update" fields have sensible values that match your theme.

**Comment by JustineCrenier** [comment]
Hello,

Thank a lot for your help.
With the Debug Bar plugin I find out what was wrong.
