### ISSUE TITLE
Incompatibility with PHP Scoper and Mozart

### ISSUE THREAD

**Issue by matzeeable** [YahnisElsts/plugin-update-checker#394]
Hi @YahnisElsts !

First, thanks for this awesome package, it takes away a lot of headaches. We have successfully implemented the package in our plugin, everything runs well locally. But as soon as we build the plugin over our CI, we get a fatal error:

```
PHP Fatal error:  Uncaught Error: Class 'Puc_v4p10_Plugin_UpdateChecker' not found in /var/www/html/wp-content/plugins/[...]/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p10/Factory.php:94
```

The line `94` is not compatible to your coding as we do **scope** our plugin with [PHP Scoper](https://github.com/humbug/php-scoper) (there is a similar tool called [mozart](https://github.com/mozart/mozart), perhaps you know that one):

> PHP-Scoper is a tool which essentially moves any body of code, including all dependencies such as vendor directories, to a new and distinct namespace.

That means, all your `Puc_*` classes gets namespaces to `DevOwl\OurPlugin\Vendor\Puc_*`.

Back to the main issue..., the problem lies here:

https://github.com/YahnisElsts/plugin-update-checker/blob/0edd15f67822464af8a23285ce367b30d515a855/Puc/v4p10/Factory.php#L116

PUC tries to create a new instance from a "random" string instead of using the full qualified name.

## Possible solution

PHP Scoper (and mozart) are using special cases when it comes to vendor-namespacing. One of them, is using full qualified names with [`::class`](https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) keyword. Unfortunately, `plugin-update-checker` needs still to be compatible with PHP 5.2 (it's in your `composer.json`), so PuC needs to instantiate each class individually, e.g.:

```php
return new Plugin_UpdateChecker($metadataUrl, $id, $slug, $checkPeriod, $optionName, $muPluginFile);
```

Would you be willing to change this? If so, could you tell me all the affected parts of the code that do such dynamic initialization, so I can start a PR?

Regards,
Matthew :-)

**Comment by YahnisElsts** [comment]
Could something as simple as adding [`__NAMESPACE__`](https://www.php.net/manual/en/language.namespaces.nsconstants.php) to `$checkerClass` work? For PHP 5.2 compatibility, we could check if `__NAMESPACE__` is defined and do nothing if it isn't.

**Comment by matzeeable** [comment]
Yeah, you can for sure do something like this:

```php
// Generate namespaced class name so scoping tools like php-scoper and mozart works here, too
$checkerClass = PHP_VERSION_ID >= 50300 ? __NAMESPACE__ . '\\' . $checkerClass : $checkerClass;
return new $checkerClass($metadataUrl, $id, $slug, $checkPeriod, $optionName, $muPluginFile); 
```

What do you think about this?

Do you use something like this anywhere else in your code? :-)

**Comment by YahnisElsts** [comment]
There is one more place that uses dynamically generated class names: the Debug Bar panel that's shows debugging information. Other than that, the factory is the only one that really need to be changed.

I've just committed a change that adds the current namespace to the class name. Please give it a try.

**Comment by matzeeable** [comment]
Hi @YahnisElsts !

I just tried it and unfortunately `defined('__NAMESPACE__')` never returns `true` as `defined` does not support magic constants.

But if I have a look at your commit you can omit the `defined` condition, `version_compare` should be enough.

Regards,
Matthew :-)

**Comment by YahnisElsts** [comment]
All right, I've removed the `defined('__NAMESPACE__')` checks.

**Comment by matzeeable** [comment]
Hi @YahnisElsts !

Thanks a lot for your effort. I think we are getting closer to the solution! Unfortunately I have found some more places in the code where you would have to prefix the namespace because Puc **passes class names as string to methods**.

https://github.com/YahnisElsts/plugin-update-checker/blob/dee87bbfe621fb79df6eb0195c7ff8b94bdb8126/Puc/v4p10/Plugin/UpdateChecker.php#L130

https://github.com/YahnisElsts/plugin-update-checker/blob/dee87bbfe621fb79df6eb0195c7ff8b94bdb8126/Puc/v4p10/Theme/UpdateChecker.php#L45

You have two choices:

- Prefix the passed class in `requestMetadata` method (you did this in `Extension.php`, too)
- Prefix the string in method invocation

Regards,
Matthew 😎

**Comment by YahnisElsts** [comment]
It looks like I missed those because I was only looking for stuff like `new $className()`. All right, I've added some prefixing code to `requestMetadata()` as well.

**Comment by matzeeable** [comment]
Hi @YahnisElsts ! Just checked our CI/CD with the newest commit and it works perfectly! Thanks a lot for your help. 😎
