### ISSUE TITLE
WP update server and Plugin Update checker

### ISSUE THREAD

**Issue by aryanrajcom** [YahnisElsts/plugin-update-checker#395]
Hi,

I would like to create a theme and offers automatic update. I am little confused about WP update server and Plugin Update checker plugin and there is also naming theme update checker which i assume is same plugin update checker.

Can i use the plugin update checker as mentioned for both plugin and themes? if i re-read I understand that wp update server is for server management panel like updates.example.com where this plugin will be installed and then use the plugin update checker in your theme and plugin to push the updates.

sorry if i am on wrong way.

Appreciate you all for the great work. I was not able to find a simple solution to push update on a theme.

**Comment by YahnisElsts** [comment]
Yes, you can use this library (`plugin-update-checker`) for theme updates. I used to have two separate projects called "plugin update checker" and "theme update checker", but both of them were doing a lot of similar things so eventually I combined them into one - that is, the one that you're looking at right now.

`wp-update-server` is a tool you can use to provide update information to `plugin-update-checker`. The update checker should be included in your plugin, and the update server should be installed on your site/server. That said, you don't necessarily have to use `wp-update-server` - you could just have a static JSON file with update information ([example](https://github.com/YahnisElsts/plugin-update-checker/blob/4778dd3eb4efa6c31a28c154940b1c5474eef056/examples/plugin.json)), or write your own script that outputs JSON data in the appropriate format.

**Comment by aryanrajcom** [comment]
Thank you. Appreciate it. I will go ahead and test with a sample theme.
