### ISSUE TITLE
site_transient_update_plugins not work !

### ISSUE THREAD

**Issue by amirsheikhhassan** [YahnisElsts/plugin-update-checker#397]
When the plugin is activated and the puc code is executed, the information of the new version of the plugin that can be updated will not be saved in update_plugins transient.

Without the site_transient_update_plugins filter in WordPress, the plugin cannot be updated like below feature.

![image](https://user-images.githubusercontent.com/24798231/96194401-2018ce00-0f57-11eb-9935-8d6d88506fe7.png)
This feature not work when update_plugins transient is empty from informations (stdclass) of this plugin .

How can i fix this bug ?

thanks

**Comment by YahnisElsts** [comment]
I'm not sure I fully understand the issue. Are you saying that the update checker doesn't add a `site_transient_update_plugins` feature? Or that this filter is not available or not called for some reason?

In general, PUC does not make changes to the `update_plugins` transient that is stored in the database. This is not a bug. The idea is to apply those changes using a filter instead. As far as I know, this works in all versions of WordPress that I have tested, at least as long as PUC is running.
