### ISSUE TITLE
E_COMPILE_ERROR

### ISSUE THREAD

**Issue by remcokalf** [YahnisElsts/plugin-update-checker#402]
I am trying to update plugins and get Errors for both UpdraftPlus, Admin Menu Editor Pro and Wordpress Toolbar Editor plugins. All 3 errors point to plugin-update-checker.php. See messages below. 
I have never seen this before. Reverting the plugins to previous version solves it. 

Any idea if this is server related or caused by plugin-update-checker?

Wordpress 5.3.1, php 7.0

UpdraftPlus:
Trying to update from 2.16.27.24 >2.16.42.24

An error of type E_COMPILE_ERROR was caused in line 10 of the file /home3/xxxnl/public_html/wp-content/plugins/updraftplus/vendor/yahnis-elsts/plugin-update-checker/plugin-update-checker.php. Error message: require(): Failed opening required '/home3/nvvostnl/public_html/wp-content/plugins/updraftplus/vendor/yahnis-elsts/plugin-update-checker/load-v4p9.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear')

Admin Menu Editor Pro:
Trying to update from 2.10.2 > 2.12.4

An error of type E_COMPILE_ERROR was caused in line 10 of the file /home3/xxxnl/public_html/wp-content/plugins/admin-menu-editor-pro/plugin-updates/plugin-update-checker.php. Error message: require(): Failed opening required '/home3/nvvostnl/public_html/wp-content/plugins/admin-menu-editor-pro/plugin-updates/load-v4p8.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear')

Wordpress Toolbar Editor
Trying to update from 1.3.2 > 1.3.4

An error of type E_COMPILE_ERROR was caused in line 10 of the file /home3/xxxnl/public_html/wp-content/plugins/wp-toolbar-editor/includes/plugin-updates/plugin-update-checker.php. Error message: require(): Failed opening required '/home3/nvvostnl/public_html/wp-content/plugins/wp-toolbar-editor/includes/plugin-updates/load-v4p9.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear')

**Comment by YahnisElsts** [comment]
I don't think I've seen these particular errors before either, but my guess would be that they have to do with updating from an older version of Plugin Update Checker to a newer version. Some old versions had a bug where they could throw an error during an update if the new plugin version used a different Plugin Update Checker version (however, the error message was different).

It looks like two of the plugins are using version 4.9 and one is using 4.8. The most recent PUC release is 4.10, so it could be that the updates that you're trying to install are using that version.

While this bug should be fixed in the latest PUC release, I don't think there's much that can be done for older versions. I would recommend uploading the updates manually. Future updates should not be affected by this bug.

**Comment by remcokalf** [comment]
Ok, thanks. I also have never seen this before in 15 years Wordpress. 
Will update manually and see what happens in future updates.

**Comment by YahnisElsts** [comment]
All right, I will close this issue for now, but if you see the same error(s) in a future update, feel free to reopen it.

**Comment by remcokalf** [comment]
FYI, 
I encountered the same error on a different server, a different hosting provider and other website:

WordPress versie 5.6
Plugin: Admin Menu Editor Pro (versie 2.12.4)
PHP version 7.4.9

Foutdetails
===========
Een fout van het type E_COMPILE_ERROR werd veroorzaakt op regelnummer 2353 van het bestand /home/wvo/domains/thedomain.nl/public_html/wp-content/plugins/admin-menu-editor-pro/extras.php. Foutmelding: require(): Failed opening required '/home/wvo/domains/thedomain.nl/public_html/wp-content/plugins/admin-menu-editor-pro/plugin-updates/plugin-update-checker.php' (include_path='.:/usr/local/php74/lib/php')

**Comment by YahnisElsts** [comment]
This one looks a bit different: the file that it's trying and failing to load is present in all recent PUC versions, so this is not a problem with using an older version. Instead, it sounds like one of the required plugin files is or was missing.

How exactly are you installing these updates? Using the WordPress dashboard or some third-party tool?

**Comment by remcokalf** [comment]
This was a weird one. I deleted the older plugin version, uploaded this version manually. Then got this WP error in my mail during or just after the upload. 
So this was during a manual upload/install. Site was working fine after. 

The other errors were while updating in the plugins screen. 

This might be totally unrelated to to the other errors. But in 15 years I never have seen E_COMPILE_ERROR errors while updating plugins, and now within 2 days, on 2 different servers both pointing to plugin-update-checker.php.

**Comment by YahnisElsts** [comment]
I did some quick research and it looks like `E_COMPILE_ERROR` has been around for years. It's not entirely clear, but I suspect the reason that we're only seeing it now is that previous PHP versions used to just throw a warning or a fatal error when they couldn't find a require()'d file, not an `E_COMPILE_ERROR`. 

In any case, it looks like there are lots of users reporting `E_COMPILE_ERROR` errors in different plugins, many of which don't use Plugin Update Checker: WPML, Yoast SEO, and so on. There doesn't seem to be any clear consensus on what exactly causes it, though some have mentioned opcache as a potential issue.

**Comment by remcokalf** [comment]
Good to know. I also had a hunch it has something to do with higher PHP versions. Although I also manage VPS with latest PHP, and opcache, with no update problems in Wordpress whatsoever. 
Anyway, thanks for looking into it.
