### ISSUE TITLE
Issue with Homestead

### ISSUE THREAD

**Issue by slobich** [YahnisElsts/plugin-update-checker#408]
I'm experiencing an issue when using the library in Homestead, to be more specific when installing Homestead with ["Per Project Installation"](https://laravel.com/docs/8.x/homestead#per-project-installation). The update runs but just doesn't copy the library. It copies everything else from the plugin just not `plugin-update-checker` folder. I get an [error like this in the admin](https://prnt.sc/xg7xyu) and I get [this](https://gist.github.com/slobich/d9f868c4b0f1bba54e510107e0440302) in `debug.log`. I also [see leftover files](https://prnt.sc/xg8d4y) in the `upgrade` folder inside `wp-content`. It happens both on my Mac and Windows computers. It doesn't happen when using Homestead in [default installation mode](https://laravel.com/docs/8.x/homestead#installing-homestead) or when using [Valet](https://laravel.com/docs/8.x/valet) or [Local](https://localwp.com/).

I'm using [this example plugin](https://github.com/slobich/test-update-checker) which only has the library and I change the version number for an update.  All other plugin updates, either WordPress.org plugins or paid plugins which are hosting the updates on their servers work fine. I presume this more an issue with Homestead then with the library?

**Comment by YahnisElsts** [comment]
I have no experience with Homestead so I can only offer some ideas/guesses.

- The `debug.log` also has some warnings that mention files that are not inside the `plugin-update-checker` folder, like `readme.txt` and `test-update-checker.php`. Can you confirm that those files do get copied even though the error log says:
`PHP Warning:  copy([...]/upgrade/2-ySkHGv/test-update-checker/readme.txt): failed to open stream: No such file or directory`
- The update checker doesn't perform the actual update installation, it just hands the download URL to WordPress core. In theory, there should be no difference between installing a regular plugin update and an update provided by this library. 
- Since some files are left over, can you take a look at their permissions and verify that they match the rest of plugin files?
- What about the files in `/wp-content/plugins`? When you install a regular plugin (e.g. Jetpack or some such) and the PUC example plugin, do their files and directories have the same permissions?

**Comment by slobich** [comment]
Hey Yahnis, thank you for getting back to me. As for your questions:

> Can you confirm that those files do get copied even though the error log says

Yes. Everything gets copied except the library.

> Since some files are left over, can you take a look at their permissions and verify that they match the rest of plugin files?

I installed an older version of Akismet and did an update and everything worked OK. I checked [the permissions](https://prnt.sc/xlgiv3) and they look OK to me.  I also tried the same thing with Jetpack and everything works OK.

> What about the files in `/wp-content/plugins?` When you install a regular plugin (e.g. Jetpack or some such) and the PUC example plugin, do their files and directories have the same permissions?

When I compare the permissions [between my test plugin](https://prnt.sc/xlhhfe) and [Akismet](https://prnt.sc/xlhnlx) they look OK, at least as far as I can see.

I did some additional test in my test plugin. I've added another "bigger" library ([Action Scheduler](https://github.com/woocommerce/action-scheduler)) in the plugin and also a test subfolder with a test file in it. When I did an update the same thing happens with those folders and not just with Plugin Update Checker folder. I even removed Plugin Update Checker folder from the [last test version of the test plugin](https://github.com/slobich/test-update-checker) and the same thing happens. So it's looks like this issue is something to do with WordPress and Homestead and not Plugin Update Checker. Based on all that I think we can close this issue since it doesn't look like it's connected to Plugin Update Checker.

Thank you for your help with this and for all of your work on Plugin Update Checker.

**Comment by YahnisElsts** [comment]
It sounds like it might be a problem with copying (sub-)directories. I would double-check the permissions and ownership of the left-over folders, like the `plugin-update-checker` folder in `upgrade/whatever/test-update-checker`. I don't think any of your screenshot showed that.

It's still kind of suspicious that it only affects updates provided by PUC. I'll close this issue for now, but if you discover that it's connected to PUC after all, feel free to reopen it or create new issue.

**Comment by slobich** [comment]
Ah... forgot about that folder. As far as I can see everything there looks OK:

* The `wp-content/upgrade` has it's [permissions](https://prnt.sc/xlrgmb) set as other folders in `wp-content`.
* Folders in `wp-content/upgrade` have their [permissions](https://prnt.sc/xlrty4) set OK as far as I can tell.

If I discover anything new I'll post it here. Thnx...
