### ISSUE TITLE
Add requires_php to JSON API list

### ISSUE THREAD

**Issue by mgriego** [YahnisElsts/plugin-update-checker#413]
Add `requires_php` to the [JSON API Google Doc](https://docs.google.com/spreadsheets/d/1eOBbW7Go2qEQXReOOCdidMTf_tDYRq4JfegcO1CBPIs/edit#gid=0) as an optional field.

This field was added in WP 5.1: https://github.com/WordPress/WordPress/blob/5.1/wp-admin/includes/class-wp-plugin-install-list-table.php#L507
Currently: https://github.com/WordPress/WordPress/blob/f29d62012dc7817fb52102b6246e101f9caa8a2a/wp-admin/includes/class-wp-plugin-install-list-table.php#L514

**Comment by YahnisElsts** [comment]
I have added this field to the spreadsheet.
