### ISSUE TITLE
How can I protect my Gitlab Access Token?

### ISSUE THREAD

**Issue by mcnaveen** [YahnisElsts/plugin-update-checker#416]
If Plugin is publically available. Everyone with the code can see my Access Token and used it for unwanted purposes. Is there any way I can protect it?

**Comment by YahnisElsts** [comment]
I don't think there's a way to protect the token unless you want to proxy all update requests through your own server and create your own authentication scheme. That's certainly *possible*, but it might take a lot of work to set up.

However, you could limit the risk by only giving the token read access to the repository. I think that if the token only has the `read_repository` and `read_api` scopes, people who find it won't be able to change anything in your repository.

**Comment by mcnaveen** [comment]
Thanks for the reply brother. 

Also, I need suggestion on this 

https://github.com/YahnisElsts/plugin-update-checker/issues/222#issuecomment-790653286

**Comment by YahnisElsts** [comment]
Right, I saw that one. It's useful feedback in case I ever add license-related features to this library. 

However, I'm not sure what suggestions you're looking for. It sounds like you've already built a working system. Is there something that's missing?

**Comment by mcnaveen** [comment]
Yeah. I don't know how to Integrate with [Plugin Update Checker](https://github.com/YahnisElsts/plugin-update-checker)
For example, this is my code.

```php
if ( 'active' === $plugin_license_status ) {
// Whole Function of the plugin
}
```

I'm getting the `$plugin_license_status` value from the JSON response.

Just checking if the returned JSON Response value is `Active` the plugin will work. Because everything is inside the IF Block.

But when I tried adding the below code inside the if block. I'm getting errors.

Example

```php
if ( 'active' === $plugin_license_status ) {

// plugin-update-checker
require 'includes/plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://gitlab.com/master-the-blaster/releases/',
	__FILE__,
	'master-the-blaster'
);
$myUpdateChecker->setAuthentication($Updater);
$myUpdateChecker->setBranch('master');

// Other Functions of the Plugin
}
```

I'm not sure this is the right way of doing it. Little help will be appreciated. Thanks

**Comment by YahnisElsts** [comment]
Can you elaborate on what errors you're getting? Assuming that `$plugin_license_status`, `$Updater`  and any other variables are set up as expected, I don't see any obvious reason why that code couldn't work.

**Comment by mcnaveen** [comment]
If I add like this, I'm getting the below error.

`There has been a critical error on this website. Please check your site admin email inbox for instructions.`

Code:
```php
if ( 'active' === $plugin_license_status ) {

// plugin-update-checker
require 'includes/plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://gitlab.com/master-the-blaster/releases/',
	__FILE__,
	'master-the-blaster'
);
$myUpdateChecker->setAuthentication($Updater);
$myUpdateChecker->setBranch('master');

// Other Functions of the Plugin
}
```

**Comment by YahnisElsts** [comment]
That usually means there was a fatal PHP error somewhere. You'll need to check the PHP error log on your server for the actual error message.

**Comment by mcnaveen** [comment]
I updated the above comment with more deeper strange issue. :)

**Comment by mcnaveen** [comment]
OMG. I was missing something. Got it fixed. Thanks, @YahnisElsts for your time. 

Finally `Check for Update` Link only shows if the License Status is `Active` and Disappears when the License Status is `Inactive`

Got it working. Many Thanks.

**Comment by YahnisElsts** [comment]
> Finally Check for Update Link only shows if the License Status is Active and Disappears when the License Status is Inactive

This is expected. The "check for updates" link is added by the update checker, so it will only show up if you run the code that sets up the update checker. If you want the link to be always visible, you'll need to run the update checker even when the user doesn't have an active license.

**Comment by mcnaveen** [comment]
Haha. No Problem at all. Thanks for creating this awesome stuff. 

Actually, I planned to send each and every update as a Zip file to the Purchased Email.

Implementing your stuff changed the whole game and made it a lot easier to roll out a new update :100: 

You're genius :blush: 

And If you have a donate link please let me know. I want to send a part of the amount after I start selling.

**Comment by YahnisElsts** [comment]
Thank you, it's good to hear that this project is useful to people.

I'm not looking for donations at the moment.

**Comment by mcnaveen** [comment]
> Thank you, it's good to hear that this project is useful to people.

Yes. You did a great job bro.

> I'm not looking for donations at the moment.

Ah. Okay, bro. I'm closing this issue. Turned out to be a conversation. 

Love :heart:  from India :india:
