### ISSUE TITLE
Manual update errors not working, wrong property called

### ISSUE THREAD

**Issue by marcorocca** [YahnisElsts/plugin-update-checker#418]
Hello, I have discovered that there is an error in the `handleManualCheck()` function of the `Puc_v4p10_Plugin_Ui` class: it will check:

`if ( ($update === null) && !empty($this->lastRequestApiErrors) ) {`

But there is no lastRequestApiErrors property in the class. It must be:

`if ( ($update === null) && !empty($this->updateChecker->getLastRequestApiErrors()) ) {`

I have tried to correct this behaviour as there are a few points where it uses `$this->lastRequestApiErrors` and I will send you a pull request if you want.

**Comment by YahnisElsts** [comment]
Thank you for the report. I guess I didn't do enough testing when I moved that part of the UI code to a separate class. 

I'll merge your fix shortly.

**Comment by marcorocca** [comment]
Thank you, are there any prevision of a release including these fixes?

**Comment by YahnisElsts** [comment]
Sure, I'll make a release shortly.
