### ISSUE TITLE
Plugin updates from private repository not working

### ISSUE THREAD

**Issue by surgeonsadvisor** [YahnisElsts/plugin-update-checker#42]
Hi!,
i follow the instructions and added the folder inside my plugin, i'm also calling the update file like this, but i doesn't work.

 // Load the auto-update class
   require 'plugin-update-checker/plugin-update-checker.php';
   $className = PucFactory::getLatestClassVersion('PucGitHubChecker');
   $myUpdateChecker = new $className(
       'https://github.com/surgeonsadvisor/sa-photo-gallery',
        __FILE__,
       'master'
   );
   $myUpdateChecker->setAccessToken('######myaccesstoken######');

but i get this, 
![2015-09-23_11-18-54](https://cloud.githubusercontent.com/assets/14205833/10052240/80cd2cec-61eb-11e5-84aa-7ddbaade816f.png)

Any help will be appreciated.

Best Regards.

**Comment by YahnisElsts** [comment]
Interesting. That might be an oversight on my part. Try changing lines 95 to 97 in `github-update-checker.php` from this:

```php
if ( empty($info->download_url) ) {
	$info->download_url = $this->buildArchiveDownloadUrl($ref);
}
```

To this:

```php
if ( empty($info->download_url) ) {
	$info->download_url = $this->buildArchiveDownloadUrl($ref);
} else if ( !empty($this->accessToken) ) {
	$info->download_url = add_query_arg('access_token', $this->accessToken, $info->download_url);
}
```

**Comment by surgeonsadvisor** [comment]
Thank You! This work for me. 
![2015-09-23_13-03-27](https://cloud.githubusercontent.com/assets/14205833/10053784/8e5d3836-61f3-11e5-80b1-0bd201860f5e.png)
