### ISSUE TITLE
How can I debug the checker?

### ISSUE THREAD

**Issue by SirLouen** [YahnisElsts/plugin-update-checker#421]
I have recently created a brand new plugin and set the exact same parameters as the other plugins already working with this checker but for some reason auto updates from Github are not working.

Same procedure as always: I'm publishing releases from a private github repository based on tags with simple versioning (1.0.0, 1.0.1, 1.0.2) and everything seems ok as always. 

Don't see any errors anywhere. It just simply doesn't launch the upgrade request despite of having a new release with a new version waiting in the github repo and I can't seem to find what is hindering it.

**Comment by YahnisElsts** [comment]
Try the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin. The "PUC (plugin-slug)" panel should show some debugging information about the update checker. It should also have "Request Info" and "Check Now" buttons - try clicking those and see if the results match your new version or if there are any errors.

**Comment by SirLouen** [comment]
Thanks, I will check it.
