### ISSUE TITLE
Incorrect project id in GitLab URLs

### ISSUE THREAD

**Issue by diegovogel** [YahnisElsts/plugin-update-checker#427]
Hello,

I'm having trouble getting this to work with GitLab. The PUC debugger shows 404's for all requests and I noticed that the URLs are incorrect. The structure should be `/projects/:id/repository/` but the URLs requested are something like `/projects/:group%2F:repo-name/repository`.

Here's a [screenshot](https://drive.google.com/open?id=1F1CDH_f7Kfpdt25msFzz5AAg8fVo0cE9) from the PUC debugger.

Here is what I used to initialize PUC:
```
require get_stylesheet_directory() . '/lib/plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://gitlab.com/stablemate/stablemate-wordpress-theme.git',
	__FILE__,
	'stablemate'
);
$myUpdateChecker->setAuthentication('my-access-token');
```
Any thoughts on what might be causing this?

**Comment by diegovogel** [comment]
Looks like this may be the culprit. Line 213 in `GitLabApi.php`:

![image](https://user-images.githubusercontent.com/23545422/115098666-423bda80-9eff-11eb-8b69-11fd402dfc7b.png)

The `id` is composed of the user name and repo name, but I think the GitLab API requires a numerical repo ID.

**Comment by YahnisElsts** [comment]
I don't think it has to be numeric, the API documentation says you can use [namespaced paths](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding).

Are you sure the repository URL is correct? It probably shouldn't include the `.git` suffix.

**Comment by diegovogel** [comment]
Ah, my mistake. It works without `.git`. Thanks a lot for the quick response!
