### ISSUE TITLE
still keep "Updating..." when I click the "update now" button

### ISSUE THREAD

**Issue by loremuelgadrinab** [YahnisElsts/plugin-update-checker#43]
Ho, I have applied it in my plugin code and I am using github to host my private wp plugin. when I have pushed some updates in my repo in github, in my wp admin I have seen a new update for the plugin but when I tried to click the "update now" button, it stays and displays "Updating.." for hours.. and didn't do the update of the code or it didn't done.. 

any idea about my case? thanks in advance..

what I have done is this only that I have put in my plugin code:

require 'plugin-update-checker/plugin-update-checker.php';
$className = PucFactory::getLatestClassVersion('PucGitHubChecker');
$myUpdateChecker = new $className(
    'https://github.com/user-name/plugin-repo-name/',
    __FILE__,
    'master'
);

**Comment by YahnisElsts** [comment]
Are you using the master branch of the update checker or a release version? There's a GitHub-specific bug that has already been fixed in master but I haven't tagged a new release yet.

Try opening the "update now" link in a new tab (middle-click or right-click and select "Open In a New Tab"). This way you'll get more details about the update installation process. Are there any error messages? On that note, are there any recent entries in your PHP error log?

**Comment by loremuelgadrinab** [comment]
I have move my plugin code into my server directory. now I am using the "Self-hosted Plugins".

this is inside my json-api.json file in my server:

{
  "name" : "My Plugin",
  "version" : "1.3.1.3",
  "author" : "My Name",
  "download_url" : "http://mysite.com/plugin-directory/myplugin.zip",
  "sections" : {
    "description" : "some text here"
  }
}

in my myplugin-function.php I have this code:

require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = PucFactory::buildUpdateChecker(
    'http://mysite.com/plugin-directory/myplugin.zip/json-api.json',
    __FILE__
);

now when I click the update now button to open in new tab it says:

Downloading update from http://example.com/plugins/my-cool-plugin.zip…
Download failed. Not Found

I have no idea why it goes like this, I have checked all the files and code; even in my local codes works and update successfully. but in my live code didn't work.

please help, I am almost done with it

**Comment by YahnisElsts** [comment]
Maybe you used that URL (`http://example.com/plugins/my-cool-plugin.zip`) in `json-api.json` before, and the update checker still has that old version of the file cached? By default, it only checks for changes every 12 hours or so. Go to the "Plugins" page and click the "check for updates" link under your plugin entry. That will force it to refresh the cache.

I would also recommend installing the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin. You can find a lot of useful debugging information in the "PUC (your-plugin-slug)" section of Debug Bar.

**Comment by YahnisElsts** [comment]
Any news on this?

**Comment by alessandrobellesia** [comment]
I had a similar problem. In my case the website and the repository had the same domain. 
You can try to disable the wordpress http-get external domain security feature adding this line to your plugin:

```
add_filter( 'http_request_host_is_external', '__return_true' );
```

**Comment by YahnisElsts** [comment]
Yes, that's a known issue with hosting updates on the same domain. Maybe I should add a similar workaround to the library itself...

**Comment by YahnisElsts** [comment]
Update: Should be fixed in 7a29fda377ae7e94989b84de262883bad006083d.

**Comment by alessandrobellesia** [comment]
Great! Thank you!

**Comment by YahnisElsts** [comment]
Well, I guess it's fixed, sort of? @loremuelgadrinab , if it still doesn't work for you, feel free to comment/reopen the issue.
