### ISSUE TITLE
icons not displayed on update section

### ISSUE THREAD

**Issue by abscolo77** [YahnisElsts/plugin-update-checker#431]
Hi,
The JSON of update server has:

...
"icons": {
        "1x": "https:\/\/server.url\/package-assets\/icons\/slug-128x128.png",
        "2x": "https:\/\/server.url\/package-assets\/icons\/slug-256x256.png",
        "svg": "https:\/\/server.url\/package-assets\/icons\/slug.svg",
    },
...

but i don't see the icon on update section. I see the default icon placeholder.

Wordpress: 5.7.1

**Comment by YahnisElsts** [comment]
Could this be a caching issue - that is, could it be that the update checker is still using outdated metadata that didn't have icons?

**Comment by abscolo77** [comment]
No, It show the correct new version of the plugin

**Comment by YahnisElsts** [comment]
Try installing [Debug Bar](https://wordpress.org/plugins/debug-bar/) and check if the correct icon information also shows up in the "PUC (plugin-slug)" panel.

**Comment by abscolo77** [comment]
Oh thanks! the update server url was wrong !!! I was checking a different update server. :(
