### ISSUE TITLE
Language update recognition

### ISSUE THREAD

**Issue by gwuluo** [YahnisElsts/plugin-update-checker#436]
Thank you very much for your open source, how to identify the language update, every time it prompts to update the translation (has been updated), I want to achieve update the translation and no longer prompt。
Thank you again

**Comment by YahnisElsts** [comment]
That sounds like it could be a bug or a configuration issue. Normally, the prompt/notification should go away after you update the translations.

The update checker detects language updates by looking for a section like this in the JSON metadata:

```json
"translations": [
	{
		"language": "fr_FR",
		"version": "4.0",
		"updated": "2016-04-22 23:22:42",
		"package": "http://example.com/updates/translations/french-language-pack.zip"
	},
	{
		"language": "de_DE",
		"version": "5.0",
		"updated": "2016-04-22 23:22:42",
		"package": "http://example.com/updates/translations/german-language-pack.zip"
	}
]
```

It will show a translation as an update if the `updated` timestamp is more recent than the `PO-Revision-Date` of the installed translation. The `version` field is not used by the update checker itself.

Please make sure that your `updated` timestamps are correct and that they match the timestamp(s) in the actual translation files.
