### ISSUE TITLE
Private repo access

### ISSUE THREAD

**Issue by jonschr** [YahnisElsts/plugin-update-checker#437]
I'm using your Github integration, and it works beautifully, for a WordPress plugin. I'd love to give it access to a private repo, but if I generate an access token, it seems like that's actually way too much access to give out. 

I'm just wondering what your recommended usage would look like for a private Github repo. It would be fantastic if there were separate tokens for each plugin user, but I'm actually just fine with there being a single value solution. This plugin won't be widely used, but we don't want the source code publicly available.

**Comment by YahnisElsts** [comment]
One approach that I've seen recommended by other users is to create a new user/organization and then give that user read-only access to your private repository. Then you can create an access token as that user and the token will have the same limited access.

**Comment by YahnisElsts** [comment]
I see you (Alexlytle) created a new issue (#475) about this. I'll close this old one because it hasn't had any other activity for more than 6 months.
