### ISSUE TITLE
Notifications do not appear on some hosts

### ISSUE THREAD

**Issue by Alireza-Ghavabesh** [YahnisElsts/plugin-update-checker#439]
Notifications do not appear on some hosts 

I'm sure curl is working on that host and i put a code for download zip file as a plugin on that host and file downloaded as well, that Shows file can be download.

but i dont know what is the reason of this problem.

**Comment by YahnisElsts** [comment]
I think we'll need more information to figure out what caused the problem. Please install the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin and see what it shows in the "PUC (your-plugin-slug)" panel. It should have various information about the update checker configuration, installed plugin version, and any cached updates - make sure that this information is correct. Also, try clicking the "Check Now" button in the PUC panel and see if it shows any errors.

**Comment by Alireza-Ghavabesh** [comment]
problem was from our wordpress permissions, not from this library.

**Comment by janeks** [comment]
What permissions?
