### ISSUE TITLE
Mutisite Check when Plugin is not network activated

### ISSUE THREAD

**Issue by korndev** [YahnisElsts/plugin-update-checker#44]
Hey there,

Just started using this within in a plugin I'm developing and it works great when the plugin is on a single site or network activated.

However, and I'm not sure if this is an issue or something I'm missing, when the plugin is activated on a single site within a multisite install, there doesn't seem to be a way to trigger the check and update of the plugin. Is there a hook or something that can be called to make this happen?

Thanks and let me know if you need further details!

Regards,
Justin

**Comment by korndev** [comment]
Think I might have just found the answer to my own question:

```One consequence of this that may not be immediately obvious is that on a multisite installation updates will only show up if the plugin is active on the main site. This is because update notifications usually appear in the network admin, and only plugins active on the main site are loaded in that case. The main site of a WordPress network is the one that was created first and has the path “/” in the Sites -> All Sites list.```

I'll give that a try to see if that takes care of the issue.

**Comment by YahnisElsts** [comment]
You've got it. The update checker needs to be running to be able to check for/install updates, and if your plugin isn't loaded, the update checker won't work.

**Comment by korndev** [comment]
Thanks, Yahnis!
