### ISSUE TITLE
making one plugin for checking instead of add one by one code into my plugins and themes.

### ISSUE THREAD

**Issue by Alireza-Ghavabesh** [YahnisElsts/plugin-update-checker#442]
making one plugin for checking, instead of add one by one code into my each plugins and themes.

currently i thinking about algorithm of it, can you tell me Due to the this library is possible to making this plugin ?

actually i say this library have this potential ?!

**Comment by YahnisElsts** [comment]
Sure, you could do that. While the usual way to use this library is to put the code in the plugin or theme that will be updated, technically there is no reason why the code couldn't be in a different plugin. You would just need to replace the `__FILE__` constant in the initialization code with the full filename of the other plugin.

You can also create multiple instances of the update checker in one plugin, so you could have one plugins that controls updates for multiple other plugins.

**Comment by Alireza-Ghavabesh** [comment]
thank you very much for guide, I understood.
