### ISSUE TITLE
can stop periodic update ?

### ISSUE THREAD

**Issue by Alireza-Ghavabesh** [YahnisElsts/plugin-update-checker#443]

**Comment by Alireza-Ghavabesh** [comment]
I want it to run only once, because I want to check a license before of check version and if the license was _true_, 
 
something like this:

**add_action( 'my_scheduled_event', 'prefix_my_scheduled_event' );
/**
 * On the scheduled action hook, run a function.
 */

function check_version_for_update() {
    // do something 
}


function prefix_my_scheduled_event() {
     if( check_license ){}
    check_version_for_update();    //=====> only once
}
//going to use the strtotime function, so a good habit to get into is to set the PHP timezone to UTC
default_timezone_set( 'UTC' );
//define a timestamp to run this the first time.  4:20 is as good a time as any.
$timestamp = strtotime( '2013-12-14 16:20:00' ); 
//set a recurrence interval - WP has three default intervals: hourly, daily & twicedaily
$recurrence = 'daily';
//define the hook to run
$hook = 'my_scheduled_event';
//you can pass arguments to the hooked function if need be.  this parameter is optional:
$args = null;
//the following will run your function starting at the time defined by timestamp and recurring every $recurrence
wp_schedule_event( $timestamp, $recurrence, $hook, $args );**


----------------------------------------------------------------------------------------------------------------
but if i can set cundition

**Comment by YahnisElsts** [comment]
You can disable periodic checks by setting the 4th argument to zero. 

```php
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'http://example.com/path/to/details.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'unique-plugin-or-theme-slug',
	0 // How often to check for updates (in hours). Set to zero to disable.
);
```

If you want to trigger an update check directly, you can use the `checkForUpdates()` method:

```php
$myUpdateChecker->checkForUpdates();
```

**Comment by Alireza-Ghavabesh** [comment]
ok, now i have to set two code or create an instance and call checkForUpdates() ?

**Comment by YahnisElsts** [comment]
I'm not entirely sure what you mean by "set two code", but overall that sounds reasonable.

**Comment by Alireza-Ghavabesh** [comment]
I understood, thank you
