### ISSUE TITLE
GitHub Release: use binary file for update

### ISSUE THREAD

**Issue by haydeningham** [YahnisElsts/plugin-update-checker#451]
I have a plugin that uses Composer and it's good practice not to commit the vendor directory to your repository. However for the updates to the plugin the vendor directory needs to be included. Yoast upload the .zip file for the plugin update as a binary to the release. This is the approach I will be taking. My question is how do I get the plugin update checker to use the binary file eg. my-plugin.zip rather than the Source Code .zip file for the update?

**Comment by YahnisElsts** [comment]
Assuming that your repository is on GitHub and you only have one .zip file per release, this could be as simple as calling `enableReleaseAssets()` after you initialize the update checker:

```php
 $myUpdateChecker->getVcsApi()->enableReleaseAssets();
```

This will make the update checker use the attached binary instead of the source code .zip.

**Comment by haydeningham** [comment]
Brilliant, thank you Yahnis.
