### ISSUE TITLE
Update check says plugin up to date, debug bar disagrees

### ISSUE THREAD

**Issue by darylbowers** [YahnisElsts/plugin-update-checker#453]
Hi Yahnis, many thanks for the work you've put in to these plugins.

I'm having an issue with a self-hosted setup, using both your update server and checker. When doing a Check For Updates it always says that the plugin is up to date, even though I've updated the version on the server from 1.0.1 to 1.0.2.

I've installed debug bar and here are the results:

![PUC#01](https://user-images.githubusercontent.com/49780104/127781631-a28ac133-09d4-4e2d-a60a-d96867e62b15.png)
![PUC#02](https://user-images.githubusercontent.com/49780104/127781636-e8925370-abc6-4eee-acb0-1616536cbfd3.png)

The plugin checker is called from the peapods-wp-calendar.php file in the root folder of the plugin:

```
require 'plugin-update-checker/plugin-update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
    'https://peapods.co.uk/plugins/?action=get_metadata&slug=peapods-wp-calendar',
    __FILE__, //Full path to the main plugin file or functions.php.
    'peapods-wp-calendar'
);
```

Any help would be much appreciated,

Thanks,

Daryl

**Comment by YahnisElsts** [comment]
This looks like a very strange issue. All of the debug output looks fine to me, but the update isn't showing up. Could it be that PUC can't save the latest update in the database for some reason?

**Comment by darylbowers** [comment]
The external_updates entry was present in the options table, but with out of date info. I deleted it and checked for updates, the database option was recreated - again with the same out of date info. I have no idea where it got that from - any ideas?

Do PHP or Apache cache responses? 

The Debug Bar page can see the latest meta data for the plugin on the server when you click Request Info, but this isn't being stored, and the Check For Updates function only ever sees the old data. Even if I delete the options table entry!

Thoroughly confused.

**Comment by YahnisElsts** [comment]
I don't think PHP/Apache would cache these responses by default, but maybe it is a possibility in some server configurations.

It looks like your plugin download link is publicly accessible, so I tried running your plugin on a local test site. Interestingly, in my case the update showed up correctly. I changed the version number to `1.0.1` and the `1.0.3` update appeared. It also shows up in Debug Bar. This is without any code changes.

**Comment by darylbowers** [comment]
Yes, that works for me too.

I've found that automatic updates appear to work correctly, but the Check For Updates function isn't picking up new versions. Is it supposed to download the latest meta data or does it only look at the cached external_updates-... option table row?

**Comment by YahnisElsts** [comment]
The "Check For Updates" link is supposed to immediately download the latest update metadata. It also works on my test site.

Maybe you could use something like [Log HTTP Requests](https://wordpress.org/plugins/log-http-requests/) to see what happens when you click "Check For Updates"?

**Comment by darylbowers** [comment]
I installed v1.0.3 of my calendar plugin on another local site that doesn't use it, just to test.

I installed Log Http Requests and ran it to check that everything looked right.

I then built a new version 1.0.4 of the plugin and uploaded to the server. I clicked the Check for updates and it came back saying that the plugin was up to date. Log Http Request shows the following request and response:

URL:

https://peapods.co.uk/plugins/?action=get_metadata&slug=peapods-wp-calendar&installed_version=1.0.3&php=7.3.11&locale=en_GB&checking_for_updates=1

Request:
```

{
  "method": "GET",
  "timeout": 10,
  "redirection": 5,
  "httpversion": "1.0",
  "user-agent": "WordPress/5.8; http://192.168.1.130/peapods",
  "reject_unsafe_urls": false,
  "blocking": true,
  "headers": {
    "Accept": "application/json"
  },
  "cookies": [],
  "body": null,
  "compress": false,
  "decompress": true,
  "sslverify": true,
  "sslcertificates": "C:\\xampp\\htdocs\\peapods/wp-includes/certificates/ca-bundle.crt",
  "stream": false,
  "filename": null,
  "limit_response_size": null,
  "_redirection": 5
}

```
Response:
```

{
  "headers": {},
  "body": "{\n    \"name\": \"Peapods-WP-Calendar\",\n    \"version\": \"1.0.3\",\n    \"homepage\": \"peapods.co.uk\",\n    \"author\": \"Daryl Bowers\",\n    \"author_homepage\": \"peapods.co.uk\",\n    \"sections\": {\n        \"description\": \"<p>Custom front end for the phpjabbers availability calendar database.<\\/p>\",\n        \"changelog\": \"<p>1.0.3 Test update fixes\\n1.0.2 Test auto plugin update\\n1.0.1 Add automatic plugin updates\\n1.0.0 Launch version<\\/p>\"\n    },\n    \"last_updated\": \"2021-08-02 08:39:17\",\n    \"slug\": \"peapods-wp-calendar\",\n    \"download_url\": \"https:\\/\\/peapods.co.uk\\/plugins\\/?action=download&slug=peapods-wp-calendar\",\n    \"request_time_elapsed\": \"0.002\"\n}",
  "response": {
    "code": 200,
    "message": "OK"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```

However if I put the request directly into a browser I get the up-to-date version information:

https://peapods.co.uk/plugins/?action=get_metadata&slug=peapods-wp-calendar

```
{
name: "Peapods-WP-Calendar",
version: "1.0.4",
homepage: "peapods.co.uk",
author: "Daryl Bowers",
author_homepage: "peapods.co.uk",
sections: {
description: "<p>Custom front end for the phpjabbers availability calendar database.</p>",
changelog: "<p>1.0.4 Test plugin update 1.0.3 Test update fixes 1.0.2 Test auto plugin update 1.0.1 Add automatic plugin updates 1.0.0 Launch version</p>"
},
last_updated: "2021-08-03 12:53:21",
slug: "peapods-wp-calendar",
download_url: "https://peapods.co.uk/plugins/?action=download&slug=peapods-wp-calendar",
request_time_elapsed: "0.003"
}
```

I get this behaviour on 4 websites, on both the local versions and live. I'm really struggling to think how/why this would be the case. If you have any other suggestions or ideas I would be most grateful!

Thanks

**Comment by YahnisElsts** [comment]
It looks like something on your server might be caching the responses. If I try to open the first URL that you posted:

https://peapods.co.uk/plugins/?action=get_metadata&slug=peapods-wp-calendar&installed_version=1.0.3&php=7.3.11&locale=en_GB&checking_for_updates=1

I get version 1.0.3:

```json
{
    "name": "Peapods-WP-Calendar",
    "version": "1.0.3",
    "homepage": "peapods.co.uk",
    "author": "Daryl Bowers",
    "author_homepage": "peapods.co.uk",
    "sections": {
        "description": "<p>Custom front end for the phpjabbers availability calendar database.</p>",
        "changelog": "<p>1.0.3 Test update fixes\n1.0.2 Test auto plugin update\n1.0.1 Add automatic plugin updates\n1.0.0 Launch version</p>"
    },
    "last_updated": "2021-08-02 08:39:17",
    "slug": "peapods-wp-calendar",
    "download_url": "https://peapods.co.uk/plugins/?action=download&slug=peapods-wp-calendar",
    "request_time_elapsed": "0.002"
}
```

However, if I add a meaningless parameter to the URL to make the URL unique:

https://peapods.co.uk/plugins/?action=get_metadata&slug=peapods-wp-calendar&installed_version=1.0.3&php=7.3.11&locale=en_GB&checking_for_updates=1&abc=123

Then I get version 1.0.4:

```json
{
    "name": "Peapods-WP-Calendar",
    "version": "1.0.4",
    "homepage": "peapods.co.uk",
    "author": "Daryl Bowers",
    "author_homepage": "peapods.co.uk",
    "sections": {
        "description": "<p>Custom front end for the phpjabbers availability calendar database.</p>",
        "changelog": "<p>1.0.4 Test plugin update\n1.0.3 Test update fixes\n1.0.2 Test auto plugin update\n1.0.1 Add automatic plugin updates\n1.0.0 Launch version</p>"
    },
    "last_updated": "2021-08-03 12:53:21",
    "slug": "peapods-wp-calendar",
    "download_url": "https://peapods.co.uk/plugins/?action=download&slug=peapods-wp-calendar",
    "request_time_elapsed": "0.001"

}
```

I'm pretty confident that my update server implementation doesn't cache API full responses. Is there something else that's running on this server that could be doing caching? Some Apache module? A proxy?

**Comment by darylbowers** [comment]
Bingo! That appears to be the issue - it's on a Siteground shared hosting account with three levels of caching. I disabled all the caching that I could and flushed the cache of the one I couldn't disable and Bob's your uncle - it works as expected.

I believe I've now resolved this by adding a .htaccess file to the Plugin Update Server root directory using the info here: 

https://www.siteground.co.uk/kb/disable-dynamic-caching-website/

```
<IfModule mod_headers.c>
Header set Cache-Control "private"
</IfModule>
```

I don't know whether it's enough of an issue to add a no cache header to the API/server, but I've leave it here just in case:

```
<php
header("Cache-Control: no-cache");
?>
```

Thanks very much for your help, you're a star!

**Comment by YahnisElsts** [comment]
All right, it's good to hear that you figured it out.

I think explicitly turning off caching for the entire API is probably overkill; some developers might actually want to configure their server to cache API responses. Update requests can generate a lot of traffic when you have tens of thousands of users. Using a `.htaccess` file seems like a decent workaround.

It sounds like the issue has been resolved, so I'll close this now.
