### ISSUE TITLE
How to add "See details" about theme into "wp-admin/update-core.php" page?

### ISSUE THREAD

**Issue by RichForever** [YahnisElsts/plugin-update-checker#455]
How Can I add link "See changes in version X.Y" in the update-core page? I can see the link when I go to the theme page but I want to add the same link in the core view. Where should I place readme.txt file? Which files and how should I change to make it work?

**Comment by YahnisElsts** [comment]
I don't think WordPress supports that feature for themes. I'm looking at the code in `update-core.php` (WP 5.8) and it appears that it only ever shows the "View version X.Y details" link for plugins. There don't seem to be any hooks that you could use to add a custom link to a theme update.

I guess you could insert a link with JavaScript, but that seems like a bit of a hack.

**Comment by RichForever** [comment]
Ok, got it. Thanks for the reply!
