### ISSUE TITLE
Update Deleting Custom Files

### ISSUE THREAD

**Issue by DeathStapler** [YahnisElsts/plugin-update-checker#46]
It seems that when it downloads an updated version of the plugin, it will delete the old version's folder and put the new on in its place.

I have custom files stored in a sub-folder of the plugin folder.  Those files are deleted when an update occurs.  Is there some way to prevent files or folders that are not in the new version's zip file from being deleted?

EDIT: This may just be how WP handles plugin updates.  If so, I'll have to rethink how I handle storing custom files.

**Comment by YahnisElsts** [comment]
It is just how plugin updates work in WordPress. As far as I know, there is no way to prevent a specific sub-folder or file from being deleted.

**Comment by DeathStapler** [comment]
Ok.  Thanks.
