### ISSUE TITLE
Why didn't I check for updates

### ISSUE THREAD

**Issue by huankong233** [YahnisElsts/plugin-update-checker#465]
I didn't find the check update in "debug". Is there something wrong with my settings?
My settings:
$hkThumbnailUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
' https://www.huankong.ltd/update_check/plugin.json ',
huankong_ROOT_PATH,
'hk-thumbnail'
);

**Comment by YahnisElsts** [comment]
One problem that I noticed is that `huankong_ROOT_PATH` seems to be a *directory path*. The update checker needs the full *file path*, not just the directory. Try changing that argument to the full file path of the main plugin file.

Also, make sure that the code that initializes the update checker is actually running. If it's in a hook of some kind, it might never get executed in your tests.

**Comment by huankong233** [comment]
Oh, I didn't notice the need to use a file path. I just used a directory path.
It is now working normally. Finally, thank you for developing this plug-in update library!
