### ISSUE TITLE
Download of update not showing but red update marker showing

### ISSUE THREAD

**Issue by Webtica** [YahnisElsts/plugin-update-checker#468]
Hi, 

I implemented plugin update checker and even wp update server. 
When I upload the new plugin zip with the correct slug and a higher version the update mark appears in wordpress.
As seen here: https://plugins.webtica.be/image2.png
But the download/update option doesn't appear. Even after clearing cache multiple times. 
As seen here: https://plugins.webtica.be/image.png

Any idea how we can fix this? 

Thanks,
Dieter

**Comment by YahnisElsts** [comment]
Does the update notification also appear below the plugin entry on the "Plugins" page as it does for other plugins that have an update available? I didn't see it in the screenshot, but it could just be cut off. 

Generally speaking, when there's a problem like this, there are two main things to check:
- Are you passing the correct file name to `buildUpdateChecker()`? It must be the full path to the main plugin file. If you use anything else, the update checker won't be able to associate the update with the right plugin.
- Does the update response include a valid `download_url` field? Try opening the metadata URL in the browser (it's just JSON) and see if the information it shows makes sense for your plugin.

**Comment by Webtica** [comment]
Hi @YahnisElsts,

Thanks, the first one was the problem. It was using _FILE_ when the updater was in a subdirectory. 

Thanks,
Dieter
