### ISSUE TITLE
Can I change style.css location? ❓ 

### ISSUE THREAD

**Issue by melcarthus** [YahnisElsts/plugin-update-checker#469]
How could I go about changing the location where the plugin looks for the style.css?
I'm using a sage theme where its not in the root of the theme but inside /resources/style.css/

Kind regards,

Tim

**Comment by YahnisElsts** [comment]
The short answer is "you can't". However, there are a couple of options:

- Use Sage 10 (in development). It has `style.css` in the root directory.
- You might be able to move the `style.css` and other files to the root directory. See [this comment](https://github.com/roots/sage-installer/issues/3#issuecomment-337852956) for details.
