### ISSUE TITLE
Multisite usage

### ISSUE THREAD

**Issue by pixele** [YahnisElsts/plugin-update-checker#47]
I'm using the update-checker on a multisite WP installation. If a plugin is not active on the 'main' site, but only on sub sites, the update code is never executed and updates ar not shown.
I've tried to install a plugin executing the update checks for all these plugins but that didn't work. 

Any suggestions?

Thank for developing and maintaining this awesome checker!

eric

**Comment by YahnisElsts** [comment]
As far as I know, there's no easy way around that. Here's why: to show updates, the update checker must be running. Only plugins that are active on the main site will be running in the network admin. As a result, updates only work when your plugin - and, by extension, the update checker - is active on the main site.

If anyone has an idea for how to get around that, I'd love to hear it!

**Comment by roest01** [comment]
as far as i know this is the concept of a multisite.
The Plugin Management should only be done at the main installation.
So the main installation decide which templates and plugins are installed and which version they have.

No SubSite of an multisite installation should update an Plugin because it concerns all the other SubSites who use technically the same plugin files.

So this "bug" is a required feature because of limited authorizations of a SubSite.

**Comment by YahnisElsts** [comment]
Even so, ideally the Multisite administrator should be able to update an installed plugin even if it's not *active* on the main site.

**Comment by pixele** [comment]
Found a workaround for this issue by building a 'update-checker' plugin that only checks for updates of plugins not active on the main site. When activated on the main site it perfectly shows available updates in the administrator plugin screen. My first try failed because i forgot to change the __FILE__ to the actual path of the plugin to be checked. Now it works like a charm!

**Comment by YahnisElsts** [comment]
Yep, that works in cases where you control the site or can get the user to install an additional plugin just for updates.

**Comment by yipeecaiey** [comment]
@pixele or @YahnisElsts 
I am working on an 'update checker' plugin that will work for many different plugins I maintain in a private repository.
The PUC library only exists in this 'update checker' plugin, and the plugin loops through a list of these privately maintained plugins.
That all works great...as long as the plugins are activated.  If any plugin is not active, no update notifications show up.
I can't find anywhere in the PUC code any filter for a plugin's active status...but it sounds like @pixele didn't run into this problem.
Any thoughts/suggestions?

**Comment by yipeecaiey** [comment]
in case this helps...here is the code snippet
```
require_once('lib/plugin-update-checker/plugin-update-checker.php');
if ( ! function_exists( 'get_plugins' ) ) {
    require_once ABSPATH . 'wp-admin/includes/plugin.php';
}

//list all bxl/cxl plugins we are interested in
$bxl_plugins = array(
    'bxl-1-plugins-manager',
    'bxl-infocus-forms-plugin',
    'bxl-infusionsoft-wp-plugin',
    'bxl-kicksite-plugin',
    'cxl-wp-plugin'
);

//get all installed plugins
$all_plugins = get_plugins();

//filter all installed plugins for just the installed bxl plugins
foreach($all_plugins as $plugin_slug=>$info) {
    foreach($bxl_plugins as $bxl_plugin) if(strstr($plugin_slug,$bxl_plugin)) {
        //set up the data
        $plugin_remote_path = 'https://www.cxl1.net/wp-plugins/updates/?action=get_metadata&slug='.$bxl_plugin;
        $abs_plugin_file = trailingslashit(realpath(dirname(dirname(__FILE__)))).$plugin_slug;
        $slug = '';
        $frequency = '0.01';
        $option = 'bxl_plugins_updates_checker_'.$bxl_plugin;

        //init the updater
        $updater = PucFactory::buildUpdateChecker(
            $plugin_remote_path,
            $abs_plugin_file,
            $slug,
            $frequency,
            $option
        );
    }
}
```

**Comment by YahnisElsts** [comment]
> I can't find anywhere in the PUC code any filter for a plugin's active status...

I see you've already found a solution, but in case anyone else has that same question about plugin status, let me clarify: the library *doesn't* check if the plugin is active. 

It's just that, in most cases, you would include the library as part of your plugin, which means that when your plugin is inactive then the update checker is also inactive. However, that's just a side-effect of how plugins work. There's no explicit filtering.

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for about 3 years. Even though a lot of time has passed, there is still no good way to make updates work if the plugin/theme is not active on the main site in a Multisite network. If anyone has an idea for a solution, feel free to open a new issue.
