### ISSUE TITLE
Update logging?

### ISSUE THREAD

**Issue by petersterling** [YahnisElsts/plugin-update-checker#470]
Hello, thanks for this library - it looks like a fantastic effort - well done!

I have 2 queries:
1. It would be useful to me if there were some level of logging of downloads. The aim being to know which of my clients have successfully obtained the latest version of a plugin. Obviously this is tricky for you to get involved in as the logging would be on the remote server specified by "download_url". However, maybe this could be specified as a logging PHP script on the remote server that takes a parameter (or two see next query) that identifies the download and so redirects to it?
2. Another parameter might be a token that the logger validates to provide a level of licensing authority. That is, only valid tokens permit a download?

What do you think? Any recommendations?

**Comment by YahnisElsts** [comment]
1. Take a look at my [`wp-update-server` project](https://github.com/YahnisElsts/wp-update-server). It already logs update checks and download requests, including the site URL that it gets from the `User-Agent` header. It might not log all of the information that you need, but it could be easier to modify an existing script to suit your needs than to write it from scratch.
2. Licensing has occasionally come up in a past. I don't have a ready-to-use solution - my plugins use a custom implementation that's not easily reusable - but [I posted some basic suggestions here](https://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/).

**Comment by petersterling** [comment]
Thanks. Very helpful. 🤓
