### ISSUE TITLE
cURL error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated

### ISSUE THREAD

**Issue by llirikcmb** [YahnisElsts/plugin-update-checker#471]
Hello. I got this error message when I was trying to check my plugin updates hosted on bitbucket.org.

> cURL error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated. http_request_failed
> cURL error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated. http_request_failed
> cURL error 56: GnuTLS recv error (-110): The TLS connection was non-properly terminated. http_request_failed
> Could not retrieve version information from the repository. This usually means that the update checker either can't connect to the repository or it's configured incorrectly. puc-no-update-source

I get this error only on php7.4. (I tested it on php7.0 and php7.4)
Bitbucket return response with status code 200, but wp_remote_get raise an error because cURL handler detects "GnuTLS recv error".

Perhaps this is a common bug when trying to request bitbucket on php7.4 
Has anyone faced this problem? How to solve it?

**Comment by llirikcmb** [comment]
Thank you for your answer. I just changed bitbucket storage to a self-hosted archive, because it is the best decision for me.
I use wp-update-server, it is a really useful tool!

It seems to be impossible to force each plugin user to recompile PHP.  It's easier not to use the bitbucket connection at all.

**Comment by YahnisElsts** [comment]
Sounds good; I'll close this now.
