### ISSUE TITLE
Access token in Github

### ISSUE THREAD

**Issue by Alexlytle** [YahnisElsts/plugin-update-checker#475]
I can push a public repo without any issues :) but when I try a private repo it doesn't work. I create a personal access token in GitHub get access to everything and it doen't work. Is it not personal access tokens and is it another sort of token to get this to work?

**Comment by Alexlytle** [comment]
I guess my question what of token is this package looking for?

**Comment by YahnisElsts** [comment]
It was a personal access token the last time I tested it, which, admittedly, was a few months ago. I'm talking about the tokens that you can create in "Settings -> Developer settings -> Personal access tokens".

This may sound obvious, but please double-check that you're passing the correct token (and the whole token) to `setAuthentication()`.

I would also recommend installing the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin. The update checker integrates with Debug Bar to provide additional debugging information. In the debug bar, open the "PUC (your-slug)" section and try clicking the "Check Now" button. If there are any GitHub API errors, the update checker should show them there.

**Comment by Alexlytle** [comment]
I did exactly that with no luck. I didn't get any errors with the debug bar. I guess i will try GitLab or use GitHub and toggle private to public on the repo settings. I really do appreciate this package thanks for your work :)
**
![image](https://user-images.githubusercontent.com/44213950/148815396-4fc25f8a-85b1-4160-ad08-a0ef1470dbb6.png)
**

![image](https://user-images.githubusercontent.com/44213950/148815492-5a858060-5287-4d47-8d06-4e6ab86e00f6.png)

**Comment by YahnisElsts** [comment]
All right. I'll close the issue for now, but if you want to investigate this problem further at some point, feel free to reopen it or create a new one.

**Comment by Alexlytle** [comment]
Im sorry its working i didnt realize you have to personal access token inside the theme your updating. I only had the personal access token inside in my development theme

**Comment by YahnisElsts** [comment]
Ah, yes. The update checker needs access to the repository to detect updates, and if the repository is private, it can't do that without the token.

**Comment by Alexlytle** [comment]
Thank you so much for your help !
