### ISSUE TITLE
 Failed to update the theme, always prompt ：The directory structure of the update is incorrect. All files should be inside a directory named unique-plugin-or-theme-slug, not at the root of the ZIP archive.

### ISSUE THREAD

**Issue by muchenkezhan** [YahnisElsts/plugin-update-checker#482]
The directory structure of the update is incorrect. All files should be inside a directory named unique-plugin-or-theme-slug, not at the root of the ZIP archive.

 I can't understand ，json  Here's the file ：
` {
 	"version": "4.8",
 	"details_url": "https://xxx.cn/zhuti/51.html",
 	"download_url": "http://www.xxx.cn/wp-content/themes/qzdy-4.8.zip"
 }`

 Is the download path name wrong

**Comment by muchenkezhan** [comment]
[https://s3.bmp.ovh/imgs/2022/03/d45c4d9c1ad4c6d3.png](url)

**Comment by YahnisElsts** [comment]
This error has to do with the contents of the ZIP file. When you make the ZIP file, all of the theme files should be in a directory that has the same name as the theme slug. So when you open the ZIP file, you should only see one directory, and all of the theme files/directories should be inside that directory.

Some ZIP software can make it look like the contents of a ZIP archive are inside a directory when they are actually not. For example, I've received multiple reports from people who use macOS that it shows ZIP archives like that. If you're on a Mac, I would recommend trying a third-party ZIP tool.
