### ISSUE TITLE
Support for WordPress 4.2  - is-dismissible class

### ISSUE THREAD

**Issue by hareesh-pillai** [YahnisElsts/plugin-update-checker#49]
In [WordPress 4.2](https://make.wordpress.org/core/2015/04/23/spinners-and-dismissible-admin-notices-in-4-2/) a new class was introduced to make the admin notices dismissible. The admin notice displayed after the plugin update check can be dismissed using this.

**Comment by YahnisElsts** [comment]
The relevant pull request has been merged, so I'm closing this issue.
