### ISSUE TITLE
How to get listed in "Used by" section?

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/plugin-update-checker#490]
How to get my repository listed in ["Used by"](https://github.com/YahnisElsts/plugin-update-checker/network/dependents?package_id=UGFja2FnZS01NDMyMzk3Njg%3D) section of this repository? (see below "Packages")

Thanks

**Comment by YahnisElsts** [comment]
I'm actually not sure how that section works. It seems to be generated automatically. I think it might be based on `composer.json`? So you might need to list this package (`yahnis-elsts/plugin-update-checker`) as a dependency in your own `composer.json`, if you have one.

**Comment by ddur** [comment]
Thanks

**Comment by ddur** [comment]
My guess is to have sub-directory named after your repository (`yahnis-elsts/plugin-update-checker`). Maybe under /vendor/.

**Comment by ddur** [comment]
Yes, composer.

Looks like this is the another way: [7.11 Git Tools - Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by ddur** [comment]
@YahnisElsts 

GitHub shows dependencies using composer.json only, although composer is not used at all.

**Comment by YahnisElsts** [comment]
For what it's worth, Composer *is* used in this project. This update checker is also a valid Composer package.

**Comment by ddur** [comment]
I'm aware of that, thank you.
