### ISSUE TITLE
Update failed: Could not remove the old plugin.

### ISSUE THREAD

**Issue by lDemodexl** [YahnisElsts/plugin-update-checker#508]
When trying to update plugin it removes current version and just shows this error.
In php errors found such errors: "PHP Warning:  Can&#039;t to read the Version header for &#039;plugin main file&#039;. The filename is incorrect or is not a plugin. "

**Comment by YahnisElsts** [comment]
In most cases, the error "Could not remove the old plugin" is unrelated to the update checker. It's more likely that some of the file permissions are incorrect, or that one of the files in the plugin directory was locked/inaccessible during the update. For example, if you had a file open in a code editor, or if there was an in-use `.svn` or `.git` subdirectory in the plugin directory, that might trigger an error like this.

Also, just to verify, does it literally say 'plugin main file' in the error message, or did you edit out the plugin file name?

**Comment by lDemodexl** [comment]
@YahnisElsts of course i changed file path in error. 
TY, I think I figured out where the problem came from
