### ISSUE TITLE
Possible update needed because of changes in core

### ISSUE THREAD

**Issue by jrfnl** [YahnisElsts/plugin-update-checker#51]
See https://core.trac.wordpress.org/ticket/35301

**Comment by YahnisElsts** [comment]
Thanks for the heads-up. I've added the ticket to my watchlist. Hopefully they'll add a new hook that lets plugins change/add the update information (it looks like somebody has already mentioned that).

**Comment by YahnisElsts** [comment]
Fixed this a while ago in 67fb7c0e6b5a21e0d42f37e32d6e330607fc8777
