### ISSUE TITLE
[Ask] How to showing confirmation box for Update Available

### ISSUE THREAD

**Issue by wickborlan** [YahnisElsts/plugin-update-checker#510]
Hello, 

Previously, thanks for the great plugin 

Next, I have a little problem with my settings and maybe my expectations also. On my setting below, the plugin is working properly, when I push to bitbucket, the theme on my WordPress dashboard is also affected (version changed). 

But the update is directly working, my expectation there is an update with my theme, the system should show a yellow notification update first, then I can click the confirmation link, like this : 

my expectation
![Screen Shot 2022-12-25 at 18 04 03](https://user-images.githubusercontent.com/16150261/209465557-3e875245-cb94-4eb1-a96e-534ccb1dc388.png)

my theme condition
![Screen Shot 2022-12-25 at 18 06 54](https://user-images.githubusercontent.com/16150261/209465621-118356f3-d309-40a1-aea7-60e7242f2bf6.png)

==================
function.php
```
require 'plugin-update-checker-5.0/plugin-update-checker.php';
    use YahnisElsts\PluginUpdateChecker\v5\PucFactory;

    $myUpdateChecker = PucFactory::buildUpdateChecker(
    	'https://bitbucket.org/xxx/peekha',
    	__FILE__,
    	'peekha'
    );

    //Optional: Set the branch that contains the stable release.
    $myUpdateChecker->setBranch('master');
```
readme.txt
```
=== Peekha ===
Contributors: Peekha
Tags: clean, simple, company profile, hotel, resort, landing page
Requires at least: 4.7
Stable tag: 1.0.10
Version: 1.0.10
License: GPLv2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html

== Description ==
Peekha is a Wordpress Multipurpose Landing Page Theme. 

== Changelog ==

= 1.0.10 =
* A change since the previous version.

= 1.0.9 =
* A change since the previous version.
* Another change.
```
style.css
```
/*!
  Theme Name: Peekha
  Author: Peekha Team
  Author URI: http://peekha.com
  Theme URI:
  Description: Peekha is a Wordpress Multipurpose Landing Page Theme. 
  Version: 1.0.10
  Tags: landing page, HTML5, CSS3, company profile, hotel, resort
  License: MIT
  License URI: http://opensource.org/licenses/mit-license.php
*/
```
theme folder structure
![Screen Shot 2022-12-25 at 18 08 06](https://user-images.githubusercontent.com/16150261/209465659-003b1f66-6ba8-4a33-b46e-92cdaf939b8d.png)

Thanks

**Comment by YahnisElsts** [comment]
I wonder if this could be unrelated to the update checker. As a test, please comment out all the update checker code, but leave the rest of the code the same. Then push a new version. Does anything happen?

Also, is there anything on the site - like a plugin or some other code in the theme - that tries to control automatic updates? There are ways to enable automatic updates even if the user hasn't explicitly enable them, which would be another possible explanation for how an update can get installed without you seeing a notification.

**Comment by wickborlan** [comment]
wow .. very nice .. its works like my expectation

![Screen Shot 2022-12-26 at 08 20 06](https://user-images.githubusercontent.com/16150261/209487883-fbe3b8f3-0ff9-448e-9bff-3fdfd2c9b5d1.png)

previously I also install wppusher plugin, I deactivate the plugin, push the change to repo .. then the notification showed up

many thanks, @YahnisElsts

**Comment by YahnisElsts** [comment]
Well, I didn't entirely understand that, but it sounds like the issue has been resolved. If not, feel free to reopen it.
