### ISSUE TITLE
Github assets issue (+ fix in PR)

### ISSUE THREAD

**Issue by liedekef** [YahnisElsts/plugin-update-checker#514]
I created a PR  #513 to fix issues with gihub and assets :
- in GitHubApi.php: array_filter keeps the index, so if the asset matching has index 1, an array with key 1 is returned. However, further down, $matchingAssets[0] is always used. This will then fail. Using array_values after array_filter resets the indexes on the array from 0, solving the problem.
- When setting "$myUpdateChecker->setBranch('main');" the setting enableReleaseAssets was ignored. But since on newer github repos "main" is the default (and not "master"), it should allow it (even though it is ok to omit it).

**Comment by YahnisElsts** [comment]
Good catch on the array index issue.

Regarding the `main` branch: I think the way PUC currently handles default branches and associated releases is sub-optimal, but I don't feel like rewriting that logic at this time. I'll merge the change. 

Ideally, enabling release assets should probably enable releases regardless of the selected branch. Also, the existing `vcs_update_detection_strategies` filter should provide an easier way to enable specific strategies, maybe with something like an `$availableStrategies` argument.
