### ISSUE TITLE
Version 3.0 backward incompatible changes

### ISSUE THREAD

**Issue by dangoodman** [YahnisElsts/plugin-update-checker#52]
I have noticed a commit message saying that version 3 is not backward compatible. However, I can't find changes making it so. Would you mind to point me to them? Is it something related to the update server response fields?

Also, is it expected to be safe to use v.3 in a plugin while there is another plugin using an older version, both running on the same WordPress instance?

**Comment by YahnisElsts** [comment]
A few public methods and properties were moved from `PluginUpdateChecker` to a new class called `PucScheduler`:
- `$checkPeriod`
- `$throttleRedundantChecks`
- `$throttledCheckPeriod`
- `maybeCheckForUpdates()`

These changes won't affect most plugins, but they *can* break things for people who use or override those fields to customize how often the library checks for updates.

Also, the `$triggerErrors` parameter was removed from the method `PluginInfo::fromJson`.

**Comment by YahnisElsts** [comment]
> Also, is it expected to be safe to use v.3 in a plugin while there is another plugin using an older version, both running on the same WordPress instance?

Yes, as long as the older plugin instantiates a specific version (i.e. `new PluginUpdateChecker_x_y(...)`). If it's using `PluginUpdateChecker` or `PucFactory::buildUpdateChecker`, there is a (small) chance it might break.

**Comment by dangoodman** [comment]
Thank you.
