### ISSUE TITLE
Customize check period

### ISSUE THREAD

**Issue by baddate** [YahnisElsts/plugin-update-checker#520]
Can I custom the check period? how?

**Comment by YahnisElsts** [comment]
You can pass a custom check period to the `buildUpdateChecker` method as the 4th argument, after the slug:

```php
$myUpdateChecker = PucFactory::buildUpdateChecker(
	'https://example.com/path/to/details.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'unique-plugin-or-theme-slug',
	48 // <-- Check every 48 hours.
);
```

You could also set it to `0` to disable automatic update checks and then set up your own schedule (e.g. using a cron job) that calls `$myUpdateChecker->checkForUpdates()`.

**Comment by baddate** [comment]
thanks! i got it.

>
