### ISSUE TITLE
Plugin Checker doesn't work with private repository GitHub

### ISSUE THREAD

**Issue by AlFazal** [YahnisElsts/plugin-update-checker#524]
I am getting errors using the private repository GitHub 

Image Proff :
[http://alfazalq.online/wp-content/uploads/2023/03/ssa.png](http://alfazalq.online/wp-content/uploads/2023/03/ssa.png)

But when i change repository to public then its working fine 

Please give me the solution

**Comment by cocodedesigns** [comment]
What's the code you're using to get the repo? I have a number of projects in private repos and have so far had no issue with updating through them.

**Comment by YahnisElsts** [comment]
AlFazal and I already discussed this via email yesterday, and we didn't really get anywhere. The code they showed me looked fine, and they said that the access token was correct and had the necessary permissions. If anyone else has some ideas, feel free to chime in.

**Comment by AlFazal** [comment]
> What's the code you're using to get the repo? I have a number of projects in private repos and have so far had no issue with updating through them.

This is the repo code which i am using in my plugin 

 require 'plugin-update-checker/plugin-update-checker.php';
 use YahnisElsts\PluginUpdateChecker\v5\PucFactory;
 
 $myUpdateChecker = PucFactory::buildUpdateChecker(
	 'https://github.com/AlFazal/Testcrypt',
	 __FILE__,
	 'Testcrypt'
 );
 
 //Optional: If you're using a private repository, specify the access token like this:
 $myUpdateChecker->setAuthentication('my token');

$myUpdateChecker->setBranch('main');

**Comment by AlFazal** [comment]
> AlFazal and I already discussed this via email yesterday, and we didn't really get anywhere. The code they showed me looked fine, and they said that the access token was correct and had the necessary permissions. If anyone else has some ideas, feel free to chime in.

Yes , I couldn't found any solution yet , so i came here maybe some other may know this issue , that's why i raised here ticket brother

**Comment by AlFazal** [comment]
I have fixed this issue , how to close this ticket , can you close by ur side please , thank you for the support

**Comment by YahnisElsts** [comment]
All right, closing it now.

**Comment by AlFazal** [comment]
Thank you 👍
