### ISSUE TITLE
Plugin stopped finding updates

### ISSUE THREAD

**Issue by gibonwebb** [YahnisElsts/plugin-update-checker#527]
Hi there, we've been using your package for a long time and have never had any issues. However, we recently encountered a problem with one of our plugins, Plugin X, which is updated regularly through PUC.

When we press the "Check for updates" button, nothing happens. We've checked other plugins on the same site that are also served through PUC, and they are updating fine. All of our plugins are running on v5 of PUC and the latest version of WP.

We've tried troubleshooting through Query Monitor and enabling wp-debug logs, but we haven't found anything that could help us identify the issue. We would appreciate your help in troubleshooting this problem.

Could you please let us know if there are any error messages or other information we can provide to help you diagnose the issue? Thank you!

**Comment by YahnisElsts** [comment]
When you say that "nothing happens", do you mean that you get an admin notice that says there are no updates, or is it that literally nothing happens? Normally, you should get a page refresh and a notice even if PUC isn't able to find any updates.

To get more information about the situation, install the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin and look at the "PUC (your-slug)" tab in the debug bar. Also, try clicking the "Check Now" and "Request Info" buttons in that panel and see if they show the expected information.

**Comment by gibonwebb** [comment]
Thank you so much for the fast help. After installing the Debug Bar. I managed to find the faulty release. The issue was that a release had the wrong version that where higher than the current one.

**Comment by YahnisElsts** [comment]
Sounds like the issue has been resolved, so I will close this now.
