### ISSUE TITLE
using just the main file

### ISSUE THREAD

**Issue by misulicus** [YahnisElsts/plugin-update-checker#53]
If i want to bundle in plugins just plugin-update-checker.php and not use the entire directly it fails because for example `require_once(dirname(__FILE__) . '/github-checker.php');`

any way to use the main plugin file without the rest without commenting manually the not needed lines like the github one ?

**Comment by YahnisElsts** [comment]
No, there's no way to do that without removing/commenting out the `require`'s. If you want a modified version of the library, you will have to, well, *modify* it.
