### ISSUE TITLE
PHP 8.2 Compatibility - Deprecation Notice

### ISSUE THREAD

**Issue by ddur** [YahnisElsts/plugin-update-checker#536]
`Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p1\Plugin\PluginInfo::$request_time_elapsed is deprecated in plugin-update-checker-5.1/Puc/v5p1/Metadata.php on line 55
`

PHP 8.2.6

**Comment by mbsouth** [comment]
I found a quick and dirty hack for myself. I don't know if this is so production-ready, so use at your own risk and please don't beat me up!

Insert into
`...\lib\plugin-update-checker\Puc\v5p1\Metadata.php` line above class definition `#[\AllowDynamicProperties]`:

`[...]`
`#[\AllowDynamicProperties]`
`abstract class Metadata {`
`[...]`

Works for me on 8.2.4
ym2c

**Comment by ddur** [comment]
Thanks, @mbsouth 

This is actually not issue to me, but warning that I guess, may help to the author.

I was testing something else on PHP 8.2.7 with WP_DEBUG on and got it.

When WP_DEBUG is off, warning is gone, but in next major php release (9?) plugin may crash.

**Comment by mbsouth** [comment]
@YahnisElsts

Thanks!
