### ISSUE TITLE
Deprecation notices PHP8

### ISSUE THREAD

**Issue by topwebstudio** [YahnisElsts/plugin-update-checker#539]
Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p1\Plugin\PluginInfo::$status is deprecated  
Deprecated: Creation of dynamic property YahnisElsts\PluginUpdateChecker\v5p1\Plugin\PluginInfo::$error_note is deprecated 

Just need to define those variables in PluginInfo class.

**Comment by YahnisElsts** [comment]
I think this should already be fixed in the `master` branch, I just haven't made a new release since making that commit. Consider trying the development version.

**Comment by ddur** [comment]
@YahnisElsts 

> I think this should already be fixed in the `master` branch, I just haven't made a new release since making that commit. Consider trying the development version.

I made copy of modified files over 5.1 v. 
What you mean by "development version", how to use it?

Thanks

**Comment by YahnisElsts** [comment]
I just meant the unreleased changes in the `master` branch, i.e. code that's "in development". Anyway, that's unnecessary now because I've released version 5.2 which includes those changes.
