### ISSUE TITLE
Using PUC on an external server

### ISSUE THREAD

**Issue by crftwrk** [YahnisElsts/plugin-update-checker#542]
First, thank you very much for this amazing plugin!

I'm trying to get library work on an external url, but failed. The case is that I have a couple of plugins and themes and do not want to include PUC in each plugin/theme. The plan is to install PUC once somewhere in the web and each plugin uses the `plugin-update-checker.php` from there.

For example roughly changing:

```php
require 'plugin-update-checker/plugin-update-checker.php';
```

to

```php
require 'https://update.mydomain.com/plugin-update-checker/plugin-update-checker.php';
```

Is something like this possible?

Thanks in advance

**Comment by YahnisElsts** [comment]
I think that _technically_ this can be done if you enable both [`allow_url_fopen` and `allow_url_include`](https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-include) in your PHP configuration. 

However, I recommend against doing that. It's a security risk. Even if you're sure that nobody can access your server and edit that one file, there's still the problem that enabling those two PHP options allows _all other code_ to load remote PHP files. Also, loading a file from an external URL for every admin page load will have significant performance overhead.

**Comment by crftwrk** [comment]
Thank you, this makes sense.
