### ISSUE TITLE
API for self update function

### ISSUE THREAD

**Issue by Masegi** [YahnisElsts/plugin-update-checker#544]
I'm trien to make my plugin update itself, when I call an api. Its an internal plugin and a server to server connection, so it should be secure enough.

I tried different things, but Plugin_Upgrader always returns "The plugin is at the latest version".

I tried this for example:

`global $tdhPluginUpdateChecker;	
	$plugin_slug = 'justawesome-asd';
	
	$plugin = plugin_basename( sanitize_text_field( wp_unslash( $plugin_slug ) ) );

	$status = array(
		'success'     => false,
		'update'     => 'plugin',
		'slug'       => sanitize_key( wp_unslash( $plugin_slug ) ),
		'oldVersion' => '',
		'newVersion' => '',
		'errorMessage' => '',
	);

	$plugin_data = get_plugin_data( __FILE__ );
	print_r($plugin_data);
	$status['plugin']     = $plugin;
	$status['pluginName'] = $plugin_data['Name'];

	if ( $plugin_data['Version'] ) {
		$status['oldVersion'] = $plugin_data['Version'];
	}

	require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';

	$tmpUpdate = $tdhPluginUpdateChecker->checkForUpdates();
	wp_update_plugins();

	$skin     = new WP_Ajax_Upgrader_Skin();
	$upgrader = new Plugin_Upgrader( $skin );
	// $result   = $upgrader->bulk_upgrade( array( $plugin ) );
	$result   = $upgrader->upgrade( $plugin );

	var_dump($result);
	// print_r($skin->result);

	if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
		$status['debug'] = $skin->get_upgrade_messages();
	}

	if ( is_wp_error( $skin->result ) ) {
		$status['errorCode']    = $skin->result->get_error_code();
		$status['errorMessage'] = $skin->result->get_error_message();
		return $status;
	} elseif ( $skin->get_errors()->has_errors() ) {
		$status['errorMessage'] = $skin->get_error_messages();
		return $status;
	} elseif ( is_array( $result ) && ! empty( $result[ $plugin ] ) ) {
		if ( true === $result[ $plugin ] ) {
			$status['errorMessage'] = $upgrader->strings['up_to_date'];
			return $status;
		}

		$plugin_data = get_plugins( '/' . $result[ $plugin ]['destination_name'] );
		$plugin_data = reset( $plugin_data );

		if ( $plugin_data['Version'] ) {
			$status['newVersion'] = $plugin_data['Version'];
			$status['success'] = true;
		}

		return $status;
	} elseif ( false === $result ) {
		global $wp_filesystem;

		$status['errorCode']    = 'unable_to_connect_to_filesystem';
		$status['errorMessage'] = __( 'Unable to connect to the filesystem. Please confirm your credentials.' );

		// Pass through the error from WP_Filesystem if one was raised.
		if ( $wp_filesystem instanceof WP_Filesystem_Base && is_wp_error( $wp_filesystem->errors ) && $wp_filesystem->errors->has_errors() ) {
			$status['errorMessage'] = esc_html( $wp_filesystem->errors->get_error_message() );
		}

		return $status;
	}

	// An unhandled error occurred.
	$status['errorMessage'] = __( 'Plugin update failed.' );
	return $status;	`

By using code from ajax updater and trien to make plugin-update-checker inject the external plugin.

So basicly my target is an function call to check and update plugin by rest api.

**Comment by YahnisElsts** [comment]
Does the update show up in "Dashboard -> Updates"? If it doesn't, there might be a problem with PUC initialization or configuration. If it does, the problem might be something more complicated.

**Comment by Masegi** [comment]
Yes, when I do update by dashboard its already working fine

**Comment by YahnisElsts** [comment]
Hmm, I don't see an obvious reason why it wouldn't work then. Since you're already doing some output/logging in that code, could you also dump the `site_transient_update_plugins` site transient just after the `checkForUpdates` call to see if your plugin is getting added to the update list or not? 

You could also try calling the `getUpdate` method on PUC and dump the result. This is to see if PUC itself knows that there is an update. It should return either update details or NULL.

**Comment by Masegi** [comment]
ok the plugin is shown in the object but im note sure if version is correc,t in the checked propery is the current version shown not the outstanding, but when I look at return of PUC checkForUpdates it shows next version as expected. But in the object[pluginname] property is the next / coming version, so hat seem to be correct.

**Comment by Masegi** [comment]
just to get sure, it looks like this:

`PUC->checkForUpdates:

Array
(
    [WC requires at least] => 
    [WC tested up to] => 
    [Woo] => 
    [Name] => TDH CRM Frontend
    [PluginURI] => https://www.justaswesome.de
    [Version] => 1.0.508
    [Description] => TDH | www.JustAwesome.de  [justawesome-tdh-konfigurator site="VerkaufskanalNameKurz" mode="both"] mode options: both, contact, 3d, b2b | debug = true und beta = true für admin tests <cite>By <a href="https://www.justawesome.de/ueber-uns/">Matthias Graffe</a>.</cite>
    [Author] => <a href="https://www.justawesome.de/ueber-uns/">Matthias Graffe</a>
    [AuthorURI] => https://www.justawesome.de/ueber-uns/
    [TextDomain] => justawesome-tdh
    [DomainPath] => 
    [Network] => 
    [RequiresWP] => 
    [RequiresPHP] => 
    [UpdateURI] => 
    [Title] => <a href="https://www.justaswesome.de">TDH CRM Frontend</a>
    [AuthorName] => Matthias Graffe
)

upgrader->upgrade( $plugin ):

YahnisElsts\PluginUpdateChecker\v5p2\Plugin\Update Object
(
    [id] => 0
    [homepage] => https://www.justawesome.de/
    [upgrade_notice] => 
    [tested] => 6.2.999
    [requires_php] => 
    [icons] => Array
        (
        )

    [filename] => justawesome-tdh/justawesome-tdh.php
    [slug] => justawesome-tdh
    [version] => 1.0.509
    [download_url] => https://crm-dev.terrassendach-haendler.de/resources/_plugin/justawesome-tdh.zip
    [translations] => Array
        (
        )

    [extraProperties:protected] => Array
        (
        )

)

get_site_transient('update_plugins'):
object(stdClass)#36101 (5) {
  ["last_checked"]=>
  int(1697810681)
  ["response"]=>
  array(3) {
    ....
    ["justawesome-tdh/justawesome-tdh.php"]=>
    object(stdClass)#36102 (8) {
      ["slug"]=>
      string(15) "justawesome-tdh"
      ["new_version"]=>
      string(7) "1.0.509"
      ["package"]=>
      string(79) "https://crm-dev.terrassendach-haendler.de/resources/_plugin/justawesome-tdh.zip"
      ["id"]=>
      int(0)
      ["url"]=>
      string(27) "https://www.justawesome.de/"
      ["tested"]=>
      string(7) "6.2.999"
      ["requires_php"]=>
      NULL
      ["plugin"]=>
      string(35) "justawesome-tdh/justawesome-tdh.php"
    }
  }....
  }
  ["checked"]=>
  array(39) {
    ...
    ["justawesome-tdh/justawesome-tdh.php"]=>
    string(7) "1.0.508"
	...
  }
}`

**Comment by YahnisElsts** [comment]
That looks fine-ish to me. 

Are you sure you're passing the correct value to `$upgrader->upgrade()`? The PHPDoc for that method says the argument should be:
> Path to the plugin file relative to the plugins directory.

Usually, this will look something like `foo/bar.php`. Does the `$plugin` value look like that at that point, or is it something else?

**Comment by Masegi** [comment]
Thanks for your ast response again btw.

its working fine now, did it like this:
``
function pluginname_asd_upgrade_plugin( ) {
	global $tdhPluginUpdateChecker;	
	
	$plugin_slug = 'pluginname-asd';
	$plugin_base_name = $plugin_slug.'/'.$plugin_slug.'.php';
	
	$plugin = plugin_basename( sanitize_text_field( wp_unslash( $plugin_base_name ) ) );

	$status = array(
		'success'     => false,
		'update'     => 'plugin',
		'slug'       => sanitize_key( wp_unslash( $plugin_slug ) ),
		'oldVersion' => '',
		'newVersion' => '',
		'errorMessage' => '',
	);

	// if ( ! current_user_can( 'update_plugins' ) || 0 !== validate_file( $plugin ) ) {
		// $status['errorMessage'] = __( 'Sorry, you are not allowed to update plugins for this site.' );
		// return $status;
	// }
	
	$plugin_data = get_plugin_data( __FILE__ );
	$status['plugin']     = $plugin;
	$status['pluginName'] = $plugin_data['Name'];

	if ( $plugin_data['Version'] ) {
		$status['oldVersion'] = $plugin_data['Version'];
	}

	require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';

	$tdhPluginUpdateChecker->checkForUpdates();
	wp_update_plugins();

	$skin     = new WP_Ajax_Upgrader_Skin();
	$upgrader = new Plugin_Upgrader( $skin );
	
	if($upgrader->upgrade( $plugin ))
	{	 
		$plugin_data = get_plugin_data( __FILE__ );

		if ( $plugin_data['Version'] ) {
			$status['newVersion'] = $plugin_data['Version'];
			$status['success'] = true;
		}
		activate_plugin( $plugin_base_name );
		return $status;
	} 
	else
	{
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			$status['debug'] = $skin->get_upgrade_messages();
		}

		if ( is_wp_error( $skin->result ) ) {
			$status['errorCode']    = $skin->result->get_error_code();
			$status['errorMessage'] = $skin->result->get_error_message();
			return $status;
		} elseif ( $skin->get_errors()->has_errors() ) {
			$status['errorMessage'] = $skin->get_error_messages();
			return $status;
		} elseif ( false === $result ) {
			global $wp_filesystem;

			$status['errorCode']    = 'unable_to_connect_to_filesystem';
			$status['errorMessage'] = __( 'Unable to connect to the filesystem. Please confirm your credentials.' );

			// Pass through the error from WP_Filesystem if one was raised.
			if ( $wp_filesystem instanceof WP_Filesystem_Base && is_wp_error( $wp_filesystem->errors ) && $wp_filesystem->errors->has_errors() ) {
				$status['errorMessage'] = esc_html( $wp_filesystem->errors->get_error_message() );
			}

			return $status;
		}
	}
	// An unhandled error occurred.
	$status['errorMessage'] = __( 'Plugin update failed.' );
	return $status;	
}
 
function pluginname_asd_api_update( WP_REST_Request $request ) {			
	$returnObj = array();	
	$returnObj['success'] = false;
	
	$data = $request->get_params();
	if($data['key'] == 'o38wf42348ngo832ng4o')
	{				
		$returnObj = pluginname_asd_upgrade_plugin();
	}	
	return $returnObj;
}

add_action( 'rest_api_init', function () {
  register_rest_route( 'pluginname-asd/v1', '/update', array(
    'methods' => 'POST',
    'callback' => 'pluginname_asd_api_update',
    'permission_callback' => '__return_true',
  ) );
  register_rest_route( 'pluginname-asd/v1', '/update', array(
    'methods' => 'GET',
    'callback' => 'pluginname_asd_api_update',
    'permission_callback' => '__return_true',
  ) );
} );``

**Comment by YahnisElsts** [comment]
All right. Since the problem appears solved, I will close this issue now.
