### ISSUE TITLE
Attractive proposal for development

### ISSUE THREAD

**Issue by mehdi-najaran** [YahnisElsts/plugin-update-checker#555]
Hello good time
First of all, thank you for your complete and excellent project.
Respectfully, I had a suggestion, I would be happy to check it:

Now we have to manually put the raw html in the "" of the json file to provide the description and change log. If this section contains a lot of content, managing and changing it is annoying

The suggestion I had is to put the link of an html file for each section in json, so that file can be executed in the desired section.

for example :
```
"sections": {
    "description": "load_from_file:descriptions.html",
    "installation": "load_from_file:installation.html",
    "changelog": "load_from_file:changelog.html"
  }
  ```

**Comment by YahnisElsts** [comment]
There is already another, more complete solution for generating the metadata JSON: [wp-update-server](https://github.com/YahnisElsts/wp-update-server). When using that, you only need to write the description and changelog in the readme.txt file, like you would for a free plugin hosted on wordpress.org. The update server will automatically extract the readme from your ZIP file, parse it into sections, and include it in the JSON.

**Comment by mehdi-najaran** [comment]
I checked it now, it was interesting!
But still I am more comfortable with the current project

I wish you implement this feature that I said!

**Comment by YahnisElsts** [comment]
Sorry, I don't think I'm going to make a second, separate implementation of this.
