### ISSUE TITLE
My Plugin Has Update. but WP shows it's up-to-date

### ISSUE THREAD

**Issue by AP-Totalogistix** [YahnisElsts/plugin-update-checker#556]

**Comment by AP-Totalogistix** [comment]
<?php
/*
	Plugin Name: ShipSmart TMS Plugin
	Plugin URI: https://shipsmarttms.com/
	Description: Rates from ShipSmart TMS
	Version: 1.0.0
	Author: Aptean
	Author URI: https://shipsmarttms.com/
	*/
require 'plugin-update-checker/plugin-update-checker.php';
use YahnisElsts\PluginUpdateChecker\v5\PucFactory;

$updateChecker = PucFactory::buildUpdateChecker(
    'https://github.com/AP-Totalogistix/YB_WooCommerce_Plugin/', // The exact URL to your GitHub repository
    __FILE__, // Full path to the main plugin file
    'WP_YB_WooCommercePlugin' // Unique slug. If your plugin is hosted on WordPress.org, this should match your WordPress.org plugin's slug.
);

$updateChecker->setAuthentication('ghp_*****');

$updateChecker->setBranch('master');

**Comment by AP-Totalogistix** [comment]
My verison is 3 but in verison it shows 1.0.0

<img width="635" alt="image" src="https://github.com/YahnisElsts/plugin-update-checker/assets/60214473/473ab33c-3e4b-463c-91e2-4fb7f1569668">

**Comment by YahnisElsts** [comment]
Does the `Version` header in the plugin file have the correct version number?
