### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by mehdi-najaran** [YahnisElsts/plugin-update-checker#557]
Hello . I have used your project on my personal plugin.

And I have installed it on different sites and there were no problems

Until one of the sites faces a WordPress error after installation and activation.

Error text:

```
YahnisElsts\P\v\P\UpdateChecker::__construct()
wp-content/plugins/my-plugin-name/include/update-checker/Puc/v5p3/PucFactory.php:122
YahnisElsts\P\v\PucFactory::buildUpdateChecker()
wp-content/plugins/my-plugin-name/include/setup-plugin.php:12
dw_auto_update_setup()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:348
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-settings.php:506
require_once()
wp-config.php:182
require_once()
wp-load.php:50
require_once()
wp-blog-header.php:13
require()
index.php:17
```

**Comment by mehdi-najaran** [comment]
Yes, as I said above, on a large number of sites it was without problems and the project worked without errors

It is like this only on 2-3 sites

![Untitled-3](https://github.com/YahnisElsts/plugin-update-checker/assets/84453959/619c36cc-f792-4b90-a12f-b3eb58d8a191)

**Comment by YahnisElsts** [comment]
Could be a namespace-related bug. Please try this: open that file and replace line 4

```php
if ( !class_exists('Ui', false) ):
```

with this:

```php
if ( !class_exists(Ui::class, false) ):
```

**Comment by mehdi-najaran** [comment]
Yes, problem solved
