### ISSUE TITLE
Request : Please Update *How to Release an Update* Section

### ISSUE THREAD

**Issue by dev0098** [YahnisElsts/plugin-update-checker#560]
Due to the fact that I could not check the new version of the theme with the DebugBar plugin and I was facing an error, I used the [WP Crontrol plugin](https://wordpress.org/plugins/wp-crontrol/) for this and performed the new version check event with it, which was a much better method.
Please add this item to your script tutorial if approved

**Comment by YahnisElsts** [comment]
If there is a problem with the DebugBar integration, I think I would rather fix it than discard the plugin immediately. Also, in addition to manually running update checks, the DebugBar integration displays various debugging information, so it cannot be completely replaced with WP Crontrol.

Could you elaborate on what error you ran into and how it's related to the DebugBar plugin?

**Comment by dev0098** [comment]
I was receiving an error with the following text while using the DebugBar plugin
The URL … does no point to a valid plugin metadata file.

But the addresses of all the files were completely correct.
And after many searches on the Internet, I did not get the result.
And because your script was executed in a cron job, I thought to use the WP Conntrol plugin instead of the Debugbar plugin.
In my first test with the WP Conntrol plugin, the result was positive, and checking the new version of the theme was also successful
My suggestion is that as a complementary method, add the WP Conntrol plugin in the tutorial section of the script
