### ISSUE TITLE
How to set up a Github App for a private repository

### ISSUE THREAD

**Issue by gerardreches** [YahnisElsts/plugin-update-checker#561]
We used to have access tokens, but they are now gone and we have to create a "GitHub App". The form makes me wanna shoot myself, I can't understand what do I need to check to get a token to use in PUC.

Is there any tutorial on how to set up a GitHub App to use PUC with a private GitHub repository?

Not only that, but after creating the GitHub App they ask you to generate a private key, which automatically downloads a file. What am I supposed to do with all of this? I want just the old good plain access token...

Any help on how to set up a private GitHub repo?

**Comment by YahnisElsts** [comment]
What's that about access tokens being gone? I still see a "Personal access tokens" section under my developer settings. I tested one of the fine-grained access tokens just now and it still works fine. Are you sure they are supposed to be gone?

**Comment by gerardreches** [comment]
@YahnisElsts Where do you go to find it? I go to `Settings > Developer settings` and... Ah! Thanks god. I see it now. I could only find documentation about GitHub Apps when I was googleing for the access tokens plus some comment I read about that they had changed the system, so I must have rushed it and did not see the other options on the sidebar when I arrived there.

I had even made my repo public to be able to receive the updates without the access token.

Thank you!!!!
