### ISSUE TITLE
Plugin Description and Changelog

### ISSUE THREAD

**Issue by hupe13** [YahnisElsts/plugin-update-checker#565]
I'm trying to integrate PUC 5.4 into my [plugin](https://github.com/hupe13/extensions-leaflet-map-dsgvo). Updates are working as expected, but the "Description" and "Changelog"  don't seem to work properly. 

I use [tags](https://github.com/hupe13/extensions-leaflet-map-dsgvo/tags). If I want to see details I get as "Description"  the "Description" line from [plugins php file](https://github.com/hupe13/extensions-leaflet-map-dsgvo/blob/main/leafext-dsgvo.php#L4C1-L4C67):
` * Description:       DSGVO Snippet for Extensions for Leaflet Map`

The "Changelog" is from [changes.md](https://github.com/hupe13/extensions-leaflet-map-dsgvo/blob/main/changes.md). This is fine.

I tested to publish a Release. But there I got the "Description" as above and the "Changelog" is the description of the release.

I want to see in "Description" the content of [readme.md](https://github.com/hupe13/extensions-leaflet-map-dsgvo/blob/main/readme.md) and if I published a release I would like to get the content of changes.md in "Changelog". 

The compatibility with WordPress 6.4.3 is unknown, although this is specified.

Am I understanding or doing something wrong? How does it work properly?

Thank you very much.

**Comment by YahnisElsts** [comment]
Generally speaking, PUC tries to emulate how updates work for plugins hosted on wordpress.org. Everything else is an added-on extra. So the best-supported path is to structure your plugin as if you were going to upload it to the wordpress.org plugin directory.

In this case, that means having a `readme.txt` file that follows the [WordPress plugin readme standard](https://wordpress.org/plugins/readme.txt). If a valid `readme.txt` exists, PUC will parse it and take the description and changelog from there. Using `changes.md` and release descriptions are fallback strategies.

**Comment by hupe13** [comment]
Then that was my mistake. Plugins in the WordPress reposority do not necessarily need a readme.txt, a readme.md will do the job also. Then I will provide a readme.txt for PUC and a readme.md for Github.

Thank you very much.

**Comment by YahnisElsts** [comment]
> Plugins in the WordPress reposority do not necessarily need a readme.txt, a readme.md will do the job also.

Hmm, I wasn't aware of that. Looking at [the documentation](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/), I see no mention of `readme.md`. Is it one of those things where it's not "officially" supported but it works anyway?

**Comment by hupe13** [comment]
See [here](https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/). I don't have a readme.txt in [Extensions for Leaflet Map](https://plugins.trac.wordpress.org/browser/extensions-leaflet-map/tags/4.1) .

**Comment by YahnisElsts** [comment]
I see, thanks for the information.

**Comment by hupe13** [comment]
For the sake of completeness: There is a difference between my WordPress readme.md and the Github readme.md in the  FAQ section.
