### ISSUE TITLE
Add greek translation

### ISSUE THREAD

**Issue by theo-gk** [YahnisElsts/plugin-update-checker#571]
Hello, could you please add the greek translation for the update checker?

i18n files attached
[el_translation.zip](https://github.com/YahnisElsts/plugin-update-checker/files/15268407/el_translation.zip)

Thank you,
Theo

**Comment by YahnisElsts** [comment]
Thanks, I added it in [040a2ef](https://github.com/YahnisElsts/plugin-update-checker/commit/040a2ef65832ce4486f8ab1b5fdb5631a6dbc076).
