### ISSUE TITLE
No update triggered if style.css is not in root of repo

### ISSUE THREAD

**Issue by nick-panelco** [YahnisElsts/plugin-update-checker#583]
The updates do not trigger if the style.css file in not in the root of the repo. 

Sometimes I have files that need to be version-controlled in the root of WP (where wp-content / wp-admin directories are), so cannot move to root to the theme itself.

Other than using the json file in the root, is there a way to get an update merged to a production branch in Git to trigger an update?

**Comment by YahnisElsts** [comment]
That's not a supported repository layout. You _might_ be able to work around it by creating a tag or release for each update, but even then, the generated ZIP archive has to have a particular directory structure (one directory at root, theme files including `style.css` in that directory). If the theme files are in some deeper subdirectory, the update most likely won't install correctly.
