### ISSUE TITLE
PHP 8.4: Implicitly nullable parameter declarations deprecated

### ISSUE THREAD

**Issue by kkataria3010** [YahnisElsts/plugin-update-checker#585]
### Getting these warnings on updating to php v8.4.1

> [16-Dec-2024 19:06:12 UTC] PHP Deprecated:  Puc_v4p13_StateStore::setUpdate(): Implicitly marking parameter $update as nullable is deprecated, the explicit nullable type must be used instead in /Applications/MAMP/htdocs/wp-content/plugins/updraftplus/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p13/StateStore.php on line 79

>[16-Dec-2024 19:06:12 UTC] PHP Deprecated:  Puc_v4p13_UpdateChecker::fixSupportedWordpressVersion(): Implicitly marking parameter $update as nullable is deprecated, the explicit nullable type must be used instead in /Applications/MAMP/htdocs/wp-content/plugins/updraftplus/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p13/UpdateChecker.php on line 360

### Problem

[`public function setUpdate(Update $update = null) {`](https://github.com/YahnisElsts/plugin-update-checker/blob/master/Puc/v5p5/StateStore.php#L80)

Setting `$update` to `null` as default value is throwing this warning.
### Solution

`public function setUpdate(?Update $update = null) {`

### Reference Article
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

**Comment by YahnisElsts** [comment]
This library still supports old PHP versions like PHP 5.6.20, so using nullable types doesn't work. As far as I know, those were introduced in PHP 7.1. I don't currently see a good way to avoid that deprecation notice without breaking backwards compatibility.

**Comment by matzeeable** [comment]
@YahnisElsts is there any ETA when PHP 5 support will be dropped?

**Comment by YahnisElsts** [comment]
I don't have a specific timeframe in mind. Looking at the [WordPress.org PHP version stats](https://wordpress.org/about/stats/#php_versions), I think it would be fine to drop PHP 5 now (~3.3% usage). However, if I were to change PHP requirements, I would want to go to at least PHP 7.4, and >10% of sites are still running PHP versions older than that. It would be an easier choice if it was below 5%.
