### ISSUE TITLE
Hangs on "Updating..." even when plugin was updated succesfully

### ISSUE THREAD

**Issue by markpatx** [YahnisElsts/plugin-update-checker#60]
I am doing some tests and encountered a small issue. When clicking the "update now" link on the wp-admin/plugins.php page after a new update is available, entering the ftp details and clicking proceed, wp says "Updating..." and shows the rotating icon, and it never finish. But when I open the site again, the plugin was updated successfully. Could it be a problem with my setup? Updating from wp-admin/update-core.php shows no errors and it updates fine.

update: Nevermind, now it works fine, not sure what happened.

**Comment by GrapsasFilippos** [comment]
The name of the plugin main file and the name in ajax response must be equals.

**Comment by YahnisElsts** [comment]
It could also be a plugin conflict. A bug in any other active plugin that causes it to output an error message (or any other unexpected output, really) could break the AJAX response that WordPress generates when you click the "update now" link.
