### ISSUE TITLE
after update complete my plugin folder name changed

### ISSUE THREAD

**Issue by PetyaxD** [YahnisElsts/plugin-update-checker#61]
Hello, can u help me whats the problem. I updating the plugin and after update complete, i go to plugins dir and the plugin folder name is changed like plugin-name-"deaf324" --> this is always a random key.
Any idea? thanks

**Comment by YahnisElsts** [comment]
That usually happens when your ZIP file directory structure is incorrect. The update checker is supposed to fix that automatically, but the automatic workaround is not 100% reliable.

To fix this problem, 1) make sure you're using the latest version of the update checker, 2) when creating the ZIP file, ensure the plugin files are in a subdirectory that matches the plugin's slug.

Correct:
```
filename.zip
    /plugin-slug
        /includes
        plugin-slug.php
        readme.txt
        other plugin files
```

Incorrect:
```
filename.zip
    /includes
    plugin-slug.php
    readme.txt
    other plugin files
```

**Comment by PetyaxD** [comment]
i use the correct format and the latest version :/ any other idea?

**Comment by YahnisElsts** [comment]
Are you *sure* that the directory structure is correct? Some users have reported that certain ZIP applications (especially on Mac OS X) display the structure in a misleading way where it *looks* like the files are in a directory when they actually aren't. 

Could you perhaps send me the file for testing? If you don't want to post it here, you can contact me via email: `whiteshadow@w-shadow.com`.

**Comment by PetyaxD** [comment]
yes, I'm an OS X user, but i think a have the correct structure. here is the file, 
[webcreatives-core.zip](https://github.com/YahnisElsts/plugin-update-checker/files/288338/webcreatives-core.zip)

**Comment by YahnisElsts** [comment]
Looks like it's mostly correct, but the ZIP file has a `_MACOSX` subdirectory. Try removing that and updating again.

**Comment by PetyaxD** [comment]
nice, it works :) thanks a lot !!! and thanks for the script to :)
