### ISSUE TITLE
Getting "Update Failed: The directory structure of the update is incorrect." (When directory structure appears to be correct)

### ISSUE THREAD

**Issue by rbenhase** [YahnisElsts/plugin-update-checker#62]
Hello,

I'm trying to use both the plugin update checker and the [WP update server](https://github.com/YahnisElsts/wp-update-server). As far as I can tell, the update server is working fine; visiting http://myserver.com/wp-update-server/?action=get_metadata&slug=my-plugin gives me a nice JSON output.

However, when updating plugins, the update checker (3.1) successfully recognizes that an update is available, but whenever I actually attempt the update, I get this message: 

"Update Failed: The directory structure of the update is incorrect. All plugin files should be inside a directory named [directory-name], not at the root of the ZIP file."

Note: [directory-name] here is where the actual directory name appears. 

I've triple-checked that the ZIP file specified by "download_url" in the JSON output expands to create a single folder, with all plugin files and subdirectories contained inside it. All plugin files are indeed inside a directory with the same name as the plugin slug, not at the root of the ZIP. As far as I can tell, the directory structure is correct:

pluginname.zip -> extracts to create -> pluginname (directory) -> which contains pluginname.php (along with other plugin files)

I've also tried creating an alternate directory structure by nesting the pluginname folder inside ANOTHER directory by the same name, then zipping it up for the updater to use. When I do that, I receive a 500 Error from the update server, telling me that no valid package was found.

This has to be a bug, right? Or am I nuts?

**Comment by YahnisElsts** [comment]
Are you on OS X and using the built-in ZIP tools, by any chance? Several users have reported that it presents ZIP directory structure in a misleading way - it makes it look like the files are inside a directory when they actually aren't.

Also, could you post (or email) a sample ZIP file? I don't need the entire plugin - just a ZIP with the plugin directory, the main plugin file, and the readme.txt will do. You can basically make a copy of your update ZIP and delete everything non-essential. I'd like to test it locally and see if I can reproduce the error that you mentioned.

If you don't want to post it publicly, you can email it to whiteshadow@w-shadow.com

**Comment by rbenhase** [comment]
I am indeed on OS X, using built-in ZIP tools, so that could definitely be the issue. I guess the only odd thing is that the update server doesn't accept my package when I nest the plugin files inside a directory, then ZIP it up.

I'd be happy to email you a sample ZIP file -- should be coming shortly.

For now, I may try to use the GitHub updater instead. Thanks for the response!

**Comment by YahnisElsts** [comment]
Thank you, I've received the file. It's as I suspected - the files are at the root of the ZIP, not in a directory.

Consider using a different ZIP archiver. I'm not really familiar with OS X, but surely there must be some third-party options available.

**Comment by rbenhase** [comment]
Thanks. For now, I just went ahead and switched to hosting my codebase on
GitHub (and using the GitHub updater instead). Works like a charm.

Ryan
