### ISSUE TITLE
Lovely plugin but getting PHP notice with PHP 7

### ISSUE THREAD

**Issue by ayanize** [YahnisElsts/plugin-update-checker#67]
Hello,

This is a must have plugin for all theme developers. Thanks for this. But with PHP 7, we are getting the following PHP warnings and notices 

`PHP Fatal error:  Uncaught Error: Call to undefined method PluginUpdateChecker_3_0::getCronHookName() in /absolute-path/plugins/ac-shortcodes/files/updater/debug-bar-panel.php:79`

`#0 /absolute-path/plugins/debug-bar/debug-bar.php(244): PluginUpdateCheckerPanel->render()`
`#1 /absolute-path/wp-includes/plugin.php(524): Debug_Bar->render('')`
`#2 /absolute-path/wp-admin/admin-footer.php(72): do_action('admin_footer', '')`

**Comment by YahnisElsts** [comment]
It looks like the plugin is using an older version of the library. Have you tried the latest release (3.1)?

**Comment by ayanize** [comment]
Thanks for your quick reply. No I have not used the latest 3.1. Let me try this now and update this thread. Once again thanks for this awesome library.

**Comment by YahnisElsts** [comment]
Any updates on this issue? Did 3.1 fix it?

**Comment by indikatordesign** [comment]
It's fixed with this version, yes..

Like ayanize, I thank you for this great plugin..!

**Comment by YahnisElsts** [comment]
All right, that's good to hear.
