### ISSUE TITLE
Multisite with SSH sits in maintenance mode

### ISSUE THREAD

**Issue by davidpMFA** [YahnisElsts/plugin-update-checker#69]
I have a plugin that allows me to update plugins, themes, etc. over SSH by providing cred. (SSH SFTP Updater Support). When I update anything I get a popup with SFTP, SSL, an SSH as options (SFTP and SSL are the defaults in WP). This happens when I try to update with your code as well so all is good.

However, when I choose to update the circles for the update action spins with the text "updating" and that's it. It never actually updates. I don't get an errors and I checked the server error logs. The site stays in maintenance mode and I have to delete the `.maintenance` file to delete it.

I don't think the SSH is the issue since I get that popup like normal. And other plugins update as expected. Any ideas?

**Comment by YahnisElsts** [comment]
That's strange, it sounds like a server-side error of some kind, so it should be logged _somewhere_. Did you look at the site specific log or the global Apache & PHP logs? Depending on the PHP configuration, some errors might not be logged in the place that you would expect. Also, are there any error messages in the browser's JS console when the progress indicator gets stuck?

I'll check _SSH SFTP Updater Support_ source code to see if it does anything unusual with plugin update information, but I doubt I'll find anything.

**Comment by davidpMFA** [comment]
No errors in the console. I turned on `wp_debug_log` to try to capture any of the ajax issues there. I don't have any other logs aside from what's in the standard `/etc/httpd/logs/` directory.

**Comment by davidpMFA** [comment]
My organization has a CDN service that cache's the most recent version of our files. I pointed the update to the CDN so the files are pulling from a CDN not our servers. I get the same issue. I still get a similar error, `Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

**Comment by YahnisElsts** [comment]
> Actually I let it run for a while and I got a `503 (Service Unavailable)` for `/wp-admin/admin-ajax.php`

That's probably just another side-effect of the site being in maintenance mode. The "Maintenance" page returns status code 503 by default.

> My organization has a CDN service that cache's the most recent version of our files. [...]

Does the CDN have a domain whitelist or something like that? How about firewalls filtering outgoing HTTP requests? Maybe WordPress gets a network timeout or an error when it tries to download the update package because the update is hosted on an "untrusted" domain.

Also, try starting the update from _Dashboard -> Updates_ or opening the "update now" link in a new tab to get more information about the update process. It should at least show you the step where it gets stuck - when downloading the package, or when uploading the new files, etc.

**Comment by davidpMFA** [comment]
I opened the updater in a new window and found it got stuck deleting the old version (downloaded and unpacked fine). I checked the permissions on the plugin (root directory) and found it had the wrong `owner:group` settings. I fixed it with a `chmod` and then I was able to update it. 

This is resolved and anyone else who gets stuck like this should check file permissions. Thanks for all your help!

**Comment by YahnisElsts** [comment]
All right, it's good to hear that you figured it out.
