### ISSUE TITLE
[ASK] Doing login authentication before upgrade the plugin

### ISSUE THREAD

**Issue by resarahman** [YahnisElsts/plugin-update-checker#7]
Hi there,

Is there a way to add some authentication before downloading new file update ? I would like when click button "update now" it will perform authentication first to the download server and once the authentication is valid then proceed the downloading.

Could you point me to some hooks in this class to achieve this if any ?

Nice class btw !!

Thanks

**Comment by YahnisElsts** [comment]
Closing this again due to lack of activity.
