### ISSUE TITLE
PluginUpdate conflict

### ISSUE THREAD

**Issue by acharyasarvesh** [YahnisElsts/plugin-update-checker#70]
I am using two plugins i2sdk and wpachievements, both of them are using this update library. One works fine alone but after activating the second one i get
Plugin could not be activated because it triggered a fatal error.

**Comment by YahnisElsts** [comment]
Could you please provide the actual PHP error message? It should be in your PHP error log.

In general, two plugins using this library shouldn't cause any problems unless they're both using a very, *very* old version of it.

**Comment by acharyasarvesh** [comment]
PHP message: PHP Fatal error:  Class 'PluginUpdateChecker_1_4' not found in /var/www/html/trc-premium/wp-content/plugins/i2sdk2/lib/plugin-update-checker.php on line 939" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /trc-premium/wp-admin/plugins.php?action=error_scrape&plugin=wpachievements%2Fwpachievements.php&_wpnonce=8e87d1e1d9 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost", referrer: "http://localhost/trc-premium/wp-admin/plugins.php?plugin=wpachievements%2Fwpachievements.php"

**Comment by YahnisElsts** [comment]
Thank you. As expected, the plugin is using an old version of the update checker - version 1.4 was released more than two years ago.

Ideally, the plugin author(s) should upgrade to the latest release. There's a good chance that this would fix the error. Maybe you could report the error to them and suggest this as a possible solution?
