### ISSUE TITLE
Add in Persian

### ISSUE THREAD

**Issue by Pro-Style** [YahnisElsts/plugin-update-checker#72]
Hello
Persian language file for Wordpress Persian
Thanks

[plugin-update-checker-fa_IR.zip](https://github.com/YahnisElsts/plugin-update-checker/files/554530/plugin-update-checker-fa_IR.zip)

**Comment by YahnisElsts** [comment]
Thank you. Could you please also include the .po file?

**Comment by Pro-Style** [comment]
Are you need it?
I can upload po file if u need this.
This file is only mo file

**Comment by Pro-Style** [comment]
I use plugin-update-checker for pro Persian plugin ( Pro Persian plugin translated bbpress & bodypress to Persian WP language )
For Auto update ability we use your source 
Thanks for plugin-update-checker 😉

**Comment by YahnisElsts** [comment]
Yes, having the .po file would be useful. This way, if there's some new text to translate in the future and the original translator (i.e. you) is not available, someone else can easily update the translation.

**Comment by Pro-Style** [comment]
ok 
its po & mo in languages.zip file
[languages.zip](https://github.com/YahnisElsts/plugin-update-checker/files/558189/languages.zip)
best regards
