### ISSUE TITLE
Duplicate DB Option

### ISSUE THREAD

**Issue by prowp** [YahnisElsts/plugin-update-checker#73]
If you have two plugins that have a generic name for the base file (i.e. plugin.php), the db option is duplicate and it causes malfunctions in updates ( a cross up between the plugins). Not really sure if this is something that will affect many, might just be an item to add to documentation.

**Comment by YahnisElsts** [comment]
This can be easily avoided by setting the plugin slug explicitly:

```php
$myUpdateChecker = PucFactory::buildUpdateChecker(
	'http://example.com/path/to/metadata.json',
	__FILE__,
	'unique-plugin-slug'
);

I've added a note about this to the readme.

**Comment by YahnisElsts** [comment]
I've also updated the library to throw an error if it detects a duplicate slug. See 93c9d661d5e8a2a755bf11f2538533e18d564bd6
