### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by amiga-500** [YahnisElsts/plugin-update-checker#76]
Every WP plugin updater ive seen online besides yours makes use of the **_pre_set_site_transient_update_plugins_** filter and then verifies that the **`->checked`** object exists and if so then it adds its response to the transient object if their plugin is new.   This is what supposedly will trigger an alert (when plugins are being checked by WP) and a new version exists.  Here is an example code:

```php

add_filter( 'pre_set_site_transient_update_plugins', array( $this, 'api_check' ) );

public function api_check( $transient ) {
   // Check if the transient contains the 'checked' information
  // If not, just return its value without hacking it

   if ( empty( $transient->checked ) )
      return $transient;

   // check the version and decide if it's new
   $update = version_compare($this->new_version, $this->current_version);

   if ( 1 === $update ) {
      $response = new stdClass;
      $response->new_version = $this->new_version;
      $response->slug = $this->slug;
      $response->url = $this->url;
      $response->package = $this->zip_url;
      $response->tested = $this->tested_version;

      // If response is false, don't alter the transient
      if ( false !== $response ) {
         $transient->response[ $this->slug] = $response;
      }
   }

   return $transient;
}
```

Curious, why didn't you do this approach for your updater?  More specifically, why arent you using the pre_ filter and its corresponding ->check?  Is there a flaw in this approach?  From what i can see you just go about setting up a wp cron scheduled event to trigger when you do your version checks.  So again, just wondering why that approach and not the most common approach as outlined above.

Interestingly, from my tests, by modifying the _update_plugins_ field (to more than 12 hours old) in the _wp_options_ table of the db and then triggering the _wp_versions, wp_update_plugins_ crons to start now i find that no update ever gets notified even tho a new version exists  Cant figure out why.  The filter is being called correctly but because the _update_plugins_ entry in the database doesnt have a `->checked` section the updater never gets triggered.

However, if I click the "**Check Again**" button (found within WP's admin _Update_ tab) then the _->checked_ field is created and the updater performs as expected.

Love to hear your thoughts on the matter and the reasoning for your choices...maybe you noticed this issue and why you went with using different wp filters?

Thanks for the info.

**Comment by YahnisElsts** [comment]
There are actually a couple of design differences here.

1. Checking for updates on an independent schedule instead of doing at the same time as WordPress. Reasons:
    - Customization. Using an independent cron schedule lets plugin developers choose their own update frequency. 
    - Performance. A custom schedule enables optimizations like checking less often when we already know that an update is available.
    - Robustness. Using a separate cron event helps ensure that an unexpected timeout the update checker (e.g. due to the update server being overloaded and slow) won't interfere with the normal update process. If you run your update check when WordPress is about to update the `update_plugins` transient, there's a (small) risk that a bug or delay in your script could break updates for *all* plugins.
2. Inserting the update on read (`site_transient_update_plugins`) instead of on write (`pre_set_site_transient_update_plugins`). 

    This one is more subjective as there are benefits and disadvantages to both approaches. If you use the `pre_set...` filter then your custom update will get saved to the database. If the user then deactivates your plugin, you could end up with incorrect/outdated update notifications because the database contains stale information. 

    On the other hand, using the transient read filter (`site_transient....`) means that your update notifications won't show up *at all* when the plugin is inactive. However, when the plugin is active, they will be up-to-date. Personally, I like this approach better, but I can see why some people might prefer the first option.

Summary:
- I don't want my code to break other people's code.
- Performance and customizability are nice to have.
- I think no information is better than wrong information.

**Comment by amiga-500** [comment]
Wonderful response.  That explains everything.
Thanks very much @YahnisElsts 

Kimberly :octocat:
