### ISSUE TITLE
How to use on multiple plugins?

### ISSUE THREAD

**Issue by bstras21** [YahnisElsts/plugin-update-checker#80]
It works great with one plugin but when I add it to another I get this error:

Fatal error: Cannot declare class Puc_v4_Autoloader, because the name is already in use in wp-content/plugins/pluginName/plugin-update-checker/Puc/v4/Autoloader.php on line 3

**Comment by YahnisElsts** [comment]
Oops, that's really a silly oversight on my part. It should be fixed now.

**Comment by bstras21** [comment]
Awesome thanks!!!!
