### ISSUE TITLE
keep config file from old version

### ISSUE THREAD

**Issue by xenDE** [YahnisElsts/plugin-update-checker#81]
hi,

thanks for this plugin!

i need to keep a config.php inside my plugin-dir on an update.

any ideas how i can manage this?

best regards,
Daniel

**Comment by YahnisElsts** [comment]
Short answer: You can't.

WordPress doesn't support that kind of thing. It always removes the entire plugin directory when installing an update. There's no way to preserve specific files. 

(I guess if you were deeply familiar with how WP installs updates you *might* find a way to back up the file and then restore it after the update installed. However, I don't know how to do that, at least not off the top of my head.)

**Comment by xenDE** [comment]
Hi Yahnis,

ok, then i need to move the config file to an other location.

i have the full "plugin-update-checker" directory in my plugin directory.

makes this problems on update?
Or makes the WP-core and not the plugin the update?

best regards,
daniel.

**Comment by YahnisElsts** [comment]
Putting the `plugin-update-checker` directory in the plugin directory is fine. It's the recommended way to do things and it shouldn't cause any problems. 

Presumably, your update will also include the `plugin-update-checker` directory, so when you install the update the directory will just get overwritten with an identical copy.

> Or makes the WP-core and not the plugin the update?

The way it works is that PUC detects the update, tells WordPress core about it, and then WordPress installs the update. So most of the installation process is handled by WP core. PUC does a couple of minor things like making sure that the plugin directory name is correct and that the update ZIP file has the right directory structure.

**Comment by xenDE** [comment]
Thanks, then al will be fine.

Thanks a lot!
