### ISSUE TITLE
Github Updates Not Authenticating from Private Repository

### ISSUE THREAD

**Issue by prowp** [YahnisElsts/plugin-update-checker#84]
Thank you for your recent work on this. I'm trying to set up a theme for automatic updating and when trying to pull from github, the access token is not getting appended to the url. 

Reading through the code, I think the githubapi file is missing it's own version of signDownloadUrl possibly. If I append $this->accessToken to the url manually it works fine, but there is something not quite right is the routine.

**Comment by YahnisElsts** [comment]
Thank you for the report. It looks like you're right - that part of the authentication code got lost in the 4.0 overhaul. 

Try the master branch - the bug should be fixed there.

**Comment by prowp** [comment]
Thank you! Please let me know if you are taking donations anywhere for the work on this repository.

**Comment by YahnisElsts** [comment]
Sure, no problem.

I don't take donations at the moment.
