### ISSUE TITLE
Error when using v4 with wp-update-server

### ISSUE THREAD

**Issue by DGeoWils** [YahnisElsts/plugin-update-checker#85]
Hello, 

I'm getting an error that looks like this when I set up v4.

Fatal error: PUC does not support updates for plugins using JSON metadata in /var/www/fingerpaint-sandbox/public_html/wp-content/themes/fpm-tools-wp-theme/vendor/yahnis-elsts/plugin-update-checker/Puc/v4/Factory.php on line 80

I am attempting to use your wp-update-server to serve the Json info and the zip file. After tracing your code it seems that the factory is failing when getCompatibleClassVersion('Plugin_UpdateChecker') is called on line 70

**Comment by YahnisElsts** [comment]
That's one of those "this should never happen" errors. Are all of the library files present? Did you remember to load `plugin-update-checker.php` (only including the autoloader won't work)? 

Assuming the answer is "yes" to both, try dumping the `Puc_v4_Factory::$classVersions` and see if there's anything obviously wrong with the class list. You can add something like this to `getCompatibleClassVersion`:

```php
var_dump($class, self::$classVersions);
```

**Comment by DGeoWils** [comment]
Turns out this error occurred because I was using composer to autoload the Factory class. I took the PUC out of my classmap definition and required plugin-update-checker.php directly and it worked fine.

Thank you for your response, and for your work
