### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

### ISSUE THREAD

**Issue by codekraft-studio** [YahnisElsts/plugin-update-checker#87]
Hi, i'm not sure is an issue related with the plugin but before opening it I tried couple of things.

I've this plugin called "plugin-name.zip" in a public accessible folder, inside of it there is a folder called plugin-name with inside all the plugin files like mentioned here: [spreadsheet](https://spreadsheets.google.com/pub?key=0AqP80E74YcUWdEdETXZLcXhjd2w0cHMwX2U1eDlWTHc&authkey=CK7h9toK&hl=en&single=true&gid=0&output=html)

I tried to zip the folder with 7zip on windows and built in zip tool on linux and I get the same error during plugin updates.
`PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`
I googled a lot and people suggest lack of memory but it isn't (in my case), permissions but it isn't (in my case) or zip file corruption, but is the 12 time I try lol
All the rest of the people suggest to download the plugin and install manually but is not the case. 

What can be the problem? How can I debug it? 
Many thanks in advance.

**Comment by YahnisElsts** [comment]
Here are a few suggestions:

- Install [Core Control](https://wordpress.org/plugins/core-control/) and use the HTTP Access Logger Module to log the request that WordPress makes to download the update. Verify that the request is successful (i.e. 200 OK) and that it has the correct size and response headers. Chances are, you will discover that there's something wrong with the response.
- WordPress displays the update download URL during the update process. Verify that it matches the URL you specified in the JSON file, and try opening the URL manually.
- Edit the `download_url` function that's located in `/wp-admin/includes/file.php`. Make it output `$tmpfname` and immediately exit after downloading the file. Look at the downloaded ZIP file and verify that it's valid and contains the expected folders and files.

**Comment by codekraft-studio** [comment]
I looked into:
`SELECT * FROM `wp_options` WHERE `option_name` LIKE '%update_plugins%'` and seems good.

On the apache log: `"GET /path/to/plugin.zip HTTP/1.1" 200`

It looks like the $tmpfname is: `["filename":protected]=>"/tmp/plugin-name-TtGL7i.tmp"`

probably after the call of this: `$tmpfname = wp_tempnam( $url_filename );`

The $url variable is pointing to the right file: "/path/to/plugin.zip" 
The $url_filename variable is good too: "plugin-name.zip".
But after the **wp_tempname** call it change in "/tmp/plugin-name-TtGL7i.tmp" is that good? 

The download_url function return correctly the tmpfname I comment out all the unlink() calls but I still can't find the file in /tmp folder..it's strange.

**Comment by YahnisElsts** [comment]
> But after the wp_tempname call it change in "/tmp/plugin-name-TtGL7i.tmp" is that good?

I don't know if it's good, but it's expected. The `wp_tempnam` function is supposed to return a unique temporary file name, and it looks like that's what it does.

> The download_url function return correctly the tmpfname I comment out all the unlink() calls but I still can't find the file in /tmp folder..it's strange.

There is other code in WP core that will delete the temporary file after the update. You could try to track down and comment out all of the relevant code, but, unless it's a production site, it would probably be easier to just immediately stop execution (`die` / `exit`) in `download_url` and then look at the file.

**Comment by codekraft-studio** [comment]
alright I will try... seems like the problem is when the file is unpacked but is good that the file has a .tmp extension instead of .zip? the $tmpfname has .tmp extension it shouldn't be .zip?

**Comment by codekraft-studio** [comment]
I will close the issue since is not related with your plugin but if you want to keep help me to debug is appreciated :)

**Comment by YahnisElsts** [comment]
The extension doesn't matter; the PclZip library that WordPress uses will treat it as a ZIP file anyway. For debugging purposes, you can just rename it from .tmp to .zip before you try to open it.

> I will close the issue since is not related with your plugin but if you want to keep help me to debug is appreciated :)

Sure, if you have any further questions, feel free to post them.

**Comment by codekraft-studio** [comment]
It's happening a strange thing, in download_url I wrote this:
```
$response = wp_safe_remote_get( $url, array( 'timeout' => $timeout, 'stream' => true, 'filename' => tmpfname ) );
var_dump( $response );
die();
```

and the file: `ls /tmp/ | grep plugin-name-*` is not showing any file.. the /tmp folder has **drwxrwxrwt   1 root root** like it should be

I don't get the problem :(

**Comment by YahnisElsts** [comment]
File permissions could be an issue. However, that would affect all plugin updates, not just this one. Have you tried updating anything else? 

Another possibility is that the response is empty (i.e. a success with zero bytes of data). Maybe `wp_safe_remote_get` skips empty files; I'm not sure, I haven't tested that. 

By the way, the code you posted is missing the `$` prefix before the `tmpfname`.

**Comment by codekraft-studio** [comment]
I accidentally deleted while posting but in the file there is, I tried to update yoast and it worked

**Comment by YahnisElsts** [comment]
Right, so does the size and contents of the file match the plugin.zip?

**Comment by codekraft-studio** [comment]
The filesize seems to match but I still can't find this file... It's incredible I looked in /tmp and /wp-content/upgrade but there is no file.. I wonder what php is checking in is_file($tmpfname) and filesize($tmpfname)

**Comment by YahnisElsts** [comment]
The file *must* be there if filesize() works. Maybe it gets deleted before you look for it, or you don't have the right permissions to see the file? 

Anyway, you could [`copy`](http://php.net/manual/en/function.copy.php) it to another location for analysis.

**Comment by codekraft-studio** [comment]
oh man maybe I found out.. by running: `find / -name plugin-name-*` I realized that the tmp files were downloaded in: /tmp/systemd-private-8e0f64e277404f329207822ce13f717b-apache2.service-ofT86W/tmp/

is an apache conf problem.. maybe

**Comment by codekraft-studio** [comment]
I realized the .tmp file size is  699498 and the original size: 707506
My php script is pretty simple 
```php
  header( 'Content-Description: Download' );
  header( 'Content-Type: application/zip' );
  header( "Content-length: " . filesize(dirname(__FILE__) . '/releases/plugin-name.zip') );
  header( "Content-Disposition: attachment; filename=plugin-name.zip" );
  readfile( dirname(__FILE__) . '/releases/plugin-name.zip' );
  exit;
```
If I visit manually the file is correctly downloaded and I can unzip it.

**Comment by YahnisElsts** [comment]
You could try turning off gzip compression for ZIP files;
http://stackoverflow.com/questions/9249243/how-to-disable-apache-gzip-compression-for-some-media-files-in-htaccess-file

Also, try comparing the contents of the downloaded file with the actual file. This could be a bit tricky since it's a binary file, but apparently the [`cmp`](http://stackoverflow.com/questions/8385618/using-cmp-to-compare-two-binaries) command can do that.

**Comment by codekraft-studio** [comment]
man, it was the f***ing gzip compression that was enabled for zip files too.. i disabled it for all the kind of archive formats to avoid such bugs in future.. many many thanks for your help.

**Comment by langan** [comment]
@YahnisElsts you sir are made of win!
