### ISSUE TITLE
Use on premium plugins

### ISSUE THREAD

**Issue by seldimi** [YahnisElsts/plugin-update-checker#88]
Hello. Fantastic work about this plugin, it does what it says!
My only question is how can I protect my premium plugins? Currently, on JSON metadata, there is a full URL and users can use it directly to download it without our permission.
I was thinking of adding API keys in databases, but can you suggest on how to merge it with your plugin ?

**Comment by YahnisElsts** [comment]
Here's a general overview of how I handle this in my own commercial plugins:
http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/

**Comment by seldimi** [comment]
Hello. Thanks for y our answer, I found the documentation really useful. The only thing that I couldn’t manage to make is to make wordpress say “No license or invalid license on plugins page”. It currently says there is no automatic update for this plugin

**Comment by YahnisElsts** [comment]
You can use the `after_plugin_row_$pluginBasename` hook to output your own message below the plugin row. 

As for the "no automatic update" message, that's a standard warning that WordPress shows when a plugin update doesn't have a download link. You could probably hide it somehow, but I haven't tried that myself.

**Comment by YahnisElsts** [comment]
Given the lack of activity, I'm going to close this issue for now. If you have any further questions, feel free to reopen it or to create a new one.

**Comment by seldimi** [comment]
Hey,
Thanks for the answers, I did what you suggested :)
