### ISSUE TITLE
Help me to config this

### ISSUE THREAD

**Issue by zaingithub** [YahnisElsts/plugin-update-checker#90]
require_once ( MY_PLUGIN_PATH . '/updater/plugin-update-checker.php' );

$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://bitbucket.org/myname/myplugin-release',
	__FILE__,
	'pluginslug'
);

$myUpdateChecker->setAuthentication(array(
	'consumer_key' => '...',
	'consumer_secret' => '...',
));

$myUpdateChecker->setBranch('master');

Please, i don't know exactly what is called pluginslug (unique plugin slug name).
Where can i find the slud?

I have change / edited the version in bitbucket, refresh wp-plugin and no notification of an update. Thanks.

**Comment by YahnisElsts** [comment]
In most cases, the plugin slug should be the same as the name of your plugin directory. For example, if your plugin is located in `wp-content/plugins/my-awesome-plugin`, the slug should be `my-awesome-plugin`. Alternatively, you could use your repository name as the slug (i.e. the `myplugin-release` bit).

The slug must be unique.

**Comment by zaingithub** [comment]
Thank you for reply. I have set the slug plugin as your direction too, but nothing changed.

Can you specify how i should make a change to my configuration?

Bitbucket stucture : http://prntscr.com/erydav
Bitbucket Oauth : http://prntscr.com/erydoa

my file : my-plugin.php contains this plugin information : 

/**
 * Plugin Name: My Plugin Name
 * Plugin URI:	http://example.com
 * Description: My description
 * Version: 2.2.0
 * Author: my Name
 * Author URI:	my fb url
 * Text Domain: example.com
 */

in my localhost, the version still 1.0.0, i have update the version in bitbucket repo with 2.2.0 to have a test. But still same.

**Comment by YahnisElsts** [comment]
What you should do is install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and then look at the "PUC (your-slug)" panel in the debug bar. Does everything look correct there? Try clicking the "Request Info" and "Check Now" buttons - what is the response?

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a couple of years. 

If you still encounter this problem, feel free to reopen the issue or create a new one.
