### ISSUE TITLE
Question: Github Releases - What is downloaded?

### ISSUE THREAD

**Issue by Luehrsen** [YahnisElsts/plugin-update-checker#93]
Hey, 

I am just thinking about integrating this library for a project. We are still unsure, because we are using a non standard file structure in our repo. 

So when I create a release and the plugin downloads it, what gets downloaded? The source code (which will not work with our git structure) or does it honor an attached binary? 

Best,
Hendrik

**Comment by YahnisElsts** [comment]
The update checker uses the `zipball_url` field returned by the GitHub API. I believe that's the source code. I'm not sure how the API works with attached binaries, but it should be probably reasonably easy to modify the library to download the binary instead. Do you have an example release that I can look at?

**Comment by Luehrsen** [comment]
https://api.github.com/repos/luehrsenheinrich/afb_instant_articles/releases

As you can see in this example the zipball_url is actually not what we are looking for, but the assets, or a filtered version of the zipball_url. 

Maybe I can hack something together. :)

**Comment by YahnisElsts** [comment]
To make this easier, I've added the GitHub API response to the object returned by `Puc_v4p1_Vcs_GitHubApi::getLatestRelease` (see 22689ce0ccb277d2b62756c3be2fbeccd79f1c9e). You could probably override the method in a subclass and then change the download URL like this:

```php
$reference = parent::getLatestRelease();
if ($reference && isset($reference->apiResponse, $reference->apiResponse->assets, $reference->apiResponse->assets[0]) {
    $reference->downloadUrl = $reference->apiResponse->assets[0]->browser_download_url;
}
return $reference;
```

(This is just off the top of my head; I haven't tested this code.)

**Comment by hughfm** [comment]
I'm also interested in this, since I prefer to attach a copy of the built theme to the GitHub release, rather than have the entire build checked in to git. 

Is there a safe way to drop in a custom subclass, as you suggest above @YahnisElsts? Would obviously like the changes to persist when updating the library.

Thanks for all your work on these tools.

**Comment by YahnisElsts** [comment]
Just put the subclass in a separate file and store it anywhere outside the `plugin-update-checker` directory. There's no requirement for it to be physically inside the library.

**Comment by hughfm** [comment]
So if I create a subclass of GithubApi, is there a way to inject that when calling buildUpdateChecker? Sorry if I'm missing something!

**Comment by YahnisElsts** [comment]
Not at the moment. You'd have to create the update checker instance yourself. It's relatively straightforward: instantiate `Puc_v4p1_Vcs_PluginUpdateChecker` and pass an instance of your custom API class as the first constructor argument. The other arguments are the same as those passed to `buildUpdateChecker`.

Untested example:
```php
require 'path/to/plugin-update-checker.php';
require 'MyCustomApi.php';

$updateChecker = new Puc_v4p1_Vcs_PluginUpdateChecker(
    new MyCustomApi($repositoryUrl),
    __FILE__,
    'plugin-slug'
);
```

**Comment by hughfm** [comment]
Ah ok gotcha. Thanks for explaining, I will give that a go.

**Comment by Luehrsen** [comment]
While the approach by @YahnisElsts is great, the github API is kind of strange in that regard. 

The asset `browser_download_url` requires proper oAuth, which WordPress doesn't do with the `download_url()` function. I haven't found any filters or actions to hook into. 

There is the possibility to download the asset via api.github.com as described here: https://developer.github.com/v3/repos/releases/#get-a-single-release-asset

But then again do you have to modify the header information to set the `Accept` header. The one way I found is to tunnel the download through an own script, but I haven't yet found an elegant solution to do this without creating huge security risks.

**Comment by YahnisElsts** [comment]
> The asset browser_download_url requires proper oAuth (...)

Is that something that only applies to private repositories? I wonder if you could use the existing signature generator (`Puc_v4p1_OAuthSignature`) to sign the download URL. The API class already has a `signDownloadUrl` method, but right now it just adds the access token as a query parameter. You could override it to use OAuth instead.

**Comment by connerbw** [comment]
We got this working based on the untested examples posted on Apr 12 and Apr 22

However, there are a few places where "zipball" still appears, example:

![worked](https://user-images.githubusercontent.com/812192/30655677-b003a30e-9dff-11e7-80ad-6b0950933591.png)

(_zipball was not downloaded_)

I'm not going to bother fixing the above minor discrepancy,  but it would be nice if this plugin had an option to change  to `zipball_url`  to something else without having to override. Like the other people in this thread, we are particularly interested in the `browser_download_url` node [as seen here](https://api.github.com/repos/pressbooks/pressbooks/releases/7799826).

Code for anyone who's interested:

```php
<?php
/**
 * @see https://github.com/YahnisElsts/plugin-update-checker/issues/93
 */
class Updater extends Puc_v4p2_Vcs_GitHubApi {

	/**
	 * @return null|\Puc_v4p2_Vcs_Reference
	 */
	public function getLatestRelease() {
		$reference = parent::getLatestRelease();
		if ( $reference && isset( $reference->apiResponse, $reference->apiResponse->assets, $reference->apiResponse->assets[0] ) ) {
			$reference->downloadUrl = $this->signDownloadUrl( $reference->apiResponse->assets[0]->browser_download_url );
		}
		return $reference;
	}
}

// ... snip ...

$updater = new Puc_v4p2_Vcs_PluginUpdateChecker(
	new Updater( 'https://github.com/my-plugin/my-plugin/' ),
	__DIR__ . '/my-plugin.php', // Fully qualified path to the main plugin file
	'my-plugin'
);
$updater->setBranch( 'master' );
```

**Comment by YahnisElsts** [comment]
I tested this today and `zipball` doesn't appear in the update log when using that code. Perhaps one of the intervening releases fixed that?

**Comment by YahnisElsts** [comment]
Official asset support has been added. Usage: Set up the update checker instance as usual, then call the new `enableReleaseAssets()` method of the GitHub API class. 

```php
$gitHubUpdateChecker = Puc_v4p3_Factory::buildUpdateChecker(
	'https://github.com/YahnisElsts/example-repository',
	__FILE__
);
$gitHubUpdateChecker->setAuthentication('abcdef1234567891234657891234567891234567');
$gitHubUpdateChecker->getVcsApi()->enableReleaseAssets();
`

I've only run some basic tests so far.
