### ISSUE TITLE
Download update after license key inserted

### ISSUE THREAD

**Issue by vol4ikman** [YahnisElsts/plugin-update-checker#94]
Hi, thank you for your work!
How can I implement license key, saved in my database, after user purchase the plugin.

Thanks!!

**Comment by YahnisElsts** [comment]
I don't have a complete tutorial about licensing, but you might find this useful:
http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/

**Comment by vol4ikman** [comment]
Thanks
