### ISSUE TITLE
Extent of MU Plugin support? ("Automatic update is unavailable for this plugin")

### ISSUE THREAD

**Issue by cpruitt** [YahnisElsts/plugin-update-checker#95]
Hi,

I'm trying to implement automatic updates for an MU plugin but, admittedly, I do not know to what extent the plugin checker supports MU plugins. I've tried a few different things but none seem to work.

In my setup I have a single proxy file `plugin-core.php` in the `mu-plugins` directory and a `plugin-core` subdirectory containing various other plugin files. The only job of `mu-plugins/plugin-core.php` is to load `mu-plugins/plugin-core/main.php` which is the actual starting point for the plugin's functionality.

In the file `plugin-update-checker-4.1/Puc/v4/Factory.php` I see that there is an argument for `$muPluginFile`. Which lead me to believe that MU plugins *might* be supported. Currently I've got things set up like this:

```php
$updateChecker = Puc_v4_Factory::buildUpdateChecker(
  'http://www.testupdates.dev/plugin-core/info.json',
  __FILE__,
  'plugin-core/main.php',
  12,
  '',
  'plugin-core.php'
);
```

The WordPress admin page for mu plugins shows me that an update is available, but gives the message "Automatic update is unavailable for this plugin". It's my understanding that WordPress itself does not support auto-updates of MU plugins so this might be a limitation of WordPress, not PUC. So my questions would be:

1. Are updates for MU plugins possible or am I only able to check for the *existence* of available updates that need to be installed manually?

2. If MU updates are possible, are they limited to single file updates only or is the "proxy-loader" pattern I'm using possible?

3. If proxy's with additional directories are possible, is there any advice you can offer to help troubleshoot?

Thanks very much for making the PUC source available and for taking the time to answer questions!

**Comment by YahnisElsts** [comment]
WordPress doesn't support automatic updates for MU plugins. As you have already discovered, you can make it display an update notification, but you won't be able to actually install the update. The purpose of the `$muPluginFile` parameter is to enable the notification message.

The last time that I looked at that part of WordPress core, there was no way to make MU plugin updates work without writing a custom update installer. That seems like a lot of work. If it's something you're interested in pursuing, take a look at the source code of the [Plugin_Upgrader](https://developer.wordpress.org/reference/classes/plugin_upgrader/) class.

**Comment by cpruitt** [comment]
@YahnisElsts I'll take a look at the class and see what's going on inside, though it might end up being more work than is worth. In addition to a custom installer, I'd need to find some way of getting the WP admin interface to allow the update to be initiated. There are also a lot of security considerations (such as update verifications) to account for. That's fine if I'm writing something for myself that updates from a trusted source on a secure network, but submitting a PR would mean a more general purpose use case and introducing new points of failure for security might not be a great idea. It's probably best to let the update checker do the reporting & just build self-updates into the MU plugin itself or write a WP-CLI command to do the same.

Thanks for the response!

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a couple of years. 

At this time, automatic update installation is still not available for `mu-plugins`.
