### ISSUE TITLE
Update different folder than Plugin folder itself?

### ISSUE THREAD

**Issue by chozze** [YahnisElsts/plugin-update-checker#96]
Hello, let me thank you fist for this great plugin!
I have a question - I have a wp.com hosted plugin XX, which is extendable by downloadable files externally. I let users to upload these files trough my XX plugin and save them to a different folder /wp-content/plugins/XX-external-files - reason for this that I don`t want to official WP plugin updater re-write these files(actually delete them) when I release a new XX plugin version.

To my question, is it possible to configure plugin-update-checker to check and download only these external files? Folder structure is like this:

/wp-content/plugins/XX-plugin - this is where my plugins sits.
/wp-content/plugins/XX-external/external1
/wp-content/plugins/XX-external/external2
/wp-content/plugins/XX-external/external3 etc..in these folder I store the extendables and would like to check for updates each of these folder.

In those files I have few .php files, images, etc. They are not coded as standard WP plugins.
I tried to call plugin-update-checker from XX-plugin against my server with following parameters

```
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'http://example.com/?action=get_metadata&slug=external1',
	plugin_dir_path( __DIR__) . 'XX-external/external1/external1.php',
	'external1'
);

```
Which I belive works fine as I put wp plugin standard readme into external1.php but I don`t know how to handle the actual update....

thanks for your thoughts if it is even possible to use your plugin for this.

thanks

**Comment by YahnisElsts** [comment]
I doubt that it would work, at least as-is. You have a bunch of different non-plugins in a single folder that is itself stored in the `plugins` directory. The update checker was designed with the assumptions that `/wp-content/plugins` contains actual plugins and that one folder corresponds to one plugin. Clearly, there's a mismatch here, which means you're very likely to run into problems.

Even if the update checker did support your use case, it still uses the WP updater to actually install updates. As you've noticed, this installer deletes the entire folder during the update. There's no easy way to make update only a specific subdirectory.

You've probably already considered this, but one thing you could do is put each external in a separate folder and format them as plugins (basically, include a PHP file with a plugin header):

```
/wp-content/plugins/XX-external1
/wp-content/plugins/XX-external2
/wp-content/plugins/XX-external2
```

Of course, this approach also has its downsides, like polluting the plugin list with things that aren't real plugins. However, it would make it significantly easier to implement updates.

**Comment by chozze** [comment]
Thanks for a quick reply. Studying your plugin files I came to same judgment. I was thinking to turn those external folders into separate plugins, but I would like to make them somehow hidden for user so they don`t need to worry about it so I will look into custom solution for this.

Case closed. Thanks!

**Comment by YahnisElsts** [comment]
FYI, you can use the [`all_plugins`](https://developer.wordpress.org/reference/hooks/all_plugins/) filter to hide plugins from the "Plugins" page.
