### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by joelwolfgang** [YahnisElsts/plugin-update-checker#97]
So, I'm using this on several plugins, but I have one in particular that is not updating. After I create a release in Github and try to update it - WP says that the plugin is up to date, when I know that it clearly is not. Do you have any insight into this?

**Comment by YahnisElsts** [comment]
Install [Debug Bar](https://wordpress.org/plugins/debug-bar/) and look at the "PUC (your-plugin-slug)" debug bar panel. Does all of the info look correct? Try clicking the "Request info" and "Check now" buttons. Does this produce the expected response (i.e. some debug output with correct version information)?

**Comment by joelwolfgang** [comment]
Ok, I've resolved this. Sorry to trouble you and everyone else listening. Apparently, along-the-way my GitHub authorization key got corrupted (probably my error). I just created a new one. Thankfully, I have everyone's email so they can redownload it.
