### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by DeveloperWilco** [YahnisElsts/plugin-update-checker#98]
Hey there, 

There is a broken link in your readme documentation wich I'd like to see fixed :) 

its this part:

This is a minimal example that leaves out optional fields. See[ this table](https://spreadsheets.google.com/pub?key=0AqP80E74YcUWdEdETXZLcXhjd2w0cHMwX2U1eDlWTHc&authkey=CK7h9toK&hl=en&single=true&gid=0&output=html) for a full list of supported fields and their descriptions.

also noticed an error when having WP_debug on true. it appears sometimes saying unidentified index 1 in the file readme-parser.php. Mabye because I don't use a readme file?

Thanks in advance

**Comment by YahnisElsts** [comment]
Thank you for the report. The link has been fixed.

As for the error, are there any more details that you could provide, e.g. a stack trace or at least a line number? 

> Mabye because I don't use a readme file?

If I recall correctly, the parser won't even be called if you don't have a readme. It sounds like an odd situation.

**Comment by YahnisElsts** [comment]
Have you had the time to look into this?

**Comment by YahnisElsts** [comment]
I'm closing this issue because it has been inactive for a couple of years. 

If you still encounter the error that you mentioned, feel free to reopen the issue or create a new one.
