### ISSUE TITLE
Using Debug Bar

### ISSUE THREAD

**Issue by christianstclair** [YahnisElsts/plugin-update-checker#99]
Hi,

I don't think the Debug Bar plugin has been updated in some time. 

When I activate it on multiple installs I get a fatal error

**Comment by YahnisElsts** [comment]
It doesn't seem to be actively maintained, but it should still work. I'm running Debug Bar 0.8.4 on several sites using PHP 7 and WP 4.7.4. No errors.

There's probably something else going on in your case. What was the exact error message?

**Comment by christianstclair** [comment]
Ah I found it. I think one of my other plugins was using an older version of the plugin-update-checker.php and for some reason was failing. 

The plugin that was causing the trouble is called acf-tooltip (https://wordpress.org/plugins/acf-tooltip/)

Not sure if it's using an older version of your update checker, or if something else is going on in my local environment.

**Comment by YahnisElsts** [comment]
> The plugin that was causing the trouble is called acf-tooltip (https://wordpress.org/plugins/acf-tooltip/)
> Not sure if it's using an older version of your update checker, or if something else is going on in my local environment.

For what it's worth, I don't think it's using this update checker at all. I briefly checked the plugin source code and didn't find any references to PUC. Also, there's no `plugin-update-checker.php` in that plugin.

**Comment by christianstclair** [comment]
Yeah I just downloaded the latest version, not sure how I have an older one as it looks like the first release. Perhaps it's an older version before he released it on wordpress, thus his using of the plugin update checker. It was utilizing version 2.1

**Comment by christianstclair** [comment]
But thanks for your help! I got it sorted out now.
